// ---------- document ----------
const XL = require('./xl.json');
const children = [];
const spacer = () => new Paragraph({ children: [], spacing: { after: 60, line: 120 } });
const push = (...x) => x.forEach(y => { if (Array.isArray(y)) return push(...y); children.push(y); if (y instanceof Table) children.push(spacer()); });
const RULES_NOTE = M.RULES_VERSION;
const NCALC = data.calcs.length, LASTC = 'C' + String(NCALC).padStart(2, '0');
const callout = t => new Table({ width: { size: W, type: WidthType.DXA }, columnWidths: [W], rows: [new TableRow({ children: [cell(t, W, { fill: SUN_L, size: 18 })] })] });
const ASM_USE = { inv: 'Plan', cash: 'Plan', pen: 'C12, C13, C14 growth (pre-fill); plan', penRet: 'C15 growth; plan', penChg: 'C12–C14 growth after charges; plan', wage: 'C12; plan', bands: 'Plan', spGrow: 'Plan', spYears: 'C12 other income (State Pension); plan', spPartly: 'C12 other income; plan', spNotSure: 'C12 other income; plan', ownShare: 'C13, C14 (what you pay in); plan', retireMult: 'C12 target', retireSpend: 'Plan', lumpSum: 'C12 lump sum', drawRule: 'Plan', ddTiming: 'C15, C16', drawFixed: 'Plan', safetyMonths: 'C11 months; plan', mortRate: 'C01, C02, C04, C05, C06, C07, C23 rate; plan', cardRate: 'C27 APR; plan', loanRate: 'C28 APR; plan', cashYears: 'Plan', investShare: 'Plan', saveShare: 'Plan', noAnswer: 'Plan', lifeShare: 'C21', lifeYears: 'C21 years', survivor: 'C21 survivor\'s pension', budgetNeeds: 'C26', budgetWants: 'C26', budgetSave: 'C26', rentRise: 'C07', houseGrow: 'C07 house prices', upkeep: 'C07', buyFees: 'C01, C03, C07', depEarn: 'C07', riskMu1: 'C16, C20', riskMu2: 'C16, C20', riskMu3: 'C16, C20', riskVol1: 'C20', riskVol2: 'C20', riskVol3: 'C20', planEnd: 'C15; plan', startYear: 'Plan' };
const fmtNum = v => typeof v === 'number' ? String(+v.toFixed(4)) : String(v);
const chipBox = (i, f) => f && f.kind === 'chip' ? f.box : null;

// Cover
push(new Paragraph({ children: [run('LifeGoals', { size: 28, bold: true, color: SEA_D })], spacing: { before: 2200, after: 120 } }),
  new Paragraph({ children: [run('Calculators: UI/UX build specification', { size: 52, bold: true, color: INK })], spacing: { after: 200 } }),
  new Paragraph({ children: [run('An exact-replica specification of every calculator in the LifeGoals customer journey prototype (' + NCALC + ' calculators, C01 to ' + LASTC + '), the inflation chips and the Your assumptions screen', { size: 26, color: MUTED })], spacing: { after: 500 } }),
  kv([['Source of truth', 'LifeGoals-Customer-Journey-Prototype.html (CALCS, calculator screen V.CALC, fieldR / fieldC inputs, calcOut result card, inflChoice, the "Adjust for inflation" switch, statement uploads DOCT, Your assumptions ASM, rules register RULES_IE_2026)'], ['Maths reference', 'LifeGoals-Calculators.xlsx. Sheet "Cnn …" holds the maths for calculator Cnn (e.g. "C01 Borrowing").'], ['Rules version', RULES_NOTE + '. Budget 2027 (6 October 2026) will require updates.'], ['Prepared for', 'Pooja Tirupati, Proposition owner'], ['Prepared by', 'UI/UX design, LifeGoals team'], ['Date', '2 October 2026'], ['Status', 'Guidance, not advice. All figures are illustrative.']]),
  brk());
push(new Paragraph({ heading: HeadingLevel.HEADING_1, children: [new TextRun({ text: 'Contents', font: FONT })], spacing: { after: 160 } }), new TableOfContents('Contents', { hyperlink: true, headingStyleRange: '1-1' }));
push(H1('Purpose and how to use this document'),
  P('This document lets a designer and developer rebuild every Explore calculator exactly as it behaves in the prototype: the same words, the same numbers, the same limits and the same states. Every label, default, limit and line of copy was taken from the prototype source and then checked automatically against the live screen (see uiux-spec-check.md).'),
  callout('**Rules version: ' + RULES_NOTE + '.** Every statutory figure (tax bands, USC, PRSI, State Pension and benefit rates, pension limits, stamp duty, Central Bank limits, DIRT and exit tax) comes from one register (section 3.2). **Budget 2027 (6 October 2026) will require updates** to that register and to any copy that quotes those figures (marked in this document where they appear).'),
  H3('How to use it'),
  B('**Design system** (section 1): tokens, type, components (slider + value box, choice chips, the inflation chips in their three states, tags, switch) and accessibility rules shared by every calculator.'),
  B('**Explore structure** (section 2): the 6 calculator groups, "Focus on one area" topics, statement-upload cards and the Add to my plan sheet.'),
  B('**Rules and Your assumptions** (section 3): the rules version, the Irish rules 2026 register, and the "Your assumptions" screen with every customer-choice input.'),
  B('**One section per calculator** (C01 to ' + LASTC + ', in CALCS order): screenshots, inputs, the result card copy with {placeholders}, the matching workbook sheet with its input and output names, states, actions and accessibility.'),
  B('**Maths lives in the workbook.** Placeholders use the workbook\'s defined names where one exists (e.g. {Home_Price}), so design, engineering and the workbook stay aligned.'),
  B('**Appendix A** is the copy deck; **Appendix B** lists open points still to decide.'),
  H3('Conventions'),
  table([2300, W - 2300], ['Notation', 'Meaning'], [
    ['{Name}', 'A dynamic value. Format and meaning are in the calculator\'s placeholder table. Names in the workbook are marked "Workbook name".'],
    ['«A|B»', 'One of the options, chosen by the rule in "Shown when". An empty option («text|») means nothing is shown.'],
    ['★', 'In screen-value tables: the input shows the green "From your statement" tag.'],
    ['Verbatim', 'Quoted text and the copy columns are exact, including straight apostrophes (\'), ×, ·, …, and the minus sign − (U+2212) in negative or signed euro amounts.'],
    ['Default state', 'The calculator opened from Explore before a plan, with nothing told us and no inflation rate chosen (it is blank until the customer picks one). "On screen" shows what the customer actually sees; ⚠ marks a field the tool always pre-fills, so it differs from the CALCS default.'],
    ['Screenshots', '390 px wide (device scale 2), full screen length; on a 390×844 phone the content scrolls between the fixed header and the tab bar.'],
  ], { size: 15 }),
  H3('Value formats'),
  table([1700, 2000, W - 3700], ['Format', 'Name', 'Rule'], Object.entries(TYPES).map(([k, v]) => [k, v[0], v[1]]), { size: 15 }));

// ---------- 1 Design system ----------
push(H1('1. Design system'));
push(P('Visual language: the "Teal & Navy" theme. Values below are copied verbatim from the prototype CSS.'));
push(H2('1.1 Colour tokens'));
const hexOf = v => (v.match(/^#([0-9A-Fa-f]{6})$/) || [])[1];
push(table([1900, 1500, 900, W - 4300], ['Token', 'Value', 'Swatch', 'Use'], tokens.filter(t => !/^--f[hb]$/.test(t[0])).map(([k, v]) => [k, v, hexOf(v) ? cell('', 900, { fill: hexOf(v) }) : '—', TOKEN_USE[k] || (/-t$/.test(k) ? 'Status text colour (passes 4.5:1 on white and on its -l tint)' : /-l$/.test(k) ? 'Status tint (background)' : /^--(good|nudge|alert|sunny|showers|storm|ok|dip|gap)/.test(k) ? 'Status fill (fills only, never text)' : /^--(plain|mark)/.test(k) ? 'Header gradient / brand mark' : '')]), { size: 15 }));
push(P('Other fixed colours on calculator screens: result-card body text #DCE7F2; result-card row divider rgba(255,255,255,.14); what-if card border #B9C9D6 (dashed); value-box underline #8CC7BF (dashed); statement card border #B5E3DB; page behind the phone #E4ECE8; neutral tag background #EEF2F0; gold gradient top #F7C24F.', { size: 18, before: 80 }));
push(H2('1.2 Typography'));
push(table([2200, W - 2200], ['Item', 'Value (verbatim)'], [['Heading font (--fh)', tokens.find(t => t[0] === '--fh')[1]], ['Body font (--fb)', tokens.find(t => t[0] === '--fb')[1]], ['Web font load', 'Google Fonts: Bricolage Grotesque 500, 700, 800; Figtree 400, 500, 600, 700, 800; display=swap'], ['Heading rule', 'h1, h2, h3: font-family var(--fh); letter-spacing -.01em']]));
const TS = [['Screen title (h2.t)', 'h2.t', 'Bricolage Grotesque'], ['Question / subtitle (.sub)', '.sub', 'Figtree'], ['Category eyebrow (.eyebrow)', '.eyebrow', 'Figtree'], ['Field label (.flabel)', '.field>label,.flabel', 'Figtree'], ['Small text (.small)', '.small', 'Figtree'], ['Tip note (.note)', '.note', 'Figtree'], ['Disclaimer (.disc)', '.disc', 'Figtree'], ['Tag (.tag)', '.tag', 'Figtree'], ['Chip (.chip)', '.chip', 'Figtree'], ['Hint (.nbhint)', '.nbhint', 'Figtree'], ['List row title (.goal b)', '.goal b', 'Figtree']];
const ruleFor = s => { try { return cssRule(s); } catch (e) { const m = HTML.match(new RegExp(s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&') + '\\{([^}]*)\\}')); return m ? m[1] : ''; } };
push(table([2600, 1700, W - 4300], ['Element', 'Font', 'CSS (verbatim)'], TS.map(([n, s, f]) => [n, f, ruleFor(s)]).concat([['Result headline value', 'Bricolage Grotesque', 'font-family:var(--fh);font-size:36px;font-weight:800;margin:4px 0'], ['Result line', 'Figtree', 'margin:0;font-size:14px;line-height:1.5;color:#DCE7F2'], ['Result rows', 'Figtree', 'justify-content:space-between;border-top:1px solid rgba(255,255,255,.14);padding:8px 0;margin-top:8px;font-size:13.5px (value bold)'], ['Result eyebrow', 'Figtree', '.eyebrow with color:var(--sun)']]), { size: 15 }));
push(H2('1.3 Radii, shadows and spacing'));
push(table([2600, W - 2600], ['Element', 'CSS (verbatim)'], [['Card (.card)', cssRule('.card')], ['Card stack', cssRule('.card+.card')], ['Calculator cards', 'Inputs and inflation cards: margin-bottom:12px. What-if card: margin-top:12px;border:1.5px dashed #B9C9D6;box-shadow:none'], ['Result card', '.card with background:var(--ink);color:#fff'], ['Statement card (.card.pst)', cssRule('.card.pst')], ['Field (.field)', cssRule('.field')], ['Label row (.flabel)', cssRule('.field>label,.flabel')], ['Screen scroll area (.scroll)', cssRule('.scroll')], ['Header (.sky)', cssRule('.sky')], ['Two-column grid (.grid2)', cssRule('.grid2')], ['List row (.goal)', cssRule('.goal')], ['Tip note (.note)', cssRule('.note')], ['Phone frame (presentation)', cssRule('.phone')]], { size: 15 }));
push(H2('1.4 Buttons'));
push(table([2300, W - 2300], ['Style', 'CSS (verbatim)'], [['Primary: gold with navy text (.btn)', cssRule('.btn')], ['Primary hover', cssRule('.btn:hover')], ['Primary pressed', cssRule('.btn:active')],
  ['Navy small (.btn.sm): "＋ Add to my plan", "Upload a statement"', '.btn.sm{background:var(--ink);color:#fff;box-shadow:none} .btn.sm{min-height:44px;font-size:14px;width:auto;padding:0 18px}; hover var(--ink2); width:100% on calculators'],
  ['Outline / ghost (.btn.ghost): "Ask an expert", "Use a sample statement", "Not now", "Use all suggested values"', cssRule('.btn.ghost') + ' hover: border-color:var(--ink)'], ['Disabled', '.btn[disabled]{opacity:.45;cursor:not-allowed}'], ['Text link (.link)', cssRule('.link')], ['Back button (.backb)', cssRule('.backb') + ' Text: "‹ Back"']], { size: 15 }));
push(P('Gold primary is used for the main call to action in sheets and flows ("Add it", "Update it", "Raise it", "Note it", "OK", "Looks right, fill in my tools"). On the calculator the two actions are small: navy "＋ Add to my plan" and ghost "Ask an expert".', { size: 18 }));
push(imgP('K-actions.png', 340, 200), cap('Calculator actions'));
push(H2('1.5 Slider with editable value box'));
push(P('Every numeric input is a labelled range slider with an editable value box at the right of the label.'));
push(table([2300, W - 2300], ['Part', 'Specification (verbatim CSS)'], [['Slider', cssRule('input[type=range]') + ' Attributes: min, max = max(slider max, current value), step, value, aria-labelledby the label.'], ['Value box (.nbox)', cssRule('.nbox')], ['Value input (.nbox .nb)', '.nbox .nb{border:0;background:transparent;font:inherit;font-weight:800;color:var(--sea-d);text-align:right;padding:4px 0;min-width:2.6ch;max-width:16ch;box-sizing:content-box}; width (max(2, characters) + 0.6)ch'], ['Box focus', '.nbox:focus-within{border-bottom:2px solid var(--sea-d);background:var(--sea-l);border-radius:6px 6px 0 0}'], ['Unit (.nbu)', 'aria-hidden. € before; % after; "yrs" after; "mo" after; "age " before; plain numbers none.'], ['Hint (.nbhint)', '.nbhint{display:block;font-size:12px;color:var(--nudge-t)} .nbhint:empty{display:none}; role="status" aria-live="polite"']], { size: 15 }));
['**Drag**: snaps to the step; the box shows the value (en-IE grouping, up to 4 decimals); the result updates live.', '**Type**: tapping selects the text; the result updates live once the text is a number; Enter or leaving the box commits and re-formats.', '**Typed precision is kept**; the step applies only when dragging. Pre-filled values off the step show exactly in the box while the thumb sits at the nearest step; results use the box value.', '**Parsing**: only digits, ".", "," and "-" count; commas are thousand separators. Empty, "-" or "." is ignored while typing; on commit the box returns to the last valid value.', '**€ fields above the slider top**: accepted up to 10 × the slider maximum; the slider widens. Above that: clamps, hint "Max €…".', '**Other units** clamp to the slider range; hint "Max 8%", "Max 35 yrs", "Max 12 mo", "Max 70".', '**Below the minimum**: clamps; hint "Min €15,000" (euros) or "Min 1" (others, no unit).', '**Hint timing**: shows as soon as the text passes a limit and after leaving the box; clears on the next in-range value. Quirk: Enter then leaving the box clears it (Appendix B).', '**Touched fields win** over any pre-fill for the session; a new statement upload resets the tool to the statement.', '**Keyboard**: inputmode="decimal" when the step has decimals or the unit is %, else "numeric".'].forEach(t => push(B(t)));
push(imgGrid([{ file: 'K-focus.png', caption: 'Value box focused' }, { file: 'C02-hint.png', caption: 'Max hint on a rate field' }, { file: 'K-widen.png', caption: '€ above the slider top' }], 3, 140));
push(H2('1.6 Choice chips for whole-number inputs'));
push(P('Inputs that can only take a few whole values are chips, never sliders, so a value such as 0.5 or 2.5 cannot be entered.'));
push(table([2200, 3400, W - 5600], ['Input type', 'Chips (verbatim)', 'Used in'], [['Yes / No', '"Yes" (1) · "No" (0)', 'C01 First-time buyer?; C21 Is the mortgage cleared by mortgage protection? (most are)'], ['Style', '"1 · Cautious" · "2 · Balanced" · "3 · Growth"', 'C20 Style'], ['Tax rate', '"20%" · "40%"', 'C13, C14 Your tax rate']], { size: 15 }));
push(P('Markup: the label is a .flabel span; the chips sit in .chips with role="group" aria-labelledby the label; each chip is .chip.sm with aria-pressed; the selected chip uses .chip.sel (' + cssRule('.chip.sel') + '). Tapping a chip counts as the customer\'s own choice (it wins over pre-fill) and focus stays on the chip.', { size: 18 }));
push(imgP('K-chipfield.png', 330, 120), cap('C01 First-time buyer? chips'));
push(H2('1.7 Inflation chips: three states'));
const IU = data.infl.unset;
push(P('Inflation is the customer\'s own choice and is **blank until picked**. Results that need it show "' + require('./spec').NO + '" instead of a number, and goals in today\'s money are blocked until a rate is chosen. One rate is shared by every tool, Your assumptions and the plan. Shown on ' + M.INFL_TOOLS.filter(x => !M.ADJ_TOOLS.includes(x)).map(NUM).sort().join(', ') + ', and on ' + M.ADJ_TOOLS.map(NUM).join(', ') + ' when "Adjust for inflation" is on; also at the top of Your assumptions (Prices & growth) and in the Add to my plan sheet when a goal is blocked.'));
push(table([2300, W - 2300], ['Part', 'Copy (verbatim)'], [['Title', IU.title], ['Help', IU.help], ['Chip 1', IU.chips[0].t + ' (sets ' + F.nbFmt(M.INFL.std * 100) + '%)'], ['Chip 2', IU.chips[1].t + ' (sets ' + F.nbFmt(M.INFL.ie * 100) + '%; source label "' + M.INFL.src + '")'], ['Chip 3', IU.chips[2].t], ['Own rate', data.infl.other.other + ' with a % value box (0 to 10, decimals; hints "Max 10%" / "Min 0")'], ['Collapsed line', data.infl.collapsed.note + ' ("Change" is a link that re-opens the chips)']], { size: 15 }));
push(table([1900, 2600, W - 4500], ['State', 'What shows', 'Behaviour'], [['1. Not chosen', 'Card with title, help and three chips, none pressed (aria-pressed="false")', 'Results show "Enter your inflation rate"; "Add to my plan" says "Choose an inflation rate first" for today\'s-money goals.'], ['2. Chosen', 'In a calculator the card closes and the collapsed line shows under the result. After "Change" (or in Your assumptions) the chosen chip is pressed (.chip.sel).', 'Choosing a chip sets the rate everywhere and saves a plan version "Inflation: 2%".'], ['3. Other', '"Other" pressed and the own-rate box "' + data.infl.other.other + '" (starts at 2.5%)', 'Typing commits the rate (0–10%).']], { size: 15 }));
push(imgGrid([{ file: 'K-infl-1-unset.png', caption: '1. Not chosen' }, { file: 'K-infl-2-chosen.png', caption: '2. Chosen (2%, after Change)' }, { file: 'K-infl-3-other.png', caption: '3. Other with own rate' }], 3, 300));
push(imgP('K-infl-collapsed.png', 300, 240), cap('After choosing in a calculator: the result updates; the "Prices rising … · Change" line sits under the card'));
push(H2('1.8 Tags, switch and tip'));
push(table([2300, W - 2300], ['Component', 'Specification'], [['Tag (.tag)', cssRule('.tag')], ['"From your statement"', '.tag.doc (var(--ok-l) / var(--ok-t)); after the label text in a calculator, on each input filled from an uploaded statement.'], ['"From your statement (corrected)"', 'Your finances only: "✅ From your statement (corrected)" when the customer changed a value on the confirm screen; uncorrected values show "✅ From document · 95%".'], ['Confidence (confirm screen)', '"✓ 95% sure" (.tag.doc) at 80% or more; "⚠️ Check this · 76% sure" (.tag.look) below 80%; optional values add "If shown · clear it if not".'], ['Suggested (Your assumptions)', '"Suggested · change if you like" (.tag.pre: var(--sea-l) / var(--sea-d)).'], ['Statement precedence (Your finances)', '"You typed €X. Your statement says €Y; we\'re using that." In calculators the stated figure is named in the copy: "From your statement." / "(from your statement)".'], ['Tip note (.note)', cssRule('.note') + ' Only C11: "💡 Ideal emergency fund: 6 months of your monthly spending."'],
  ['"Adjust for inflation" switch (C10, C18)', 'Chip with role="switch", aria-checked. Off: "Adjust for inflation"; on: "✓ Adjust for inflation". Helper: "Show the result in today\'s money". Off by default, remembered per tool.']], { size: 15 }));
push(imgGrid([{ file: 'K-switch-off.png', caption: 'Switch off' }, { file: 'K-switch-on.png', caption: 'Switch on' }, { file: 'K-tag.png', caption: '"From your statement" tag' }], 3, 120));
push(imgP('K-tip.png', 300, 300), cap('Header with the Emergency fund tip'));
push(H2('1.9 Calculator screen anatomy'));
['**Header**: "‹ Back", profile initial (aria-label "Profile and privacy"), title h2 = emoji + name, the question, the tip (C11).', '**Category eyebrow** in capitals.', '**"Adjust for inflation" row** (C10, C18).', '**Inflation chips card** (inflation tools, while no rate is chosen or when changing).', '**Inputs card**: sliders + value boxes, and choice chips, in CALCS order.', '**Result card** (navy, aria-live="polite"): eyebrow label (gold), headline, explanation line, rows.', '**"Prices rising … (your choice) · Change"** once a rate is chosen.', '**What if… card** (dashed; C01, C02, C03, C12, C27).', '**Actions**: "＋ Add to my plan" (navy small) and "Ask an expert" (ghost small).', '**Disclaimer**: "Illustrative figures, not a guarantee and not advice."'].forEach(t => push(N(t)));
push(H2('1.10 Focus and accessibility rules'));
[':focus-visible{outline:3px solid var(--sun);outline-offset:2px}; chips and buttons: 3px solid var(--ink), offset 3px.', 'Screen titles get focus on a new screen (tabindex="-1", no visible outline).', 'Sliders and value boxes are labelled by the visible label (aria-labelledby), which includes the statement tag. Chip groups are role="group" labelled by the field label; chips use aria-pressed.', 'The result region is aria-live="polite"; hints are role="status".', 'Emoji in rows, tiles and units are aria-hidden; the title emoji is not (hide it in the build).', 'Sliders have no aria-valuetext yet: add the formatted value with unit (e.g. "€60,000").', 'Tap targets: value box 44px, small buttons 44px, chips 40–46px.', 'prefers-reduced-motion: all animation off.', 'Mobile first: below 800 px wide the phone frame is dropped; on desktop the app shows in a 390×844 frame.'].forEach(t => push(B(t)));

// ---------- 2 Explore structure ----------
push(H1('2. Explore structure'));
push(P('Explore: title "Explore", subtitle "Tools, calculators and short videos. Try anything, no plan needed." Sections: What-ifs for your goals (after a plan), Calculators, Tools for you, Watch · picked for you, Focus on one area, then "Calculators and videos explain general topics. Figures are illustrative, not a guarantee and not advice."'));
push(H2('2.1 Calculators: 6 groups'));
push(P('Two-column grid of coloured tiles: emoji, group name, "{n} tools". A group page has header "{emoji} {group}", the blurb, the statement card (3 groups) and one list row per calculator (emoji, name, question, ›).'));
push(table([700, 2300, 1300, 2300, 700, W - 7300], ['Emoji', 'Group (verbatim)', 'Tile colour', 'Blurb', 'Tools', 'Calculators, in order'], M.CATS.map(c => { const l = data.calcs.filter(x => x.cat === c.id); const col = c.color.match(/--c\d/)[0]; return [c.em, c.name, col + ' ' + tokens.find(t => t[0] === col)[1], c.blurb, l.length + ' tools', l.map(x => x.n + ' ' + x.name).join('; ')]; }), { size: 15 }));
push(H2('2.2 Focus on one area'));
push(P('Topic page: "{emoji} {topic}", "{subtitle}.", then "Try the calculator" rows, a "Talk to … →" link, a statement link where it applies, videos, live sessions and "Topics explain general ideas. They are not advice."'));
push(table([600, 1400, 2400, 1900, 2200, W - 8500], ['Emoji', 'Topic', 'Subtitle', 'Expert link', 'Calculators', 'Statement link'], M.TOPICS.map(t => { const x = M.EXPERT_FOR[t[3]].toLowerCase(), a = /^[aeiou]/.test(x) ? 'an ' : 'a '; const doc = M.DOCT[t[4]];
  return [t[0], t[1], t[2], 'Talk to ' + a + x + ' →', M.TOPIC_TOOLS[t[1]].map(id => NUM(id) + ' ' + byId[id].name).join('; '), doc ? '"📄 Upload ' + (/^[aeiou]/.test(doc.what) ? 'an ' : 'a ') + doc.what + ' statement to fill in these tools →"; after upload "📄 Your ' + doc.what + ' statement is uploaded · see it →"' : '—']; }), { size: 15 }));
push(imgGrid([{ file: 'X-explore.png', caption: 'Explore (before a plan)' }, { file: 'X-topic-Mortgages.png', caption: 'Topic page: Mortgages' }, { file: 'X-cat-home-unverified.png', caption: 'Group page with statement card' }], 3, 700));
push(H2('2.3 Statement-upload cards'));
push(table([2300, W - 2300], ['Part', 'Copy and behaviour (verbatim)'], [['Card', '.card.pst on Pensions & Retirement, Home & Mortgage, Investments.'], ['Heading', '"📄 Have a {pension | mortgage} statement? Upload it and we\'ll fill in these tools for you." / "📄 Have an investment statement? …"'], ['Documents line', '"We can read: {documents joined with " · "}."'], ['Buttons', '"Upload a statement" (navy small; .pdf, .jpg, .jpeg, .png, .heic) · "Use a sample statement" (ghost small)'], ['Account gate line', '"🔐 First we\'ll secure your account (email and mobile code), so your documents stay private." (until verified)'], ['Gate', '"Secure your account" / "Before you add any money figures, we check your email and mobile once.", then email code, mobile code, optional Face ID / passkey; the upload resumes.'], ['Reading', '"Reading your statement…", file name, "Finding your {what} figures" (about 1.4 s).'], ['Confirm', '"We read these values" / "Please confirm. Change anything that looks wrong."; one row per value with a confidence tag and an editable box; "These also go into Your finances, so we won\'t ask for them again."; "Looks right, fill in my tools" (gold) · "Cancel" (ghost).'], ['After', 'Values fill Your finances and the tools; the group page and main calculator open; toast "Added to your plan too ({where})" or "Saved. Your plan will use it when you make it".'], ['Uploaded', '"✅ Uploaded: {statement title} · {date}" · "Replace statement" · "Remove statement" (toast "Statement removed. Your own figures are used again").']], { size: 15 }));
const PRE_TXT = { retire: [['C12 Retirement projection', 'Pension value today; Monthly contributions (you + employer); Target retirement age (plan age, else the statement\'s); Other yearly income (from PRSI years, rounded to €500); Growth after charges (if charges shown)'], ['C13 / C14', 'Years to retirement; Growth assumption (if charges shown)'], ['C15 / C16', 'Retirement savings ← projected value (else current value)']], home: [['C02, C04, C05, C06', 'Balance, rate, years left (Term A in C06); the statement\'s monthly repayment is used while those fields are untouched']], invest: [['C18', 'Monthly amount; Yearly fees (0, untagged, if not shown)'], ['C10', 'Amount; Yearly fees'], ['C17', 'Amount'], ['C19', 'Amount invested; Fee A'], ['C20', 'Amount; Style from shares %']] };
for (const k of ['retire', 'home', 'invest']) { const T = M.DOCT[k];
  push(H3(T.em + ' ' + T.title + ' (' + CATN[k].name + ')'));
  push(kv([['Card heading', '📄 Have ' + (/^[aeiou]/.test(T.what) ? 'an ' : 'a ') + T.what + ' statement? Upload it and we\'ll fill in these tools for you.'], ['We can read', T.reads.join(' · ')], ['Sample statement', T.title + ' · ' + T.date + (T.old ? ' (shows "Statement is over 12 months old")' : '')], ['Opens after confirming', NUM(T.open) + ' ' + byId[T.open].name]]));
  const rowsV = T.f.map(f => [f[1] + (f[4] === '%' ? ' (%)' : ''), String(f[2]), f[3] < 80 ? '⚠️ Check this · ' + f[3] + '% sure' : '✓ ' + f[3] + '% sure', f[5] ? 'Optional: "If shown · clear it if not"' : 'Required']);
  (T.text || []).forEach(t => rowsV.push([t[0], t[1], '✓ ' + t[2] + '% sure', 'Text']));
  if (T.extra) T.extra.f.forEach(f => rowsV.push([f[1], String(f[2]), '✓ ' + f[3] + '% sure', 'Card "' + T.extra.t + '": "Expected State Pension" {Expect full | Partly | Not sure}; "A full State Pension needs 40 years (2,080 weeks) of PRSI contributions and credits. You need at least 10 years of paid contributions to qualify. Check your record on MyWelfare."']));
  rowsV.push(['Statement date', T.date, T.old ? 'Tag "Statement is over 12 months old"' : '—', '—']);
  push(table([3000, 1500, 2000, W - 6500], ['Label on confirm screen (verbatim)', 'Sample value', 'Confidence tag', 'Rule'], rowsV, { size: 15 }));
  push(table([2600, W - 2600], ['Pre-fills (tag "From your statement")', 'Inputs'], PRE_TXT[k], { size: 15 })); }
push(imgGrid([{ file: 'X-gate.png', caption: 'Gate' }, { file: 'X-confirm-retire.png', caption: 'We read these values (pension)' }, { file: 'X-cat-invest-uploaded.png', caption: 'Uploaded state' }], 3, 560));
push(H2('2.4 Add to my plan and the expert doors'));
push(P('"＋ Add to my plan" opens a sheet. What it does depends on the result (the plan only takes goals in today\'s money). Text ends with "This saves a new version of your plan." after a plan, else "It will be on your timeline when you make your plan."'));
const SHK = [['borrow-fresh', 'Spending goal (C01, C02, C03, C07, C08)'], ['compound-freshInfl', 'Savings pot (C09, C10, C18, C25)'], ['compound-fresh', 'Blocked: no inflation rate (C09, C10, C18)'], ['overpay-fresh', 'Milestone (C04)'], ['emergency-fresh', 'Safety net (C11)'], ['retirement-freshInfl', 'Retirement goal update (C12)'], ['contrib-fresh', 'Pension contribution (C13, C14)'], ['lifecover-fresh', 'Protection need (C21, C22)'], ['incomegap-fresh', 'Protection need, monthly (C22)'], ['ratechange-fresh', 'No goal (C05, C06, C15–C17, C19, C20, C23, C24, C26, C28)'], ['debtpay-fresh', 'No goal, debt (C27)']];
push(table([2600, W - 2600], ['Kind', 'Sheet copy, verbatim (example values; pieces separated by " | ")'], SHK.map(([k, t]) => [t, data.sheets[k].join(' | ')]), { size: 15 }));
push(P('Toasts after confirming: "{goal name} added to your plan" / "{goal name} added. It will be on your timeline when you make your plan", "Retirement goal updated", "Pension contribution raised by €X a month", "Noted for your adviser", "Mortgage free added to your plan".', { size: 18 }));
push(P('"Ask an expert" (calculators) and "Talk to … →" (topics) open the Experts tab with the matching expert chosen ("You chose a mortgage expert."): Home & Mortgage → Mortgage expert; Pensions & Retirement → Pension & retirement expert; Protection → Protection expert; Investments → Investment expert; Savings & Goals and Everyday Money → Financial planner.', { size: 18 }));
push(imgGrid([{ file: 'S-borrow-fresh.png', caption: 'Spending goal' }, { file: 'S-compound-fresh.png', caption: 'Blocked until inflation is chosen' }, { file: 'S-lifecover-fresh.png', caption: 'Protection need' }], 3, 420));

// ---------- 3 Rules and Your assumptions ----------
push(H1('3. Rules and Your assumptions'));
push(H2('3.1 Rules version'));
push(callout('**' + RULES_NOTE + '.** Budget 2027 is on 6 October 2026: it will require updates to the register below (tax bands and credits, USC, PRSI path, State Pension and benefit rates, pension and savings tax) and to copy that quotes them (e.g. "€299.30 a week", "€254 a week", "€259.50 a week", "DIRT at 33%", "exit tax at 38%", "€2.2m in 2026", "1% up to €1m"). Re-check every row marked "Verify" and change the version label.'));
push(P('The label is shown to customers in Your assumptions ("Rules: ' + RULES_NOTE + '. Tax rates, credits and State Pension rates are set by law, so they are not here.") and in the "Our assumptions" sheet ("Rules" row).', { size: 18 }));
push(H2('3.2 Irish rules 2026 register'));
push(P('Every statutory value in one place (RULES_IE_2026 in the prototype). Customers cannot change these; judgement values are in Your assumptions (3.3). ' + M.RULES.length + ' values, ' + M.RULES.filter(r => r[4]).length + ' marked to verify before release.', { size: 18 }));
push(table([2700, 2900, 2600, W - 8200], ['Key', 'Value', 'Effective', 'Verify'], M.RULES.map(r => [r[0], r[1].length > 90 ? r[1].slice(0, 90) + '…' : r[1], r[2], r[4] ? 'Yes' : 'No']), { size: 14, cantSplit: true }));
push(H2('3.3 Your assumptions screen'));
const AH = data.asm.prices.head.split('\n').map(s => s.trim()).filter(Boolean);
push(P('Opened from Me ("🧮 Your assumptions · Prices, growth, retirement and safety-net settings") and from the plan what-if ("Your assumptions · prices, growth, retirement and safety-net settings"). Header: title "' + AH.find(x => x === 'Your assumptions') + '", subtitle "' + AH[AH.length - 1] + '". Four collapsible cards (details/summary): ' + M.ASM_GRP.map(g => '"' + g[1] + '"').join(', ') + '; "Prices & growth" opens first. The Prices & growth card starts with the inflation chips (1.7, required pick) and the "Growth assumptions set" toggle (Standard / Cautious). Then ' + Object.keys(M.ASM).length + ' inputs covering the 27 customer-choice items B1–B27. Every input starts at the suggested value.'));
push(table([2300, W - 2300], ['Part', 'Copy and behaviour (verbatim)'], [['Status line (suggested)', '"Suggested · change if you like" (.tag.pre)'], ['Status line (changed)', '"' + data.asm.mine[0].fields.find(f => f.k === 'retireMult').status + '" (example after typing 30 in the retirement target): "Your choice" in bold, "Use suggested" is a link (toast "Back to the suggested value")'], ['Status line (optional, no value)', '"Optional"'], ['Guidance', 'One .small line under each input (verbatim in the tables).'], ['Number inputs', 'Value box only (no slider); % inputs are typed as percents (e.g. 4.5); hints "Max …" / "Min …" as 1.5.'], ['Choice inputs', 'Chips (aria-pressed).'], ['Budget check', 'If needs + wants + savings ≠ 100%: note "' + (data.asm.budgetNote || '') + '"'], ['Footer', data.asm.prices.foot.join(' · ') + ' ("Use all suggested values" is a ghost button)'], ['Growth set copy', 'Standard: "Standard uses typical long-run growth. Cautious assumes slower growth, so results are lower but safer. Growth is never guaranteed. Inflation is your own choice, below." Cautious: "Cautious assumes slower growth, so results are lower but safer. Growth is never guaranteed. Inflation is your own choice, below."']], { size: 15 }));
const asmShown = (g, k, d) => { const f = data.asm[g].dom[0].fields.find(x => x.k === k); let v;
  if (f.chips.length) v = (f.chips.find(x => x.pressed === 'true') || {}).t; else { const bx = f.box; v = bx.val === '' ? 'Not set' : bx.suf === '%' ? bx.val + '%' : bx.pre === '€' ? '€' + bx.val : bx.pre === 'age ' ? 'age ' + bx.val : bx.suf === 'yrs' ? bx.val + ' years' : bx.val; }
  return v + (d.opt ? ' (blank by default: the box shows 0, status "Optional")' : v !== d.sugTxt && d.sugTxt !== 'Not set' ? ' (written as "' + d.sugTxt + '")' : ''); };
const asmRange = d => d.t === 'choice' ? d.o.map(o => '"' + o[1] + '"').join(' / ') : d.t === 'pct' ? F.nbFmt(d.min) + '% to ' + F.nbFmt(d.max) + '%' : d.t === 'eur' ? F.eur(d.min) + ' to ' + F.eur(d.max) : F.nbFmt(d.min) + ' to ' + F.nbFmt(d.max);
const asmCtl = d => d.t === 'choice' ? 'Chips' : d.t === 'pct' ? 'Box, suffix "%"' : d.t === 'eur' ? 'Box, prefix "€"' : d.t === 'yrs' ? 'Box, suffix "yrs"' : d.t === 'age' ? 'Box, prefix "age"' : 'Box, no unit';
for (const [g, gt] of M.ASM_GRP) { push(H3('3.3.' + (M.ASM_GRP.findIndex(x => x[0] === g) + 1) + ' ' + gt));
  const ks = Object.keys(M.ASM).filter(k => M.ASM[k].g === g);
  push(table([600, 2500, 1100, 1300, 700, 1200, W - 7400], ['Code', 'Label (verbatim)', 'Control', 'Range / options', 'Step', 'Suggested', 'Guidance (verbatim) · used by'], ks.map(k => { const d = M.ASM[k]; return [d.b, d.l, asmCtl(d), asmRange(d), d.t === 'choice' ? '—' : (d.t === 'pct' ? F.nbFmt(d.step) + '%' : F.nbFmt(d.step)), asmShown(g, k, d), d.help + ' · Used by: ' + ASM_USE[k]]; }), { size: 14 }));
  const SL = require('./slices.json')[g]; push(imgGrid(SL.map((f, i) => ({ file: f, caption: 'Your assumptions · ' + gt + ' open (' + (i + 1) + ' of ' + SL.length + ')' })), 4, 640)); }
push(P('Suggested values that depend on the customer: safety net months 3 for a two-income employed couple, else 6; share you pay yourself 100% if self-employed, else 50%; plan to age 95 with a partner, else 90; start year 2027 from 1 October 2026 (2026 before). Suggested growth rates follow the Standard / Cautious set.', { size: 18 }));

// ---------- 4 Calculators ----------
const STATE_SHORT = { default: 'Default', infl: 'Inflation 2%', adjUnset: 'Switch on, no rate', adjSet: 'Switch on, 2%', plan: 'Plan pre-fill', stmt: 'Statement' };
for (const c of data.calcs) { const S = SPEC[c.id], cat = CATN[c.cat], dflt = c.states.find(s => s.key === 'default'), dom = dflt.dom, fulls = c.states.filter(s => s.kind === 'full'), edges = c.states.filter(s => s.kind === 'result'), hint = c.states.find(s => s.key === 'hint'), X = XL[c.n];
  const xnames = new Set([...X.results, ...X.plan, ...X.inputs].map(r => r.name));
  push(H1(c.n + ' ' + c.name));
  const im = inflMode(c.id);
  push(kv([['Calculator', c.n + ' · internal id "' + c.id + '" · workbook sheet "' + X.sheet + '"'], ['Category (eyebrow)', cat.name + ' (shown in capitals)'], ['Title (h2)', dom.title], ['Emoji', c.em], ['Question (subtitle)', c.q], ['Tip', c.tip ? '💡 ' + c.tip : 'None'],
    ['Inflation', im === 'switch' ? '"Adjust for inflation" switch (off by default); inflation chips when on and no rate chosen' : im === 'chips' ? 'Inflation chips while no rate is chosen (results show "Enter your inflation rate"); "Prices rising … · Change" once chosen' : 'Not used'],
    ['What if… card', c.wi.length ? c.wi.map(i => '"' + i.l + '"').join(', ') : 'None'], ['Statement upload', STMT[c.id] ? M.DOCT[STMT[c.id]].title : 'None'], ['Ask an expert goes to', expertFor(c.cat)]]));
  push(H2(c.n + ' Screens'));
  push(imgGrid(fulls.map(s => ({ file: s.file, caption: c.n + ' · ' + s.title })), Math.min(3, fulls.length), 720));
  push(H2(c.n + ' Inputs'));
  const ins = allInputs(c), fd = k => dom.fields.find(f => f.k === k);
  const onScreen = (i, f) => f.kind === 'chip' ? f.box : F.boxText(f.pre, f.box, f.suf), cdef = i => F.CHIPS[i.u] ? F.chipLabel(i.u, i.v) : F.boxText(F.PARTS[i.u][0], F.nbFmt(i.v), F.PARTS[i.u][1]);
  push(table([2600, 1150, 1100, 1250, 900, 900, 766, 1200], ['Label (verbatim)', 'Unit shown', 'CALCS default', 'On screen (default)', 'Min', 'Max', 'Step', 'Keyboard'], ins.map(i => { const f = fd(i.k), chip = !!F.CHIPS[i.u];
    return [(i.wi ? '[What if] ' : '') + i.l, F.unitDisplay(i.u), cdef(i), onScreen(i, f) + (onScreen(i, f) !== cdef(i) ? ' ⚠' : ''), chip ? '—' : F.nbFmt(i.min), chip ? '—' : F.nbFmt(i.max), chip ? '—' : F.nbFmt(i.step), chip ? 'tap (chips)' : (i.step % 1 !== 0 || i.u === '%' ? 'decimal' : 'numeric')]; }), { size: 15 }));
  if (ins.some(i => onScreen(i, fd(i.k)) !== cdef(i))) push(P('⚠ Always pre-filled (from Your assumptions, About you or the plan), so even before a plan the screen shows the "On screen" value.', { size: 16, color: MUTED }));
  push(table([2600, 2500, 1200, W - 6300], ['Label', 'Typed above max', 'Typed below min', 'Pre-fill (Your finances / plan / Your assumptions) · Statement (tag)'], ins.map(i => { const pf = (PF[c.id] || {})[i.k] || ['', ''], chip = !!F.CHIPS[i.u];
    const above = chip ? 'Not possible (chips)' : i.u === '€' ? 'Accepted up to ' + F.eur(i.max * 10) + ' (slider widens); above: clamps, hint "' + F.maxHint(i) + '"' : 'Clamps to ' + F.nbFmt(i.max) + ', hint "' + F.maxHint(i) + '"';
    return [i.l, above, chip ? 'Not possible (chips)' : 'Clamps, hint "' + F.minHint(i) + '"', (pf[0] ? pf[0] : 'Tool default') + (pf[1] ? ' · Statement: ' + pf[1] + ' → tag "From your statement"' : '')]; }), { size: 15 }));
  push(P('Pre-fill order (highest first): the customer\'s own move of this field > the uploaded statement\'s figure for this tool > Your finances (statement > typed > estimate) > the plan and Your assumptions > the tool default. Pre-filled values are clamped to the slider range and not rounded to the step.', { size: 16, color: MUTED, before: 60 }));
  if (hint) { const hf = hint.dom.fields.find(f => f.k === hint.field); push(imgP(hint.file, 330, 120), cap(c.n + ' · ' + hint.title + ' → box shows "' + hf.box + '", hint "' + hf.hint + '"')); }
  // result card
  push(H2(c.n + ' Result card'));
  push(table([1500, 5566, 2800], ['Part', 'Text (verbatim template)', 'Shown when'], S.lbl.map(([t, w]) => ['Label (eyebrow)', t, w]).concat(S.val.map(([t, w]) => ['Headline value', t, w]), S.line.map(([t, w]) => ['Line', t, w])), { size: 16 }));
  push(P('Rows, in order (label left, bold value right):', { bold: true, size: 18, before: 80 }));
  push(table([3500, 3366, 3000], ['Row label (verbatim template)', 'Row value', 'Shown when'], S.rows.map(([l, vals, w]) => [l, vals.map(([v, vw]) => v + (vw ? ' (' + vw + ')' : '')).join(' / '), w]), { size: 16 }));
  push(P('Placeholders:', { bold: true, size: 18, before: 80 }));
  push(table([2000, 1500, W - 3500], ['Placeholder', 'Format', 'Meaning (maths in sheet "' + X.sheet + '")'], Object.entries(S.ph).map(([k, v]) => ['{' + k + '}', TYPES[v[0]][0], (v[1] || k.replace(/_/g, ' ')) + (xnames.has(k) ? ' · Workbook name: ' + k : '')]), { size: 16 }));
  push(P('Add to my plan: ' + (S.goal || 'no goal ("Nothing to add · This result doesn\'t create a goal.").'), { size: 18, before: 80 }));
  // workbook pointer (d)
  push(H2(c.n + ' Workbook sheet "' + X.sheet + '"'));
  push(P('Workbook: LifeGoals-Calculators.xlsx, sheet "' + X.sheet + '" (title "' + X.title + '"). Inputs and outputs below use the workbook\'s defined names; the right-hand column shows the value behind the default screenshot (and the inflation-2% screenshot for inflation tools) so both can be checked against Excel.', { size: 18 }));
  const XIN = Object.assign({}, S.xin); const norm = s => String(s).toLowerCase().replace('what if:', '').replace(/'s/g, '').replace(/[^a-z0-9]/g, '');
  const wbIn = X.inputs.filter(i => !/^(Used_|Stmt_)/.test(i.name));
  ins.forEach(i => { if (!XIN[i.k]) { const m = wbIn.find(j => norm(j.label) === norm(i.l)); if (m) XIN[i.k] = m.name; } });
  push(table([2900, 2200, W - 5100], ['Screen input (label)', 'Workbook input name', 'Workbook label · allowed'], ins.map(i => { const m = wbIn.find(j => j.name === XIN[i.k]); return [i.l, XIN[i.k] || '—', m ? m.label + ' · ' + (m.allowed || '') : '—']; }), { size: 15 }));
  const extra = wbIn.filter(j => !Object.values(XIN).includes(j.name));
  if (extra.length) push(table([2900, 2200, W - 5100], ['Workbook-only input (no control on this screen)', 'Name', 'Comes from'], extra.map(j => [j.label, j.name, (j.group === 'YOUR INFLATION CHOICE' ? 'The inflation chips' : /Statement_Check|Statement_Uploaded|Use_Statement/.test(j.name) ? 'Statement reader' : /Goal_Years/.test(j.name) ? 'Add to my plan default' : 'Your assumptions') + (j.allowed && !/ƒx|=/.test(j.allowed) ? ' · ' + j.allowed : '')]), { size: 15 }));
  const stmtIn = X.inputs.filter(i => /^Stmt_/.test(i.name)); if (stmtIn.length) push(P('Statement inputs (filled by the document reader): ' + stmtIn.map(j => j.label + ' (' + j.name + ')').join('; ') + '.', { size: 16 }));
  const nst = [dflt].concat(c.states.filter(s => s.key === 'infl'));
  push(table([2400, 3100, 2183, 2183], ['Workbook output name', 'Workbook label', 'Default screen', nst[1] ? 'Inflation 2% screen' : '—'], X.results.concat(X.plan).filter(r => r.name in (dflt.num || {}) ).map(r => [r.name, r.label, fmtNum(dflt.num[r.name]), nst[1] ? fmtNum(nst[1].num[r.name]) : '—']), { size: 15 }));
  // screen values
  push(H2(c.n + ' Screen values in the screenshots'));
  const cols = fulls.length, lw = 2300, cw = Math.floor((W - lw) / cols), widths = [lw].concat(Array(cols).fill(cw)); widths[cols] += W - lw - cw * cols;
  const vrows = [];
  ins.forEach(i => vrows.push([i.l].concat(fulls.map(s => { const f = s.dom.fields.find(x => x.k === i.k); return f ? (f.kind === 'chip' ? f.box : F.boxText(f.pre, f.box, f.suf)) + (f.tag ? ' ★' : '') : '—'; }))));
  vrows.push(['Result label'].concat(fulls.map(s => s.dom.result.lbl))); vrows.push(['Headline value'].concat(fulls.map(s => s.dom.result.val)));
  const rowLabels = []; fulls.forEach(s => s.dom.result.rows.forEach(r => { if (!rowLabels.includes(r[0])) rowLabels.push(r[0]); }));
  rowLabels.forEach(l => vrows.push(['Row: ' + l].concat(fulls.map(s => { const r = s.dom.result.rows.find(x => x[0] === l); return r ? r[1] : '—'; }))));
  vrows.push(['Inflation line'].concat(fulls.map(s => s.dom.inflNote || '—')));
  push(table(widths, ['Field'].concat(fulls.map(s => STATE_SHORT[s.key] || s.key)), vrows, { size: 15, firstFill: true }));
  push(P('Result line, verbatim, per screenshot:', { bold: true, size: 18, before: 80 }));
  fulls.forEach(s => push(B('**' + (STATE_SHORT[s.key] || s.key) + '**: ' + s.dom.result.line)));
  if (edges.length) { push(H3('Edge-case results'));
    edges.forEach(s => { push(P('**' + s.title + '**' + (Object.keys(s.set).length ? ' (set: ' + Object.entries(s.set).map(([k, v]) => { const i = ins.find(x => x.k === k); return '"' + i.l + '" = ' + (F.CHIPS[i.u] ? F.chipLabel(i.u, v) : v); }).join(', ') + ')' : '') + (s.base !== 'fresh' ? ' · base: ' + ({ freshInfl: 'inflation 2%', sample: 'sample customer' }[s.base] || 'mortgage statement with the repayment corrected to €1,300') : ''), { size: 18, keepNext: true }));
      push(imgP(s.file, 300, 260), cap(c.n + ' · ' + s.title));
      push(table([2300, W - 2300], null, [['Label', s.dom.result.lbl], ['Headline value', s.dom.result.val], ['Line', s.dom.result.line]].concat(s.dom.result.rows.map(r => ['Row: ' + r[0], r[1]])), { size: 15, firstFill: true })); }); }
  push(H2(c.n + ' States and edge cases'));
  ['**Empty box**: ignored while typing; on leaving, the box returns to the last valid value. **Invalid characters** are stripped (1.5).', '**Out of range**: see the inputs table.', ...S.states,
   STMT[c.id] ? '**Statement**: inputs filled from the ' + M.DOCT[STMT[c.id]].what + ' statement show "From your statement". Removing the statement resets them.' : null,
   im !== 'none' ? '**Inflation**: blank until chosen; while blank, inflation-dependent values read "Enter your inflation rate" (1.7).' : null].filter(Boolean).forEach(t => push(B(t)));
  push(H2(c.n + ' Actions'));
  push(table([2400, 2400, W - 4800], ['Control (verbatim)', 'Style', 'Goes to'], [['‹ Back', 'Back pill', 'Previous Explore screen'], ['＋ Add to my plan', 'Navy small, full column width', S.goal || 'Sheet "Nothing to add"'], ['Ask an expert', 'Ghost small, full column width', 'Experts tab, ' + expertFor(c.cat) + ' chosen'], ...(im !== 'none' ? [['Inflation chips / Change', 'Small chips; text link', 'Sets the app-wide inflation rate']] : []), ...(im === 'switch' ? [['Adjust for inflation', 'Chip as switch', 'Shows the result in today\'s money']] : [])], { size: 16 }));
  push(P('Disclaimer (verbatim): "' + dom.disc + '"', { size: 18, before: 60 }));
  push(H2(c.n + ' Accessibility'));
  ['Title read as "' + dom.title + '" (hide the emoji in the build). Focus moves to the title when the screen opens.', 'Inputs are labelled by their visible labels' + (STMT[c.id] ? ', including the statement tag' : '') + '. Add aria-valuetext to sliders.', ins.some(i => F.CHIPS[i.u]) ? 'Choice chips are toggle buttons (aria-pressed) in a group labelled by the field label.' : null, 'The result card is a polite live region; debounce announcements while dragging.', c.wi.length ? 'Give the What if… card a group role named "What if…".' : null, im === 'switch' ? 'The "Adjust for inflation" chip is a switch (role="switch", aria-checked).' : null, im !== 'none' ? 'Inflation chips are toggle buttons in a group labelled "Prices rising (inflation)".' : null].filter(Boolean).forEach(t => push(B(t)));
}

// ---------- Appendix A ----------
push(H1('Appendix A. Copy deck'));
push(P('Every string on the calculator screens. Templates use {placeholders} and «A|B» options as defined in each calculator section.'));
push(H2('A.0 Shared strings'));
const SHARED = [['Back button', '‹ Back'], ['Add action', '＋ Add to my plan'], ['Expert action', 'Ask an expert'], ['Disclaimer', 'Illustrative figures, not a guarantee and not advice.'], ['What-if card title', 'What if…'], ['Tag on statement inputs', 'From your statement'], ['No inflation yet', require('./spec').NO], ['Blocked goal', 'Choose an inflation rate first · Goals are kept in today\'s money, so we need your inflation rate first. · OK'], ['Tax note (savings and investment tools)', require('./spec').BT],
  ['Inflation title', IU.title], ['Inflation help', IU.help], ['Inflation chips', IU.chips.map(x => x.t).join(' · ')], ['Own rate label', data.infl.other.other], ['Chosen line', 'Prices rising {infl} a year (your choice) · Change'],
  ['Switch (off / on)', 'Adjust for inflation / ✓ Adjust for inflation'], ['Switch helper', 'Show the result in today\'s money'], ['Switch prompt (on, no rate)', 'Pick an inflation rate to see it in today\'s money.'], ['Real-return sentence', 'Real return about {rr}% a year ({g}% «growth|growth after fees», prices rising {infl}).'],
  ['Choice chips', 'Yes · No · 1 · Cautious · 2 · Balanced · 3 · Growth · 20% · 40%'], ['Hints', 'Max €{10 × max} · Max {max}% · Max {max} yrs · Max {max} mo · Max {max} · Min €{min} · Min {min}'],
  ['Add sheet', 'Add to my plan · {emoji} {goal name} · {text} · Add it / Update it / Raise it / Note it · Not now'], ['No goal', 'Nothing to add · This result doesn\'t create a goal. · OK'],
  ['Rules version', RULES_NOTE], ['Your assumptions', 'Your assumptions · Judgement calls are yours. We suggest a value for each; change any you like. · Suggested · change if you like · Your choice · suggested {value} · Use suggested · Optional · Use all suggested values'],
  ['Explore disclaimer', 'Calculators and videos explain general topics. Figures are illustrative, not a guarantee and not advice.'], ['Topic disclaimer', 'Topics explain general ideas. They are not advice.'],
  ['Your finances tags', '✅ From your statement (corrected) · ✅ From document · {n}% · ✏️ Your figure · ≈ Estimated · Confirmed none · From your answers · ❓ Missing · ⚠️ Needs a look'], ['Precedence message', 'You typed {€ typed}. Your statement says {€ statement}; we\'re using that.']];
push(table([2600, W - 2600], ['Element', 'String (verbatim)'], SHARED, { size: 16, zebra: true }));
for (const c of data.calcs) { const S = SPEC[c.id], dom = c.states[0].dom;
  push(H2('A.' + c.n + ' ' + c.name));
  const rows = [['Title', dom.title], ['Question', c.q]]; if (c.tip) rows.push(['Tip', '💡 ' + c.tip]); rows.push(['Category eyebrow', CATN[c.cat].name]);
  allInputs(c).forEach(i => { rows.push([(i.wi ? 'What-if label' : 'Input label') + ' (' + F.UNIT_NAME[i.u] + ')', i.l]); rows.push(['  Unit and hints', F.CHIPS[i.u] ? F.CHIPS[i.u].map(x => x[1]).join(' · ') : (F.PARTS[i.u][0] ? 'Box prefix "' + F.PARTS[i.u][0].trim() + '" · ' : F.PARTS[i.u][1] ? 'Box suffix "' + F.PARTS[i.u][1] + '" · ' : 'No unit · ') + F.maxHint(i) + ' · ' + F.minHint(i)]); });
  S.lbl.forEach(([t]) => rows.push(['Result label', t])); S.val.forEach(([t]) => rows.push(['Headline value', t])); S.line.forEach(([t]) => rows.push(['Result line', t]));
  S.rows.forEach(([l, vals]) => rows.push(['Row', l + '  →  ' + vals.map(v => v[0]).join(' / ')]));
  if (S.goal) rows.push(['Add to my plan', S.goal]);
  if (inflMode(c.id) === 'switch') rows.push(['Switch', 'Adjust for inflation / ✓ Adjust for inflation · Show the result in today\'s money']); if (c.wi.length) rows.push(['What-if card title', 'What if…']);
  rows.push(['Actions', '‹ Back · ＋ Add to my plan · Ask an expert']); rows.push(['Disclaimer', dom.disc]);
  push(table([2600, W - 2600], ['Element', 'String (verbatim)'], rows, { size: 16, zebra: true })); }

// ---------- Appendix B ----------
push(H1('Appendix B. Open points'));
push(P('Fixed since the previous version and removed from this list: C20 Style decimals (now chips), C04 "Infinity yrs NaN mo" (now "—"), C01 first-time-buyer decimals and C13/C14 tax-rate values (now chips), C16 "60+" consistency, singular forms ("1 year", "1 month"), C03 "closes the gap" with the deposit saved, C06 equal terms, C25 €0 surplus, C10/C18 goal basis (both today\'s money), Excel sheet names (now "Cnn …").'));
[ '**Budget 2027 (6 October 2026)**: update the rules register (3.2), the copy that quotes statutory figures, and the version label "' + RULES_NOTE + '".',
  '**Grammar, C22 sheet**: "We note a income protection need of €… a month for your adviser." should read "an income protection need".',
  '**C22 headline**: "{n} months" has no singular ("1.0 months").',
  '**C15 at the 60-year cap**: "money lasts to about age 126" (start age + 60). Consider "beyond age {start + 60}".',
  '**C13 copy**: "less what you already pay in: €12,000 a year" shows the full age limit, not the limit minus what you already pay in.',
  '**Inflation "Other"**: tapping Other before any rate sets 2.5% and closes the chips at once; the own-rate box needs "Change".',
  '**Value-box hint**: Enter then leaving the box clears the max/min hint.',
  '**Your assumptions, PRSI years (optional)**: a blank value shows "0" in the box although it means "don\'t know". Show an empty box.',
  '**Year and month fields accept decimals** when typed (e.g. 2.5 years). Consider whole numbers only.',
  '**Explore note** in the prototype still says "29 calculators"; CALCS holds ' + NCALC + '.',
  '**Sliders lack aria-valuetext**; the emoji in screen titles is read aloud.',
  '**docs/journey-spec.md K6** still says Explore and its calculators are removed; this document follows the prototype, which includes Explore.' ].forEach(t => push(B(t)));
