// ---------- document ----------
const XL = require('./xl.json');
const children = [];
const spacer = () => new Paragraph({ children: [], spacing: { after: 60, line: 120 } });
const push = (...x) => x.forEach(y => { if (Array.isArray(y)) return push(...y); children.push(y); if (y instanceof Table) children.push(spacer()); });
const RULES_NOTE = M.RULES_VERSION;
const NCALC = data.calcs.length, LASTC = 'C' + String(NCALC).padStart(2, '0');
const callout = t => new Table({ width: { size: W, type: WidthType.DXA }, columnWidths: [W], rows: [new TableRow({ children: [cell(t, W, { fill: SUN_L, size: 18 })] })] });
const ASM_USE = { inv: 'Plan', cash: 'C08 growth; plan', pen: 'C12, C13, C14 growth (pre-fill); plan', penRet: 'C15 growth; plan', penChg: 'C12–C14 growth after charges; plan', wage: 'C12; plan', bands: 'Plan', spGrow: 'Plan', spYears: 'C12 other income (State Pension); plan', spWeek: 'Plan (your State Pension)', pSpWeek: 'Plan (partner\'s State Pension)', invGross: 'C09, C10, C17, C18, C19 growth', ownShare: 'Plan', retireMult: 'C12 target', retireSpend: 'Plan', lumpSum: 'C12 lump sum', drawRule: 'Plan', ddTiming: 'C15, C16', drawFixed: 'Plan', safetyMonths: 'C11 months; plan', mortRate: 'C01, C02, C04, C05, C06, C07, C23 rate; plan', cardRate: 'C27 APR; plan', loanRate: 'C28 APR; plan', cashYears: 'Plan', investShare: 'Plan', saveShare: 'Plan', noAnswer: 'Plan', lifeShare: 'C21', lifeYears: 'C21 years', survivor: 'C21 survivor\'s pension', budgetNeeds: 'C26', budgetWants: 'C26', budgetSave: 'C26', rentRise: 'C07', houseGrow: 'C07 house prices', upkeep: 'C07', buyFees: 'C01, C03, C07', depEarn: 'C07', riskMu1: 'C16, C20', riskMu2: 'C16, C20', riskMu3: 'C16, C20', riskVol1: 'C20', riskVol2: 'C20', riskVol3: 'C20', planEnd: 'C15; plan', startYear: 'Plan' };
const fmtNum = v => typeof v === 'number' ? String(+v.toFixed(4)) : String(v);
const chipBox = (i, f) => f && f.kind === 'chip' ? f.box : null;

// Cover
push(new Paragraph({ children: [run('LifeMap', { size: 28, bold: true, color: SEA_D })], spacing: { before: 2200, after: 120 } }),
  new Paragraph({ children: [run('Calculators: UI/UX build specification', { size: 52, bold: true, color: INK })], spacing: { after: 200 } }),
  new Paragraph({ children: [run('An exact-replica specification of every calculator in the LifeMap customer journey prototype (' + NCALC + ' calculators, C01 to ' + LASTC + '), the inflation chips and the Your assumptions screen', { size: 26, color: MUTED })], spacing: { after: 500 } }),
  kv([['Source of truth', 'LifeGoals-Customer-Journey-Prototype.html (CALCS, calculator screen V.CALC, fieldR / fieldC inputs, calcOut result card, inflChoice, the "Adjust for inflation" switch, statement uploads DOCT, Your assumptions ASM, rules register RULES_IE_2026)'], ['Maths reference', 'LifeGoals-Calculators.xlsx. Sheet "Cnn …" holds the maths for calculator Cnn (e.g. "C01 Borrowing").'], ['Built from', 'Prototype commit e1cbc5a (journey-spec §14, §15 example cards, statuses and gate names, and §16 LifeMap name and cover) and the workbook committed with this document, branch claude/simplify-customer-journey-zqxep3. File names keep "LifeGoals" for now (§16).'], ['Your finances', 'docs/journey-spec.md §15: "Not sure? See an example" cards (never fill a field); statuses ✅ From document · ✏️ Your figure · ❓ Missing; precedence document > typed > Missing; "Worked out from your figures" for calculations from the customer\'s own figures'], ['Value types', 'docs/journey-spec.md §14: set by law ("Set by Government · 2026", not editable); usual range ("Usually between X and Y (source)"); personal choice (blank, "Generally the standard is X (source). Choose what you want to use." and a "Use the standard (X)" chip)'], ['Rules version', RULES_NOTE + '. Budget 2027 (6 October 2026) will require updates.'], ['Prepared for', 'Pooja Tirupati, Proposition owner'], ['Prepared by', 'UI/UX design, LifeMap team'], ['Date', '6 October 2026'], ['Status', 'Guidance, not advice. All figures are illustrative.']]),
  brk());
push(new Paragraph({ heading: HeadingLevel.HEADING_1, children: [new TextRun({ text: 'Contents', font: FONT })], spacing: { after: 160 } }), new TableOfContents('Contents', { hyperlink: true, headingStyleRange: '1-1' }));
push(H1('Purpose and how to use this document'),
  P('This document lets a designer and developer rebuild every Explore calculator exactly as it behaves in the prototype: the same words, the same numbers, the same limits and the same states. Every label, default, limit and line of copy was taken from the prototype source and then checked automatically against the live screen (see uiux-spec-check.md).'),
  callout('**Rules version: ' + RULES_NOTE + '.** Every statutory figure (tax bands, USC, PRSI, State Pension and benefit rates, pension limits, stamp duty, Central Bank limits, DIRT and exit tax) comes from one register (section 3.2). **Budget 2027 (6 October 2026) will require updates** to that register and to any copy that quotes those figures (marked in this document where they appear).'),
  H3('How to use it'),
  B('**Design system** (section 1): tokens, type, components (slider + value box, choice chips, the inflation chips in their three states, tags, switch) and accessibility rules shared by every calculator.'),
  B('**Explore structure** (section 2): the 6 calculator groups, "Focus on one area" topics, statement-upload cards and the Add to my plan sheet.'),
  B('**Rules and Your assumptions** (section 3): the rules version, the Irish rules 2026 register, and the "Your assumptions" screen with every customer-choice input.'),
  B('**Your finances** (section 4): the "Not sure? See an example" card with all ' + require('./ex.json').cards.length + ' card texts, the statuses, data precedence, the checklists and how missing or worked-out figures show in the calculators (journey-spec §15).'),
  B('**LifeMap name and cover** (section 5): the new cover and the other journey-spec §16 changes the calculators touch.'),
  B('**One section per calculator** (C01 to ' + LASTC + ', in CALCS order): screenshots, inputs, the result card copy with {placeholders}, the matching workbook sheet with its input and output names, states, actions and accessibility.'),
  B('**Maths lives in the workbook.** Placeholders use the workbook\'s defined names where one exists (e.g. {Home_Price}), so design, engineering and the workbook stay aligned.'),
  B('**Appendix A** is the copy deck; **Appendix B** lists open points still to decide.'),
  H3('Conventions'),
  table([2300, W - 2300], ['Notation', 'Meaning'], [
    ['{Name}', 'A dynamic value. Format and meaning are in the calculator\'s placeholder table. Names in the workbook are marked "Workbook name".'],
    ['«A|B»', 'One of the options, chosen by the rule in "Shown when". An empty option («text|») means nothing is shown.'],
    ['★', 'In screen-value tables: the input shows the green "From your statement" tag.'],
    ['Verbatim', 'Quoted text and the copy columns are exact, including straight apostrophes (\'), ×, ·, …, and the minus sign − (U+2212) in negative or signed euro amounts.'],
    ['Default state', 'The calculator opened from Explore before a plan with nothing chosen yet (journey-spec §14): assumption inputs are blank with the tag "Not chosen yet" and the result card reads "Choose your … to see this". "Choices made" is the same screen after the standards are used and the example values typed into the remaining blanks; most result copy is specified from that state.'],
    ['Screenshots', '390 px wide (device scale 2), full screen length; on a 390×844 phone the content scrolls between the fixed header and the tab bar.'],
  ], { size: 15 }),
  H3('Value formats'),
  table([1700, 2000, W - 3700], ['Format', 'Name', 'Rule'], Object.entries(TYPES).map(([k, v]) => [k, v[0], v[1]]), { size: 15 }));

// ---------- 1 Design system ----------
push(H1('1. Design system'));
push(P('Visual language: the "Teal & Navy" theme. Values below are copied verbatim from the prototype CSS.'));
push(H2('1.1 Colour tokens'));
const hexOf = v => (v.match(/^#([0-9A-Fa-f]{6})$/) || [])[1];
push(table([1900, 1500, 900, W - 4300], ['Token', 'Value', 'Swatch', 'Use'], tokens.filter(t => !/^--f[hb]$/.test(t[0])).map(([k, v]) => [k, v, hexOf(v) ? cell('', 900, { fill: hexOf(v) }) : '—', TOKEN_USE[k] || (/-t$/.test(k) ? 'Status text colour (passes 4.5:1 on white and on its -l tint)' : /-l$/.test(k) ? 'Status tint (background)' : /^--(good|nudge|alert|sunny|showers|storm|ok|dip|gap)/.test(k) ? 'Status fill (fills only, never text)' : /^--(plain|mark)/.test(k) ? 'Header gradient / brand mark' : '')]), { size: 15 }));
push(P('Other fixed colours on calculator screens: result-card body text #DCE7F2; result-card row divider rgba(255,255,255,.14); what-if card border #B9C9D6 (dashed); value-box underline #8CC7BF (dashed); statement card border #B5E3DB; page behind the phone #E4ECE8; neutral tag background #EEF2F0; gold gradient top #F7C24F.', { size: 18, before: 80 }));
push(H2('1.2 Typography'));
push(table([2200, W - 2200], ['Item', 'Value (verbatim)'], [['Heading font (--fh)', tokens.find(t => t[0] === '--fh')[1]], ['Body font (--fb)', tokens.find(t => t[0] === '--fb')[1]], ['Web font load', 'Google Fonts: Bricolage Grotesque 500, 700, 800; Figtree 400, 500, 600, 700, 800; display=swap'], ['Heading rule', 'h1, h2, h3: font-family var(--fh); letter-spacing -.01em']]));
const TS = [['Screen title (h2.t)', 'h2.t', 'Bricolage Grotesque'], ['Question / subtitle (.sub)', '.sub', 'Figtree'], ['Category eyebrow (.eyebrow)', '.eyebrow', 'Figtree'], ['Field label (.flabel)', '.field>label,.flabel', 'Figtree'], ['Small text (.small)', '.small', 'Figtree'], ['Tip note (.note)', '.note', 'Figtree'], ['Disclaimer (.disc)', '.disc', 'Figtree'], ['Tag (.tag)', '.tag', 'Figtree'], ['Chip (.chip)', '.chip', 'Figtree'], ['Hint (.nbhint)', '.nbhint', 'Figtree'], ['List row title (.goal b)', '.goal b', 'Figtree']];
const ruleFor = s => { try { return cssRule(s); } catch (e) { const m = HTML.match(new RegExp(s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&') + '\\{([^}]*)\\}')); return m ? m[1] : ''; } };
push(table([2600, 1700, W - 4300], ['Element', 'Font', 'CSS (verbatim)'], TS.map(([n, s, f]) => [n, f, ruleFor(s)]).concat([['Result headline value', 'Bricolage Grotesque', 'font-family:var(--fh);font-size:36px;font-weight:800;margin:4px 0'], ['Result line', 'Figtree', 'margin:0;font-size:14px;line-height:1.5;color:#DCE7F2'], ['Result rows', 'Figtree', 'justify-content:space-between;border-top:1px solid rgba(255,255,255,.14);padding:8px 0;margin-top:8px;font-size:13.5px (value bold)'], ['Result eyebrow', 'Figtree', '.eyebrow with color:var(--sun)']]), { size: 15 }));
push(H2('1.3 Radii, shadows and spacing'));
push(table([2600, W - 2600], ['Element', 'CSS (verbatim)'], [['Card (.card)', cssRule('.card')], ['Card stack', cssRule('.card+.card')], ['Calculator cards', 'Inputs and inflation cards: margin-bottom:12px. What-if card: margin-top:12px;border:1.5px dashed #B9C9D6;box-shadow:none'], ['Result card', '.card with background:var(--ink);color:#fff'], ['Statement card (.card.pst)', cssRule('.card.pst')], ['Field (.field)', cssRule('.field')], ['Label row (.flabel)', cssRule('.field>label,.flabel')], ['Screen scroll area (.scroll)', cssRule('.scroll')], ['Header (.sky)', cssRule('.sky')], ['Two-column grid (.grid2)', cssRule('.grid2')], ['List row (.goal)', cssRule('.goal')], ['Tip note (.note)', cssRule('.note')], ['Phone frame (presentation)', cssRule('.phone')]], { size: 15 }));
push(H2('1.4 Buttons'));
push(table([2300, W - 2300], ['Style', 'CSS (verbatim)'], [['Primary: gold with navy text (.btn)', cssRule('.btn')], ['Primary hover', cssRule('.btn:hover')], ['Primary pressed', cssRule('.btn:active')],
  ['Navy small (.btn.sm): "＋ Add to my plan", "Upload a statement"', '.btn.sm{background:var(--ink);color:#fff;box-shadow:none} .btn.sm{min-height:44px;font-size:14px;width:auto;padding:0 18px}; hover var(--ink2); width:100% on calculators'],
  ['Outline / ghost (.btn.ghost): "Ask an expert", "Use a sample statement", "Not now", "Use the standard for all of these"', cssRule('.btn.ghost') + ' hover: border-color:var(--ink)'], ['Disabled', '.btn[disabled]{opacity:.45;cursor:not-allowed}'], ['Text link (.link)', cssRule('.link')], ['Back button (.backb)', cssRule('.backb') + ' Text: "‹ Back"']], { size: 15 }));
push(P('Gold primary is used for the main call to action in sheets and flows ("Add it", "Update it", "Raise it", "Note it", "OK", "Looks right, fill in my tools"). On the calculator the two actions are small: navy "＋ Add to my plan" and ghost "Ask an expert".', { size: 18 }));
push(imgP('K-actions.png', 340, 200), cap('Calculator actions'));
push(H2('1.5 Slider with editable value box'));
push(P('Every numeric input is a labelled range slider with an editable value box at the right of the label.'));
push(table([2300, W - 2300], ['Part', 'Specification (verbatim CSS)'], [['Slider', cssRule('input[type=range]') + ' Attributes: min, max = max(slider max, current value), step, value, aria-labelledby the label.'], ['Value box (.nbox)', cssRule('.nbox')], ['Value input (.nbox .nb)', '.nbox .nb{border:0;background:transparent;font:inherit;font-weight:800;color:var(--sea-d);text-align:right;padding:4px 0;min-width:2.6ch;max-width:16ch;box-sizing:content-box}; width (max(2, characters) + 0.6)ch'], ['Box focus', '.nbox:focus-within{border-bottom:2px solid var(--sea-d);background:var(--sea-l);border-radius:6px 6px 0 0}'], ['Unit (.nbu)', 'aria-hidden. € before; % after; "yrs" after; "mo" after; "age " before; plain numbers none.'], ['Hint (.nbhint)', '.nbhint{display:block;font-size:12px;color:var(--nudge-t)} .nbhint:empty{display:none}; role="status" aria-live="polite"']], { size: 15 }));
['**Drag**: snaps to the step; the box shows the value (en-IE grouping, up to 4 decimals); the result updates live.', '**Type**: tapping selects the text; the result updates live once the text is a number; Enter or leaving the box commits and re-formats.', '**Typed precision is kept**; the step applies only when dragging. Pre-filled values off the step show exactly in the box while the thumb sits at the nearest step; results use the box value.', '**Parsing**: only digits, ".", "," and "-" count; commas are thousand separators. Empty, "-" or "." is ignored while typing; on commit the box returns to the last valid value.', '**€ fields above the slider top**: accepted up to 10 × the slider maximum; the slider widens. Above that: clamps, hint "Max €…".', '**Other units** clamp to the slider range; hint "Max 8%", "Max 35 yrs", "Max 12 mo", "Max 70".', '**Below the minimum**: clamps; hint "Min €15,000" (euros) or "Min 1" (others, no unit).', '**Hint timing**: shows as soon as the text passes a limit and stays after Enter or leaving the box; clears on the next in-range value.', '**Whole numbers only**: years, months and ages with a whole-number step round a typed decimal and show the hint "Whole numbers only" (e.g. 2.5 → 3).', '**Touched fields win** over any pre-fill for the session; a new statement upload resets the tool to the statement.', '**Keyboard**: inputmode="decimal" when the step has decimals or the unit is %, else "numeric".'].forEach(t => push(B(t)));
push(imgGrid([{ file: 'K-focus.png', caption: 'Value box focused' }, { file: 'C02-hint.png', caption: 'Max hint on a rate field' }, { file: 'K-widen.png', caption: '€ above the slider top' }], 3, 140));
push(H2('1.6 Inputs not chosen yet, the standard chip and the result gate'));
const DB = byId.borrow.states[0].dom, DBL = DB.fields.find(f => f.kind === 'blank');
push(P('Journey-spec §14: assumption inputs (usual-range values, personal choices, retirement ages) start blank until the customer chooses. Their own data (a statement, Your finances, the plan) fills them where it exists.'));
push(table([2300, W - 2300], ['Part', 'Specification (verbatim)'], [['Blank input', 'Label + tag "Not chosen yet" for a §14 choice, or "Not added yet" for a personal figure missing from Your finances (both .tag.look: var(--gap-l) / var(--gap-t)); an empty value box (no slider until a value is set); a guidance line (.small) under it; the hint line.'], ['Guidance, usual range', 'Usually between {low} and {high} ({source}). Example: "' + DBL.guide + '"'], ['Guidance, personal choice', 'Generally the standard is {X} ({source}). Choose what you want to use.'], ['Standard chip', '"Use the standard ({X})" (.chip.sm): one tap fills the standard and counts as the customer\'s choice. Only for personal choices; usual-range values and retirement ages have none.'], ['Retirement ages', '"' + M.RETIRE_HELP + '" Never defaulted.'], ['After choosing', 'The tag goes and the slider appears; a usual-range input keeps its guidance line under the slider.'], ['Result gate', 'In place of the result card: eyebrow "' + DB.gate.eyebrow + '", bold "Choose your {item} to see this" (e.g. "' + DB.gate.b + '"), or "Add {item} to see this" when a personal figure is missing from Your finances (e.g. "' + require('./ex.json').calc['repayment-noyears'].dom.gate.b + '", section 4.7). Each input has its own natural name (e.g. C06 "' + require('./ex.json').calc['term-noyears'].dom.gate.b + '"), then "Also still to add or choose: {items}." (e.g. "' + DB.gate.also + '"). No numbers are shown.'], ['Add to my plan while gated', 'Toast "Choose {item} first" / "Add {item} first"; no sheet opens.'], ['Assumptions this tool uses', 'A collapsible card above the result (open while something is missing): summary "Assumptions this tool uses · {n} to choose"; the plan-wide Your assumptions inputs the tool reads; "Use the standard for all of these" when a personal choice is missing; note "These are your plan-wide choices: changing one here changes it everywhere."']], { size: 15 }));
push(imgGrid([{ file: 'K-blank.png', caption: 'Blank usual-range input (C01 Interest rate)' }, { file: 'K-gate.png', caption: 'Result gate (C01)' }, { file: 'C07-asm.png', caption: 'Assumptions this tool uses (C07)' }], 3, 300));
push(H2('1.7 Choice chips for whole-number inputs'));
push(P('Inputs that can only take a few whole values are chips, never sliders, so a value such as 0.5 or 2.5 cannot be entered.'));
push(table([2200, 3400, W - 5600], ['Input type', 'Chips (verbatim)', 'Used in'], [['Yes / No', '"Yes" (1) · "No" (0)', 'C01 First-time buyer?; C21 Is the mortgage cleared by mortgage protection? (most are)'], ['Style', '"1 · Cautious" · "2 · Balanced" · "3 · Growth"', 'C20 Style'], ['Tax rate', '"20%" · "40%"', 'C13, C14 Your tax rate']], { size: 15 }));
push(P('Markup: the label is a .flabel span; the chips sit in .chips with role="group" aria-labelledby the label; each chip is .chip.sm with aria-pressed; the selected chip uses .chip.sel (' + cssRule('.chip.sel') + '). Tapping a chip counts as the customer\'s own choice (it wins over pre-fill) and focus stays on the chip.', { size: 18 }));
push(imgP('K-chipfield.png', 330, 120), cap('C01 First-time buyer? chips'));
push(H2('1.8 Inflation chips: three states'));
const IU = data.infl.unset;
push(P('Inflation is the customer\'s own choice and is **blank until picked**. Results that need it show "' + require('./spec').NO + '" instead of a number, and goals in today\'s money are blocked until a rate is chosen. One rate is shared by every tool, Your assumptions and the plan. Shown on ' + M.INFL_TOOLS.filter(x => !M.ADJ_TOOLS.includes(x)).map(NUM).sort().join(', ') + ', and on ' + M.ADJ_TOOLS.map(NUM).join(', ') + ' when "Adjust for inflation" is on; also at the top of Your assumptions (Prices & growth) and in the Add to my plan sheet when a goal is blocked.'));
push(table([2300, W - 2300], ['Part', 'Copy (verbatim)'], [['Title', IU.title + ' + tag "Not chosen yet" (until chosen) or "Your choice"'], ['Help', IU.help], ['Chip 1', IU.chips[0].t + ' (sets ' + F.nbFmt(M.INFL.std * 100) + '%; the personal-choice standard)'], ['Chip 2', IU.chips[1].t + ' (sets ' + F.nbFmt(M.INFL.ie * 100) + '%: "Ireland today" is one figure everywhere, the latest CSO release with its month and index)'], ['Chip 3', IU.chips[2].t], ['Own rate', data.infl.other.other + ' with a % value box (0 to 10, decimals; hints "Max 10%" / "Min 0"); empty until typed'], ['Collapsed line', data.infl.collapsed.note + ' ("Change" is a link that re-opens the chips)']], { size: 15 }));
push(table([1900, 2600, W - 4500], ['State', 'What shows', 'Behaviour'], [['1. Not chosen', 'Card with title, tag "Not chosen yet", help and three chips, none pressed', 'Results show "' + require('./spec').NO + '" (or the sentence "Choose your inflation rate to …"); "Add to my plan" says "Choose an inflation rate first" for today\'s-money goals; "Use the standard for all of these" also sets 2%.'], ['2. Chosen', 'In a calculator the card closes and the collapsed line shows under the result. After "Change" (or in Your assumptions) the chosen chip is pressed (.chip.sel) and the tag reads "Your choice".', 'Choosing sets the rate everywhere and saves a plan version "Inflation: 2%".'], ['3. Other', '"Other" pressed and the own-rate box "' + data.infl.other.other + '"; the card stays open', 'Typing commits the rate (0–10%).']], { size: 15 }));
push(imgGrid([{ file: 'K-infl-1-unset.png', caption: '1. Not chosen' }, { file: 'K-infl-2-chosen.png', caption: '2. Chosen (2%, after Change)' }, { file: 'K-infl-3-other.png', caption: '3. Other with own rate' }], 3, 300));
push(imgP('K-infl-collapsed.png', 300, 240), cap('After choosing in a calculator: the result updates; the "Prices rising … · Change" line sits under the card'));
push(H2('1.9 Tags, switch and tip'));
push(table([2300, W - 2300], ['Component', 'Specification'], [['Tag (.tag)', cssRule('.tag')], ['"From your statement"', '.tag.doc (var(--ok-l) / var(--ok-t)); after the label text in a calculator, on each input filled from an uploaded statement.'], ['"From your statement (corrected)"', 'Your finances only: "✅ From your statement (corrected)" when the customer changed a value on the confirm screen; uncorrected values show "✅ From document · 95%".'], ['Confidence (confirm screen)', '"✓ 95% sure" (.tag.doc) at 80% or more; "⚠️ Check this · 76% sure" (.tag.look) below 80%; optional values add "If shown · clear it if not".'], ['Value-type tags', '"Not chosen yet" (.tag.look), "Your choice" (.tag.doc), "Set by Government · 2026" (.tag.none), "How the plan works" (.tag.typed), "Usually {low}–{high}" (.tag.pre) in What your plan assumes.'], ['Statement precedence (Your finances)', 'Document > typed > Missing (§15). "You typed €X. Your statement says €Y; we\'re using that." In calculators the stated figure is named in the copy: "From your statement." / "(from your statement)".'], ['Your finances statuses', '"✅ From document · 95%", "✅ From your statement (corrected)", "✏️ Your figure", "✏️ Your figure · from your answers", "❓ Missing", "⚠️ Needs a look" (section 4.5). "≈ Estimated" and "Confirmed none" are removed.'], ['"Worked out from your figures"', '.tag.pre (var(--sea-l) / var(--sea-d)) after the label of a calculator input filled with a calculation from the customer\'s own figures (C25, C27), with the reason in a .small line under the slider (section 4.7).'], ['Tip note (.note)', cssRule('.note') + ' Only C11: "💡 Ideal emergency fund: 6 months of your monthly spending."'],
  ['"Adjust for inflation" switch (C10, C18)', 'Chip with role="switch", aria-checked. Off: "Adjust for inflation"; on: "✓ Adjust for inflation". Helper: "Show the result in today\'s money". Off by default, remembered per tool.']], { size: 15 }));
push(imgGrid([{ file: 'K-switch-off.png', caption: 'Switch off' }, { file: 'K-switch-on.png', caption: 'Switch on' }, { file: 'K-tag.png', caption: '"From your statement" tag' }], 3, 120));
push(imgP('K-tip.png', 300, 300), cap('Header with the Emergency fund tip'));
push(H2('1.10 Calculator screen anatomy'));
['**Header**: "‹ Back", profile initial (aria-label "Profile and privacy"), title h2 = emoji + name, the question, the tip (C11).', '**Category eyebrow** in capitals.', '**"Adjust for inflation" row** (C10, C18).', '**Inflation chips card** (inflation tools, while no rate is chosen or when changing).', '**Inputs card**: sliders + value boxes, and choice chips, in CALCS order.', '**Result card** (navy, aria-live="polite"): eyebrow label (gold), headline, explanation line, rows.', '**"Prices rising … (your choice) · Change"** once a rate is chosen.', '**What if… card** (dashed; C01, C02, C03, C12, C27).', '**Actions**: "＋ Add to my plan" (navy small) and "Ask an expert" (ghost small).', '**Disclaimer**: "Illustrative figures, not a guarantee and not advice."'].forEach(t => push(N(t)));
push(H2('1.11 Focus and accessibility rules'));
[':focus-visible{outline:3px solid var(--sun);outline-offset:2px}; chips and buttons: 3px solid var(--ink), offset 3px.', 'Screen titles get focus on a new screen (tabindex="-1", no visible outline).', 'Sliders and value boxes are labelled by the visible label (aria-labelledby), which includes the statement tag. Chip groups are role="group" labelled by the field label; chips use aria-pressed.', 'The result region is aria-live="polite"; hints are role="status".', 'Emoji in rows, tiles and units are aria-hidden; the title emoji is not (hide it in the build).', 'Sliders carry aria-valuetext with the formatted value and unit (e.g. "€60,000").', 'Tap targets: value box 44px, small buttons 44px, chips 40–46px.', 'prefers-reduced-motion: all animation off.', 'Mobile first: below 800 px wide the phone frame is dropped; on desktop the app shows in a 390×844 frame.'].forEach(t => push(B(t)));

// ---------- 2 Explore structure ----------
push(H1('2. Explore structure'));
push(P('Explore: title "Explore", subtitle "Tools, calculators and short videos. Try anything, no plan needed." Sections: What-ifs for your goals (after a plan), Calculators, Tools for you, Watch · picked for you, Focus on one area, then "Calculators and videos explain general topics. Figures are illustrative, not a guarantee and not advice."'));
push(H2('2.1 Calculators: 6 groups'));
push(P('Two-column grid of coloured tiles: emoji, group name, "{n} tools". A group page has header "{emoji} {group}", the blurb, the statement card (3 groups) and one list row per calculator (emoji, name, question, ›).'));
push(table([700, 2300, 1300, 2300, 700, W - 7300], ['Emoji', 'Group (verbatim)', 'Tile colour', 'Blurb', 'Tools', 'Calculators, in order'], M.CATS.map(c => { const l = data.calcs.filter(x => x.cat === c.id); const col = c.color.match(/--c\d/)[0]; return [c.em, c.name, col + ' ' + tokens.find(t => t[0] === col)[1], c.blurb, l.length + ' tools', l.map(x => x.n + ' ' + x.name).join('; ')]; }), { size: 15 }));
push(H2('2.2 Focus on one area'));
push(P('Topic page: "{emoji} {topic}", "{subtitle}.", then "Try the calculator" rows, a "Talk to … →" link, a statement link where it applies, videos, live sessions and "Topics explain general ideas. They are not advice."'));
push(table([600, 1400, 2400, 1900, 2200, W - 8500], ['Emoji', 'Topic', 'Subtitle', 'Expert link', 'Calculators', 'Statement link'], M.TOPICS.map(t => { const x = M.EXPERT_FOR[t[3]].toLowerCase(), a = /^[aeiou]/.test(x) ? 'an ' : 'a '; const doc = M.DOCT[t[4]];
  return [t[0], t[1], t[2], 'Talk to ' + a + x + ' →', M.TOPIC_TOOLS[t[1]].map(id => NUM(id) + ' ' + byId[id].name).join('; '), doc ? '"📄 Upload ' + (/^[aeiou]/.test(doc.what) ? 'an ' : 'a ') + doc.what + ' statement to fill in these tools →"; after upload "📄 Your ' + doc.what + ' statement is uploaded · see it →"' : '—']; }), { size: 15 }));
push(imgGrid([{ file: 'X-explore.png', caption: 'Explore (before a plan)' }, { file: 'X-topic-Mortgages.png', caption: 'Topic page: Mortgages' }, { file: 'X-cat-home-unverified.png', caption: 'Group page with statement card' }], 3, 700));
push(H2('2.3 Statement-upload cards'));
push(table([2300, W - 2300], ['Part', 'Copy and behaviour (verbatim)'], [['Card', '.card.pst on Pensions & Retirement, Home & Mortgage, Investments.'], ['Heading', '"📄 Have a {pension | mortgage} statement? Upload it and we\'ll fill in these tools for you." / "📄 Have an investment statement? …"'], ['Documents line', '"We can read: {documents joined with " · "}."'], ['Buttons', '"Upload a statement" (navy small; .pdf, .jpg, .jpeg, .png, .heic) · "Use a sample statement" (ghost small)'], ['Account gate line', '"🔐 First we\'ll secure your account (email and mobile code), so your documents stay private." (until verified)'], ['Gate', '"Secure your account" / "Before you add any money figures, we check your email and mobile once.", then email code, mobile code, optional Face ID / passkey; the upload resumes.'], ['Reading', '"Reading your statement…", file name, "Finding your {what} figures" (about 1.4 s).'], ['Confirm', '"We read these values" / "Please confirm. Change anything that looks wrong."; one row per value with a confidence tag and an editable box; "These also go into Your finances, so we won\'t ask for them again."; "Looks right, fill in my tools" (gold) · "Cancel" (ghost).'], ['After', 'Values fill Your finances and the tools; the group page and main calculator open; toast "Added to your plan too ({where})" or "Saved. Your plan will use it when you make it".'], ['Uploaded', '"✅ Uploaded: {statement title} · {date}" · "Replace statement" · "Remove statement" (toast "Statement removed. Your own figures are used again").']], { size: 15 }));
const PRE_TXT = { retire: [['C12 Retirement projection', 'Pension value today; Monthly contributions (you + employer); Target retirement age (plan age, else the statement\'s); Other yearly income (from PRSI years, rounded to €500); Growth after charges (if charges shown)'], ['C13 / C14', 'Years to retirement; Growth assumption (if charges shown)'], ['C15 / C16', 'Retirement savings ← projected value (else current value)']], home: [['C02, C04, C05, C06', 'Balance, rate, years left (Term A in C06); the statement\'s monthly repayment is used while those fields are untouched']], invest: [['C18', 'Monthly amount; Yearly fees (0, untagged, if not shown)'], ['C10', 'Amount; Yearly fees'], ['C17', 'Amount'], ['C19', 'Amount invested; Fee A'], ['C20', 'Amount; Style from shares %']] };
for (const k of ['retire', 'home', 'invest']) { const T = M.DOCT[k];
  push(H3(T.em + ' ' + T.title + ' (' + CATN[k].name + ')'));
  push(kv([['Card heading', '📄 Have ' + (/^[aeiou]/.test(T.what) ? 'an ' : 'a ') + T.what + ' statement? Upload it and we\'ll fill in these tools for you.'], ['We can read', T.reads.join(' · ')], ['Sample statement', T.title + ' · ' + T.date + (T.old ? ' (shows "Statement is over 12 months old")' : '')], ['Opens after confirming', NUM(T.open) + ' ' + byId[T.open].name]]));
  const rowsV = T.f.map(f => [f[1] + (f[4] === '%' ? ' (%)' : ''), String(f[2]), f[3] < 80 ? '⚠️ Check this · ' + f[3] + '% sure' : '✓ ' + f[3] + '% sure', f[5] ? 'Optional: "If shown · clear it if not"' : 'Required']);
  (T.text || []).forEach(t => rowsV.push([t[0], t[1], '✓ ' + t[2] + '% sure', 'Text']));
  if (T.extra) T.extra.f.forEach(f => rowsV.push([f[1], String(f[2]), '✓ ' + f[3] + '% sure', 'Card "' + T.extra.t + '": "Expected State Pension" {Expect full | Partly | Not sure}; "A full State Pension needs 40 years (2,080 weeks) of PRSI contributions and credits. You need at least 10 years of paid contributions to qualify. Check your record on MyWelfare."']));
  rowsV.push(['Statement date', T.date, T.old ? 'Tag "Statement is over 12 months old"' : '—', '—']);
  push(table([3000, 1500, 2000, W - 6500], ['Label on confirm screen (verbatim)', 'Sample value', 'Confidence tag', 'Rule'], rowsV, { size: 15 }));
  push(table([2600, W - 2600], ['Pre-fills (tag "From your statement")', 'Inputs'], PRE_TXT[k], { size: 15 })); }
push(imgGrid([{ file: 'X-gate.png', caption: 'Gate' }, { file: 'X-confirm-retire.png', caption: 'We read these values (pension)' }, { file: 'X-cat-invest-uploaded.png', caption: 'Uploaded state' }], 3, 560));
push(H2('2.4 Add to my plan and the expert doors'));
push(P('"＋ Add to my plan" opens a sheet. What it does depends on the result (the plan only takes goals in today\'s money). Text ends with "This saves a new version of your plan." after a plan, else "It will be on your timeline when you make your plan."'));
const SHK = [['borrow-chosen', 'Spending goal (C01, C02, C03, C07, C08)'], ['compound-chosen', 'Savings pot (C09, C10, C18, C25)'], ['compound-chosenNoInfl', 'Blocked: no inflation rate (C09, C10, C18)'], ['overpay-chosen', 'Milestone (C04)'], ['emergency-chosen', 'Safety net (C11)'], ['retirement-chosen', 'Retirement goal update (C12)'], ['contrib-chosen', 'Pension contribution (C13, C14)'], ['lifecover-chosen', 'Protection need (C21, C22)'], ['incomegap-chosen', 'Protection need, monthly (C22)'], ['ratechange-chosen', 'No goal (C05, C06, C15–C17, C19, C20, C23, C24, C26, C28)'], ['debtpay-chosen', 'No goal, debt (C27)'], ['borrow-sample', 'Spending goal after a plan (C01, sample customer)']];
push(table([2600, W - 2600], ['Kind', 'Sheet copy, verbatim (example values; pieces separated by " | ")'], SHK.map(([k, t]) => [t, data.sheets[k].join(' | ')]), { size: 15 }));
push(P('Toasts after confirming: "{goal name} added to your plan" / "{goal name} added. It will be on your timeline when you make your plan", "Retirement goal updated", "Pension contribution raised by €X a month", "Noted for your adviser", "Mortgage free added to your plan".', { size: 18 }));
push(P('"Ask an expert" (calculators) and "Talk to … →" (topics) open the Experts tab with the matching expert chosen ("You chose a mortgage expert."): Home & Mortgage → Mortgage expert; Pensions & Retirement → Pension & retirement expert; Protection → Protection expert; Investments → Investment expert; Savings & Goals and Everyday Money → Financial planner.', { size: 18 }));
push(imgGrid([{ file: 'S-borrow-chosen.png', caption: 'Spending goal' }, { file: 'S-compound-chosenNoInfl.png', caption: 'Blocked until inflation is chosen' }, { file: 'S-lifecover-chosen.png', caption: 'Protection need' }], 3, 420));

// ---------- 3 Rules and Your assumptions ----------
push(H1('3. Rules and Your assumptions'));
push(H2('3.1 Rules version'));
push(callout('**' + RULES_NOTE + '.** Budget 2027 is on 6 October 2026: it will require updates to the register below (tax bands and credits, USC, PRSI path, State Pension and benefit rates, pension and savings tax) and to copy that quotes them (e.g. "€299.30 a week", "€254 a week", "€259.50 a week", "DIRT at 33%", "exit tax at 38%", "€2.2m in 2026", "1% up to €1m"). Re-check every row marked "Verify" and change the version label.'));
push(P('Customers see the label in Your assumptions (Set by Government card: "Set by law and the same for everyone, so you can\'t change them. ' + RULES_NOTE + '.") and in "What your plan assumes" (row "Rules", tag "Set by Government · 2026").', { size: 18 }));
push(H2('3.2 Three types of value (journey-spec §14)'));
push(table([1600, 2700, 2900, W - 7200], ['Type', 'Rule', 'Wording on screen (verbatim pattern)', 'Examples'], [
  ['1. Set by law', 'Set automatically, the same for everyone, not editable.', '"' + M.T_GOV + '" (tag .tag.none)', 'Income tax bands and credits, USC, PRSI, pension relief %, earnings cap, lump-sum tax, DIRT, exit tax, Central Bank limits, full State Pension, Illness Benefit and survivor\'s pension rates'],
  ['2. Usual range', 'The customer enters theirs; the range is stated. Blank until entered (unless their own data gives it).', '"Usually between {low} and {high} ({source})." In "What your plan assumes" the tag reads "Usually {low}–{high}".', 'Mortgage rate 3.5%–4.5%, card APR 13%–23%, loan APR 6%–10%, fund charges 0.5%–1.5%, buying fees €2,500–€3,500, own State Pension, Illness Benefit'],
  ['3. Personal choice', 'No default: blank until chosen. One tap on the standard chip fills it and counts as the customer\'s decision.', '"Generally the standard is {X} ({source}). Choose what you want to use." Chip "Use the standard ({X})". Tag "' + M.T_MINE + '" once chosen.', 'Inflation, pay rises, cash, investment and pension growth, share you pay, safety-net months, withdrawal timing, retirement multiple, budget split'],
  ['Chosen individually', 'Retirement age and plan-until age are never defaulted and never part of "Use the standard for all of these".', 'Retirement age: "' + M.RETIRE_HELP + ' Choose the age you want to plan for." Plan until age: "' + M.ASM.planEnd.help + '"', '—'],
  ['How the plan works', 'Fixed modelling rules, not choices.', '"' + M.T_HOW + '" (tag .tag.typed)', 'Spare money not saved is assumed spent; order savings go to goals; known limits']], { size: 15 }));
push(P('"Use the standard for all of these" (ghost small button) fills every personal choice not made yet, including inflation (2%); helper text: "Fills every choice you haven\'t made yet with its standard. It never sets your retirement age or plan-until age: choose those yourself." Toast: "Standard used for {n} choices" (e.g. "' + (data.asm.useAllToast || '').replace(/^\W+/, '') + '"). Until a required choice is made, results read "Choose your {item} to see this". The sample customer has every plan choice made.', { size: 18 }));
push(H2('3.3 Irish rules 2026 register'));
push(P('Every figure in one place (RULES_IE_2026): it (income tax), usc, prsi, pen, ae, sp, sav, home and infl are set by law or official statistics; guide holds the usual ranges and guidance facts (type 2); std holds the standards for personal choices (type 3). ' + M.RULES.length + ' values, ' + M.RULES.filter(r => r[4]).length + ' marked to verify before release.', { size: 18 }));
push(table([2700, 2900, 2600, W - 8200], ['Key', 'Value', 'Effective', 'Verify'], M.RULES.map(r => [r[0], r[1].length > 90 ? r[1].slice(0, 90) + '…' : r[1], r[2], r[4] ? 'Yes' : 'No']), { size: 14, cantSplit: true }));
push(H2('3.4 Your assumptions screen'));
const AH = data.asm.prices.head.split('\n').map(s => s.trim()).filter(Boolean), TOP = data.asm.prices.dom.top;
push(P('Opened from Me ("🧮 Your assumptions"), the plan what-if, "Make my choices" on a gate, and "Choose" on the timeline strip. Header: "' + AH.find(x => x === 'Your assumptions') + '", subtitle "' + AH[AH.length - 1] + '".'));
push(table([2300, W - 2300], ['Part', 'Copy and behaviour (verbatim)'], [['Top card (while personal choices are missing)', '"' + TOP.b + '" (e.g., count of choices not made) · "' + TOP.p + '" · button "' + TOP.btn + '" · "' + TOP.note + '"'], ['Cards', M.ASM_GRP.map(g => '"' + g[1] + '"').join(', ') + ', then "' + M.T_GOV + '" (collapsible details; "Prices & growth" opens first)'], ['Prices & growth extras', 'The inflation chips (1.8) and "Growth assumptions set" (Standard / Cautious). Choosing a set fills pay rises, cash, investment and pension growth with its rates.'], ['Each input', 'Label + tag ("Not chosen yet" / "Your choice"); value box or chips (empty until chosen); "Use the standard (X)" chip for personal choices; one guidance line (verbatim below).'], ['Plan length card', 'Starts with Retirement age (box, prefix "age", whole numbers, 50 or your age + 1 to 75): "' + M.RETIRE_HELP + ' Choose the age you want to plan for."'], ['Budget check', 'When all three budget shares are chosen and do not total 100%: "Your budget split adds up to {n}%. It should total 100%."'], ['Set by Government card', data.asm.law.dom.groups[0].law.rows.length + ' rows (below) and "' + data.asm.law.dom.groups[0].law.note + '"']], { size: 15 }));
const typeTxt = d => d.ty === 2 ? '2 · Usual range' : d.own ? '3 · Choose yourself' : '3 · Personal choice';
const asmRange = d => d.t === 'choice' ? d.o.map(o => '"' + o[1] + '"').join(' / ') : d.t === 'pct' ? F.nbFmt(d.min) + '% to ' + F.nbFmt(d.max) + '%' : d.t === 'eur' || d.t === 'eurw' ? F.eur(d.min) + ' to ' + (d.t === 'eurw' ? '€' + (+d.max).toFixed(2) : F.eur(d.max)) : F.nbFmt(d.min) + ' to ' + F.nbFmt(d.max);
const asmCtl = d => d.t === 'choice' ? 'Chips' : d.t === 'pct' ? 'Box, suffix "%"' : d.t === 'eur' || d.t === 'eurw' ? 'Box, prefix "€"' : d.t === 'yrs' ? 'Box, suffix "yrs"' : d.t === 'age' ? 'Box, prefix "age"' : 'Box, no unit';
for (const [g, gt] of M.ASM_GRP) { push(H3('3.4.' + (M.ASM_GRP.findIndex(x => x[0] === g) + 1) + ' ' + gt));
  const G = data.asm[g].dom.groups[0];
  push(table([550, 2350, 1000, 1150, 1250, 600, W - 6900], ['Code', 'Label (verbatim)', 'Type', 'Control', 'Range / options', 'Step', 'Guidance (verbatim) · standard chip · used by'], G.fields.map(f => { const d = M.ASM[f.k];
    if (!d) return ['—', f.label, '3 · Choose yourself', 'Box, prefix "age"', '50 (or age + 1) to 75', '1', f.guide + ' · No standard chip · Used by: plan, C12, C13, C14, C15'];
    return [d.b, f.label, typeTxt(d), asmCtl(d), asmRange(d), d.t === 'choice' ? '—' : (d.t === 'pct' ? F.nbFmt(d.step) + '%' : F.nbFmt(d.step)), (f.guide || '—') + ' · ' + (f.std ? 'Chip "' + f.std + '"' : 'No standard chip') + ' · Used by: ' + (ASM_USE[f.k] || 'Plan')]; }), { size: 14 }));
  const SL = require('./slices.json')[g]; push(imgGrid(SL.map((f, i) => ({ file: f, caption: 'Your assumptions · ' + gt + ' (' + (i + 1) + ' of ' + SL.length + ')' })), 4, 640)); }
push(H3('3.4.5 ' + M.T_GOV));
push(table([2800, W - 2800], ['Row', 'Value shown (verbatim)'], data.asm.law.dom.groups[0].law.rows, { size: 15 }));
push(H2('3.5 Plan builder step 7: "Your assumptions"'));
const S7 = data.step7.text.split('\n').map(x => x.trim()).filter(Boolean);
push(P('Step 7 of 8 ("' + data.step7.head.split('\n').map(x => x.trim()).filter(Boolean)[1] + '"), under the check list and the "These details are right, as far as I know" tick, a card "' + S7[0] + '": "' + S7[1] + '" It holds, in order: the inflation chips; Retirement age; Plan until age; any usual-range values the plan needs (e.g. your partner\'s State Pension, card and loan APRs when you have those debts); then "Other choices" with "{n} of {total} not chosen yet." (e.g. "' + (S7.find(x => /not chosen yet\.$/.test(x)) || '') + '"), "Use the standard for all of these" and a collapsible "See or change each one". "See my results" stays disabled until everything is chosen; the line above it reads "Choose your {first missing item} above to see your results." (e.g. "' + data.step7.foot.split('\n')[0] + '").'));
push(imgP('P-step7.png', 300, 860), cap('Step 7 · Your assumptions card (sample customer with every choice cleared)'));
push(H2('3.6 "What your plan assumes"'));
const AS2 = data.assumeSheet;
push(P('Sheet opened from "What your plan assumes" on the results page. Title "' + AS2.title + '", intro "' + AS2.intro + '". Each row: label, a tag naming its type, and the value. Type-1 rows are folded into a collapsible "' + AS2.gov + '". Values below are for the sample customer.', { size: 18 }));
push(table([3000, 2300, W - 5300], ['Row', 'Tag (type)', 'Value (sample customer)'], AS2.rows, { size: 14 }));

// ---------- 4 Your finances (journey-spec §15) ----------
const EX = require('./ex.json');
push(H1('4. Your finances: "Not sure? See an example"'));
push(P('Journey-spec §15: every customer\'s money is different, so we never fill in a figure for them. Each Your finances field (' + EX.cards.length + ' fields across the 6 sections) has the link "Not sure? See an example". It opens a short example card built from the sample customers Aoife and Cian (SAMPLE_FIN, the same figures as the sample customer). The card never fills the field. "Not sure? Estimate for me" and "I don\'t have this" are removed everywhere.'));
push(H2('4.1 The link'));
const LK = EX.cards[0].link;
push(table([2300, W - 2300], ['Part', 'Specification (verbatim)'], [['Text', LK.text], ['Markup', '<div class="fhelp"><button class="link" data-a="fex" data-p="{field}" aria-haspopup="' + LK.haspopup + '">' + LK.text + '</button></div>'], ['Style', '.link{' + cssRule('.link') + '} .fhelp{' + cssRule('.fhelp') + '}'], ['Placement', 'Under the field: after the input, the statement note, the hint and any "Worked out from your figures" line. On choice fields, under the chips. Every one of the ' + EX.cards.length + ' fields has it (checked).'], ['What it does', 'Opens the example card for that field. The field value and its status do not change (checked for all ' + EX.cards.length + ' fields).']], { size: 15 }));
push(imgP('E-field-cash.png', 330, 200), cap('Cash savings field with the link (sample customer)'));
push(H2('4.2 Card layout'));
const C0 = EX.cards.find(c => c.k === 'cash');
push(table([2300, W - 2300], ['Part, in order', 'Specification (verbatim)'], [
  ['Container', 'Bottom sheet. .sheet-bg{' + cssRule('.sheet-bg') + '} .sheet{' + cssRule('.sheet') + '}; grab handle .grab; close button .sx (✕, aria-label "' + C0.close + '").'],
  ['1. Title', 'h2.t id="ex-t": "Example: {field label}", e.g. "' + C0.title + '".'],
  ['2. Options (choice fields only)', 'ul.small: one item per option, "<b>{option}</b>: {meaning}" (the colon and meaning are left out when the meaning is empty).'],
  ['3. Example sentence', 'p.sub id="ex-s": one sentence about Aoife and Cian with their sample figures, ending with what they enter or pick, e.g. "' + C0.sentence + '"'],
  ['4. Where to find yours', 'p.small: "📍" (aria-hidden) + bold "Where to find yours:" + one line naming the document or app, e.g. "' + C0.where + '"'],
  ['5. Enter 0', 'p.small, bold: "' + C0.zero + '" Euro-amount fields only (not on ages, years or choices), as journey-spec §15 now says.'],
  ['6. Small print', 'p.small in var(--muted): "' + C0.small + '"'],
  ['7. Button', 'Gold primary .btn: "' + C0.button + '" (closes the card).']], { size: 15 }));
push(imgGrid([{ file: 'E-card-cash.png', caption: 'Euro field: Cash savings' }, { file: 'E-card-home.png', caption: 'Choice field: Your home' }, { file: 'E-card-age.png', caption: 'Number field: Your age (no "Enter 0")' }], 3, 700));
push(imgGrid([{ file: 'E-card-life.png', caption: 'Yes / No / Not sure: Life cover' }, { file: 'E-card-sp.png', caption: 'State Pension' }, { file: 'E-card-mortPayM.png', caption: 'Monthly repayment' }], 3, 700));
push(H2('4.3 Dialog behaviour'));
const DG = EX.dialog;
['**Semantics**: role="' + C0.role + '", aria-modal="' + C0.modal + '", aria-labelledby="' + C0.labelledby + '" (the title), aria-describedby="' + C0.describedby + '" (the sentence). The link has aria-haspopup="dialog".',
 '**Opening**: tapping the link opens the card; focus moves to "' + DG.openFocus + '".',
 '**Focus trap**: Tab from "' + DG.tab2 + '" wraps to the close button (✕), Tab again returns to "' + DG.tab2 + '", Shift+Tab wraps backwards. Focus never leaves the card while it is open.',
 '**Closing**: "Got it", the ✕ button, Escape, or a tap on the dimmed backdrop. After "Got it", ✕ or Escape, focus returns to the link that opened the card (checked: "' + DG.escape.focus + '").',
 '**Never fills anything**: the field value and status are unchanged after the card closes (checked for all ' + EX.cards.length + ' fields).',
 '**Motion**: the sheet slides up (animation "up"); off under prefers-reduced-motion.'].forEach(t => push(B(t)));
push(H2('4.4 All ' + EX.cards.length + ' example cards (verbatim)'));
push(P('Every card has the title "Example: {field label}", the small print "' + C0.small + '" and the button "' + C0.button + '". The texts come from the sample customers\' figures, so they change if the sample data changes.', { size: 18 }));
const SECN = ['About you', 'Income and expenses', 'Assets', 'Liabilities', 'Protection', 'Pension'];
for (let si = 0; si < 6; si++) { const cs = EX.cards.filter(c => EX.ff[c.k].sec === si); if (!cs.length) continue;
  push(H3('4.4.' + (si + 1) + ' ' + SECN[si]));
  push(table([1700, 2100, 3000, 2266, 800], ['Card title', 'Options: meaning', 'Example sentence', 'Where to find yours', 'Enter 0 line'], cs.map(c => [c.title, c.opts.length ? c.opts.map(o => o[0] + (o[1] ? ': ' + o[1] : '')).join(' · ') : '—', c.sentence, c.where.replace(/^📍 Where to find yours: /, ''), c.zero ? 'Yes' : '—']), { size: 14 })); }
push(H2('4.5 Statuses on Your finances fields'));
const TG = EX.tags;
push(table([3000, 1500, W - 4500], ['Tag (verbatim)', 'Class', 'When'], [[TG.doc[0], '.tag.doc', 'Read from an uploaded document, with the reader\'s confidence ("' + TG.docNoConf[0] + '" when there is none)'], [TG.fixed[0], '.tag.doc', 'Read from a document and corrected by the customer on "We read these values"'], [TG.typed[0], '.tag.typed', 'Typed by the customer, including 0'], [TG.pre[0], '.tag.pre', 'Carried over from the customer\'s first answers (name, age, retirement age)'], ['From your answers', '.tag.pre', 'The partner and dependants controls in About you'], [TG.none[0], '.tag.none', 'Left blank. Counts as €0 and stays on the checklists until added'], [TG.look[0], '.tag.look', 'A figure that needs a second look (e.g. a statement over 12 months old). Shown ahead of any other tag']], { size: 15 }));
push(P('Removed by §15: "≈ Estimated" and "Confirmed none". **Data precedence**: document > customer-typed > (nothing: ❓ Missing). A statement figure is never overwritten by a later typed one: the typed figure is kept and the note reads "' + TG.docNote + '" (example). Removing the statement brings the typed figure back.', { size: 18 }));
const WO = EX.p3.liab.filter(f => f.worked);
push(P('**Worked out from your figures**: calculations from the customer\'s own figures, never guesses about the person. Shown as a small teal line (var(--sea-d), id "wo-{field}") under the field, which keeps its own status tag:', { size: 18 }));
push(table([2400, W - 2400], ['Field', 'Line (verbatim template · example)'], [['Monthly repayment (mortgage)', 'Worked out from your figures: about {€} a month, from your balance, rate and years left. Type yours to replace it. · "' + WO[0].worked + '" Shown when the balance and years left are given but no repayment.'], ['Credit cards / Other loans: monthly repayment', 'Worked out from your figures: {€} a month clears it in 5 years, because «no repayment was given (blank)|a €0 repayment wouldn\'t clear it (typed €0)|the repayment given doesn\'t cover the interest (too small)». Type yours to replace it. · "' + WO[1].worked + '"']], { size: 15 }));
push(imgP('E-p3-liab.png', 300, 900), cap('Liabilities: From document, ❓ Missing with a worked-out repayment, ✏️ Your figure (0) with a worked-out repayment'));
push(H2('4.6 Checklists'));
const CK = EX.check;
push(P('**Check your details** (plan builder step 7) lists only ⚠️ Needs a look and ❓ Missing items; a section left completely empty is one row ("{emoji} {section} · skipped", "Not added yet, so it counts as €0 for now"; Protection: "Not added yet"). Everything else folds into "✅ {n} details look good" with each field\'s tag. Rows for the example below:', { size: 18 }));
push(table([600, 2500, 1500, W - 6100, 1500], ['Icon', 'Field', 'Section', 'Line (verbatim)', 'Actions'], CK.rows.map(r => [r.icon, r.title, r.sec.replace(/^· /, ''), r.line, r.actions.join(' · ')]), { size: 14 }));
push(P('My money has the same list as a card "' + EX.money.title + '": ' + EX.money.rows.map(r => '"' + r[0] + '" + "' + r[1] + '"').join('; ') + '.', { size: 18 }));
push(imgGrid([{ file: 'E-p4.png', caption: 'Check your details' }, { file: 'E-money.png', caption: 'My money · To sharpen your plan' }], 2, 520));
push(H2('4.7 In the calculators'));
const CG = EX.calc, NM = { repayment: 'C02', overpay: 'C04', ratechange: 'C05', term: 'C06', mortgageprotect: 'C23' };
push(P('A personal figure the tool needs but Your finances does not have is never filled in. Example: years left on the mortgage. The box stays blank with the tag "Not added yet" ("Not chosen yet" is only for §14 choices), and the result card reads "Add {natural name} to see this"; other missing items follow as "Also still to add or choose: {items}." "Add to my plan" shows the toast "Add {natural name} first". Mortgage balance known, years left missing (sample customer):', { size: 18 }));
push(table([1200, 2400, W - 3600], ['Tool', 'Blank input', 'Result gate (verbatim)'], Object.entries(NM).map(([id, n]) => { const x = CG[id + '-noyears'], f = x.dom.fields.find(f => f.kind === 'blank'); return [n, f.label, x.dom.gate.b + (x.dom.gate.also ? ' · ' + x.dom.gate.also : '')]; }), { size: 15 }));
push(P('Worked-out figures in calculators carry the tag "Worked out from your figures" (.tag.pre) after the label, with the same line under the slider minus "Type yours to replace it.":', { size: 18 }));
const WT = [['C25 Monthly surplus', CG['surplus-worked']], ['C27 Debt repayment', CG['debtpay-worked']]];
push(table([2000, 2800, W - 4800], ['Tool', 'Input (tag)', 'Line under the slider (verbatim)'], WT.flatMap(([n, x]) => x.dom.fields.filter(f => f.guide && /^Worked out/.test(f.guide)).map(f => [n, f.label + ' · Worked out from your figures', f.guide])), { size: 15 }));
push(imgGrid([{ file: 'E-repayment-gate.png', caption: 'C02: Add your term to see this' }, { file: 'E-surplus-worked.png', caption: 'C25: worked-out essentials' }, { file: 'E-debtpay-worked.png', caption: 'C27: worked-out payment' }], 3, 260));
push(P('A stated monthly mortgage repayment (from a document or typed) is used by C02, C04 and C23 while the mortgage fields are untouched; a repayment the app works out is never used there.', { size: 18 }));

// ---------- 5 LifeMap (journey-spec §16) ----------
push(H1('5. LifeMap name and cover'));
push(P('Journey-spec §16: the product is **LifeMap** (by DigiPro.AI). Every customer-facing string in the prototype, the workbook and this document says LifeMap; file names stay as they are for now (LifeGoals-Customer-Journey-Prototype.html, LifeGoals-Calculators.xlsx, this .docx).'));
push(H2('5.1 Cover (D0)'));
const CV = EX.cover;
push(table([2300, W - 2300], ['Part', 'Specification (verbatim)'], [['Photo', 'Full-bleed photo of a winding road through Irish countryside (to be supplied and licensed). It is one CSS custom property, --cover-photo, on :root; until the photo arrives it holds a drawn placeholder (sky, green hills, a winding road). Position: center 30%, cover.'], ['Shade', 'Navy gradient over the photo, clear at the top and dark at the bottom: .cover-shade{' + cssRule('.cover-shade') + '}. Short screens start it higher.'], ['Logo', CV.logo + ' (mark + wordmark, navy on the sky)'], ['Top right', '"' + CV.invite + '" (white pill, navy text; opens "Enter your invite code")'], ['Headline (h2, focused on arrival)', CV.h], ['Line', CV.line], ['Button', CV.btn + ' (gold, full width; goes to D1)'], ['Under the button', CV.under], ['Link', '"' + CV.why + '" (white; opens "Why we ask")'], ['Nothing else', 'No trust line and no "Guidance, not advice." on the cover (that stays wherever results are shown).']], { size: 15 }));
push(imgP('B-cover.png', 300, 650), cap('Cover at 390 × 844, with the placeholder photo'));
push(P('Contrast: white text measured against the lightest pixel behind it is at least 9.2:1 at 390 × 844, 1280 × 800, 844 × 390 and 360 × 640; the invite pill is at least 4.97:1.', { size: 16, color: MUTED }));
push(H2('5.2 Other §16 changes the calculators touch'));
push(table([2600, W - 2600], ['Where', 'Now (verbatim)'], [['D1 title', EX.d1.h + ' (chips unchanged, incl. "' + EX.d1.chips.find(c => /safety net/.test(c)) + '")'], ['Goal tile', EX.tile.e + ' ' + EX.tile.t + ' (was "Build a safety net"; no helper line)'], ['C11 Add to my plan', 'The goal is named "' + EX.tile.t + '" too (sheet title "' + data.sheets['emergency-chosen'][1] + '")'], ['Discover Q8', EX.q8.h + ' / ' + EX.q8.sub], ['Q8 answers', EX.q8.o.map(o => o[0] + ' ' + o[1] + ' (' + o[2] + ')').join(' · ')]], { size: 15 }));
push(imgP('B-q8.png', 260, 560), cap('Discover Q8, road version'));

// ---------- Calculators ----------
const STATE_SHORT = { default: 'Default (nothing chosen)', chosen: 'Choices made', noInfl: 'No inflation yet', adjUnset: 'Switch on, no rate', adjSet: 'Switch on, 2%', plan: 'Plan pre-fill', stmt: 'Statement' };
const RES = s => s.dom.result || { lbl: s.dom.gate.eyebrow, val: s.dom.gate.b, line: s.dom.gate.also || '', rows: [] };
const kindOf = f => !f.guide ? '' : f.guide.startsWith('Usually') ? 'Usual range (type 2)' : f.guide.startsWith('Generally') ? 'Personal choice (type 3)' : f.guide.startsWith('You can usually draw') ? 'Retirement age (choose yourself)' : '';
for (const c of data.calcs) { const S = SPEC[c.id], cat = CATN[c.cat], dflt = c.states.find(s => s.key === 'default'), chs = c.states.find(s => s.key === 'chosen'), dom = dflt.dom, fulls = c.states.filter(s => s.kind === 'full'), edges = c.states.filter(s => s.kind === 'result'), hint = c.states.find(s => s.key === 'hint'), X = XL[c.n];
  const xnames = new Set([...X.results, ...X.plan, ...X.inputs].map(r => r.name));
  push(H1(c.n + ' ' + c.name));
  const im = inflMode(c.id);
  push(kv([['Calculator', c.n + ' · internal id "' + c.id + '" · workbook sheet "' + X.sheet + '"'], ['Category (eyebrow)', cat.name + ' (shown in capitals)'], ['Title (h2)', dom.title], ['Emoji', c.em], ['Question (subtitle)', c.q], ['Tip', c.tip ? '💡 ' + c.tip : 'None'],
    ['Inflation', im === 'switch' ? '"Adjust for inflation" switch (off by default); inflation chips when on and no rate chosen' : im === 'chips' ? 'Inflation chips while no rate is chosen (results read "Choose your inflation rate to see this"); "Prices rising … · Change" once chosen' : 'Not used'], ['Before any choice (result gate)', dom.gate ? dom.gate.b + (dom.gate.also ? ' · ' + dom.gate.also : '') : 'No gate: the result shows straight away'],
    ['What if… card', c.wi.length ? c.wi.map(i => '"' + i.l + '"').join(', ') : 'None'], ['Statement upload', STMT[c.id] ? M.DOCT[STMT[c.id]].title : 'None'], ['Ask an expert goes to', expertFor(c.cat)]]));
  push(H2(c.n + ' Screens'));
  push(imgGrid(fulls.map(s => ({ file: s.file, caption: c.n + ' · ' + s.title })), Math.min(3, fulls.length), 720));
  push(H2(c.n + ' Inputs'));
  const ins = allInputs(c), fd = k => dom.fields.find(f => f.k === k);
  const onScreen = (i, f) => f.look && !f.box ? 'blank · ' + f.look : f.kind === 'chip' ? f.box : F.boxText(f.pre, f.box, f.suf), cdef = i => F.CHIPS[i.u] ? F.chipLabel(i.u, i.v) : F.boxText(F.PARTS[i.u][0], F.nbFmt(i.v), F.PARTS[i.u][1]);
  push(table([2600, 1150, 1100, 1250, 900, 900, 766, 1200], ['Label (verbatim)', 'Unit shown', 'CALCS default', 'On screen (default)', 'Min', 'Max', 'Step', 'Keyboard'], ins.map(i => { const f = fd(i.k), chip = !!F.CHIPS[i.u];
    return [(i.wi ? '[What if] ' : '') + i.l, F.unitDisplay(i.u), cdef(i), onScreen(i, f) + (onScreen(i, f) !== cdef(i) ? ' ⚠' : ''), chip ? '—' : F.nbFmt(i.min), chip ? '—' : F.nbFmt(i.max), chip ? '—' : F.nbFmt(i.step), chip ? 'tap (chips)' : (i.step % 1 !== 0 || i.u === '%' ? 'decimal' : 'numeric')]; }), { size: 15 }));
  if (ins.some(i => onScreen(i, fd(i.k)) !== cdef(i))) push(P('⚠ Differs from the CALCS default: blank until the customer chooses (§14), or always pre-filled from About you or the plan.', { size: 16, color: MUTED }));
  const chF = dom.fields.filter(f => f.guide || f.look);
  if (chF.length) { push(P('Choices on this screen (journey-spec §14), verbatim:', { bold: true, size: 18, before: 80 })); push(table([2600, 1700, 4166, 1400], ['Label', 'Kind', 'Guidance under the input', 'Standard chip'], chF.map(f => [f.label, kindOf(f) || (f.look || ''), f.guide || '—', f.stdChip || '—']), { size: 15 })); }
  if (dom.calcAsm) { push(P('"' + dom.calcAsm.summary + '" card (open while something is missing), verbatim:', { bold: true, size: 18, before: 80 })); push(table([2900, 4566, 2400], ['Plan-wide input (Your assumptions)', 'Guidance', 'Standard chip'], dom.calcAsm.fields.map(f => [f.label, f.guide || '—', f.std || '—']), { size: 15 })); push(P((dom.calcAsm.useAll ? '"' + dom.calcAsm.useAll + '" button. ' : '') + 'Note: "' + dom.calcAsm.note + '"', { size: 16 })); }
  push(table([2600, 2500, 1200, W - 6300], ['Label', 'Typed above max', 'Typed below min', 'Pre-fill (Your finances / plan / Your assumptions) · Statement (tag)'], ins.map(i => { const pf = (PF[c.id] || {})[i.k] || ['', ''], chip = !!F.CHIPS[i.u];
    const above = (chip ? 'Not possible (chips)' : i.u === '€' ? 'Accepted up to ' + F.eur(i.max * 10) + ' (slider widens); above: clamps, hint "' + F.maxHint(i) + '"' : 'Clamps to ' + F.nbFmt(i.max) + ', hint "' + F.maxHint(i) + '"') + (['y', 'm', 'age'].includes(i.u) && i.step % 1 === 0 ? '. Decimals round, hint "Whole numbers only"' : '');
    return [i.l, above, chip ? 'Not possible (chips)' : 'Clamps, hint "' + F.minHint(i) + '"', (pf[0] ? pf[0] : 'Tool default') + (pf[1] ? ' · Statement: ' + pf[1] + ' → tag "From your statement"' : '')]; }), { size: 15 }));
  push(P('Pre-fill order (highest first): the customer\'s own move of this field > the uploaded statement\'s figure for this tool > Your finances (document > typed; nothing is ever filled in for the customer, so a missing personal figure leaves the box blank, tagged "Not added yet", and the result reads "Add … to see this") > the plan and Your assumptions > the tool default. Pre-filled values are clamped to the slider range and not rounded to the step.', { size: 16, color: MUTED, before: 60 }));
  if (hint) { const hf = hint.dom.fields.find(f => f.k === hint.field); push(imgP(hint.file, 330, 120), cap(c.n + ' · ' + hint.title + ' → box shows "' + hf.box + '", hint "' + hf.hint + '"')); }
  // result card
  push(H2(c.n + ' Result card'));
  push(table([1500, 5566, 2800], ['Part', 'Text (verbatim template)', 'Shown when'], S.lbl.map(([t, w]) => ['Label (eyebrow)', t, w]).concat(S.val.map(([t, w]) => ['Headline value', t, w]), S.line.map(([t, w]) => ['Line', t, w])), { size: 16 }));
  push(P('Rows, in order (label left, bold value right):', { bold: true, size: 18, before: 80 }));
  push(table([3500, 3366, 3000], ['Row label (verbatim template)', 'Row value', 'Shown when'], S.rows.map(([l, vals, w]) => [l, vals.map(([v, vw]) => v + (vw ? ' (' + vw + ')' : '')).join(' / '), w]), { size: 16 }));
  push(P('Placeholders:', { bold: true, size: 18, before: 80 }));
  push(table([2000, 1500, W - 3500], ['Placeholder', 'Format', 'Meaning (maths in sheet "' + X.sheet + '")'], Object.entries(S.ph).map(([k, v]) => ['{' + k + '}', TYPES[v[0]][0], (v[1] || k.replace(/_/g, ' ')) + (xnames.has(k) ? ' · Workbook name: ' + k : '')]), { size: 16 }));
  push(P('Add to my plan: ' + (S.goal || 'no goal ("Nothing to add · This result doesn\'t create a goal.").'), { size: 18, before: 80 }));
  // workbook pointer (d)
  push(H2(c.n + ' Workbook sheet "' + X.sheet + '"'));
  push(P('Workbook: LifeGoals-Calculators.xlsx, sheet "' + X.sheet + '" (title "' + X.title + '"). Inputs and outputs below use the workbook\'s defined names; the value columns show the numbers behind the "Choices made" screenshot (and "No inflation yet" for inflation tools) so both can be checked against Excel. Before any choice the screen computes nothing (result gate).', { size: 18 }));
  const XIN = Object.assign({}, S.xin); const norm = s => String(s).toLowerCase().replace('what if:', '').replace(/'s/g, '').replace(/[^a-z0-9]/g, '');
  const wbIn = X.inputs.filter(i => !/^(Used_|Stmt_)/.test(i.name) && i.name !== 'Statement_Check');
  const wbNames = new Set(wbIn.map(j => j.name)); Object.keys(XIN).forEach(k => { if (!wbNames.has(XIN[k]) && wbNames.has(XIN[k] + '_Entry')) XIN[k] = XIN[k] + '_Entry'; });
  ins.forEach(i => { if (!XIN[i.k]) { const m = wbIn.find(j => norm(j.label) === norm(i.l)); if (m) XIN[i.k] = m.name; } });
  const usedOf = n => { const u = 'Used_' + String(n).replace(/_Entry$/, ''); return X.inputs.some(j => j.name === u) ? u : null; };
  push(table([2900, 2200, W - 5100], ['Screen input (label)', 'Workbook input name (entry · value used)', 'Workbook label · allowed'], ins.map(i => { const m = wbIn.find(j => j.name === XIN[i.k]); return [i.l, (XIN[i.k] || '—') + (XIN[i.k] && usedOf(XIN[i.k]) ? ' · ' + usedOf(XIN[i.k]) : ''), m ? m.label + ' · ' + (m.allowed || '') : '—']; }), { size: 15 }));
  const extra = wbIn.filter(j => !Object.values(XIN).includes(j.name));
  if (extra.length) push(table([2900, 2200, W - 5100], ['Workbook-only input (no control on this screen)', 'Name', 'Comes from'], extra.map(j => [j.label, j.name, (j.group === 'YOUR INFLATION CHOICE' ? 'The inflation chips' : /Statement_Check|Statement_Uploaded|Use_Statement/.test(j.name) ? 'Statement reader' : /Goal_Years/.test(j.name) ? 'Add to my plan default' : 'Your assumptions') + (j.allowed && !/ƒx|=/.test(j.allowed) ? ' · ' + j.allowed : '')]), { size: 15 }));
  const stmtIn = X.inputs.filter(i => /^Stmt_/.test(i.name)); if (stmtIn.length) push(P('Statement inputs (filled by the document reader): ' + stmtIn.map(j => j.label + ' (' + j.name + ')').join('; ') + '.', { size: 16 }));
  const nst = [chs].concat(c.states.filter(s => s.key === 'noInfl'));
  push(table([2400, 3100, 2183, 2183], ['Workbook output name', 'Workbook label', 'Choices made', nst[1] ? 'No inflation yet' : '—'], X.results.concat(X.plan).filter(r => r.name in (chs.num || {}) ).map(r => [r.name, r.label, fmtNum(chs.num[r.name]), nst[1] ? fmtNum(nst[1].num[r.name]) : '—']), { size: 15 }));
  // screen values
  push(H2(c.n + ' Screen values in the screenshots'));
  const cols = fulls.length, lw = 2300, cw = Math.floor((W - lw) / cols), widths = [lw].concat(Array(cols).fill(cw)); widths[cols] += W - lw - cw * cols;
  const vrows = [];
  ins.forEach(i => vrows.push([i.l].concat(fulls.map(s => { const f = s.dom.fields.find(x => x.k === i.k); return f ? onScreen(i, f) + (f.tag ? ' ★' : '') : '—'; }))));
  vrows.push(['Result label'].concat(fulls.map(s => RES(s).lbl))); vrows.push(['Headline value'].concat(fulls.map(s => RES(s).val)));
  const rowLabels = []; fulls.forEach(s => RES(s).rows.forEach(r => { if (!rowLabels.includes(r[0])) rowLabels.push(r[0]); }));
  rowLabels.forEach(l => vrows.push(['Row: ' + l].concat(fulls.map(s => { const r = RES(s).rows.find(x => x[0] === l); return r ? r[1] : '—'; }))));
  vrows.push(['Inflation line'].concat(fulls.map(s => s.dom.inflNote || '—')));
  push(table(widths, ['Field'].concat(fulls.map(s => STATE_SHORT[s.key] || s.key)), vrows, { size: 15, firstFill: true }));
  push(P('Result line, verbatim, per screenshot:', { bold: true, size: 18, before: 80 }));
  fulls.forEach(s => push(B('**' + (STATE_SHORT[s.key] || s.key) + '**: ' + (RES(s).line || '(none)'))));
  if (edges.length) { push(H3('Edge-case results'));
    edges.forEach(s => { push(P('**' + s.title + '**' + (Object.keys(s.set).length ? ' (set: ' + Object.entries(s.set).map(([k, v]) => { const i = ins.find(x => x.k === k); return '"' + i.l + '" = ' + (F.CHIPS[i.u] ? F.chipLabel(i.u, v) : v); }).join(', ') + ')' : '') + ' · base: ' + ({ chosen: 'choices made', sample: 'sample customer' }[s.base] || 'mortgage statement with the repayment corrected to €1,300'), { size: 18, keepNext: true }));
      push(imgP(s.file, 300, 260), cap(c.n + ' · ' + s.title));
      push(table([2300, W - 2300], null, [['Label', s.dom.result.lbl], ['Headline value', s.dom.result.val], ['Line', s.dom.result.line]].concat(s.dom.result.rows.map(r => ['Row: ' + r[0], r[1]])), { size: 15, firstFill: true })); }); }
  const GAP = Object.entries(EX.calc).filter(([k]) => k.split('-')[0] === c.id);
  if (GAP.length) { push(H3('Your finances gaps (journey-spec §15)'));
    GAP.forEach(([k, x]) => { if (x.dom.gate) { const f = x.dom.fields.find(f => f.kind === 'blank'); push(P('**Years left missing in Your finances** (sample customer without it): "' + f.label + '" stays blank (tag "' + f.look + '"); nothing is filled in.', { size: 18, keepNext: true })); push(imgP(x.file, 300, 200), cap(c.n + ' · ' + x.dom.gate.b)); push(table([2300, W - 2300], null, [['Eyebrow', x.dom.gate.eyebrow], ['Gate', x.dom.gate.b], ['Also', x.dom.gate.also || '(none)']], { size: 15, firstFill: true })); }
      else { push(P('**Repayment not given in Your finances** (sample customer without it): the tool fills a figure worked out from the customer\'s own figures and says so.', { size: 18, keepNext: true })); push(imgP(x.file, 300, 220), cap(c.n + ' · Worked out from your figures')); push(table([2300, 2600, W - 4900], ['Input', 'Tag', 'Line under the slider (verbatim)'], x.dom.fields.filter(f => f.guide && /^Worked out/.test(f.guide)).map(f => [f.label, 'Worked out from your figures', f.guide]), { size: 15 })); } }); }
  push(H2(c.n + ' States and edge cases'));
  ['**Empty box**: ignored while typing; on leaving, the box returns to the last valid value. **Invalid characters** are stripped (1.5).', '**Out of range**: see the inputs table.', ...S.states,
   STMT[c.id] ? '**Statement**: inputs filled from the ' + M.DOCT[STMT[c.id]].what + ' statement show "From your statement". Removing the statement resets them.' : null,
   im !== 'none' ? '**Inflation**: blank until chosen; while blank, inflation-dependent values read "Choose your inflation rate to see this" (1.8).' : null].filter(Boolean).forEach(t => push(B(t)));
  push(H2(c.n + ' Actions'));
  push(table([2400, 2400, W - 4800], ['Control (verbatim)', 'Style', 'Goes to'], [['‹ Back', 'Back pill', 'Previous Explore screen'], ['＋ Add to my plan', 'Navy small, full column width', S.goal || 'Sheet "Nothing to add"'], ['Ask an expert', 'Ghost small, full column width', 'Experts tab, ' + expertFor(c.cat) + ' chosen'], ...(im !== 'none' ? [['Inflation chips / Change', 'Small chips; text link', 'Sets the app-wide inflation rate']] : []), ...(im === 'switch' ? [['Adjust for inflation', 'Chip as switch', 'Shows the result in today\'s money']] : [])], { size: 16 }));
  push(P('Disclaimer (verbatim): "' + dom.disc + '"', { size: 18, before: 60 }));
  push(H2(c.n + ' Accessibility'));
  ['Title read as "' + dom.title + '" (hide the emoji in the build). Focus moves to the title when the screen opens.', 'Inputs are labelled by their visible labels' + (STMT[c.id] ? ', including the statement tag' : '') + '. Sliders carry aria-valuetext with the unit (e.g. "' + ((chs.dom.fields.find(f => f.valuetext) || {}).valuetext || '') + '").', dom.fields.some(f => f.look) ? 'Blank inputs carry the visible tag "Not chosen yet"; the result gate text is in the polite live region.' : null, ins.some(i => F.CHIPS[i.u]) ? 'Choice chips are toggle buttons (aria-pressed) in a group labelled by the field label.' : null, 'The result card is a polite live region; debounce announcements while dragging.', c.wi.length ? 'Give the What if… card a group role named "What if…".' : null, im === 'switch' ? 'The "Adjust for inflation" chip is a switch (role="switch", aria-checked).' : null, im !== 'none' ? 'Inflation chips are toggle buttons in a group labelled "Prices rising (inflation)".' : null].filter(Boolean).forEach(t => push(B(t)));
}

// ---------- Appendix A ----------
push(H1('Appendix A. Copy deck'));
push(P('Every string on the calculator screens. Templates use {placeholders} and «A|B» options as defined in each calculator section.'));
push(H2('A.0 Shared strings'));
const SHARED = [['Back button', '‹ Back'], ['Add action', '＋ Add to my plan'], ['Expert action', 'Ask an expert'], ['Disclaimer', 'Illustrative figures, not a guarantee and not advice.'], ['What-if card title', 'What if…'], ['Tag on statement inputs', 'From your statement'], ['No inflation yet', require('./spec').NO], ['Blocked goal', 'Choose an inflation rate first · Goals are kept in today\'s money, so we need your inflation rate first. · OK'], ['Tax note (savings and investment tools)', require('./spec').BT],
  ['Inflation title', IU.title], ['Inflation help', IU.help], ['Inflation chips', IU.chips.map(x => x.t).join(' · ')], ['Own rate label', data.infl.other.other], ['Chosen line', 'Prices rising {infl} a year (your choice) · Change'],
  ['Switch (off / on)', 'Adjust for inflation / ✓ Adjust for inflation'], ['Switch helper', 'Show the result in today\'s money'], ['Switch prompt (on, no rate)', 'Pick an inflation rate to see it in today\'s money.'], ['Real-return sentence', 'Real return about {rr}% a year ({g}% «growth|growth after fees», prices rising {infl}).'],
  ['Choice chips', 'Yes · No · 1 · Cautious · 2 · Balanced · 3 · Growth · 20% · 40%'], ['Hints', 'Max €{10 × max} · Max {max}% · Max {max} yrs · Max {max} mo · Max {max} · Min €{min} · Min {min}'],
  ['Add sheet', 'Add to my plan · {emoji} {goal name} · {text} · Add it / Update it / Raise it / Note it · Not now'], ['No goal', 'Nothing to add · This result doesn\'t create a goal. · OK'],
  ['Rules version', RULES_NOTE], ['Your assumptions', 'Your assumptions · Some values are set by law. For the rest we show the usual range or the standard, and you choose. · Not chosen yet · Your choice · Use the standard ({X}) · Use the standard for all of these · Fills every choice you haven\'t made yet with its standard. It never sets your retirement age or plan-until age: choose those yourself. · Set by Government · 2026 · How the plan works'], ['Value-type guidance', 'Usually between {low} and {high} ({source}). · Generally the standard is {X} ({source}). Choose what you want to use.'], ['Result gate', 'Your result · Choose {item} to see this · Add {item} to see this ({item} is the input\'s own name, e.g. "your mortgage rate", "the first fee (fee A)") · Also still to add or choose: {items}. · toast: Choose {item} first / Add {item} first · tags: Not chosen yet (§14 choice) / Not added yet (Your finances figure)'], ['Worked-out tag', 'Worked out from your figures'], ['Example link', 'Not sure? See an example'], ['Example card', 'Example: {field label} · 📍 Where to find yours: {where} · Nothing to add? Enter 0. · Example only. Not a typical or recommended amount. · Got it'], ['Cover', 'LifeMap · I have an invite · The life you\'d like, mapped out. · A life map that guides you, step by step. · Let\'s start · An easy tool, built for you. · Why we ask'],
  ['Explore disclaimer', 'Calculators and videos explain general topics. Figures are illustrative, not a guarantee and not advice.'], ['Topic disclaimer', 'Topics explain general ideas. They are not advice.'],
  ['Your finances tags', '✅ From your statement (corrected) · ✅ From document · {n}% · ✏️ Your figure · ✏️ Your figure · from your answers · From your answers · ❓ Missing · ⚠️ Needs a look'], ['Precedence message', 'You typed {€ typed}. Your statement says {€ statement}; we\'re using that.']];
push(table([2600, W - 2600], ['Element', 'String (verbatim)'], SHARED, { size: 16, zebra: true }));
for (const c of data.calcs) { const S = SPEC[c.id], dom = c.states[0].dom;
  push(H2('A.' + c.n + ' ' + c.name));
  const rows = [['Title', dom.title], ['Question', c.q]]; if (c.tip) rows.push(['Tip', '💡 ' + c.tip]); rows.push(['Category eyebrow', CATN[c.cat].name]);
  allInputs(c).forEach(i => { rows.push([(i.wi ? 'What-if label' : 'Input label') + ' (' + F.UNIT_NAME[i.u] + ')', i.l]); rows.push(['  Unit and hints', F.CHIPS[i.u] ? F.CHIPS[i.u].map(x => x[1]).join(' · ') : (F.PARTS[i.u][0] ? 'Box prefix "' + F.PARTS[i.u][0].trim() + '" · ' : F.PARTS[i.u][1] ? 'Box suffix "' + F.PARTS[i.u][1] + '" · ' : 'No unit · ') + F.maxHint(i) + ' · ' + F.minHint(i)]); });
  S.lbl.forEach(([t]) => rows.push(['Result label', t])); S.val.forEach(([t]) => rows.push(['Headline value', t])); S.line.forEach(([t]) => rows.push(['Result line', t]));
  S.rows.forEach(([l, vals]) => rows.push(['Row', l + '  →  ' + vals.map(v => v[0]).join(' / ')]));
  if (S.goal) rows.push(['Add to my plan', S.goal]);
  if (inflMode(c.id) === 'switch') rows.push(['Switch', 'Adjust for inflation / ✓ Adjust for inflation · Show the result in today\'s money']); if (c.wi.length) rows.push(['What-if card title', 'What if…']);
  rows.push(['Actions', '‹ Back · ＋ Add to my plan · Ask an expert']); rows.push(['Disclaimer', dom.disc]);
  push(table([2600, W - 2600], ['Element', 'String (verbatim)'], rows, { size: 16, zebra: true })); }

// ---------- Appendix B ----------
push(H1('Appendix B. Open points'));
push(P('Fixed since the previous version and removed from this list (prototype e1cbc5a, workbook a04796c): a personal figure missing from Your finances now has its own tag "Not added yet" ("Not chosen yet" is only for §14 choices); every calculator input has its own natural gate name (e.g. C06 "' + require('./ex.json').calc['term-noyears'].dom.gate.b + '"); the worked-out note gives the right reason for a blank, a typed €0 or a too-small repayment; "Nothing to add? Enter 0." on euro fields only is now in journey-spec §15; the workbook C11 goal is named "Emergency fund". Older fixes: see previous versions.'));
[ '**Budget 2027 (6 October 2026)**: update the rules register (3.3), the copy that quotes statutory figures, and the version label "' + RULES_NOTE + '".',
  '**Screen titles**: the emoji in the title is read aloud by screen readers; hide it in the build.',
  '**§16 · Cover photo**: the cover uses a drawn placeholder until the licensed photo is supplied; swap it in --cover-photo and re-check the text contrast (at least 4.5:1).' ].forEach(t => push(B(t)));
