  // ---------- §15 Your finances and §16 LifeMap (independent: re-driven live, compared with the docx) ----------
  { const s4 = secs.find(s => s.title === '4. Your finances: "Not sure? See an example"'), s5 = secs.find(s => s.title === '5. LifeMap name and cover'), p4 = R.pass, f4 = R.fail.length;
    if (ok(s4 && s5, 'sections 4 and 5 present')) {
    const cardT = s4.blocks.filter(b => b.t === 'tbl' && b.rows[0][0] === 'Card title').flatMap(b => b.rows.slice(1));
    const keys = await page.evaluate(() => Object.keys(EXAMPLES)); ok(cardT.length === keys.length, 'card table has ' + cardT.length + ' rows for ' + keys.length + ' cards');
    for (const k of keys) { await page.evaluate(k => { loadSample(); if (k === 'ae') { delete S.fin.pensionM; delete S.src.pensionM; delete S.fin.pensionOwnM; delete S.src.pensionOwnM; } lastId = null; render(); openSec(FSEC.findIndex(s => s.f.includes(k))); }, k);
      const before = await page.evaluate(k => JSON.stringify([S.fin[k], S.src[k]]), k); const link = page.locator('[data-a="fex"][data-p="' + k + '"]');
      if (!ok(await link.count() === 1 && norm(await link.textContent()) === 'Not sure? See an example', 'card ' + k + ': link')) continue; await link.click();
      const c = await page.evaluate(() => { const sh = document.querySelector('.sheet'), t = e => e ? e.textContent.replace(/\s+/g, ' ').trim() : null, ps = [...sh.querySelectorAll(':scope > p')];
        return { title: t(sh.querySelector('#ex-t')), opts: [...sh.querySelectorAll('ul li')].map(li => t(li).replace(/: /, ': ')).join(' · ') || '—', sentence: t(sh.querySelector('#ex-s')), where: t(ps.find(p => /Where to find yours/.test(p.textContent))).replace(/^📍 Where to find yours: /, ''), zero: ps.some(p => /Nothing to add\? Enter 0\./.test(p.textContent)) ? 'Yes' : '—', small: t(ps.find(p => /Example only/.test(p.textContent))), btn: t(sh.querySelector('.btn')), role: sh.getAttribute('role'), lb: sh.getAttribute('aria-labelledby'), db: sh.getAttribute('aria-describedby') }; });
      const r = cardT.find(x => x[0] === c.title);
      ok(r && r[1] === c.opts && r[2] === c.sentence && r[3] === c.where && r[4] === c.zero, 'card ' + k + ': doc row ' + JSON.stringify(r) + ' vs live ' + JSON.stringify([c.title, c.opts, c.sentence, c.where, c.zero]));
      ok(s4.text.includes(c.small) && s4.text.includes('"' + c.btn + '"') && c.role === 'dialog' && c.lb === 'ex-t' && c.db === 'ex-s', 'card ' + k + ': small print, button, dialog semantics');
      await page.keyboard.press('Escape'); const after = await page.evaluate(k => JSON.stringify([S.fin[k], S.src[k], !!document.querySelector('.sheet'), document.activeElement.dataset.p]), k);
      ok(after === JSON.stringify(JSON.parse(before).concat([false, k])), 'card ' + k + ': Escape closes, focus back on the link, field unchanged'); }
    const tg = await page.evaluate(() => { const r = []; const t = h => { const d = document.createElement('div'); d.innerHTML = h; return d.textContent; }; S.src.zz = 'doc'; S.conf.zz = 95; r.push(t(tagFor('zz'))); S.fix.zz = 1; r.push(t(tagFor('zz'))); delete S.fix.zz; S.src.zz = 'typed'; r.push(t(tagFor('zz'))); S.src.zz = 'pre'; r.push(t(tagFor('zz'))); delete S.src.zz; r.push(t(tagFor('zz'))); S.look.zz = 'x'; r.push(t(tagFor('zz'))); delete S.look.zz; return r; });
    const stT = s4.blocks.find(b => b.t === 'tbl' && b.rows[0][0] === 'Tag (verbatim)'); tg.forEach(x => ok(stT && stT.rows.some(r => r[0] === x), 'status tag "' + x + '"'));
    ok(!/≈ Estimated|Confirmed none/.test(await page.evaluate(() => document.documentElement.innerHTML.replace(/<script[\s\S]*?<\/script>/g, ''))), 'no removed statuses on screen');
    await page.evaluate(() => { loadSample(); delete S.fin.mortPayM; delete S.src.mortPayM; delete S.fin.ip; delete S.src.ip; S.look.homeValue = 'This looks high for the area'; S.app = false; S.pb = true; S.tab = 'plan'; S.scr = 'P4'; S.checked = false; lastId = null; render(); });
    const ck = await page.evaluate(() => [...document.querySelectorAll('#main .ck')].map(c => { const t = e => e ? e.textContent.replace(/\s+/g, ' ').trim() : null; return [t(c.querySelector('.i')), t(c.querySelector('b')), t(c.querySelector(':scope > div > div.small'))]; }));
    const ckT = s4.blocks.find(b => b.t === 'tbl' && b.rows[0][0] === 'Icon'); ck.forEach(r => ok(ckT && ckT.rows.some(x => x[0] === r[0] && x[1] === r[1] && x[3] === r[2]), 'checklist row "' + r[1] + '"'));
    ok(ck.every(r => ['⚠️', '❓'].includes(r[0])), 'checklist only ⚠️ / ❓');
    for (const id of ['repayment', 'overpay', 'ratechange', 'term', 'mortgageprotect']) { await page.evaluate(id => { loadSample(); delete S.fin.mortYears; delete S.src.mortYears; delete S.conf.mortYears; S.tab = 'explore'; S.xs = []; lastId = null; render(); ACT.calc(id); }, id); const g = await page.evaluate(() => ({ b: document.querySelector('#cgate b').textContent, f: (document.querySelector('.field .tag.look') || {}).textContent }));
      const N = 'C' + String(calcs.findIndex(c => c.id === id) + 1).padStart(2, '0'), sec = secs.find(s => s.title.startsWith(N + ' '));
      ok(/^Add .+ to see this$/.test(g.b) && s4.text.includes(g.b) && sec.text.includes(g.b), N + ': missing years gate "' + g.b + '" in 4.7 and the calculator section'); }
    for (const [id, del] of [['surplus', ['mortPayM', 'cardPayM']], ['debtpay', ['cardPayM']]]) { await page.evaluate(([id, del]) => { loadSample(); del.forEach(k => { delete S.fin[k]; delete S.src[k]; delete S.conf[k]; }); S.tab = 'explore'; S.xs = []; lastId = null; render(); ACT.calc(id); }, [id, del]);
      const w = await page.evaluate(() => [...document.querySelectorAll('#main .field')].filter(f => f.querySelector('.tag.pre')).map(f => [f.querySelector('.tag.pre').textContent, [...f.querySelectorAll(':scope > span.small')].map(x => x.textContent).join(' ')]));
      const N = 'C' + String(calcs.findIndex(c => c.id === id) + 1).padStart(2, '0'), sec = secs.find(s => s.title.startsWith(N + ' '));
      ok(w.length > 0, N + ': worked-out tag shown'); w.forEach(([tag, line]) => ok(tag === 'Worked out from your figures' && s4.text.includes(norm(line)) && sec.text.includes(norm(line)), N + ': worked-out line "' + line + '"')); }
    // §16
    await page.evaluate(() => { S = fresh(); lastId = null; render(); });
    const cv = await page.evaluate(() => ({ els: [...document.querySelectorAll('.cover .brand, .cover-inv, .cover h2, .cover-line, .cover .wbtn, .cover-under, .cover .link')].map(e => e.textContent.trim()), all: document.querySelector('.cover').innerText.replace(/\s+/g, ' ').trim(), title: document.title }));
    const cvT = s5.blocks.find(b => b.t === 'tbl' && b.rows[0][0] === 'Part');
    cv.els.forEach(t => ok(cvT && cvT.rows.some(r => r[1] === t || r[1].startsWith(t + ' (') || r[1].startsWith('"' + t + '"')), 'cover text "' + t + '" in 5.1'));
    ok(cv.all === cv.els.join(' '), 'cover shows only the agreed copy'); ok(!/Guidance, not advice|Free · About a minute/.test(cv.all), 'no trust line or disclaimer on the cover');
    ok(secs.find(s => s.title === 'Appendix A. Copy deck').text.includes(cv.els.join(' · ')), 'cover strings in Appendix A');
    await page.evaluate(() => { S = fresh(); S.scr = 'D5'; S.di = 3; lastId = null; render(); }); const q8 = await page.evaluate(() => [document.querySelector('#screen h2').textContent, document.querySelector('.qsub').textContent].concat([...document.querySelectorAll('.opt')].map(e => e.querySelector('.em').textContent + ' ' + e.querySelector('.tx').textContent + ' (' + e.querySelector('.otag').textContent.replace(/^◆ /, '') + ')')));
    q8.forEach(t => ok(s5.text.includes(t), 'Q8 "' + t + '"'));
    await page.evaluate(() => { S = fresh(); S.shell = true; S.pb = true; S.tab = 'plan'; S.scr = 'F1'; lastId = null; render(); }); const tile = await page.evaluate(() => document.querySelector('.gtile[data-p="safety"] .nm').textContent); ok(tile === 'Emergency fund' && s5.text.includes('🪂 ' + tile), 'goal tile "' + tile + '"');
    await page.evaluate(() => { S = fresh(); S.scr = 'D1'; lastId = null; render(); }); const d1 = await page.evaluate(() => document.querySelector('#screen h2').textContent); ok(s5.text.includes(d1), 'D1 title "' + d1 + '"');
    const all = secs.map(s => s.title + ' ' + s.text).join(' '), stray = (all.match(/LifeGoals(?!-Customer-Journey-Prototype\.html|-Calculators\.xlsx|-Calculators-UIUX-Spec)[^ ]{0,20}/g) || []).filter(x => !/^LifeGoals" for now/.test(x));
    ok(stray.length === 0, 'no customer-facing "LifeGoals" in the docx: ' + stray.slice(0, 5).join(', '));
    ok(!/Start · about 1 min|Your life\. Your plan\.|Pick a forecast|Build a safety net"? ?\(C|≈ Estimated ·|Also still to choose:/.test(all), 'no old wording in the docx'); }
    // ---------- §17 (Explore order, emoji, Ask) and §18 (partner rates) ----------
    { const s2 = secs.find(s => s.title === '2. Explore structure'), s3 = secs.find(s => s.title === '3. Rules and Your assumptions'), s1 = secs.find(s => s.title === '1. Design system'), p17 = R.pass, f17 = R.fail.length;
      await page.evaluate(() => { loadSample(); S.tab = 'explore'; S.xs = []; lastId = null; render(); });
      const ex = await page.evaluate(() => ({ secs: [...document.querySelectorAll('#main .sec h3')].map(h => h.textContent), rows: [...document.querySelectorAll('#main [data-a="cat"]')].map(r => [r.querySelector('.ic').textContent, r.querySelector('b').textContent, r.querySelector('.small').textContent]) }));
      const want = ['What-ifs for your goals', 'Focus on one area', 'Tools for you', 'Watch · picked for you', 'Calculators'];
      ok(JSON.stringify(ex.secs) === JSON.stringify(want) && s2.text.includes('Sections in this order (journey-spec §17): What-ifs for your goals (after a plan), Focus on one area, Tools for you, Watch · picked for you, Calculators'), 'Explore order live and in the doc: ' + ex.secs.join(' → '));
      const gT = s2.blocks.find(b => b.t === 'tbl' && b.rows[0][0] === 'Emoji' && b.rows[0][1] === 'Group (verbatim)');
      ex.rows.forEach(r => ok(gT && gT.rows.some(x => x[0] === r[0] && x[1] === r[1] && x[2] === r[2]), 'Calculators row "' + r[1] + ' | ' + r[2] + '"')); ok(ex.rows.length === 6, 'six Calculators rows');
      ok(!(await page.evaluate(() => document.querySelectorAll('#main .ctile[data-a="cat"]').length)), 'no coloured group tiles');
      // emoji never read aloud: headings of every calculator and the sample screens have the emoji in aria-hidden spans, and the doc says so
      ok(/aria-hidden="true">…<\/span>, so the accessible name is the words only/.test(s1.text), 'doc 1.11 specifies the aria-hidden emoji pattern');
      for (const [n, c] of calcs.entries()) { await D.base('fresh'); await D.calc(c.id); const t = await page.evaluate(() => { const h = document.querySelector('#screen h2.t'), sp = h.querySelector('span[aria-hidden="true"]'); const cl = h.cloneNode(true); cl.querySelectorAll('[aria-hidden="true"]').forEach(x => x.remove()); return { emo: sp ? sp.textContent : null, name: cl.textContent.replace(/\s+/g, ' ').trim() }; });
        const N = 'C' + String(n + 1).padStart(2, '0'), sec = secs.find(s => s.title.startsWith(N + ' ')); ok(t.emo && !/\p{Extended_Pictographic}/u.test(t.name) && sec.text.includes('accessible name is "' + t.name + '"'), N + ': title accessible name "' + t.name + '" (emoji ' + t.emo + ' hidden)'); }
      const hid = await page.evaluate(() => { const o = []; [['XPL', () => { S = fresh(); S.shell = true; S.tab = 'explore'; S.xs = []; }], ['HOME', () => { loadSample(); S.tab = 'home'; }], ['ME', () => { loadSample(); S.tab = 'me'; S.me = 'home'; }], ['PLAN', () => { loadSample(); }]].forEach(([n, f]) => { f(); lastId = null; render(); const bad = [...document.querySelectorAll('#screen h1, #screen h2, #screen h3, #screen button.goal b')].filter(h => { const c = h.cloneNode(true); c.querySelectorAll('[aria-hidden="true"]').forEach(x => x.remove()); return /\p{Extended_Pictographic}/u.test(c.textContent); }).length; o.push([n, bad]); }); return o; });
      hid.forEach(([n, bad]) => ok(bad === 0, 'no emoji in the accessible names on ' + n));
      // Ask button
      const askOn = () => page.evaluate(() => !!document.querySelector('#screen .askfab'));
      await page.evaluate(() => { S = fresh(); lastId = null; render(); }); const ob = [['D0', await askOn()]];
      await page.click('.cover .wbtn'); ob.push(['D1', await askOn()]); await page.click('.qfoot .qback');
      for (let i = 0; i < 6; i++) { ob.push(['D' + (i + 2), await askOn()]); await page.click('.opt >> nth=1'); await page.waitForTimeout(450); }
      ob.push(['DR', await askOn()]); await page.click('text=Get a more accurate picture: make my plan'); ob.push(['DS', await askOn()]); await page.evaluate(() => { S.sheet = 'saveprompt'; render(); }); ob.push(['DS sheet', await askOn()]); await page.keyboard.press('Escape');
      ok(ob.every(x => x[1] === false), 'Ask hidden on all onboarding screens: ' + JSON.stringify(ob)); await page.click('[data-a="dsskip"]'); const inapp = [await askOn()];
      for (const t of ['explore', 'plan', 'me', 'exp', 'home']) { await page.click('[data-a="tab"][data-p="' + t + '"]'); inapp.push(await askOn()); } await page.click('[data-a="tab"][data-p="plan"]'); await page.click('[data-a="makeplan"]'); inapp.push(await askOn());
      ok(inapp.every(Boolean), 'Ask shown in the app and plan builder: ' + inapp.join(','));
      ok(s5.text.includes('is **not shown on any onboarding screen**'.replace(/\*\*/g, '')) && s5.text.includes('aria-label "Ask: help and plain-English explanations"'), 'doc 5.3 states the Ask rule');
      // §18 partner rates: the block, the chips, the override, the workbook block
      const live = await page.evaluate(() => JSON.parse(JSON.stringify(PARTNER_RATES))), XPR = XL._partner.rows, wrow = n => XPR.find(r => r[1].includes('[' + n + ']')) || [];
      const prT = s3.blocks.find(b => b.t === 'tbl' && b.rows[0][0] === 'Market rate (workbook name)');
      for (const [k, nm, wk] of [['mortRate', 'Mortgage rate (Suggest_Mortgage_Rate)', 'Suggest_Mortgage_Rate'], ['loanRate', 'Personal and car loans, APR (Suggest_Loan_APR)', 'Suggest_Loan_APR'], ['cardRate', 'Credit cards, APR (Suggest_Card_APR)', 'Suggest_Card_APR'], ['depRate', 'Deposit rate, fixed term (Suggest_Deposit_Rate)', 'Suggest_Deposit_Rate'], ['buyFees', 'Suggested buying fees', 'Suggest_Buying_Fees'], ['fundChg', 'Fund and pension charges a year (Suggest_Fund_Charges)', 'Suggest_Fund_Charges']]) { const r = prT && prT.rows.find(x => x[0].includes('(' + wk + ')')); const pv = live[k].v, wv = wrow(wk)[2];
        ok(r && r[2].startsWith(live[k].label), '3.7 label for ' + k + ': ' + live[k].label); ok((pv == null && (wv === '' || wv == null)) || (pv != null && Math.abs(+wv - pv) < 1e-12), 'workbook ' + wk + ' = prototype ' + k + ' (' + wv + ' vs ' + pv + ')'); ok(r && (pv == null ? r[1] === 'none' : /\d/.test(r[1])), '3.7 suggested value for ' + k + ': ' + (r && r[1])); }
      ok(+wrow('Card_APR_Cap')[2] === 0.23 && s3.text.includes('Card_APR_Cap 23%'), 'Card_APR_Cap 23% in the workbook and 3.7'); ok(wrow('Partner_Name')[1].includes('Partner_Name') && s3.text.includes('Partner_Name'), 'Partner_Name in the workbook and 3.7');
      const chipsLive = async () => { const o = {}; for (const g of ['safety', 'prices']) { await page.evaluate(g => { S = fresh(); S.shell = true; S.tab = 'me'; S.me = 'asm'; S.asmOpen = g; lastId = null; render(); }, g); const a = await page.evaluate(extractAsm); a.groups[0].fields.forEach(f => { o[f.k] = f.std; }); } return o; };
      const dflt = await chipsLive(), cT = s3.blocks.find(b => b.t === 'tbl' && b.rows[0][0] === 'Input (Your assumptions)');
      for (const k of ['mortRate', 'loanRate', 'cardRate', 'buyFees', 'depEarn', 'penChg']) { const lab = await page.evaluate(k => ASM[k].l, k), r = cT && cT.rows.find(x => x[0] === lab); ok(r && (dflt[k] ? r[1] === dflt[k] : /^No chip/.test(r[1])), '3.7 default chip for ' + k + ': ' + dflt[k]); }
      ok(dflt.mortRate === 'Use the suggested rate (3.48%) · Central Bank of Ireland: average rate on new mortgages, Jul 2026' && !dflt.cardRate && !dflt.buyFees, 'default chips: mortgage suggested, card and buying fees none');
      await page.evaluate(() => { PARTNER_RATES.name = 'Example Credit Union'; PARTNER_RATES.mortRate.v = 0.0399; PARTNER_RATES.loanRate.v = 0.0850; PARTNER_RATES.cardRate.v = 0.1900; PARTNER_RATES.buyFees.v = 3000; });
      const ovr = await chipsLive(); for (const k of ['mortRate', 'loanRate', 'cardRate', 'buyFees', 'depEarn', 'penChg']) { const lab = await page.evaluate(k => ASM[k].l, k), r = cT && cT.rows.find(x => x[0] === lab); ok(ovr[k] && /Suggested by Example Credit Union$/.test(ovr[k]) && r && r[2] === ovr[k], '3.7 partner chip for ' + k + ': ' + ovr[k]); }
      const tagP = await page.evaluate(() => { loadSample(); S.asm = {}; S.sheet = 'assume'; render(); return [...document.querySelectorAll('.sheet .mini')].map(m => (m.querySelector('.tag') || {}).textContent).filter(t => /Suggested/.test(t || '')); }); ok(tagP.length > 0 && tagP.every(t => /^Suggested [\d.]+%$/.test(t)), 'What your plan assumes shows "Suggested X%" with a partner: ' + tagP);
      await page.evaluate(() => { PARTNER_RATES.name = ''; PARTNER_RATES.mortRate.v = 0.0348; PARTNER_RATES.loanRate.v = 0.0672; PARTNER_RATES.cardRate.v = null; PARTNER_RATES.buyFees.v = null; });
      const hp = await page.evaluate(() => [ASM.mortRate.help, ASM.cardRate.help, ASM.loanRate.help, ASM.penChg.help, ASM.depEarn.help, ASM.planEnd.help, asmGuide(ASM.buyFees)]); hp.forEach(t => ok(s3.text.includes(t), '3.7 guidance text: ' + t.slice(0, 70)));
      ok(!/Usually between 3\.5% and 4\.5%|Usually between 13% and 23%|Usually between 6% and 10%|Usually between €2,500|Usually between 0\.5% and 1\.5%|Usually between 1\.3%/.test(secs.map(x => x.text).join(' ')), 'no made-up "Usually between" market ranges in the doc');
      ok(/83 for men and 86 for women \(CSO, Irish Life Tables No\. 17/.test(s3.text), 'life expectancy guidance cites CSO Irish Life Tables No. 17 (about 83 men, 86 women)');
      R.perCalc.push(['§17 / §18', 'Explore order and rows, emoji accessible names, Ask visibility, partner rates block, chips and override', R.pass - p17, R.fail.length - f17]); }
    R.perCalc.push(['§15 / §16', 'Example cards, statuses, checklist, gaps in calculators; LifeMap cover, Q8, tile', R.pass - p4, R.fail.length - f4]); }
