      // ---------- §19: Settings (3.7), lists (4.8 to 4.10), complete on save, Emergency fund months (6.1), goal order (6.2) ----------
      const sec6 = secs.find(s => s.title === '6. Goals: Emergency fund months and goal order'), cell = r => norm(r), allT = t => t.rows.flat().join(' ');
      const lv = await page.evaluate(() => ({ s: JSON.parse(JSON.stringify(SETTINGS.s)), g: JSON.parse(JSON.stringify(SETTINGS.g)), fmt: Object.fromEntries(Object.entries(SETTINGS.s).map(([k, v]) => [k, setFmt(v, v.v)])), ie: INFL_IE }));
      const keysS = Object.keys(lv.s); ok(keysS.length === 37 && /\*\*37 standards\*\*/.test('**' + keysS.length + ' standards**') && s3.text.includes('37 standards'), 'Settings has 37 standards live and in the doc: ' + keysS.length);
      const stdT = s3.blocks.filter(b => b.t === 'tbl' && b.rows[0][0] === 'Setting (workbook name)').flatMap(b => b.rows.slice(1)); ok(stdT.length === keysS.length, '3.7.1 tables hold ' + stdT.length + ' rows');
      const XSR = XL._settings.rows, wcell = nmx => { for (const row of XSR) for (const c of row) if (c[1].includes(nmx)) return c[0]; return undefined; }, same = (a, b) => (b == null ? a === '' || a == null : typeof b === 'number' ? Math.abs(+a - b) < 1e-12 : String(a) === String(b));
      for (const k of keysS) { const x = lv.s[k], nmn = 'Set_' + k + (x.u === 'pct3' ? '_1 to _3' : ''), r = stdT.find(t => t[0] === x.n + ' (' + nmn + ')'), src = [(x.src || 'no source (no published figure)') + ' · as at ' + x.asat].concat(x.guide ? ['Guidance: ' + x.guide] : [], x.note ? ['Note: ' + x.note] : []).join(' ');
        ok(r && r[1] === lv.fmt[k] && r[2] === (x.label || x.by) && r[3] === src && r[4] === (x.verify ? 'Yes' : 'No'), 'Settings ' + k + ': doc row ' + JSON.stringify(r));
        if (x.u === 'pct3') x.v.forEach((v, i) => ok(same(wcell('Set_' + k + '_' + (i + 1)), v), 'workbook Set_' + k + '_' + (i + 1) + ' = ' + v + ' (' + wcell('Set_' + k + '_' + (i + 1)) + ')')); else ok(same(wcell('Set_' + k), x.v), 'workbook Set_' + k + ' = ' + x.v + ' (' + wcell('Set_' + k) + ')');
        ok(wcell('Set_' + k + '_Label') === x.by, 'workbook Set_' + k + '_Label = prototype wording'); if (x.vc != null) ok(same(wcell('Set_' + k + '_Cautious'), x.vc), 'workbook Set_' + k + '_Cautious = ' + x.vc); }
      for (const [k, x] of Object.entries(lv.g)) ok(same(wcell('Set_g_' + k), x.v) && s3.text.includes(x.n + ' = ' + x.v), 'guidance figure ' + k + ' = ' + x.v + ' in the workbook and 3.7');
      ok(same(wcell('Set_inflNow'), lv.ie) && same(wcell('Card_APR_Cap'), 0.23) && s3.text.includes('Set_inflNow') && s3.text.includes('Card_APR_Cap'), 'fixed values on the Settings sheet: Ireland now ' + lv.ie + ', card cap 23%');
      ok(s3.text.includes('Partner_Name') && XSR.some(row => row.some(c => c[1].includes('Partner_Name'))), 'Partner_Name in the workbook and 3.7');
      // admin view and the partner override (live)
      const adm = await page.evaluate(() => { loadSample(); S.admin = true; lastId = null; render(); const T = e => e ? e.textContent.replace(/\s+/g, ' ').trim() : null; return { note: T(document.querySelector('.note[role="note"]')), label: T(document.querySelector('label[for="set-partner"]')), groups: [...document.querySelectorAll('details.asmg')].map(d => T(d.querySelector('summary'))), head: T(document.querySelector('header.sky')), jump: document.getElementById('jumps').textContent.includes('Admin (not for customers)') }; });
      const admT = s3.blocks.find(b => b.t === 'tbl' && b.rows.some(r => r[0].startsWith('Marked-off note'))); ok(admT && admT.rows.some(r => r[1] === adm.note) && admT.rows.some(r => r[1].includes(adm.label)) && adm.groups.every(g => allT(admT).includes('"' + g + '"')), 'admin view note, partner label and group summaries in 3.7.3: ' + adm.groups.join(' | ')); ok(adm.jump && adm.head.includes('🔒 Admin view · not for customers'), 'admin view is marked not for customers and reached from the jump list');
      const ovr = await page.evaluate(() => { const T = e => e ? e.textContent.replace(/\s+/g, ' ').trim() : null; S = fresh(); S.shell = true; S.tab = 'me'; S.me = 'asm'; SETTINGS.partner = 'Example Credit Union'; SET.infl.pv = 0.025; SET.mortRate.pv = 0.0399; SET.safetyMonths.pv = 4; const o = {};
        S.asmOpen = 'prices'; lastId = null; render(); const ic = document.querySelector('.infl'); o.infl = [T(ic.querySelector('p.small')), T(ic.querySelector('.chip'))]; o.wage = T(document.querySelector('.field.asmf[data-k="wage"] > span.small:last-child')); o.cash = T(document.querySelector('.field.asmf[data-k="cash"] > span.small:last-child'));
        S.asmOpen = 'safety'; render(); o.months = [T(document.querySelector('.field.asmf[data-k="safetyMonths"] > span.small:last-child')), T(document.querySelector('.field.asmf[data-k="safetyMonths"] [data-a="asmstd"]'))]; o.mort = T(document.querySelector('.field.asmf[data-k="mortRate"] [data-a="asmsug"]')); o.loan = T(document.querySelector('.field.asmf[data-k="loanRate"] [data-a="asmsug"]'));
        S.admin = true; render(); const tag = document.querySelector('#setl-infl .tag'); o.tag = T(tag); o.resetAll = T(document.querySelector('[data-a="setreset"][data-p="all"]')); SETTINGS.partner = ''; Object.values(SET).forEach(s => { delete s.pv; }); applyAssume(); S.admin = false; return o; });
      const ovT = s3.blocks.find(b => b.t === 'tbl' && b.rows[0][0] === 'Where the customer sees it'), ovAll = ovT ? allT(ovT) : '';
      ok(ovAll.includes(ovr.infl[0]) && ovAll.includes(ovr.infl[1]) && ovAll.includes(ovr.months[0]) && ovAll.includes(ovr.months[1]) && ovAll.includes(ovr.mort) && ovAll.includes(ovr.loan) && ovAll.includes(ovr.wage), '3.7.2 partner example strings equal the live screens: ' + [ovr.infl[0], ovr.mort].join(' | '));
      ok(/Suggested by Example Credit Union/.test(ovr.infl[0] + ovr.months[0] + ovr.mort) && !/Suggested by/.test(ovr.wage + ovr.cash + ovr.loan), '"Suggested by {partner}" only beside the figures the partner changed'); ok(s3.text.includes(ovr.tag) && s3.text.includes(ovr.resetAll), 'tag "' + ovr.tag + '" and "' + ovr.resetAll + '" in 3.7.2');
      // Your lists: item blocks, labels, buttons, hints
      const SL = await page.evaluate(() => ({ LDEF: JSON.parse(JSON.stringify(LDEF)), FFI: JSON.parse(JSON.stringify(FFI)), hint: PROT_HINT.workCover }));
      for (const lk of Object.keys(SL.LDEF)) { const D = SL.LDEF[lk]; ok(s4.text.includes('"' + D.add + '"') || s4.text.includes(D.add), 'add button "' + D.add + '" in section 4.8'); ok(s4.text.includes(D.up), 'upload text "' + D.up + '" in section 4.8'); D.f.forEach(f => ok(s4.text.includes(SL.FFI[lk + '.' + f].l), 'item field label "' + SL.FFI[lk + '.' + f].l + '" in 4.8')); }
      ok(s4.text.includes(SL.hint), 'cover-through-work hint in 4.8.3');
      const lst = async (secI, base) => page.evaluate(([i, base]) => { if (base === 'sample') loadSample(); else { S = fresh(); } S.app = false; S.pb = true; S.shell = true; S.tab = 'plan'; S.scr = 'P3'; lastId = null; openSec(i); const T = e => e ? e.textContent.replace(/\s+/g, ' ').trim() : null; return { adds: [...document.querySelectorAll('[data-a="iadd"]')].map(T), ups: [...document.querySelectorAll('[data-a="iupl"]')].map(T), titles: [...document.querySelectorAll('[id^="item-"] > .row b')].map(T), labels: [...document.querySelectorAll('[id^="item-"] label')].map(l => { const c = l.cloneNode(true); c.querySelectorAll('.tag').forEach(x => x.remove()); return T(c); }), lead: [...document.querySelectorAll('#main .card > p')].map(T), blank: T([...document.querySelectorAll('#main p.small')].find(p => /Leave blank/.test(p.textContent))), seg: document.querySelectorAll('.seg button').length, sub: T(document.querySelector('header.sky p.sub')) }; }, [secI, base]);
      const L3 = await lst(3, 'fresh'); ok(L3.adds.includes('＋ Add a credit card') && L3.adds.includes('＋ Add a loan') && L3.titles.includes('Credit card 1') && L3.titles.includes('Loan 1') && s4.text.includes(L3.blank) && s4.text.includes('Credit card 1'), 'Liabilities: add buttons, first empty items and the blank note: ' + L3.adds.join(' | '));
      L3.labels.forEach(l => ok(s4.text.includes(l), 'Liabilities item label "' + l + '" in the doc'));
      const L4 = await lst(4, 'fresh'); ok(L4.lead[0] === 'Do you have any of the following?' && L4.seg === 0 && s4.text.includes(L4.lead[0]) && s4.text.includes(L4.lead[1]) && s4.text.includes(L4.sub) && s4.text.includes('no generic upload at the top of this section'), 'Protection: lead-in, no generic upload, header line "' + L4.sub + '"');
      const L4b = await page.evaluate(() => { const o = []; S.fin.life = 'Yes'; S.fin.workCover = 'Yes'; S.fin.ip = 'Yes'; S.fin.ci = 'Yes'; S.fin.health = 'Yes'; lastId = null; render(); const T = e => e ? e.textContent.replace(/\s+/g, ' ').trim() : null; return { adds: [...document.querySelectorAll('[data-a="iadd"]')].map(T), titles: [...document.querySelectorAll('[id^="item-"] > .row b')].map(T), hint: T(document.getElementById('ph-workCover')) }; });
      ok(L4b.adds.length === 5 && L4b.adds.every(a => s4.text.includes(a)) && L4b.titles.every(t => s4.text.includes(t) || /\d$/.test(t)) && L4b.hint === SL.hint, 'Protection: five add buttons and the work-cover hint (' + L4b.adds.join(' | ') + ')');
      const L5 = await lst(5, 'fresh'); ok(L5.adds.includes('＋ Add another pension') && s4.text.includes('＋ Add another pension') && L5.labels.every(l => s4.text.includes(l)), 'Pension: separate items with the add button');
      // per-item upload flow and complete-on-save
      const up = await page.evaluate(async () => { S = fresh(); S.shell = true; S.pb = true; S.app = false; S.tab = 'plan'; S.scr = 'P3'; lastId = null; openSec(3); const it = document.querySelector('[data-a="iupl"][data-p^="cards|"]'); it.click(); await new Promise(r => setTimeout(r, 1700)); const a = document.getElementById('main').innerText.replace(/\s+/g, ' ').trim(), cur = document.getElementById('curid').textContent; document.querySelector('[data-a="uplok"]').click(); await new Promise(r => setTimeout(r, 300)); const T = e => e ? e.textContent.replace(/\s+/g, ' ').trim() : null; return { a, cur, toast: document.getElementById('toast').innerText, row: T(document.querySelector('[id^="item-cards"] .mini')), tags: [...document.querySelectorAll('[id^="item-cards"] label .tag')].map(T) }; });
      ok(s4.text.includes(up.a) && s4.text.includes(up.cur.replace(/^PU-confirm · /, '')) && s4.text.includes(up.toast.replace(/^\W+/, '')) && s4.text.includes(up.row), 'per-item upload: confirm screen, toast and the "From …" row equal 4.8.4: ' + up.a + ' | ' + up.row);
      const sv = await page.evaluate(() => { const hub = () => [...document.querySelectorAll('#main button.goal')].map(b => b.querySelector('b').textContent + ' = ' + b.querySelector('.sr').textContent); S = fresh(); S.shell = true; S.pb = true; S.app = false; S.tab = 'plan'; S.scr = 'P3'; lastId = null; openSec(3); const a = document.getElementById('i-cards-1-owed'); a.value = '400'; a.dispatchEvent(new Event('input', { bubbles: true })); document.querySelector('.foot .btn').click(); const h1 = hub(); openSec(2); document.querySelector('.foot .btn').click(); const h2 = hub(); const t = document.getElementById('toast').innerText; S.scr = 'P4'; S.pb = true; lastId = null; render(); const miss = [...document.querySelectorAll('#main .ck .small')].map(x => x.textContent.replace(/\s+/g, ' ').trim()).filter(x => /^Missing/.test(x)); return { h1, h2, t, miss }; });
      ok(sv.h2.includes('Assets = Done') && sv.h2.includes('Liabilities = Done') && sv.h2.every(h => s4.text.includes(h) || /Not started/.test(h)) && sv.miss.length > 0 && sv.miss.every(m => m === 'Missing · optional, counts as €0' && s4.text.includes(m)), 'a saved section (even with blanks) is Done and Missing reads optional: ' + sv.h2.join(', ') + ' | ' + sv.miss[0]);
      // workbook Your lists and the calculators that fall back to it
      const XL2 = XL._lists, lnames = [].concat(...XL2.rows.map(r => [].concat(...r.map(c => c[1])))).filter(n => /_Total|_Avg/.test(n)); const lt = s4.blocks.find(b => b.t === 'tbl' && b.rows[0][0] === 'Total (label)');
      ok(lnames.length >= 12 && lt && lnames.every(n => allT(lt).includes(n)), 'every named total of the sheet "Your lists" is in 4.10: ' + lnames.join(', ')); ok(s4.text.includes(XL2.intro), 'Your lists sheet intro text in 4.10');
      for (const [c, list] of Object.entries(XL._fallback)) { const csec = secs.find(s => s.title.startsWith(c + ' ')); list.forEach(([cl, lab, nms]) => ok(csec.text.includes(cl + ' "' + lab + '" ← ' + nms.join(' + ')) && s4.text.includes(lab), c + ' falls back to ' + nms.join(' + ') + ' (' + cl + ')')); }
      ok(Object.keys(XL._fallback).join(',') === 'C12,C13,C14,C21,C24,C25' && ['C27', 'C28'].every(c => secs.find(s => s.title.startsWith(c + ' ')).text.includes('not fed by the sheet "Your lists"')), 'exactly C12, C13, C14, C21, C24, C25 fall back to Your lists; C27 and C28 are not fed');
      // Emergency fund months: one value
      const mo = await page.evaluate(async () => { const o = {}; const T = e => e ? e.textContent.replace(/\s+/g, ' ').trim() : null; loadSample(); S.asm = Object.assign({}, S.asm); delete S.asm.safetyMonths; applyAssume(); syncSafety(); S.app = false; S.shell = true; S.tab = 'explore'; S.xs = []; lastId = null; render(); ACT.calc('emergency');
        o.gate = document.getElementById('cgate').innerText.replace(/\n/g, ' · '); o.tag = T(document.querySelector('#co-mt').closest('.field').querySelector('.tag')); const b = document.getElementById('co-mt'); b.value = '3'; b.dispatchEvent(new Event('input', { bubbles: true })); b.blur(); o.line = document.querySelector('#cout .card p').textContent; o.asm3 = S.asm.safetyMonths;
        S.tab = 'plan'; S.pb = true; S.scr = 'F2'; S.xs = []; S.tlOpen = {}; S.tlOpen[S.goals.find(g => g.k === 'safety').id] = true; lastId = null; render(); const gi = document.querySelector('[data-gmonths]'); o.goalShows = gi.value; o.goalLabel = T(gi.closest('label').querySelector('.fl')); o.goalNote = T(gi.closest('label').querySelector('.small')); o.ph = gi.placeholder; gi.value = '4'; gi.dispatchEvent(new Event('change', { bubbles: true })); o.asm4 = S.asm.safetyMonths;
        S.tab = 'explore'; S.xs = []; lastId = null; render(); ACT.calc('emergency'); o.calcAfter = document.getElementById('co-mt').value; S.tab = 'plan'; S.scr = 'P4'; S.pb = true; lastId = null; render(); const a = document.getElementById('p4-asm'); a.querySelectorAll('details').forEach(d => d.open = true); const f = a.querySelector('.field.asmf[data-k="safetyMonths"]'); o.p4 = f.querySelector('input.nb').value; o.p4tag = T(f.querySelector('.flabel .tag')); return o; });
      ok(mo.asm3 === 3 && mo.goalShows === '3' && mo.asm4 === 4 && mo.calcAfter === '4' && mo.p4 === '4' && mo.p4tag === 'Your choice', 'Emergency fund months are one value: calculator 3 -> goal ' + mo.goalShows + ', goal 4 -> calculator ' + mo.calcAfter + ', step 7 ' + mo.p4);
      ok(sec6.text.includes('"' + mo.gate + '"') && sec6.text.includes('"' + mo.line + '"') && sec6.text.includes('"' + mo.goalLabel + '"') && sec6.text.includes('"' + mo.ph + '"') && sec6.text.includes(mo.goalNote) && sec6.text.includes('tag "' + mo.tag + '"'), '6.1 strings equal the live screens: ' + mo.gate + ' | ' + mo.line + ' | ' + mo.goalLabel);
      // goal order
      const rk = await page.evaluate(() => { const o = {}; const T = e => e ? e.textContent.replace(/\s+/g, ' ').trim() : null; loadSample(); S.app = false; S.shell = true; S.pb = true; S.tab = 'plan'; S.scr = 'F4'; S.rank = null; lastId = null; render(); const r = document.querySelector('[id^="rank-"]:not([id*="msg"]):not([id*="-h-"])'); o.id = r.id; o.heading = T(r.querySelector('h3')); o.help = T(r.querySelector(':scope > p.small')); o.names = rankList().map(g => g.name); o.aria = [...r.querySelectorAll('li:nth-child(2) button')].map(b => b.getAttribute('aria-label')); o.disabled = [r.querySelector('li:first-child button').getAttribute('aria-disabled'), r.querySelector('li:last-child button:last-child').getAttribute('aria-disabled')];
        r.querySelector('[data-a="grank"][data-p$="|down"]').click(); const r2 = document.querySelector('[id^="rank-"]:not([id*="msg"]):not([id*="-h-"])'); o.msg = T(r2.querySelector('[id^="rank-msg"]')); o.reset = T(r2.querySelector('[data-a="grankreset"]')); o.names2 = rankList().map(g => g.name); o.v1 = S.versions[S.versions.length - 1].note; document.querySelector('[data-a="grankreset"]').click(); o.msg3 = T(document.querySelector('[id^="rank-msg"]')); o.names3 = rankList().map(g => g.name); o.v2 = S.versions[S.versions.length - 1].note;
        S.rank = null; o.resDef = resultOrder().map(g => g.name); const l = rankList().map(g => g.id), i = l.indexOf(S.goals.find(g => g.k === 'travel').id); l.unshift(...l.splice(i, 1)); S.rank = l; o.resRank = resultOrder().map(g => g.name); S.rank = null; return o; });
      ok(rk.names[0] === 'Emergency fund' && rk.names2[1] === 'Emergency fund' && rk.names3[0] === 'Emergency fund' && rk.disabled.join() === 'true,true' && rk.msg3 === 'Back to the suggested order' && rk.v1 === 'Goal priority changed' && rk.v2 === 'Goal priority reset', 'ranking: Emergency fund first by default, movable, reset restores: ' + rk.names.join(' > ') + ' | ' + rk.names2.join(' > '));
      ok(sec6.text.includes(rk.heading) && sec6.text.includes(rk.help.replace(/ \(Not changed yet\.\)$/, '')) && rk.aria.every(a => sec6.text.includes(a)) && sec6.text.includes(rk.msg) && sec6.text.includes('"' + rk.reset + '"') && sec6.text.includes(rk.msg3) && sec6.text.includes(rk.resDef.join(', ')) && sec6.text.includes(rk.resRank.join(', ')) && sec6.text.includes(rk.names.join(' › ')) && rk.id === 'rank-f4', '6.2 strings equal the live ranking card: ' + rk.heading + ' | ' + rk.msg + ' | ' + rk.resRank.join(', '));
      ok(!/PARTNER_RATES|partner rates block/.test(secs.map(x => x.text).join(' ').replace('It replaces the earlier partner rates block (§18)', '')), 'no leftover reference to the old PARTNER_RATES block');
