// §21 / §22: Focus on one area tiles, Experts specialist boxes, Step 7 skippable, results banner
const { open } = require('./lib'); const fs = require('fs'); const SHOTS = __dirname + '/shots/';
(async () => { const { browser, page, errors } = await open(); const out = {}; const T = e => e ? e.textContent.replace(/\s+/g, ' ').trim() : null;
  const tall = async h => { await page.setViewportSize({ width: 390, height: h }); await page.waitForTimeout(250); };
  const phone = async f => { await page.evaluate(() => { document.getElementById('toast').innerHTML = ''; document.activeElement && document.activeElement.blur(); }); await page.waitForTimeout(150); await page.locator('#phone').screenshot({ path: SHOTS + f }); };
  // tiles
  await tall(1500); await page.evaluate(() => { loadSample(); S.tab = 'explore'; S.xs = []; lastId = null; render(); }); await page.waitForTimeout(500);
  out.tiles = await page.evaluate(() => ({ heading: [...document.querySelectorAll('#main h3')].map(h => h.textContent).find(t => /Focus/.test(t)), items: [...document.querySelectorAll('.ttile')].map(e => ({ em: e.querySelector('.em').textContent, name: e.querySelector('b').textContent, blurb: e.querySelector('.s').textContent, a: e.dataset.a + '|' + e.dataset.p, art: e.getAttribute('style'), fx: e.querySelectorAll('.fx *').length > 0, chev: e.querySelector('.go').textContent })), arts: ['mortgage', 'pension', 'protection', 'investing', 'savings', 'everyday'] }));
  await page.locator('.tgrid').evaluate(e => e.scrollIntoView({ block: 'center', behavior: 'instant' })); await page.waitForTimeout(300); await page.locator('.tgrid').screenshot({ path: SHOTS + 'T-tiles-390.png' });
  await page.setViewportSize({ width: 1280, height: 1500 }); await page.waitForTimeout(300); await phone('T-explore-1280.png');
  await page.setViewportSize({ width: 390, height: 1500 }); await page.waitForTimeout(200);
  // experts
  out.experts = {};
  for (const [st, f] of [['home', 'T-exp00.png'], ['c0', 'T-c0.png'], ['c1', 'T-c1.png']]) { await page.evaluate(s => { loadSample(); S.tab = 'exp'; S.exp = s; lastId = null; render(); }, st); await page.waitForTimeout(300);
    out.experts[st] = await page.evaluate(() => ({ heads: [...document.querySelectorAll('#main h3')].map(T0 => T0.textContent), boxes: [...document.querySelectorAll('button.goal.spec')].map(e => ({ ic: e.querySelector('.ic').textContent, name: e.querySelector('b').textContent, blurb: e.querySelector('.small').textContent, a: e.dataset.a + '|' + e.dataset.p, pressed: e.getAttribute('aria-pressed') })), group: (document.querySelector('[role=group][aria-label]') || {}).ariaLabel }));
    await phone(f); }
  await page.evaluate(() => { loadSample(); S.tab = 'exp'; S.exp = 'c4'; S.book.done = true; S.book.slot = SLOTS[1]; lastId = null; render(); }); out.experts.c4 = await page.evaluate(() => document.querySelectorAll('button.goal.spec').length);
  // step 7
  const toP4 = () => page.evaluate(() => { loadSample(); S.app = false; S.shell = true; S.pb = true; S.tab = 'plan'; S.scr = 'P4'; S.retireSet = false; S.infl = null; S.asm = {}; S.checked = false; lastId = null; render(); });
  const st7 = () => page.evaluate(() => ({ head: T1(document.querySelector('header.sky')), h3: [...document.querySelectorAll('#p4-asm h3')].map(h => h.textContent), p3: document.querySelector('#p4-3 h3 + p').textContent, count: document.getElementById('p4-count').textContent, restP: document.querySelector('#p4-rest h3 + p').textContent, btn: (document.querySelector('[data-a=useall][data-p=p4]') || {}).textContent || null, note: (document.querySelector('[data-a=useall][data-p=p4]') ? document.querySelector('[data-a=useall][data-p=p4]').nextElementSibling.textContent : null), summary: document.querySelector('#p4-rest summary').textContent, need: (document.getElementById('p4-need') || {}).textContent || null, see: [document.getElementById('seeres').textContent, document.getElementById('seeres').disabled], skip: [document.getElementById('skipres').textContent, document.getElementById('skipres').disabled], tick: !!document.querySelector('[data-chk]'), labels: ['#p4-infl b', '#p4-3 .field >> nth=0'].length, order: [...document.querySelectorAll('#main > *')].map(e => e.id || e.className.split(' ')[0]).slice(0, 4) }));
  await page.evaluate(() => { window.T1 = e => e ? e.innerText.replace(/\s+/g, ' ').trim() : ''; });
  await tall(2300); await toP4(); await page.waitForTimeout(300); out.step7a = await st7(); await phone('T-step7a.png');
  await page.click('[data-a=useall][data-p=p4]'); await page.waitForTimeout(250); out.step7b = await st7();
  await page.click('#p4-infl [data-a="infl"][data-p="0.02"]'); await page.fill('[data-nb="ret|a"]', '65'); await page.press('[data-nb="ret|a"]', 'Enter'); await page.fill('[data-nb="asm|planEnd"]', '90'); await page.press('[data-nb="asm|planEnd"]', 'Enter'); await page.waitForTimeout(250); out.step7c = await st7(); await phone('T-step7c.png');
  // banner: skip -> results
  await page.click('#skipres'); await page.waitForTimeout(2300);
  out.skip = await page.evaluate(() => ({ app: S.app, tab: S.tab, banner: (document.getElementById('miss-banner') || {}).textContent || '', gate: (document.getElementById('gate-res') || {}).textContent || '', n: missingFlags().length }));
  await tall(1100); await page.evaluate(() => { document.getElementById('r-res').scrollIntoView({ block: 'start', behavior: 'instant' }); }); await page.waitForTimeout(300); await phone('T-banner-skip.png');
  const force = async k => page.evaluate(k => { loadSample(); S.app = true; S.shell = true; S.pb = false; S.tab = 'plan'; S.planSeg = 'main'; S.retireSet = true; S.infl = 0.02; S.asm.planEnd = 90; useAllStd(); const ks = []; FSEC.forEach(s => s.f.filter(fieldVisible).filter(x => x !== 'retireAge' && !FF[x].opt).forEach(x => ks.push(x))); ks.forEach(x => { S.src[x] = 'typed'; }); Object.keys(S.look).forEach(x => delete S.look[x]); ks.slice(0, k).forEach(x => { delete S.src[x]; delete S.fin[x]; }); lastId = null; render(); return { n: missingFlags().length, banner: (document.getElementById('miss-banner') || {}).textContent || '', link: (document.querySelector('[data-a=addmiss]') || {}).textContent || '' }; }, k);
  out.banner = {}; for (const k of [0, 1, 3]) { out.banner[k] = await force(k); if (k) { await page.evaluate(() => document.getElementById('r-res').scrollIntoView({ block: 'start', behavior: 'instant' })); await page.waitForTimeout(250); await page.locator('#miss-banner').screenshot({ path: SHOTS + 'T-banner-' + k + '.png' }); } }
  await force(3); await page.click('[data-a=addmiss]'); await page.waitForTimeout(250); out.addMany = await page.evaluate(() => ({ tab: S.tab, me: S.me, title: (document.querySelector('header.sky h2') || {}).textContent, list: [...document.querySelectorAll('#main .card')].map(c => T1(c)).find(t => /To sharpen/.test(t)) }));
  await force(1); await page.click('[data-a=addmiss]'); await page.waitForTimeout(250); out.addOne = await page.evaluate(() => ({ tab: S.tab, fsec: S.fsec, title: (document.querySelector('header.sky h2') || {}).textContent }));
  out.errors = errors; fs.writeFileSync(__dirname + '/s21.json', JSON.stringify(out, null, 1)); console.log('s21 done', errors); await browser.close(); })();
