// §19 part B: Settings admin view, partner override, Emergency fund months, goal ranking
const { open } = require('./lib'); const fs = require('fs'); const SHOTS = __dirname + '/shots/'; const extractAsm = require('./extract-asm');
(async () => { const { browser, page, errors } = await open(); const out = {}; const T = e => e ? e.textContent.replace(/\s+/g, ' ').trim() : null;
  const full = async (file) => { await page.evaluate(() => { document.getElementById('toast').innerHTML = ''; const m = document.getElementById('main'); if (m) m.scrollTop = 0; });
    const h = await page.evaluate(() => { const m = document.getElementById('main'), last = m.lastElementChild; return document.querySelector('header.sky').offsetHeight + (last.getBoundingClientRect().bottom - m.getBoundingClientRect().top + m.scrollTop) + 30 + (document.querySelector('.foot') ? document.querySelector('.foot').offsetHeight : 0) + (document.querySelector('nav.tabs') || { offsetHeight: 0 }).offsetHeight; });
    await page.setViewportSize({ width: 390, height: Math.min(4400, Math.ceil(h)) }); await page.waitForTimeout(150); await page.evaluate(() => document.activeElement && document.activeElement.blur()); await page.locator('#phone').screenshot({ path: SHOTS + file }); await page.setViewportSize({ width: 390, height: 844 }); await page.waitForTimeout(60); };
  const admin = async (open) => { await page.evaluate(open => { loadSample(); S.admin = true; S.asmOpen = open || null; lastId = null; render(); if (open === 'ALL') document.querySelectorAll('details.asmg').forEach(d => d.open = true); }, open); await page.waitForTimeout(100); };
  const adminDom = () => page.evaluate(() => { const T = e => e ? e.textContent.replace(/\s+/g, ' ').trim() : null; document.querySelectorAll('details.asmg').forEach(d => d.open = true);
    return { head: T(document.querySelector('header.sky')), note: T(document.querySelector('.note[role="note"]')), partnerLabel: T(document.querySelector('label[for="set-partner"]')), partnerValue: document.getElementById('set-partner').value, resetAll: T(document.querySelector('[data-a="setreset"][data-p="all"]')), back: T(document.querySelector('.backb')),
      groups: [...document.querySelectorAll('details.asmg')].map(d => ({ g: d.dataset.g, summary: T(d.querySelector('summary')), fields: [...d.querySelectorAll(':scope > div > .field')].map(f => { const spans = [...f.querySelectorAll(':scope > span.small')].map(T); const inp = f.querySelector('input, select');
        return { label: T(f.querySelector('.flabel')), tag: T(f.querySelector('.flabel .tag')), lines: spans, inputs: [...f.querySelectorAll('input')].map(i => [i.getAttribute('aria-label'), i.placeholder, i.value]), select: f.querySelector('select') ? [...f.querySelectorAll('option')].map(T) : null, reset: T(f.querySelector('[data-a="setreset"]')) }; }), tail: T(d.querySelector(':scope > div > p.small')) })) }; });
  await admin(); out.admin = await adminDom(); const card = async (g, file, nfields) => { await page.setViewportSize({ width: 390, height: 3200 }); await page.waitForTimeout(100); const loc = page.locator('details.asmg[data-g="' + g + '"]'); await loc.evaluate(d => { d.open = true; }); await loc.screenshot({ path: SHOTS + file }); await page.setViewportSize({ width: 390, height: 844 }); };
  await admin('set-Prices & growth'); await page.setViewportSize({ width: 390, height: 844 }); await page.evaluate(() => { document.getElementById('main').scrollTop = 0; }); await page.screenshot({ path: SHOTS + 'T-admin-top.png' });
  await admin(); await card('set-Market rates', 'T-admin-market.png');
  // partner override: one overridden figure each for a standard and for a market rate
  out.override = {};
  await page.evaluate(() => { loadSample(); S.asm = {}; S.infl = null; SETTINGS.partner = 'Example Credit Union'; SET.infl.pv = 0.025; SET.wage.vc = SET.wage.vc; SET.mortRate.pv = 0.0399; SET.safetyMonths.pv = 4; applyAssume(); S.admin = true; S.asmOpen = 'set-Prices & growth'; lastId = null; render(); });
  out.override.admin = await adminDom(); await admin(); await page.evaluate(() => { SETTINGS.partner = 'Example Credit Union'; SET.infl.pv = 0.025; SET.mortRate.pv = 0.0399; SET.safetyMonths.pv = 4; S.admin = true; render(); }); await page.evaluate(() => { document.getElementById('main').scrollTop = 0; }); await page.screenshot({ path: SHOTS + 'T-admin-override.png' }); await card('set-Emergency fund & saving', 'T-admin-emerg-override.png');
  const goAsm = g => page.evaluate(g => { S = fresh(); S.shell = true; S.tab = 'me'; S.me = 'asm'; S.asmOpen = g; lastId = null; render(); }, g);
  const ff = async keys => { const a = await page.evaluate(extractAsm); const o = {}; a.groups[0].fields.filter(f => keys.includes(f.k)).forEach(f => { o[f.k] = { label: f.label, guide: f.guide, std: f.std, tag: f.tag }; }); return o; };
  await goAsm('prices'); out.override.prices = await ff(['wage', 'cash', 'inv', 'pen']); await goAsm('safety'); out.override.safety = await ff(['mortRate', 'loanRate', 'cardRate', 'safetyMonths', 'buyFees']);
  await page.evaluate(() => { S = fresh(); S.shell = true; S.tab = 'me'; S.me = 'asm'; S.asmOpen = 'prices'; lastId = null; render(); }); out.override.infl = await page.evaluate(() => { const ic = document.querySelector('.infl'); const T = e => e ? e.textContent.replace(/\s+/g, ' ').trim() : null; return { help: T(ic.querySelector('p.small')), chips: [...ic.querySelectorAll('.chip')].map(T) }; });
  await goAsm('safety'); await page.locator('.field.asmf[data-k="mortRate"]').screenshot({ path: SHOTS + 'T-cust-mort-partner.png' }); await goAsm('prices'); await page.locator('.field.asmf[data-k="wage"]').screenshot({ path: SHOTS + 'T-cust-wage.png' });
  await page.evaluate(() => { loadSample(); S.asm = {}; S.sheet = 'assume'; render(); document.querySelectorAll('.sheet details').forEach(d => d.open = true); }); out.override.sheet = await page.evaluate(() => [...document.querySelectorAll('.sheet .mini')].map(m => { const sp = m.querySelector('span'), tg = sp && sp.querySelector('.tag'), c = sp.cloneNode(true); c.querySelectorAll('.tag').forEach(x => x.remove()); const t = e => e ? e.textContent.replace(/\s+/g, ' ').trim() : ''; return [t(c), t(tg), t(m.querySelector('b'))]; }).filter(r => /^(Prices rise|Mortgage rate|Other loans rate|Safety net)/.test(r[0])));
  await admin('set-Prices & growth'); await page.evaluate(() => { SETTINGS.partner = 'Example Credit Union'; SET.infl.pv = 0.025; render(); }); await page.click('[data-a="setreset"][data-p="infl"]'); out.override.afterReset = await page.evaluate(() => ({ pv: SET.infl.pv, tag: !!document.querySelector('[id="setl-infl"] .tag') })); await page.click('[data-a="setreset"][data-p="all"]');
  out.override.restored = await page.evaluate(() => ({ partner: SETTINGS.partner, any: Object.values(SET).some(s => s.pv != null) }));
  // typing into the admin view: a partner figure and the partner name
  await admin('set-Prices & growth'); await page.fill('#set-partner', 'Example Credit Union'); await page.press('#set-partner', 'Tab'); await page.fill('#set-infl', '2.5'); await page.press('#set-infl', 'Tab'); await page.waitForTimeout(100);
  out.typed = await page.evaluate(() => ({ partner: SETTINGS.partner, pv: SET.infl.pv, tag: (e => e ? e.textContent.replace(/\s+/g, " ").trim() : null)(document.querySelector('#setl-infl .tag')), resetAll: !!document.querySelector('[data-a="setreset"][data-p="all"]') })); 
  await page.click('[data-a="setreset"][data-p="all"]');
  // Emergency fund months: one value
  out.months = {};
  const step7 = () => page.evaluate(() => { const T = e => e ? e.textContent.replace(/\s+/g, ' ').trim() : null; const a = document.getElementById('p4-asm'); const f = a && a.querySelector('.field.asmf[data-k="safetyMonths"]'); if (a) a.querySelectorAll('details').forEach(d => d.open = true); const f2 = a && a.querySelector('.field.asmf[data-k="safetyMonths"]'); return { text: T(a), field: f2 ? { label: T(f2.querySelector('.flabel')), tag: T(f2.querySelector('.flabel .tag')), box: (f2.querySelector('input.nb') || {}).value, guide: T(f2.querySelector(':scope > span.small')), chip: T(f2.querySelector('[data-a="asmback"]')) } : null, months: typeof asmMine === 'function' && asmMine('safetyMonths') ? asmGet('safetyMonths') : null }; });
  const toP4 = () => page.evaluate(() => { S.app = false; S.shell = true; S.pb = true; S.tab = 'plan'; S.scr = 'P4'; S.checked = false; lastId = null; render(); });
  await page.evaluate(() => { loadSample(); S.asm = Object.assign({}, S.asm); delete S.asm.safetyMonths; applyAssume(); syncSafety(); }); await toP4(); out.months.p4Before = await step7();
  await page.evaluate(() => { S.app = false; S.shell = true; S.tab = 'explore'; S.xs = []; lastId = null; render(); ACT.calc('emergency'); }); out.months.calcBlank = await page.evaluate(() => ({ box: document.getElementById('co-mt').value, gate: (document.getElementById('cgate') || {}).innerText || null, tag: (e => e ? e.textContent.replace(/\s+/g, " ").trim() : null)(document.querySelector('#co-mt').closest('.field').querySelector('.tag')) }));
  await page.fill('#co-mt', '3'); await page.evaluate(() => document.activeElement.blur()); out.months.calcSet = await page.evaluate(() => ({ box: document.getElementById('co-mt').value, asm: S.asm.safetyMonths, line: (document.querySelector('#cout .card p') || {}).textContent })); await toP4(); out.months.p4AfterCalc = await step7();
  await page.evaluate(() => { loadSample(); S.asm = Object.assign({}, S.asm); delete S.asm.safetyMonths; applyAssume(); syncSafety(); S.app = false; S.shell = true; S.pb = true; S.tab = 'plan'; S.scr = 'F2'; const g = S.goals.find(g => g.k === 'safety'); S.tlOpen = S.tlOpen || {}; S.tlOpen[g.id] = true; lastId = null; render(); });
  out.months.goalRow = await page.evaluate(() => { const l = document.querySelector('[data-gmonths]').closest('label'); return { label: (e => e ? e.textContent.replace(/\s+/g, " ").trim() : null)(l.querySelector('.fl')), placeholder: document.querySelector('[data-gmonths]').placeholder, note: (e => e ? e.textContent.replace(/\s+/g, " ").trim() : null)(l.querySelector('.small')) }; });
  await page.locator('.grow:has([data-gmonths])').screenshot({ path: SHOTS + 'M-goal-months.png' });
  await page.fill('[data-gmonths]', '4'); await page.evaluate(() => document.activeElement.blur()); await page.waitForTimeout(100); out.months.goalSet = await page.evaluate(() => ({ asm: S.asm.safetyMonths, input: document.querySelector('[data-gmonths]').value }));
  await page.evaluate(() => { S.tab = 'explore'; S.xs = []; lastId = null; render(); ACT.calc('emergency'); }); out.months.calcAfterGoal = await page.evaluate(() => document.getElementById('co-mt').value); await toP4(); out.months.p4AfterGoal = await step7(); await page.setViewportSize({ width: 390, height: 2600 }); await page.evaluate(() => { document.querySelectorAll('#p4-asm details').forEach(d => d.open = true); const f = document.querySelector('#p4-asm .field.asmf[data-k="safetyMonths"]'); f.scrollIntoView({ block: 'center' }); }); await page.waitForTimeout(150); await page.locator('#p4-asm .field.asmf[data-k="safetyMonths"]').screenshot({ path: SHOTS + 'M-step7.png' }); await page.setViewportSize({ width: 390, height: 844 });
  // Goal ranking
  out.rank = {};
  const rankDom = () => page.evaluate(() => { const T = e => e ? e.textContent.replace(/\s+/g, ' ').trim() : null; const r = document.querySelector('[id^="rank-"]:not([id*="msg"]):not([id*="-h-"])'); if (!r) return null; return { id: r.id, heading: T(r.querySelector('h3')), help: T(r.querySelector(':scope > p.small')), items: [...r.querySelectorAll('ol > li')].map(li => ({ text: T(li.querySelector('span')), btns: [...li.querySelectorAll('button')].map(b => [b.textContent, b.getAttribute('aria-label'), b.getAttribute('aria-disabled')]) })), msg: T(r.querySelector('[id^="rank-msg"]')), reset: T(r.querySelector('[data-a="grankreset"]')) }; });
  await page.evaluate(() => { loadSample(); S.app = false; S.shell = true; S.pb = true; S.tab = 'plan'; S.scr = 'F4'; S.rank = null; lastId = null; render(); }); out.rank.f4 = await rankDom(); await page.locator('[id="rank-f4"], .card:has(ol.rank)').first().screenshot({ path: SHOTS + 'K-rank-default.png' });
  const order = () => page.evaluate(() => rankList().map(g => g.name)); out.rank.order0 = await order();
  await page.click('[data-a="grank"][data-p$="|down"] >> nth=0'); out.rank.afterDown = await rankDom(); out.rank.order1 = await order();
  const lastUp = page.locator('[data-a="grank"][data-p$="|up"]').nth(await page.locator('[data-a="grank"][data-p$="|up"]').count() - 1); await lastUp.click(); out.rank.afterUp = await rankDom(); out.rank.order2 = await order();
  await page.locator('.card:has(ol.rank)').first().screenshot({ path: SHOTS + 'K-rank-moved.png' });
  out.rank.firstUpDisabled = await page.evaluate(() => document.querySelector('[data-a="grank"][data-p$="|up"]').getAttribute('aria-disabled')); await page.click('[data-a="grankreset"]'); out.rank.afterReset = await rankDom(); out.rank.order3 = await order(); out.rank.versions = await page.evaluate(() => S.versions.map(v => v.note).slice(-3));
  // results order follows the ranking (after a plan)
  await page.evaluate(() => { loadSample(); S.rank = null; lastId = null; render(); }); out.rank.resultsDefault = await page.evaluate(() => resultOrder().map(g => g.name));
  await page.evaluate(() => { const l = rankList().map(g => g.id); const i = l.indexOf(S.goals.find(g => g.k === 'travel').id); l.unshift(...l.splice(i, 1)); S.rank = l; render(); }); out.rank.resultsRanked = await page.evaluate(() => resultOrder().map(g => g.name)); out.rank.rankedList = await page.evaluate(() => rankList().map(g => g.name));
  await page.evaluate(() => { S.tab = 'plan'; S.planSeg = 'main'; lastId = null; render(); }); out.rank.planCtx = await rankDom(); out.rank.planGoalsBox = await page.evaluate(() => [...document.querySelectorAll('#main .gs .nm, #main .gs b')].map(e => e.textContent.trim()).slice(0, 8));
  out.errors = errors; fs.writeFileSync(__dirname + '/s19b.json', JSON.stringify(out, null, 1)); console.log('part B done', errors); await browser.close(); })();
