// §23 to §25: cover photo and contrast, naming, Budget 2027 note, Liabilities, What-if, saving files, photos on tiles, real videos
const { open } = require('./lib'); const fs = require('fs'), path = require('path'), crypto = require('crypto'); const SHOTS = __dirname + '/shots/';
const { chromium } = require('/opt/node22/lib/node_modules/playwright');
const LIB = '/tmp/claude-0/-home-user-lifegoals-prototype/bb23c080-deb2-506f-b951-1207e03dac85/scratchpad/s23/lib/';
(async () => { const { browser, page, errors } = await open(); const out = {}; const T = e => e ? e.textContent.replace(/\s+/g, ' ').trim() : null;
  const tall = async (w, h) => { await page.setViewportSize({ width: w, height: h }); await page.waitForTimeout(250); };
  const phone = async f => { await page.evaluate(() => { document.getElementById('toast').innerHTML = ''; document.activeElement && document.activeElement.blur(); }); await page.waitForTimeout(200); await page.locator('#phone').screenshot({ path: SHOTS + f }); };
  // --- cover at four sizes, with contrast of every line of text against the worst pixel behind it
  out.cover = { sizes: {} };
  for (const [w, h] of [[390, 844], [360, 640], [844, 390], [1280, 800]]) { await tall(w, h); await page.evaluate(() => { S = fresh(); S.scr = 'D0'; lastId = null; render(); }); await page.waitForTimeout(500);
    await page.screenshot({ path: SHOTS + 'B-cover-' + w + 'x' + h + '.png' });
    await page.addStyleTag({ content: '.cover h2,.cover .cover-line,.cover .cover-under,.cover .cover-small .link,.cover .brand{color:transparent!important;text-shadow:none!important}.cover .brand .mark{visibility:hidden}' });
    const items = await page.evaluate(() => [['Wordmark', '.cover .brand'], ['Headline', '.cover h2'], ['Line', '.cover-line'], ['Under the button', '.cover-under'], ['Why we ask', '.cover-small .link']].map(([n, s]) => { const e = document.querySelector(s); let r = e.getBoundingClientRect(); if (n === 'Wordmark') { const rg = document.createRange(); rg.selectNodeContents(e.lastChild); r = rg.getBoundingClientRect(); } return { n, x: r.x, y: r.y, w: r.width, h: r.height }; }));
    const buf = await page.screenshot(); const res = await page.evaluate(async ([b64, items]) => { const i = new Image(); i.src = 'data:image/png;base64,' + b64; await i.decode(); const c = document.createElement('canvas'); c.width = i.width; c.height = i.height; const g = c.getContext('2d'); g.drawImage(i, 0, 0); const L = v => { v /= 255; return v <= .03928 ? v / 12.92 : Math.pow((v + .055) / 1.055, 2.4); }; const s = i.width / innerWidth;
      return items.map(t => { const d = g.getImageData(Math.round(t.x * s), Math.round(t.y * s), Math.max(1, Math.round(t.w * s)), Math.max(1, Math.round(t.h * s))).data; let mx = 0; for (let k = 0; k < d.length; k += 4) { const l = .2126 * L(d[k]) + .7152 * L(d[k + 1]) + .0722 * L(d[k + 2]); if (l > mx) mx = l; } return [t.n, +(1.05 / (mx + .05)).toFixed(1)]; }); }, [buf.toString('base64'), items]);
    out.cover.sizes[w + 'x' + h] = res; await page.reload(); await page.waitForTimeout(400); }
  await tall(390, 844); await page.evaluate(() => { S = fresh(); S.scr = 'D0'; lastId = null; render(); });
  out.cover.css = await page.evaluate(() => ({ photoPos: getComputedStyle(document.querySelector('.cover-photo')).backgroundPosition, isJpeg: /^url\("data:image\/jpeg;base64,/.test(getComputedStyle(document.documentElement).getPropertyValue('--cover-photo')), kb: Math.round(getComputedStyle(document.documentElement).getPropertyValue('--cover-photo').length * 3 / 4 / 1024), note: V.D0().note }));
  // --- naming and Budget 2027
  await page.evaluate(() => { loadSample(); delete S.asm.safetyMonths; S.infl = 0.02; S.retireSet = true; S.asm.planEnd = 90; S.tab = 'plan'; lastId = null; render(); });
  out.naming = await page.evaluate(() => ({ gate: chooseTxt({ n: ASM.safetyMonths.n }), label: ASM.safetyMonths.l, n: ASM.safetyMonths.n, group: ASM_GRP.find(g => g[0] === 'safety')[1], row: assumeRows().find(r => /Emergency fund/.test(r[0])), calcQ: CALCS.find(c => c.id === 'emergency').q, calcLine: 'Your emergency fund covers', rows: ['Target emergency fund', 'Still to build'], me: 'Prices, growth, retirement and emergency fund settings', mis: [MIS.K16, MIS.K14c, MIS.K14l], misAdv: [MIS.K14c, MIS.K14l] }));
  out.budget = await page.evaluate(() => BUDGET27);
  // --- tiles with photos
  await tall(390, 1500); await page.evaluate(() => { loadSample(); S.tab = 'explore'; S.xs = []; lastId = null; render(); }); await page.waitForTimeout(600);
  out.tiles = await page.evaluate(() => ({ pos: TOPIC_PHOTO, kinds: ['mortgage', 'pension', 'protection', 'investing', 'savings', 'everyday'].map(k => [k, /^url\("data:image\/jpeg/.test(getComputedStyle(document.documentElement).getPropertyValue('--art-' + k)) ? 'photo' : 'drawn']) }));
  await page.locator('.tgrid').evaluate(e => e.scrollIntoView({ block: 'center', behavior: 'instant' })); await page.waitForTimeout(300); await page.locator('.tgrid').screenshot({ path: SHOTS + 'T-tiles-photos-390.png' });
  // --- videos
  await page.evaluate(() => { S = fresh(); S.shell = true; S.app = false; S.tab = 'home'; lastId = null; render(); }); await page.waitForTimeout(500);
  out.videos = { list: await page.evaluate(() => VIDEOS.map(v => ({ id: v.id, t: v.t, kind: VKIND[v.kind], who: v.who, dur: v.dur || v.mins + ' min', src: v.src || null, poster: v.poster || null, tool: C(v.tool).name }))), home: await page.evaluate(() => [...document.querySelectorAll('#main .vthumb b')].map(e => e.textContent)) };
  await phone('T-video-home.png');
  await page.evaluate(() => { S.tab = 'explore'; S.xs = [{ v: 'VIDS' }]; lastId = null; render(); }); await page.waitForTimeout(400);
  out.videos.lib = await page.evaluate(() => [...document.querySelectorAll('#main .vthumb b')].map(e => e.textContent)); await phone('T-video-library.png');
  await page.evaluate(() => { S.xs = [{ v: 'VID', p: 'v8' }]; lastId = null; render(); }); await page.waitForTimeout(1500);
  out.videos.player = await page.evaluate(() => { const e = document.getElementById('vid-el'); return { attrs: { controls: e.controls, preload: e.getAttribute('preload'), src: e.getAttribute('src'), poster: e.getAttribute('poster'), label: e.getAttribute('aria-label'), playsinline: e.hasAttribute('playsinline') }, caps: T0(document.getElementById('vid-cap')), fail: document.getElementById('vid-fail').innerText.replace(/\s+/g, ' ').trim(), failShown: !document.getElementById('vid-fail').hidden, tool: [...document.querySelectorAll('#main .btn')].map(x => x.textContent.trim()), expert: [...document.querySelectorAll('#main [data-a=expertfor]')].map(x => x.textContent.trim()), meta: document.querySelector('#main h2 + .small').textContent }; function T0(e) { return e.textContent.replace(/\s+/g, ' ').trim(); } });
  await phone('T-video-player-fallback.png');
  // --- Liabilities
  await tall(390, 2300); const L = setup => page.evaluate(src => { eval(src); S.app = true; S.shell = true; S.tab = 'me'; S.me = 'fin'; S.fsec = 3; lastId = null; render(); }, setup);
  await L('loadSample();'); out.liab = { sample: await page.evaluate(() => ({ order: [...document.querySelectorAll('#main .card')].map(c => (c.querySelector('b') || {}).textContent).filter(Boolean), labels: [...document.querySelectorAll('#main .card')[1].querySelectorAll('.flabel, label')].map(e => e.textContent.replace(/\s+/g, ' ').trim()) , add: LDEF.mort2.add, one: LDEF.mort2.one, title: LDEF.mort2.t, up: LDEF.mort2.up, fields: LDEF.mort2.f.map(f => [FFI['mort2.' + f].l, FFI['mort2.' + f].type, !!FFI['mort2.' + f].opt]), mort: ['mortYN', 'mortBal', 'mortPayM', 'mortYears', 'mortRate'].map(k => [FF[k].l, FF[k].type, !!FF[k].opt, FF[k].hint || '']), q: FF.mortYN.o })) };
  await L("loadSample();S.fin.home='Rent';S.src.home='typed';"); await page.click('[data-a=fchoice][data-p="mortYN|Yes"]'); out.liab.rent = await page.evaluate(() => ({ home: S.fin.home, note: [...document.querySelectorAll('#main p.small')].map(e => e.textContent.trim()).find(t => /You said/.test(t)) }));
  await page.fill('[data-it^="mort2|"][data-it$="|owed"]', '185000'); await page.fill('[data-it^="mort2|"][data-it$="|pay"]', '950'); await page.waitForTimeout(150); await phone('S24-liabilities.png');
  out.liab.states = await page.evaluate(() => { const o = {}; const run = (h) => { S.fin.home = h; S.src.home = 'typed'; delete S.fin.mortYN; lastId = null; render(); return { yn: mortYNval(), q: !!document.querySelector('[data-a=fchoice][data-p="mortYN|Yes"]'), main: !!document.getElementById('f-mortBal'), add: !!document.querySelector('[data-a=iadd][data-p=mort2]') }; }; ['Own outright', 'Own with mortgage', 'Rent', 'Live with family'].forEach(h => o[h] = run(h)); return o; });
  // --- What-if
  await tall(390, 1900); await page.evaluate(() => { loadSample(); S.tab = 'plan'; S.planSeg = 'main'; S.planGo = 'wi'; S.wi.m = 725; S.wi.g = S.goals[1].id; lastId = null; render(); }); await page.waitForTimeout(500);
  await page.evaluate(() => { const m = document.getElementById('main'), e = document.getElementById('r-wi'); m.scrollTop = e.offsetTop - 10; }); await page.waitForTimeout(300); await phone('S24-whatif.png');
  out.wi = await page.evaluate(() => { const o = { sections: [...document.querySelectorAll('#r-wi .wih')].map(e => e.textContent), sub: [...document.querySelectorAll('#r-wi .wisec > p.small')].map(e => e.textContent), labels: [...document.querySelectorAll('#r-wi .wisec .flabel')].map(e => e.textContent.replace(/\s+/g, ' ').trim()), put: 'Put it towards', once: [...document.querySelectorAll('#r-wi .small')].map(e => e.textContent.trim()).find(t => /^Once,/.test(t)), btns: [...document.querySelectorAll('#r-wi [data-a=wisave],#r-wi [data-a=wireset]')].map(e => e.textContent.trim()), lines: {} };
    [0, 40, 725, -25].forEach(m => { S.wi.m = m; liveUpdate(); const e = document.getElementById('wi-live'); const P = project(); o.lines[m] = { t: e.innerText.replace(/\s+/g, ' ').trim(), over: e.classList.contains('over'), base: Math.round(P.save.saveM), sp: Math.round(P.save.surplusM) }; }); o.head = document.getElementById('wi-extra-h').textContent; return o; });
  // --- Saving files (mocked downloads, real libraries served locally)
  const ctx2 = await browser.newContext({ viewport: { width: 390, height: 844 } }); const results = {};
  const MOCK = `window.__saves=[];window.claude={use:async(n)=>n==='downloads'?{save:async(o)=>{window.__saves.push({filename:o.filename,size:o.data.size,type:o.data.type})}}:null};window.__print=0;window.print=()=>{window.__print++};`;
  for (const mode of ['pdf', 'html', 'print']) { const p2 = await ctx2.newPage(); if (mode !== 'print') await p2.addInitScript(MOCK); else await p2.addInitScript('window.__print=0;window.print=()=>{window.__print++};');
    await p2.route('https://cdnjs.cloudflare.com/**', r => { if (mode === 'html') return r.abort(); const u = r.request().url(); r.fulfill({ status: 200, contentType: 'application/javascript', body: fs.readFileSync(/jspdf/.test(u) ? LIB + 'x-jspdf/package/dist/jspdf.umd.min.js' : LIB + 'x-html2canvas/package/dist/html2canvas.min.js') }); });
    await p2.goto(page.url()); await p2.waitForTimeout(400); await p2.evaluate(() => { loadSample(); S.tab = 'plan'; S.planSeg = 'main'; render(); openReport(); });
    const lab = await p2.textContent('[data-r=print]'); await p2.click('[data-r=print]'); if (mode === 'print') await p2.waitForTimeout(600); else await p2.waitForFunction(() => window.__saves.length > 0, null, { timeout: 120000 });
    results[mode] = await p2.evaluate(lab => ({ button: lab, saves: window.__saves || [], print: window.__print, msg: document.getElementById('rep-msg').textContent }), lab); await p2.close(); }
  out.save = results; out.save.consts = await page.evaluate(() => ({ jspdf: CDN_JSPDF, h2c: CDN_H2C, pdf: PDF, name: 'LifeMap-plan', bookedLabel: [dlPossible() ? 'Save meeting details (.txt)' : 'Add to my calendar'] }));
  const p3 = await ctx2.newPage(); await p3.addInitScript(MOCK); await p3.goto(page.url()); await p3.waitForTimeout(300); await p3.evaluate(() => { loadSample(); S.tab = 'exp'; S.exp = 'c4'; S.book.done = true; S.book.slot = SLOTS[1]; render(); });
  out.save.meeting = { withDl: await p3.textContent('[data-a=ics]'), file: (await (async () => { await p3.click('[data-a=ics]'); await p3.waitForTimeout(300); return p3.evaluate(() => window.__saves.map(s => s.filename)); })()) }; await p3.close();
  const p4 = await ctx2.newPage(); await p4.goto(page.url()); await p4.waitForTimeout(300); await p4.evaluate(() => { loadSample(); S.tab = 'exp'; S.exp = 'c4'; S.book.done = true; S.book.slot = SLOTS[1]; render(); }); out.save.meeting.local = await p4.textContent('[data-a=ics]'); await p4.close(); await ctx2.close();
  out.errors = errors; fs.writeFileSync(__dirname + '/s23.json', JSON.stringify(out, null, 1)); console.log('s23 done', errors); await browser.close(); })();
