// Independent check: drive the live prototype again, extract every visible label and number, and compare with the strings in the .docx.
const fs = require('fs'), path = require('path'), JSZip = require('jszip');
const { open } = require('./lib');
const { STMT_FOR, INFL_ONLY, ADJ, EDGES } = require('./states');
const extractAsm = require('./extract-asm');
const XL = require('./xl.json');
const extract = require('./extract');
const F = require('./fmt');
const { RX } = require('./tmpl');
const DOCX = process.env.DOCX || '/home/user/lifegoals-prototype/deliverables/LifeGoals-Calculators-UIUX-Spec.docx';
const norm = s => String(s == null ? '' : s).replace(/\s+/g, ' ').trim();
const ent = s => s.replace(/&lt;/g, '<').replace(/&gt;/g, '>').replace(/&quot;/g, '"').replace(/&apos;/g, "'").replace(/&#39;/g, "'").replace(/&amp;/g, '&');

// ---------- read the docx ----------
function parseDoc(xml) {
  const body = xml.slice(xml.indexOf('<w:body>'));
  const ptext = p => norm(ent([...p.matchAll(/<w:t(?: [^>]*)?>([^<]*)<\/w:t>|<w:tab\/>/g)].map(m => m[1] == null ? '\t' : m[1]).join('')));
  const blocks = []; const re = /<w:tbl>[\s\S]*?<\/w:tbl>|<w:p[ >][\s\S]*?<\/w:p>/g; let m;
  while ((m = re.exec(body))) { const s = m[0];
    if (s.startsWith('<w:tbl>')) blocks.push({ t: 'tbl', rows: [...s.matchAll(/<w:tr[ >][\s\S]*?<\/w:tr>/g)].map(r => [...r[0].matchAll(/<w:tc>[\s\S]*?<\/w:tc>/g)].map(c => norm([...c[0].matchAll(/<w:p[ >][\s\S]*?<\/w:p>/g)].map(p => ptext(p[0])).join(' ')))) });
    else { const st = (s.match(/<w:pStyle w:val="([^"]+)"/) || [])[1]; blocks.push({ t: 'p', style: st, text: ptext(s) }); } }
  const secs = []; let cur = null, h2 = null;
  for (const b of blocks) { if (b.t === 'p' && b.style === 'Heading1') { cur = { title: b.text, blocks: [] }; secs.push(cur); h2 = null; continue; }
    if (!cur) continue; if (b.t === 'p' && b.style === 'Heading2') h2 = b.text; b.h2 = h2; cur.blocks.push(b); }
  secs.forEach(s => { s.text = s.blocks.map(b => b.t === 'p' ? b.text : b.rows.map(r => r.join(' | ')).join(' || ')).join(' ## '); s.cells = new Set(s.blocks.filter(b => b.t === 'tbl').flatMap(b => b.rows.flat())); });
  return secs; }

// template → regex using the doc's own placeholder table
const TYPE_BY_NAME = { '€ amount': 'eur', 'Signed € amount': 'seur', 'Whole number': 'int', 'Number as entered': 'num', '1 decimal': 'd1', '2 decimals': 'd2', 'Percent': 'pct', 'Duration': 'yrs', 'Years': 'yrn', 'Weekly € amount': 'eurw' };
function compile(t, ph) { let i = 0; const esc = s => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  function seq(stop) { let out = ''; while (i < t.length) { const ch = t[i]; if (stop.includes(ch)) return out;
    if (ch === '«') { i++; const alts = [seq('|»')]; while (t[i] === '|') { i++; alts.push(seq('|»')); } if (t[i] !== '»') throw new Error('unclosed « in ' + t); i++; out += '(?:' + alts.join('|') + ')'; continue; }
    if (ch === '{') { const j = t.indexOf('}', i), name = t.slice(i + 1, j); if (!ph[name]) throw new Error('placeholder {' + name + '} not in the doc table: ' + t); out += '(' + RX[ph[name]] + ')'; i = j + 1; continue; }
    out += esc(ch); i++; } return out; }
  return new RegExp('^' + seq('').replace(/ +/g, ' +') + '$'); }

(async () => {
  const z = await JSZip.loadAsync(fs.readFileSync(DOCX)); const secs = parseDoc(await z.file('word/document.xml').async('string'));
  const { browser, page, errors } = await open(); const D = require('./drive')(page);
  const R = { pass: 0, fail: [], perCalc: [], expectedDefects: [] };
  const ok = (cond, what) => { if (cond) R.pass++; else R.fail.push(what); return cond; };
  const fmtNum = v => typeof v === 'number' ? String(+v.toFixed(4)) : String(v);
  const calcs = await page.evaluate(() => CALCS.map(c => ({ id: c.id, cat: c.cat, name: c.name, q: c.q, tip: c.tip || null, inputs: c.inputs.concat(c.wi || []) })));
  const shared = secs.filter(s => /^(Purpose|1\.|2\.|3\.|Appendix A)/.test(s.title)).map(s => s.text).join(' ## ');
  const boxOf = f => f.kind === 'chip' ? f.box : F.boxText(f.pre, f.box, f.suf);
  for (const [n, c] of calcs.entries()) { const N = 'C' + String(n + 1).padStart(2, '0'), sec = secs.find(s => s.title === N + ' ' + c.name), f0 = R.fail.length, p0 = R.pass, X = XL[N];
    if (!ok(sec, N + ': section missing')) continue;
    const tbls = h => sec.blocks.filter(b => b.t === 'tbl' && b.h2 === N + ' ' + h), has = s => sec.text.includes(norm(s));
    const states = [['default', 'fresh'], ['chosen', 'chosen']]; if (INFL_ONLY.includes(c.id)) states.push(['noInfl', 'chosenNoInfl']);
    if (ADJ.includes(c.id)) { states.push(['adjUnset', 'chosenNoInfl', 'adj']); states.push(['adjSet', 'chosen', 'adj']); }
    states.push(['plan', 'sample']); if (STMT_FOR[c.id]) states.push(['stmt', 'stmt:' + STMT_FOR[c.id]]);
    const COL = { default: 'Default (nothing chosen)', chosen: 'Choices made', noInfl: 'No inflation yet', adjUnset: 'Switch on, no rate', adjSet: 'Switch on, 2%', plan: 'Plan pre-fill', stmt: 'Statement' };
    const [partsT, rowsT, phT] = tbls('Result card'); const ph = {}; phT.rows.slice(1).forEach(r => { ph[r[0].replace(/[{}]/g, '')] = TYPE_BY_NAME[r[1]]; });
    const lblT = partsT.rows.filter(r => r[0] === 'Label (eyebrow)').map(r => r[1]), valT = partsT.rows.filter(r => r[0] === 'Headline value').map(r => r[1]), lineT = partsT.rows.filter(r => r[0] === 'Line').map(r => r[1]);
    const rowSpecs = rowsT.rows.slice(1).map(r => ({ l: r[0], v: r[1].split(' / ').map(v => v.replace(/ \([^()]*(?:\([^()]*\)[^()]*)*\)$/, '')) }));
    const mt = (list, s) => list.some(t => compile(t, ph).test(norm(s)));
    const checkResult = (r, tag) => { ok(mt(lblT, r.lbl), N + ' ' + tag + ': label "' + r.lbl + '" matches no template'); ok(mt(valT, r.val), N + ' ' + tag + ': value "' + r.val + '" matches no template'); ok(mt(lineT, r.line), N + ' ' + tag + ': line "' + r.line + '" matches no template');
      r.rows.forEach(([a, b]) => ok(rowSpecs.some(rs => compile(rs.l, ph).test(norm(a)) && rs.v.some(v => compile(v, ph).test(norm(b)))), N + ' ' + tag + ': row "' + a + ' = ' + b + '" matches no template')); };
    const inTs = tbls('Inputs'), inT1 = inTs.find(t => t.rows[0][1] === 'Unit shown'), inT2 = inTs.find(t => t.rows[0][1] === 'Typed above max'); const valsT = tbls('Screen values in the screenshots')[0]; const head = valsT.rows[0];
    const vcell = (label, col) => { const ci = head.indexOf(col); const row = valsT.rows.find(r => r[0] === label); return ci < 0 || !row ? undefined : row[ci]; };
    const lineBullets = sec.blocks.filter(b => b.t === 'p' && b.h2 === N + ' Screen values in the screenshots').map(b => b.text);
    const wbT = tbls('Workbook sheet "' + X.sheet + '"'); const outT = wbT.find(t => t.rows[0][0] === 'Workbook output name');
    ok(wbT.length && sec.text.includes('sheet "' + X.sheet + '"'), N + ': workbook sheet pointer "' + X.sheet + '"');
    const choiceT = sec.blocks.find(b => b.t === 'tbl' && b.h2 === N + ' Inputs' && b.rows[0][0] === 'Label' && b.rows[0][2] === 'Guidance under the input'), asmT = sec.blocks.find(b => b.t === 'tbl' && b.rows[0][0] === 'Plan-wide input (Your assumptions)');
    for (const [key, b, act] of states) { await D.base(b); await D.calc(c.id, /^chosen/.test(b)); if (act === 'adj') await page.click('[data-a="adjinfl"]');
      const d = await page.evaluate(extract), col = COL[key], nm = (await D.num(c.id)).num || {}; const R0 = d.result || { lbl: d.gate.eyebrow, val: d.gate.b, line: d.gate.also || '', rows: [] };
      if (key === 'plan' && head.indexOf(col) < 0) { await D.base('chosen'); await D.calc(c.id, true); const d0 = await page.evaluate(extract); ok(d.fields.every((f, i) => f.box === d0.fields[i].box), N + ' plan: inputs differ but no plan screenshot'); continue; }
      ok(head.indexOf(col) >= 0, N + ' ' + key + ': no column "' + col + '"');
      // workbook alignment: every output name the screen computes is a defined name in the sheet
      const xn = new Set([...X.results, ...X.plan, ...X.inputs].map(r => r.name)); Object.keys(nm).forEach(k => ok(xn.has(k), N + ' ' + key + ': output ' + k + ' not a workbook name'));
      if (key === 'chosen' || key === 'noInfl') { const ci = key === 'chosen' ? 2 : 3; outT.rows.slice(1).forEach(r => ok(r[ci] === fmtNum(nm[r[0]]), N + ' ' + key + ': workbook value ' + r[0] + ' doc "' + r[ci] + '" vs live "' + fmtNum(nm[r[0]]) + '"')); ok(outT.rows.length - 1 === X.results.concat(X.plan).filter(r => r.name in nm).length, N + ': workbook output table complete'); }
      if (key === 'default') { if (d.gate) ok(has(d.gate.b) && sec.text.includes(d.gate.b + (d.gate.also ? ' · ' + d.gate.also : '')), N + ': gate text "' + d.gate.b + '"'); else ok(has('No gate: the result shows straight away'), N + ': no-gate note');
        for (const f of d.fields.filter(f => f.guide || f.look)) { const r = choiceT && choiceT.rows.find(x => x[0] === f.label); ok(r && r[2] === (f.guide || '—') && r[3] === (f.stdChip || '—'), N + ': choice row "' + f.label + '"'); }
        if (d.calcAsm) { ok(sec.text.includes(d.calcAsm.summary) && sec.text.includes(d.calcAsm.note), N + ': assumptions card summary/note'); d.calcAsm.fields.forEach(f => { const r = asmT && asmT.rows.find(x => x[0] === f.label); ok(r && r[1] === (f.guide || '—') && r[2] === (f.std || '—'), N + ': tool assumption "' + f.label + '"'); }); }
        for (const f of d.fields) { const r1 = inT1.rows.find(r => r[0].replace(/^\[What if\] /, '') === f.label); const exp = f.look && !f.box ? 'blank · ' + f.look : boxOf(f); ok(r1 && r1[3].replace(/ ⚠$/, '') === exp, N + ' ' + f.label + ': on-screen default "' + (r1 && r1[3]) + '" vs "' + exp + '"'); }
        ok(has(d.title), N + ': title "' + d.title + '"'); ok(norm(d.sub) === norm(c.q) && has(c.q), N + ': question'); if (d.tip) ok(has(d.tip), N + ': tip "' + d.tip + '"'); else ok(!c.tip, N + ': tip missing');
        ok(has(d.eyebrow), N + ': eyebrow'); ok(shared.includes(d.back), N + ': back'); ok(has(d.disc), N + ': disclaimer'); d.buttons.forEach(bt => ok(has(bt.t) || shared.includes(bt.t), N + ': button "' + bt.t + '"'));
        if (d.whatIfTitle) ok(shared.includes(d.whatIfTitle), N + ': what-if title'); if (d.adj) { ok(shared.includes(d.adj.text) && shared.includes(d.adj.help), N + ': switch strings'); ok(d.adj.role === 'switch' && d.adj.checked === 'false', N + ': switch default off'); }
        if (d.infl) { ok(shared.includes(d.infl.title) && shared.includes(d.infl.help), N + ': inflation title/help'); d.infl.chips.forEach(ch => ok(shared.includes(ch.t) && ch.pressed === 'false', N + ': chip "' + ch.t + '" (unpressed)')); }
        }
      if (key === 'chosen') { for (const f of d.fields) { const i = c.inputs.find(x => x.k === f.k), r1 = inT1.rows.find(r => r[0].replace(/^\[What if\] /, '') === f.label), r2 = inT2.rows.find(r => r[0] === f.label);
          if (!ok(r1 && r2, N + ': input "' + f.label + '" not in inputs tables')) continue;
          ok(f.labelledby === f.lid, N + ' ' + f.label + ': control not labelled by its label');
          if (f.kind === 'chip') { ok(r1[1] === 'Chips: ' + f.chips.map(x => '"' + x.t + '"').join(' / ') && r1[1] === F.unitDisplay(i.u), N + ' ' + f.label + ': chips ' + r1[1]); ok(r1[2] === F.chipLabel(i.u, i.v), N + ' ' + f.label + ': CALCS default chip');  ok(f.role === 'group', N + ' ' + f.label + ': chip group role'); ok(r1[4] === '—' && r1[7] === 'tap (chips)' && r2[1] === 'Not possible (chips)', N + ' ' + f.label + ': chip limits'); continue; }
          ok(r1[1] === F.unitDisplay(i.u) && F.PARTS[i.u][0] === f.pre && F.PARTS[i.u][1] === f.suf, N + ' ' + f.label + ': unit ' + r1[1] + ' vs DOM "' + f.pre + '"/"' + f.suf + '"');
          ok(r1[2] === F.boxText(F.PARTS[i.u][0], F.nbFmt(i.v), F.PARTS[i.u][1]), N + ' ' + f.label + ': CALCS default');
          ok(f.valuetext && f.valuetext.length > 0, N + ' ' + f.label + ': slider aria-valuetext');
          ok(r1[4] === F.nbFmt(+f.min) && r1[5] === F.nbFmt(+f.max) && r1[6] === F.nbFmt(+f.step), N + ' ' + f.label + ': min/max/step ' + r1.slice(4, 7) + ' vs ' + [f.min, f.max, f.step]);
          ok(r1[7] === f.inputmode, N + ' ' + f.label + ': keyboard'); } }
      for (const f of d.fields) { const exp = (f.look && !f.box ? 'blank · ' + f.look : boxOf(f)) + (f.tag ? ' ★' : ''); ok(vcell(f.label, col) === exp, N + ' ' + key + ': "' + f.label + '" doc "' + vcell(f.label, col) + '" vs screen "' + exp + '"'); if (f.tag) ok(f.tag === 'From your statement' && shared.includes(f.tag), N + ': tag'); }
      ok(vcell('Result label', col) === R0.lbl, N + ' ' + key + ': result label'); ok(vcell('Headline value', col) === R0.val, N + ' ' + key + ': headline "' + R0.val + '"');
      R0.rows.forEach(([a, bb]) => ok(vcell('Row: ' + a, col) === bb, N + ' ' + key + ': row "' + a + '" doc "' + vcell('Row: ' + a, col) + '" vs "' + bb + '"'));
      ok(vcell('Inflation line', col) === (d.inflNote || '—'), N + ' ' + key + ': inflation line');
      ok(lineBullets.includes(col + ': ' + (R0.line || '(none)')), N + ' ' + key + ': verbatim line missing: ' + R0.line);
      if (d.result) checkResult(d.result, key); }
    for (const e of EDGES[c.id] || []) { const eb = e.base || 'chosen'; await D.base(eb); await D.calc(c.id, eb === 'chosen'); for (const [k, v] of Object.entries(e.set)) await D.set(k, v); const d = await page.evaluate(extract);
      const ets = sec.blocks.filter(b => b.t === 'tbl' && b.rows.some(r => r[0] === 'Line' && r[1] === d.result.line) && b.rows.some(r => r[0] === 'Headline value' && r[1] === d.result.val));
      ok(ets.some(et => d.result.rows.every(([a, bb]) => et.rows.some(r => r[0] === 'Row: ' + a && r[1] === bb)) && et.rows.some(r => r[0] === 'Label' && r[1] === d.result.lbl)), N + ' edge "' + e.t + '": result not in doc ' + JSON.stringify(d.result));
      checkResult(d.result, 'edge "' + e.t + '"'); }
    for (const i of c.inputs) { const r2 = inT2.rows.find(r => r[0] === i.l);
      if (F.CHIPS[i.u]) { for (const [v, l] of F.CHIPS[i.u]) { await D.base('chosen'); await D.calc(c.id, true); await D.set(i.k, v); const pr = await page.evaluate(([k, v]) => { const b = document.querySelector('[data-a="ckset"][data-p="' + k + '|' + v + '"]'); return [b.getAttribute('aria-pressed'), b.textContent.trim()]; }, [i.k, v]); ok(pr[0] === 'true' && pr[1] === l, N + ' ' + i.l + ': chip "' + l + '" selects'); const d = await page.evaluate(extract); checkResult(d.result, 'chip ' + l); } continue; }
      if (['y', 'm', 'age'].includes(i.u) && i.step % 1 === 0) { await D.base('chosen'); await D.calc(c.id, true); const dv = Math.min(i.max, i.min + 1) - 0.5; await D.set(i.k, dv); const hv = await page.evaluate(k => [document.getElementById('nh-ck-' + k).textContent, document.getElementById('co-' + k).value], i.k); ok(hv[0] === 'Whole numbers only' && hv[1] === String(Math.round(dv)) && r2[1].includes('hint "Whole numbers only"'), N + ' ' + i.l + ': whole numbers only (' + hv + ')'); }
      for (const [dir, v] of [['max', i.u === '€' ? i.max * 10 + 1000 : i.max + 1], ['min', i.min - 1]]) { await D.base('chosen'); await D.calc(c.id, true); await D.set(i.k, v);
        const hv = await page.evaluate(k => [document.getElementById('nh-ck-' + k).textContent, document.getElementById('co-' + k).value], i.k), cellTxt = dir === 'max' ? r2[1] : r2[2];
        ok(hv[0] !== '' && cellTxt.includes('hint "' + hv[0] + '"'), N + ' ' + i.l + ' ' + dir + ' hint "' + hv[0] + '" not in "' + cellTxt + '"');
        ok(hv[1] === F.nbFmt(dir === 'max' ? (i.u === '€' ? i.max * 10 : i.max) : i.min), N + ' ' + i.l + ' ' + dir + ' clamp ' + hv[1]); checkResult((await page.evaluate(extract)).result, i.l + ' ' + dir); }
      if (i.u === '€') { await D.base('chosen'); await D.calc(c.id, true); const w = Math.round(i.max * 1.5); await D.set(i.k, w); const hv = await page.evaluate(k => [document.getElementById('nh-ck-' + k).textContent, document.getElementById('c-' + k).max], i.k); ok(hv[0] === '' && +hv[1] === w, N + ' ' + i.l + ': € widen'); } }
    R.perCalc.push([N, c.name, R.pass - p0, R.fail.length - f0]); console.log(N, R.pass - p0, 'passed', R.fail.length - f0, 'failed'); }
  // ---------- Inflation chips, rules, Your assumptions ----------
  const s1 = secs.find(s => s.title === '1. Design system').text, s3 = secs.find(s => s.title === '3. Rules and Your assumptions'), p1 = R.pass, f1 = R.fail.length;
  await D.base('chosenNoInfl'); await D.calc('compound', true); const iu = await page.evaluate(() => { const ic = document.querySelector('.infl'), t = e => e.textContent.replace(/\s+/g, ' ').trim(); return { title: t(ic.querySelector('b')), tag: t(ic.querySelector('.tag')), help: t(ic.querySelector('p.small')), chips: [...ic.querySelectorAll('.chip')].map(c => [t(c), c.getAttribute('aria-pressed'), c.dataset.p]) }; });
  ok(s1.includes(iu.title) && s1.includes(iu.help) && iu.tag === 'Not chosen yet', 'Inflation chips: title, tag, help'); iu.chips.forEach(ch => ok(s1.includes(ch[0]) && ch[1] === 'false', 'Inflation state 1: "' + ch[0] + '" unpressed'));
  ok(/3\.9% a year right now \(CSO HICP flash, Sep 2026\)/.test(iu.help) && iu.chips[1][0] === '3.9% · Ireland now (CSO HICP flash, Sep 2026)' && iu.chips[0][0] === 'Use the standard (2%)', 'Inflation: one "Ireland today" figure 3.9% (CSO HICP flash, Sep 2026); standard chip');
  await page.click('[data-a="infl"][data-p="' + iu.chips[0][2] + '"]'); const col = await page.evaluate(() => ({ card: !!document.querySelector('.infl'), note: (([...document.querySelectorAll('#main p.small')].find(p => /Prices rising/.test(p.textContent)) || {}).textContent || '').replace(/\s+/g, ' ').trim() }));
  ok(!col.card && s1.includes(col.note), 'Inflation state 2: card closes, line "' + col.note + '"');
  await page.click('[data-a="infledit"]'); ok(await page.evaluate(() => document.querySelector('[data-a="infl"]').getAttribute('aria-pressed') === 'true' && document.querySelector('.infl .tag').textContent === 'Your choice'), 'Inflation state 2: chosen chip pressed, tag "Your choice"');
  await page.click('[data-a="infl"][data-p="other"]'); const oth = await page.evaluate(() => ({ card: !!document.querySelector('.infl'), l: (document.querySelector('.infl .flabel span') || {}).textContent, p: (document.querySelector('[data-a="infl"][data-p="other"]') || {}).getAttribute && document.querySelector('[data-a="infl"][data-p="other"]').getAttribute('aria-pressed') }));
  ok(oth.card && oth.p === 'true' && s1.includes(oth.l), 'Inflation state 3: Other keeps the card open with "' + oth.l + '"');
  const rv = await page.evaluate(() => RULES_VERSION); ok(rv === 'Irish rules 2026 · checked 2 Oct 2026' && s3.text.includes(rv) && s3.text.includes('Budget 2027') && s3.text.includes('6 October 2026'), 'Rules version note');
  const rules = await page.evaluate(() => { const out = []; const walk = (o, p) => Object.entries(o).forEach(([k, x]) => { if (x && typeof x === 'object' && 'v' in x && 'src' in x) out.push([p + k, x.eff]); else walk(x, p + k + '.'); }); walk(RULES_IE_2026, ''); return out; });
  const regT = s3.blocks.find(b => b.t === 'tbl' && b.rows[0][0] === 'Key'); rules.forEach(([k, eff]) => ok(regT.rows.some(r => r[0] === k && r[2] === eff), 'Register row ' + k));
  const T = s3.blocks.filter(b => b.t === 'tbl' && b.rows[0][0] === 'Code').flatMap(b => b.rows), tyOf = await page.evaluate(() => Object.fromEntries(Object.entries(ASM).map(([k, d]) => [k, d.mk ? '2 · Market rate (suggested)' : d.ty === 2 ? '2b · Official range' : d.own ? '3 · Required choice' : '3 · LifeMap standard'])));
  for (const [g] of await page.evaluate(() => ASM_GRP)) { await page.evaluate(g => { S = fresh(); S.shell = true; S.tab = 'me'; S.me = 'asm'; S.asmOpen = g; lastId = null; render(); }, g);
    const A = await page.evaluate(extractAsm), G = A.groups[0]; ok(s3.text.includes(G.title), 'Assumptions group "' + G.title + '"');
    if (A.top) ok(s3.text.includes(A.top.p), 'Assumptions top card');
    for (const f of G.fields) { const r = T.find(x => x[1] === f.label); if (!ok(r, 'Assumptions: "' + f.label + '" not in doc')) continue;
      ok(r[6].startsWith((f.guide || '—') + ' · Tag at the start: ' + (f.tag || 'none') + ' · ' + (f.std ? 'Chip "' + f.std + '"' : 'No chip')), 'Assumptions ' + f.k + ': guidance, tag and chip');
      ok(['Not chosen yet', 'Optional', 'Set by LifeMap', 'Assumed: add yours', null].includes(f.tag), 'Assumptions ' + f.k + ': tag at the start is one of the §27 tags ("' + f.tag + '")'); if (f.box && (['retireAge', 'planEnd', 'pRetireAge'].includes(f.k))) ok(f.box.val === '', 'Assumptions ' + f.k + ': required choice starts empty'); if (f.tag === 'Set by LifeMap') ok(!!f.box || f.chips.length > 0, 'Assumptions ' + f.k + ': a standard shows its value');
      if (tyOf[f.k]) ok(r[2] === tyOf[f.k], 'Assumptions ' + f.k + ': type ' + r[2]);
      if (f.chips.length) ok(r[3] === 'Chips' && r[4] === f.chips.map(x => '"' + x.t + '"').join(' / ') && (f.tag === 'Set by LifeMap' ? f.chips.filter(x => x.pressed === 'true').length === 1 : f.chips.every(x => x.pressed === 'false')), 'Assumptions ' + f.k + ': chips (the standard is pressed when Set by LifeMap, none otherwise)'); } }
  await page.evaluate(() => { S = fresh(); S.shell = true; S.tab = 'me'; S.me = 'asm'; S.asmOpen = 'law'; lastId = null; render(); }); const LW = (await page.evaluate(extractAsm)).groups[0].law, lawT = s3.blocks.find(b => b.t === 'tbl' && b.rows[0][0] === 'Row' && b.rows[0][1] === 'Value shown (verbatim)');
  LW.rows.forEach(([a, b]) => ok(lawT && lawT.rows.some(r => r[0] === a && r[1] === b), 'Set by Government row "' + a + '"')); ok(s3.text.includes(LW.note), 'Set by Government note');
  await page.evaluate(() => { S = fresh(); S.shell = true; S.tab = 'me'; S.me = 'asm'; S.asmOpen = 'prices'; lastId = null; render(); });
  const ua = await page.evaluate(() => ({ btn: !!document.querySelector('[data-a="useall"]'), retire: S.retireSet, planEnd: asmMine('planEnd'), infl: S.infl, left: planMissing().map(m => m.k), set: document.querySelectorAll('.asmf .tag').length }));
  ok(!ua.btn && ua.retire === false && ua.planEnd === false && ua.infl == null && ua.left.length >= 3 && /There is no "Use the standard for all of these" button any more/.test(s3.text), 'No "Use the standard for all" button; standards are applied from the start; the required choices are still open (' + JSON.stringify(ua) + ')');
  await page.evaluate(() => { loadSample(); S.asm = {}; S.infl = null; S.retireSet = false; S.app = false; S.shell = true; S.pb = true; S.tab = 'plan'; S.scr = 'P4'; lastId = null; render(); });
  const st7 = await page.evaluate(() => ({ h: document.querySelector('#p4-asm h3').textContent, p: document.querySelector('#p4-asm h3 + p').textContent, need: (document.getElementById('p4-need') || {}).textContent, dis: document.getElementById('seeres').disabled }));
  ok(s3.text.includes(st7.h) && s3.text.includes(st7.p) && s3.text.includes(st7.need) && st7.dis, 'Step 7 "Choose N things" card (§22, §27)');
  await page.evaluate(() => { loadSample(); S.sheet = 'assume'; render(); }); const AR = await page.evaluate(() => { const t = e => e ? e.textContent.replace(/\s+/g, ' ').trim() : ''; return [...document.querySelectorAll('.sheet .mini')].map(m => { const sp = m.querySelector('span'), tg = sp && sp.querySelector('.tag'), c = sp ? sp.cloneNode(true) : null; if (c) [...c.querySelectorAll('.tag')].forEach(x => x.remove()); return [t(c), tg ? t(tg) : '', t(m.querySelector('b'))]; }); });
  const asT = s3.blocks.find(b => b.t === 'tbl' && b.rows[0][0] === 'Row' && b.rows[0][1] === 'Tag (type)'); AR.forEach(r => ok(asT && asT.rows.some(x => x[0] === r[0] && x[1] === r[1] && x[2] === r[2]), 'What your plan assumes: "' + r[0] + '"'));
  ok(AR.some(r => r[1] === 'Set by Government · 2026') && AR.some(r => /^Usually /.test(r[1])) && AR.some(r => r[1] === 'Set by LifeMap'), 'What your plan assumes: type tags incl. Set by LifeMap');
  R.perCalc.push(['Components', 'Inflation chips, rules register, Your assumptions', R.pass - p1, R.fail.length - f1]);
  // ---------- Explore structure, statement cards, sheets ----------
  const s2 = secs.find(s => s.title === '2. Explore structure').text, p0 = R.pass, f0 = R.fail.length;
  const x = await page.evaluate(() => ({ cats: CATS.map(c => ({ name: c.name, blurb: c.blurb, n: CALCS.filter(x => x.cat === c.id).length })), topics: TOPICS, tt: TOPIC_TOOLS, doct: Object.keys(DOCT) }));
  await D.base('fresh'); const xp = await page.evaluate(() => document.getElementById('main').innerText);
  x.cats.forEach(c => ok(s2.includes(c.name) && s2.includes(c.blurb) && s2.includes(c.n + ' tools') && xp.includes(c.n + ' tools'), 'Explore group ' + c.name));
  for (const t of x.topics) { ok(s2.includes(t[1]) && s2.includes(t[2]) && xp.includes(t[2]), 'Topic ' + t[1]); await D.base('fresh'); await page.evaluate(p => ACT.topic(p), t[1]); const tx = await page.evaluate(() => [...document.querySelectorAll('#main .link')].map(l => l.textContent.trim()));
    tx.filter(l => !/Remind me/.test(l)).forEach(l => ok(s2.includes(norm(l)), 'Topic ' + t[1] + ' link "' + l + '"')); ok(s2.includes(x.tt[t[1]].map(id => { const i = calcs.findIndex(c => c.id === id); return 'C' + String(i + 1).padStart(2, '0') + ' ' + calcs[i].name; }).join('; ')), 'Topic ' + t[1] + ' calculators'); }
  for (const k of x.doct) { await D.base('fresh'); await page.evaluate(k => ACT.cat(k), k); const card = await page.evaluate(() => [...document.querySelectorAll('.card.pst b, .card.pst p, .card.pst label, .card.pst button')].map(e => e.textContent.replace(/\s+/g, ' ').trim()));
    card.forEach(t => ok(s2.includes(norm(t)) || s2.includes(norm(t.replace(/^We can read: /, '').replace(/\.$/, ''))), 'Statement card ' + k + ': "' + t + '"'));
    await D.base('sample'); await page.evaluate(k => { const T = DOCT[k]; S.pst = { cat: k, stage: 'confirm', files: [T.title + ' · ' + T.date + '.pdf'], edit: {} }; S.xs.push({ v: 'PST' }); lastId = null; render(); }, k);
    const rows = await page.evaluate(() => [...document.querySelectorAll('#main .mini')].map(m => ({ l: (m.querySelector('b') || {}).textContent, tag: (m.querySelector('.tag') || {}).textContent || '', v: (m.querySelector('input') || {}).value })));
    rows.filter(r => r.l && r.v != null).forEach(r => ok(s2.includes(r.l) && s2.includes(r.tag) && s2.includes('| ' + r.v + ' |'), 'Confirm ' + k + ': "' + r.l + '" ' + r.tag + ' ' + r.v)); }
  for (const [id, b] of [['borrow','chosen'], ['compound','chosenNoInfl'], ['compound','chosen'], ['overpay','chosen'], ['emergency','chosen'], ['retirement','chosen'], ['contrib','chosen'], ['lifecover','chosen'], ['incomegap','chosen'], ['ratechange','chosen'], ['debtpay','chosen']]) {
    await D.base(b); await D.calc(id, true); await page.click('[data-a="calcadd"]'); const t = await page.evaluate(() => [...document.querySelectorAll('.sheet .eyebrow, .sheet h2, .sheet p.sub, .sheet .btn')].map(e => e.textContent.replace(/\s+/g, ' ').trim()));
    ok(s2.includes(t.join(' | ')), 'Add sheet ' + id + ' (' + b + '): "' + t.join(' | ') + '"'); }
  R.perCalc.push(['Explore', 'Explore structure, statement cards, Add to my plan sheets', R.pass - p0, R.fail.length - f0]);
  // ---------- §15 Your finances and §16 LifeMap (independent: re-driven live, compared with the docx) ----------
  { const s4 = secs.find(s => s.title === '4. Your finances: "Not sure? See an example"'), s5 = secs.find(s => s.title === '5. LifeMap name and cover'), p4 = R.pass, f4 = R.fail.length;
    if (ok(s4 && s5, 'sections 4 and 5 present')) {
    const cardT = s4.blocks.filter(b => b.t === 'tbl' && b.rows[0][0] === 'Card title').flatMap(b => b.rows.slice(1));
    const keys = await page.evaluate(() => Object.keys(EXAMPLES)); let reach = 0; const SECNL = ['About you', 'Income and expenses', 'Assets', 'Liabilities', 'Protection', 'Pension'];
    for (const k of keys) { await page.evaluate(k => { loadSample(); const lk = k.split('.')[0]; if (k === 'ae') { delete S.fin.pensionM; delete S.src.pensionM; delete S.fin.pensionOwnM; delete S.src.pensionOwnM; delete S.lists.pens; S.dv = {}; } if (lk === 'mort2' && !LI('mort2').length) { S.lt = S.lt || {}; S.lt.mort2 = true; LI('mort2').push(newItem('mort2')); } if (FFI[k] && LDEF[lk].pol) { S.fin[lk] = 'Yes'; S.src[lk] = 'typed'; } lastId = null; render(); openSec(FF[k] ? FSEC.findIndex(s => s.f.includes(k)) : FSEC.findIndex(s => s.id === LDEF[lk].sec)); }, k);
      const before = await page.evaluate(() => JSON.stringify([S.fin, S.src, S.lists])); const link = page.locator('[data-a="fex"][data-p="' + k + '"]');
      if (await link.count() === 0) { ok(!/^[a-z]+\./.test(k) && ['cardBal', 'cardPayM', 'loanBal', 'loanPayM', 'pension', 'pensionM', 'pensionOwnM'].includes(k), 'card ' + k + ': no link, so it must be one of the 7 single-total cards replaced by list items'); continue; }
      reach++; if (!ok(await link.count() === 1 && norm(await link.textContent()) === 'Not sure? See an example', 'card ' + k + ': link')) continue; await link.click();
      const c = await page.evaluate(k => { const sh = document.querySelector('.sheet'), t = e => e ? e.textContent.replace(/\s+/g, ' ').trim() : null, ps = [...sh.querySelectorAll(':scope > p')], lk = k.split('.')[0], sec = FF[k] ? FSEC.findIndex(s => s.f.includes(k)) : FSEC.findIndex(s => s.id === LDEF[lk].sec);
        return { shown: FFI[k] ? LDEF[lk].one.replace(/^./, x => x.toUpperCase()) + ' item' : ['About you', 'Income and expenses', 'Assets', 'Liabilities', 'Protection', 'Pension'][sec], title: t(sh.querySelector('#ex-t')), opts: [...sh.querySelectorAll('ul li')].map(li => t(li).replace(/: /, ': ')).join(' · ') || '—', sentence: t(sh.querySelector('#ex-s')), where: t(ps.find(p => /Where to find yours/.test(p.textContent))).replace(/^📍 Where to find yours: /, ''), zero: ps.some(p => /Nothing to add\? Enter 0\./.test(p.textContent)) ? 'Yes' : '—', small: t(ps.find(p => /Example only/.test(p.textContent))), btn: t(sh.querySelector('.btn')), role: sh.getAttribute('role'), lb: sh.getAttribute('aria-labelledby'), db: sh.getAttribute('aria-describedby') }; }, k);
      const r = cardT.find(x => x[0] === c.title && x[1] === c.shown);
      ok(r && r[2] === c.opts && r[3] === c.sentence && r[4] === c.where && r[5] === c.zero, 'card ' + k + ': doc row ' + JSON.stringify(r) + ' vs live ' + JSON.stringify([c.title, c.shown, c.opts, c.sentence, c.where, c.zero]));
      ok(s4.text.includes(c.small) && s4.text.includes('"' + c.btn + '"') && c.role === 'dialog' && c.lb === 'ex-t' && c.db === 'ex-s', 'card ' + k + ': small print, button, dialog semantics');
      await page.keyboard.press('Escape'); const after = await page.evaluate(() => JSON.stringify([S.fin, S.src, S.lists, !!document.querySelector('.sheet'), document.activeElement.dataset.p]));
      ok(after === JSON.stringify(JSON.parse(before).concat([false, k])), 'card ' + k + ': Escape closes, focus back on the link, field unchanged'); }
    ok(cardT.length === reach && reach === keys.length - 7, 'card table has ' + cardT.length + ' rows for ' + reach + ' reachable cards of ' + keys.length);
    const tg = await page.evaluate(() => { const r = []; const t = h => { const d = document.createElement('div'); d.innerHTML = h; return d.textContent; }; S.src.zz = 'doc'; S.conf.zz = 95; r.push(t(tagFor('zz'))); S.fix.zz = 1; r.push(t(tagFor('zz'))); delete S.fix.zz; S.src.zz = 'typed'; r.push(t(tagFor('zz'))); S.src.zz = 'pre'; r.push(t(tagFor('zz'))); delete S.src.zz; r.push(t(tagFor('zz'))); S.look.zz = 'x'; r.push(t(tagFor('zz'))); delete S.look.zz; return r; });
    const stT = s4.blocks.find(b => b.t === 'tbl' && b.rows[0][0] === 'Tag (verbatim)'); tg.forEach(x => ok(stT && stT.rows.some(r => r[0] === x), 'status tag "' + x + '"'));
    ok(!/≈ Estimated|Confirmed none/.test(await page.evaluate(() => document.documentElement.innerHTML.replace(/<script[\s\S]*?<\/script>/g, ''))), 'no removed statuses on screen');
    await page.evaluate(() => { loadSample(); delete S.fin.mortPayM; delete S.src.mortPayM; delete S.fin.ip; delete S.src.ip; S.look.homeValue = 'This looks high for the area'; S.app = false; S.pb = true; S.tab = 'plan'; S.scr = 'P4'; S.checked = false; lastId = null; render(); });
    const ck = await page.evaluate(() => [...document.querySelectorAll('#main .ck')].map(c => { const t = e => e ? e.textContent.replace(/\s+/g, ' ').trim() : null; return [t(c.querySelector('.i')), t(c.querySelector('b')), t(c.querySelector(':scope > div > div.small'))]; }));
    const ckT = s4.blocks.find(b => b.t === 'tbl' && b.rows[0][0] === 'Icon'); ck.forEach(r => ok(ckT && ckT.rows.some(x => x[0] === r[0] && x[1] === r[1] && x[3] === r[2]), 'checklist row "' + r[1] + '"'));
    ok(ck.every(r => ['⚠️', '❓'].includes(r[0])), 'checklist only ⚠️ / ❓');
    for (const id of ['repayment', 'overpay', 'ratechange', 'term', 'mortgageprotect']) { await page.evaluate(id => { loadSample(); delete S.fin.mortYears; delete S.src.mortYears; delete S.conf.mortYears; S.tab = 'explore'; S.xs = []; lastId = null; render(); ACT.calc(id); }, id); const g = await page.evaluate(() => ({ b: document.querySelector('#cgate b').textContent, f: (document.querySelector('.field .tag.look') || {}).textContent }));
      const N = 'C' + String(calcs.findIndex(c => c.id === id) + 1).padStart(2, '0'), sec = secs.find(s => s.title.startsWith(N + ' '));
      ok(/^Add .+ to see this$/.test(g.b) && s4.text.includes(g.b) && sec.text.includes(g.b), N + ': missing years gate "' + g.b + '" in 4.7 and the calculator section'); }
    for (const [id, del] of [['surplus', ['mortPayM', 'cardPayM']], ['debtpay', ['cardPayM']]]) { await page.evaluate(([id, del]) => { loadSample(); del.forEach(k => { delete S.fin[k]; delete S.src[k]; delete S.conf[k]; }); S.tab = 'explore'; S.xs = []; lastId = null; render(); ACT.calc(id); }, [id, del]);
      const w = await page.evaluate(() => [...document.querySelectorAll('#main .field')].filter(f => f.querySelector('.tag.pre')).map(f => [f.querySelector('.tag.pre').textContent, [...f.querySelectorAll(':scope > span.small')].map(x => x.textContent).join(' ')]));
      const N = 'C' + String(calcs.findIndex(c => c.id === id) + 1).padStart(2, '0'), sec = secs.find(s => s.title.startsWith(N + ' '));
      ok(w.length > 0, N + ': worked-out tag shown'); w.forEach(([tag, line]) => ok(tag === 'Worked out from your figures' && s4.text.includes(norm(line)) && sec.text.includes(norm(line)), N + ': worked-out line "' + line + '"')); }
    // §16
    await page.evaluate(() => { S = fresh(); lastId = null; render(); });
    const cv = await page.evaluate(() => ({ els: [...document.querySelectorAll('.cover .brand, .cover-inv, .cover h2, .cover-line, .cover .wbtn, .cover-under, .cover .link')].map(e => e.textContent.trim()), all: document.querySelector('.cover').innerText.replace(/\s+/g, ' ').trim(), title: document.title }));
    const cvT = s5.blocks.find(b => b.t === 'tbl' && b.rows[0][0] === 'Part');
    cv.els.forEach(t => ok(cvT && cvT.rows.some(r => r[1] === t || r[1].startsWith(t + ' (') || r[1].startsWith('"' + t + '"')), 'cover text "' + t + '" in 5.1'));
    ok(cv.all === cv.els.join(' '), 'cover shows only the agreed copy'); ok(!/Guidance, not advice|Free · About a minute/.test(cv.all), 'no trust line or disclaimer on the cover');
    ok(secs.find(s => s.title === 'Appendix A. Copy deck').text.includes(cv.els.join(' · ')), 'cover strings in Appendix A');
    await page.evaluate(() => { S = fresh(); S.scr = 'D5'; S.di = 3; lastId = null; render(); }); const q8 = await page.evaluate(() => [document.querySelector('#screen h2').textContent, document.querySelector('.qsub').textContent].concat([...document.querySelectorAll('.opt')].map(e => e.querySelector('.em').textContent + ' ' + e.querySelector('.tx').textContent + ' (' + e.querySelector('.otag').textContent.replace(/^◆ /, '') + ')')));
    q8.forEach(t => ok(s5.text.includes(t), 'Q8 "' + t + '"'));
    await page.evaluate(() => { S = fresh(); S.shell = true; S.pb = true; S.tab = 'plan'; S.scr = 'F1'; lastId = null; render(); }); const tile = await page.evaluate(() => document.querySelector('.gtile[data-p="safety"] .nm').textContent); ok(tile === 'Emergency fund' && s5.text.includes('🪂 ' + tile), 'goal tile "' + tile + '"');
    await page.evaluate(() => { S = fresh(); S.scr = 'D1'; lastId = null; render(); }); const d1 = await page.evaluate(() => document.querySelector('#screen h2').textContent); ok(s5.text.includes(d1), 'D1 title "' + d1 + '"');
    const all = secs.map(s => s.title + ' ' + s.text).join(' '), stray = (all.match(/LifeGoals(?!-Customer-Journey-Prototype\.html|-Calculators\.xlsx|-Calculators-UIUX-Spec)[^ ]{0,20}/g) || []).filter(x => !/^LifeGoals" for now/.test(x));
    ok(stray.length === 0, 'no customer-facing "LifeGoals" in the docx: ' + stray.slice(0, 5).join(', '));
    ok(!/Start · about 1 min|Your life\. Your plan\.|Pick a forecast|Build a safety net"? ?\(C|≈ Estimated ·/.test(all), 'no old wording in the docx'); }
    // ---------- §17 (Explore order, emoji, Ask) and §18 (partner rates) ----------
    { const s2 = secs.find(s => s.title === '2. Explore structure'), s3 = secs.find(s => s.title === '3. Rules and Your assumptions'), s1 = secs.find(s => s.title === '1. Design system'), p17 = R.pass, f17 = R.fail.length;
      await page.evaluate(() => { loadSample(); S.tab = 'explore'; S.xs = []; lastId = null; render(); });
      const ex = await page.evaluate(() => ({ secs: [...document.querySelectorAll('#main .sec h3')].map(h => h.textContent), rows: [...document.querySelectorAll('#main [data-a="cat"]')].map(r => [r.querySelector('.ic').textContent, r.querySelector('b').textContent, r.querySelector('.small').textContent]) }));
      const want = ['What-ifs for your goals', 'Focus on one area', 'Tools for you', 'Watch · picked for you', 'Calculators'];
      ok(JSON.stringify(ex.secs) === JSON.stringify(want) && s2.text.includes('Sections in this order (journey-spec §17): What-ifs for your goals (after a plan), Focus on one area, Tools for you, Watch · picked for you, Calculators'), 'Explore order live and in the doc: ' + ex.secs.join(' → '));
      const gT = s2.blocks.find(b => b.t === 'tbl' && b.rows[0][0] === 'Emoji' && b.rows[0][1] === 'Group (verbatim)');
      ex.rows.forEach(r => ok(gT && gT.rows.some(x => x[0] === r[0] && x[1] === r[1] && x[2] === r[2]), 'Calculators row "' + r[1] + ' | ' + r[2] + '"')); ok(ex.rows.length === 6, 'six Calculators rows');
      ok(!(await page.evaluate(() => document.querySelectorAll('#main .ctile[data-a="cat"]').length)), 'no coloured group tiles');
      // emoji never read aloud: headings of every calculator and the sample screens have the emoji in aria-hidden spans, and the doc says so
      ok(/aria-hidden="true">…<\/span>, so the accessible name is the words only/.test(s1.text), 'doc 1.11 specifies the aria-hidden emoji pattern');
      for (const [n, c] of calcs.entries()) { await D.base('fresh'); await D.calc(c.id); const t = await page.evaluate(() => { const h = document.querySelector('#screen h2.t'), sp = h.querySelector('span[aria-hidden="true"]'); const cl = h.cloneNode(true); cl.querySelectorAll('[aria-hidden="true"]').forEach(x => x.remove()); return { emo: sp ? sp.textContent : null, name: cl.textContent.replace(/\s+/g, ' ').trim() }; });
        const N = 'C' + String(n + 1).padStart(2, '0'), sec = secs.find(s => s.title.startsWith(N + ' ')); ok(t.emo && !/\p{Extended_Pictographic}/u.test(t.name) && sec.text.includes('accessible name is "' + t.name + '"'), N + ': title accessible name "' + t.name + '" (emoji ' + t.emo + ' hidden)'); }
      const hid = await page.evaluate(() => { const o = []; [['XPL', () => { S = fresh(); S.shell = true; S.tab = 'explore'; S.xs = []; }], ['HOME', () => { loadSample(); S.tab = 'home'; }], ['ME', () => { loadSample(); S.tab = 'me'; S.me = 'home'; }], ['PLAN', () => { loadSample(); }]].forEach(([n, f]) => { f(); lastId = null; render(); const bad = [...document.querySelectorAll('#screen h1, #screen h2, #screen h3, #screen button.goal b')].filter(h => { const c = h.cloneNode(true); c.querySelectorAll('[aria-hidden="true"]').forEach(x => x.remove()); return /\p{Extended_Pictographic}/u.test(c.textContent); }).length; o.push([n, bad]); }); return o; });
      hid.forEach(([n, bad]) => ok(bad === 0, 'no emoji in the accessible names on ' + n));
      // Ask button
      const askOn = () => page.evaluate(() => !!document.querySelector('#screen .askfab'));
      await page.evaluate(() => { S = fresh(); lastId = null; render(); }); const ob = [['D0', await askOn()]];
      await page.click('.cover .wbtn'); ob.push(['D1', await askOn()]); await page.click('.qfoot .qback');
      for (let i = 0; i < 6; i++) { ob.push(['D' + (i + 2), await askOn()]); await page.click('.opt >> nth=1'); await page.waitForTimeout(450); }
      ob.push(['DR', await askOn()]); await page.click('text=Get a more accurate picture: make my plan'); ob.push(['DS', await askOn()]); await page.evaluate(() => { S.sheet = 'saveprompt'; render(); }); ob.push(['DS sheet', await askOn()]); await page.keyboard.press('Escape');
      ok(ob.every(x => x[1] === false), 'Ask hidden on all onboarding screens: ' + JSON.stringify(ob)); await page.click('[data-a="dsskip"]'); const inapp = [await askOn()];
      for (const t of ['explore', 'plan', 'me', 'exp', 'home']) { await page.click('[data-a="tab"][data-p="' + t + '"]'); inapp.push(await askOn()); } await page.click('[data-a="tab"][data-p="plan"]'); await page.click('[data-a="makeplan"]'); inapp.push(await askOn());
      ok(inapp.every(Boolean), 'Ask shown in the app and plan builder: ' + inapp.join(','));
      ok(s5.text.includes('is **not shown on any onboarding screen**'.replace(/\*\*/g, '')) && s5.text.includes('aria-label "Ask: help and plain-English explanations"'), 'doc 5.3 states the Ask rule');
      // ---------- §19: Settings (3.7), lists (4.8 to 4.10), complete on save, Emergency fund months (6.1), goal order (6.2) ----------
      const sec6 = secs.find(s => s.title === '6. Goals: Emergency fund months and goal order'), cell = r => norm(r), allT = t => t.rows.flat().join(' ');
      const lv = await page.evaluate(() => ({ s: JSON.parse(JSON.stringify(SETTINGS.s)), g: JSON.parse(JSON.stringify(SETTINGS.g)), fmt: Object.fromEntries(Object.entries(SETTINGS.s).map(([k, v]) => [k, setFmt(v, v.v)])), ie: INFL_IE }));
      const keysS = Object.keys(lv.s); ok(keysS.length >= 37 && s3.text.includes(keysS.length + ' standards'), 'Settings has 37 standards live and in the doc: ' + keysS.length);
      const stdT = s3.blocks.filter(b => b.t === 'tbl' && b.rows[0][0] === 'Setting (workbook name)').flatMap(b => b.rows.slice(1)); ok(stdT.length === keysS.length, '3.7.1 tables hold ' + stdT.length + ' rows');
      const XSR = XL._settings.rows, wcell = nmx => { for (const row of XSR) for (const c of row) if (c[1].includes(nmx)) return c[0]; return undefined; }, same = (a, b) => (b == null ? a === '' || a == null : typeof b === 'number' ? Math.abs(+a - b) < 1e-12 : String(a) === String(b));
      for (const k of keysS) { const x = lv.s[k], nmn = 'Set_' + k + (x.u === 'pct3' ? '_1 to _3' : ''), r = stdT.find(t => t[0] === x.n + ' (' + nmn + ')'), src = [(x.src || 'no source (no published figure)') + ' · as at ' + x.asat].concat(x.guide ? ['Guidance: ' + x.guide] : [], x.note ? ['Note: ' + x.note] : []).join(' ');
        ok(r && r[1] === lv.fmt[k] && r[2] === (x.label || x.by) && r[3] === src && r[4] === (x.verify ? 'Yes' : 'No'), 'Settings ' + k + ': doc row ' + JSON.stringify(r));
        if (x.u === 'pct3') x.v.forEach((v, i) => ok(same(wcell('Set_' + k + '_' + (i + 1)), v), 'workbook Set_' + k + '_' + (i + 1) + ' = ' + v + ' (' + wcell('Set_' + k + '_' + (i + 1)) + ')')); else ok(same(wcell('Set_' + k), x.v), 'workbook Set_' + k + ' = ' + x.v + ' (' + wcell('Set_' + k) + ')');
        ok(wcell('Set_' + k + '_Label') === x.by, 'workbook Set_' + k + '_Label = prototype wording'); if (x.vc != null) ok(same(wcell('Set_' + k + '_Cautious'), x.vc), 'workbook Set_' + k + '_Cautious = ' + x.vc); }
      for (const [k, x] of Object.entries(lv.g)) ok(same(wcell('Set_g_' + k), x.v) && s3.text.includes(x.n + ' = ' + x.v), 'guidance figure ' + k + ' = ' + x.v + ' in the workbook and 3.7');
      ok(same(wcell('Set_inflNow'), lv.ie) && same(wcell('Card_APR_Cap'), 0.23) && s3.text.includes('Set_inflNow') && s3.text.includes('Card_APR_Cap'), 'fixed values on the Settings sheet: Ireland now ' + lv.ie + ', card cap 23%');
      ok(s3.text.includes('Partner_Name') && XSR.some(row => row.some(c => c[1].includes('Partner_Name'))), 'Partner_Name in the workbook and 3.7');
      // admin view and the partner override (live)
      const adm = await page.evaluate(() => { loadSample(); S.admin = true; lastId = null; render(); const T = e => e ? e.textContent.replace(/\s+/g, ' ').trim() : null; return { note: T(document.querySelector('.note[role="note"]')), label: T(document.querySelector('label[for="set-partner"]')), groups: [...document.querySelectorAll('details.asmg')].map(d => T(d.querySelector('summary'))), head: T(document.querySelector('header.sky')), jump: document.getElementById('jumps').textContent.includes('Admin (not for customers)') }; });
      const admT = s3.blocks.find(b => b.t === 'tbl' && b.rows.some(r => r[0].startsWith('Marked-off note'))); ok(admT && admT.rows.some(r => r[1] === adm.note) && admT.rows.some(r => r[1].includes(adm.label)) && adm.groups.every(g => allT(admT).includes('"' + g + '"')), 'admin view note, partner label and group summaries in 3.7.3: ' + adm.groups.join(' | ')); ok(adm.jump && adm.head.includes('🔒 Admin view · not for customers'), 'admin view is marked not for customers and reached from the jump list');
      const ovr = await page.evaluate(() => { const T = e => e ? e.textContent.replace(/\s+/g, ' ').trim() : null; S = fresh(); S.shell = true; S.tab = 'me'; S.me = 'asm'; SETTINGS.partner = 'Example Credit Union'; SET.infl.pv = 0.025; SET.mortRate.pv = 0.0399; SET.safetyMonths.pv = 4; const o = {};
        S.asmOpen = 'prices'; lastId = null; render(); const ic = document.querySelector('.infl'); o.infl = [T(ic.querySelector('p.small')), T(ic.querySelector('.chip'))]; o.wage = T(document.querySelector('.field.asmf[data-k="wage"] > span.small')); o.cash = T(document.querySelector('.field.asmf[data-k="cash"] > span.small'));
        S.asmOpen = 'safety'; render(); o.months = [T(document.querySelector('.field.asmf[data-k="safetyMonths"] > span.small')), null]; o.mort = T(document.querySelector('.field.asmf[data-k="mortRate"] > span.small')); o.loan = T(document.querySelector('.field.asmf[data-k="loanRate"] > span.small'));
        S.admin = true; render(); const tag = document.querySelector('#setl-infl .tag'); o.tag = T(tag); o.resetAll = T(document.querySelector('[data-a="setreset"][data-p="all"]')); SETTINGS.partner = ''; Object.values(SET).forEach(s => { delete s.pv; }); applyAssume(); S.admin = false; return o; });
      const ovT = s3.blocks.find(b => b.t === 'tbl' && b.rows[0][0] === 'Where the customer sees it'), ovAll = ovT ? allT(ovT) : '';
      ok(ovAll.includes(ovr.infl[0]) && ovAll.includes(ovr.infl[1]) && ovAll.includes(ovr.months[0]) && (ovr.months[1] == null || ovAll.includes(ovr.months[1])) && ovAll.includes(ovr.mort) && ovAll.includes(ovr.loan) && ovAll.includes(ovr.wage), '3.7.2 partner example strings equal the live screens: ' + [ovr.infl[0], ovr.mort].join(' | ') + JSON.stringify([ovAll.includes(ovr.infl[0]), ovAll.includes(ovr.infl[1]), ovAll.includes(ovr.months[0]), ovr.months[1], ovAll.includes(ovr.mort), ovAll.includes(ovr.loan), ovAll.includes(ovr.wage), ovr.mort, ovr.wage]));
      ok(/Suggested by Example Credit Union/.test(ovr.infl[0] + ovr.months[0] + ovr.mort) && !/Suggested by/.test(ovr.wage + ovr.cash + ovr.loan), '"Suggested by {partner}" only beside the figures the partner changed'); ok(s3.text.includes(ovr.tag) && s3.text.includes(ovr.resetAll), 'tag "' + ovr.tag + '" and "' + ovr.resetAll + '" in 3.7.2');
      // Your lists: item blocks, labels, buttons, hints
      const SL = await page.evaluate(() => ({ LDEF: JSON.parse(JSON.stringify(LDEF)), FFI: JSON.parse(JSON.stringify(FFI)), hint: PROT_HINT.workCover }));
      for (const lk of Object.keys(SL.LDEF)) { const D = SL.LDEF[lk]; ok(s4.text.includes('"' + D.add + '"') || s4.text.includes(D.add), 'add button "' + D.add + '" in section 4.8'); ok(s4.text.includes(D.up), 'upload text "' + D.up + '" in section 4.8'); D.f.forEach(f => ok(s4.text.includes(SL.FFI[lk + '.' + f].l), 'item field label "' + SL.FFI[lk + '.' + f].l + '" in 4.8')); }
      ok(s4.text.includes(SL.hint), 'cover-through-work hint in 4.8.3');
      const lst = async (secI, base) => page.evaluate(([i, base]) => { if (base === 'sample') loadSample(); else { S = fresh(); } S.app = false; S.pb = true; S.shell = true; S.tab = 'plan'; S.scr = 'P3'; lastId = null; openSec(i); const T = e => e ? e.textContent.replace(/\s+/g, ' ').trim() : null; return { adds: [...document.querySelectorAll('[data-a="iadd"]')].map(T), ups: [...document.querySelectorAll('[data-a="iupl"]')].map(T), titles: [...document.querySelectorAll('[id^="item-"] > .row b')].map(T), labels: [...document.querySelectorAll('[id^="item-"] label')].map(l => { const c = l.cloneNode(true); c.querySelectorAll('.tag').forEach(x => x.remove()); return T(c); }), lead: [...document.querySelectorAll('#main .card > p')].map(T), blank: T([...document.querySelectorAll('#main p.small')].find(p => /Leave blank/.test(p.textContent))), seg: document.querySelectorAll('.seg button').length, sub: T(document.querySelector('header.sky p.sub')) }; }, [secI, base]);
      const L3 = await lst(3, 'fresh'); ok(L3.adds.includes('＋ Add a credit card') && L3.adds.includes('＋ Add a loan') && L3.titles.includes('Credit card 1') && L3.titles.includes('Loan 1') && s4.text.includes(L3.blank) && s4.text.includes('Credit card 1'), 'Liabilities: add buttons, first empty items and the blank note: ' + L3.adds.join(' | '));
      L3.labels.forEach(l => ok(s4.text.includes(l), 'Liabilities item label "' + l + '" in the doc'));
      const L4 = await lst(4, 'fresh'); ok(L4.lead[0] === 'Do you have any of the following?' && L4.seg === 0 && s4.text.includes(L4.lead[0]) && s4.text.includes(L4.lead[1]) && s4.text.includes(L4.sub) && s4.text.includes('no generic upload at the top of this section'), 'Protection: lead-in, no generic upload, header line "' + L4.sub + '"');
      const L4b = await page.evaluate(() => { const o = []; S.fin.life = 'Yes'; S.fin.workCover = 'Yes'; S.fin.ip = 'Yes'; S.fin.ci = 'Yes'; S.fin.health = 'Yes'; lastId = null; render(); const T = e => e ? e.textContent.replace(/\s+/g, ' ').trim() : null; return { adds: [...document.querySelectorAll('[data-a="iadd"]')].map(T), titles: [...document.querySelectorAll('[id^="item-"] > .row b')].map(T), hint: T(document.getElementById('ph-workCover')) }; });
      ok(L4b.adds.length === 5 && L4b.adds.every(a => s4.text.includes(a)) && L4b.titles.every(t => s4.text.includes(t) || /\d$/.test(t)) && L4b.hint === SL.hint, 'Protection: five add buttons and the work-cover hint (' + L4b.adds.join(' | ') + ')');
      const L5 = await lst(5, 'fresh'); ok(L5.adds.includes('＋ Add another pension') && s4.text.includes('＋ Add another pension') && L5.labels.every(l => s4.text.includes(l)), 'Pension: separate items with the add button');
      // per-item upload flow and complete-on-save
      const up = await page.evaluate(async () => { S = fresh(); S.shell = true; S.pb = true; S.app = false; S.tab = 'plan'; S.scr = 'P3'; lastId = null; openSec(3); const it = document.querySelector('[data-a="iupl"][data-p^="cards|"]'); it.click(); await new Promise(r => setTimeout(r, 1700)); const a = document.getElementById('main').innerText.replace(/\s+/g, ' ').trim(), cur = document.getElementById('curid').textContent; document.querySelector('[data-a="uplok"]').click(); await new Promise(r => setTimeout(r, 300)); const T = e => e ? e.textContent.replace(/\s+/g, ' ').trim() : null; return { a, cur, toast: document.getElementById('toast').innerText, row: T(document.querySelector('[id^="item-cards"] .mini')), tags: [...document.querySelectorAll('[id^="item-cards"] label .tag')].map(T) }; });
      ok(s4.text.includes(up.a) && s4.text.includes(up.cur.replace(/^PU-confirm · /, '')) && s4.text.includes(up.toast.replace(/^\W+/, '')) && s4.text.includes(up.row), 'per-item upload: confirm screen, toast and the "From …" row equal 4.8.4: ' + up.a + ' | ' + up.row);
      const sv = await page.evaluate(() => { const hub = () => [...document.querySelectorAll('#main button.goal')].map(b => b.querySelector('b').textContent + ' = ' + b.querySelector('.sr').textContent); S = fresh(); S.shell = true; S.pb = true; S.app = false; S.tab = 'plan'; S.scr = 'P3'; lastId = null; openSec(3); const a = document.getElementById('i-cards-1-owed'); a.value = '400'; a.dispatchEvent(new Event('input', { bubbles: true })); document.querySelector('.foot .btn').click(); const h1 = hub(); openSec(2); document.querySelector('.foot .btn').click(); const h2 = hub(); const t = document.getElementById('toast').innerText; S.scr = 'P4'; S.pb = true; lastId = null; render(); const miss = [...document.querySelectorAll('#main .ck .small')].map(x => x.textContent.replace(/\s+/g, ' ').trim()).filter(x => /^Missing/.test(x)); return { h1, h2, t, miss }; });
      ok(sv.h2.includes('Assets = Done') && sv.h2.includes('Liabilities = Done') && sv.h2.every(h => s4.text.includes(h) || /Not started/.test(h)) && sv.miss.length > 0 && sv.miss.every(m => m.startsWith('Missing · optional, counts as €0')) && s4.text.includes('Missing · optional, counts as €0'), 'a saved section (even with blanks) is Done and Missing reads optional: ' + sv.h2.join(', ') + ' | ' + sv.miss[0]);
      // workbook Your lists and the calculators that fall back to it
      const XL2 = XL._lists, lnames = [].concat(...XL2.rows.map(r => [].concat(...r.map(c => c[1])))).filter(n => /_Total|_Avg/.test(n)); const lt = s4.blocks.find(b => b.t === 'tbl' && b.rows[0][0] === 'Total (label)');
      ok(lnames.length >= 12 && lt && lnames.every(n => allT(lt).includes(n)), 'every named total of the sheet "Your lists" is in 4.10: ' + lnames.join(', ')); ok(s4.text.includes(XL2.intro), 'Your lists sheet intro text in 4.10');
      for (const [c, list] of Object.entries(XL._fallback)) { const csec = secs.find(s => s.title.startsWith(c + ' ')); list.forEach(([cl, lab, nms]) => ok(csec.text.includes(cl + ' "' + lab + '" ← ' + nms.join(' + ')) && s4.text.includes(lab), c + ' falls back to ' + nms.join(' + ') + ' (' + cl + ')')); }
      ok(Object.keys(XL._fallback).join(',') === 'C12,C13,C14,C21,C24,C25' && ['C27', 'C28'].every(c => secs.find(s => s.title.startsWith(c + ' ')).text.includes('not fed by the sheet "Your lists"')), 'exactly C12, C13, C14, C21, C24, C25 fall back to Your lists; C27 and C28 are not fed');
      // Emergency fund months: one value
      const mo = await page.evaluate(async () => { const o = {}; const T = e => e ? e.textContent.replace(/\s+/g, ' ').trim() : null; loadSample(); S.asm = Object.assign({}, S.asm); delete S.asm.safetyMonths; applyAssume(); syncSafety(); S.app = false; S.shell = true; S.tab = 'explore'; S.xs = []; lastId = null; render(); ACT.calc('emergency');
        o.gate = document.getElementById('cgate') ? document.getElementById('cgate').innerText.replace(/\n/g, ' · ') : null; o.tag = T(document.querySelector('#co-mt').closest('.field').querySelector('.tag')); const b = document.getElementById('co-mt'); b.value = '3'; b.dispatchEvent(new Event('input', { bubbles: true })); b.blur(); o.line = document.querySelector('#cout .card p').textContent; o.asm3 = S.asm.safetyMonths;
        S.tab = 'plan'; S.pb = true; S.scr = 'F2'; S.xs = []; S.tlOpen = {}; S.tlOpen[S.goals.find(g => g.k === 'safety').id] = true; lastId = null; render(); const gi = document.querySelector('[data-gmonths]'); o.goalShows = gi.value; o.goalLabel = T(gi.closest('label').querySelector('.fl')); o.goalNote = T(gi.closest('label').querySelector('.small')); o.ph = gi.placeholder; gi.value = '4'; gi.dispatchEvent(new Event('change', { bubbles: true })); o.asm4 = S.asm.safetyMonths;
        S.tab = 'explore'; S.xs = []; lastId = null; render(); ACT.calc('emergency'); o.edge = [S.asm.safetyMonths, document.getElementById('co-mt').value]; loadSample(); S.asm = Object.assign({}, S.asm); delete S.asm.safetyMonths; applyAssume(); syncSafety(); setSafetyMonths(4); S.app = false; S.shell = true; S.tab = 'explore'; S.xs = []; lastId = null; render(); ACT.calc('emergency'); o.calcAfter = document.getElementById('co-mt').value; S.tab = 'plan'; S.scr = 'P4'; S.pb = true; lastId = null; render(); const a = document.getElementById('p4-asm'); a.querySelectorAll('details').forEach(d => d.open = true); const f = a.querySelector('.field.asmf[data-k="safetyMonths"]'); o.p4 = f.querySelector('input.nb').value; o.p4tag = T(f.querySelector('.flabel .tag')); return o; });
      ok(mo.asm3 === 3 && mo.goalShows === '3' && mo.asm4 === 4 && mo.calcAfter === '4' && mo.p4 === '4' && mo.p4tag === 'Your choice', 'Emergency fund months are one value: calculator 3 -> goal ' + mo.goalShows + ', goal 4 -> calculator ' + mo.calcAfter + ', step 7 ' + mo.p4); ok(mo.edge[0] === 4 && mo.edge[1] === '3' && sec6.text.includes('C11 keeps the value typed there until it is retyped'), 'edge: a value typed in C11 stays there after the goal changes it (' + mo.edge + ') and the doc says so');
      ok(mo.gate === null && sec6.text.includes('"' + mo.line + '"') && sec6.text.includes('"' + mo.goalLabel + '"') && sec6.text.includes('"' + mo.ph + '"') && sec6.text.includes(mo.goalNote) && sec6.text.includes('tag "' + mo.tag + '"'), '6.1 strings equal the live screens: ' + mo.gate + ' | ' + mo.line + ' | ' + mo.goalLabel);
      // goal order
      const rk = await page.evaluate(() => { const o = {}; const T = e => e ? e.textContent.replace(/\s+/g, ' ').trim() : null; loadSample(); S.app = false; S.shell = true; S.pb = true; S.tab = 'plan'; S.scr = 'F4'; S.rank = null; lastId = null; render(); const r = document.querySelector('[id^="rank-"]:not([id*="msg"]):not([id*="-h-"])'); o.id = r.id; o.heading = T(r.querySelector('h3')); o.help = T(r.querySelector(':scope > p.small')); o.names = rankList().map(g => g.name); o.aria = [...r.querySelectorAll('li:nth-child(2) button')].map(b => b.getAttribute('aria-label')); o.disabled = [r.querySelector('li:first-child button').getAttribute('aria-disabled'), r.querySelector('li:last-child button:last-child').getAttribute('aria-disabled')];
        r.querySelector('[data-a="grank"][data-p$="|down"]').click(); const r2 = document.querySelector('[id^="rank-"]:not([id*="msg"]):not([id*="-h-"])'); o.msg = T(r2.querySelector('[id^="rank-msg"]')); o.reset = T(r2.querySelector('[data-a="grankreset"]')); o.names2 = rankList().map(g => g.name); o.v1 = S.versions[S.versions.length - 1].note; document.querySelector('[data-a="grankreset"]').click(); o.msg3 = T(document.querySelector('[id^="rank-msg"]')); o.names3 = rankList().map(g => g.name); o.v2 = S.versions[S.versions.length - 1].note;
        S.rank = null; o.resDef = resultOrder().map(g => g.name); const l = rankList().map(g => g.id), i = l.indexOf(S.goals.find(g => g.k === 'travel').id); l.unshift(...l.splice(i, 1)); S.rank = l; o.resRank = resultOrder().map(g => g.name); S.rank = null; return o; });
      ok(rk.names[0] === 'Emergency fund' && rk.names2[1] === 'Emergency fund' && rk.names3[0] === 'Emergency fund' && rk.disabled.join() === 'true,true' && rk.msg3 === 'Back to the suggested order' && rk.v1 === 'Goal priority changed' && rk.v2 === 'Goal priority reset', 'ranking: Emergency fund first by default, movable, reset restores: ' + rk.names.join(' > ') + ' | ' + rk.names2.join(' > '));
      ok(sec6.text.includes(rk.heading) && sec6.text.includes(rk.help.replace(/ \(Not changed yet\.\)$/, '')) && rk.aria.every(a => sec6.text.includes(a)) && sec6.text.includes(rk.msg) && sec6.text.includes('"' + rk.reset + '"') && sec6.text.includes(rk.msg3) && sec6.text.includes(rk.resDef.join(', ')) && sec6.text.includes(rk.resRank.join(', ')) && sec6.text.includes(rk.names.join(' › ')) && rk.id === 'rank-f4', '6.2 strings equal the live ranking card: ' + rk.heading + ' | ' + rk.msg + ' | ' + rk.resRank.join(', '));
      ok(!/PARTNER_RATES|PARTNER RATES/.test(secs.map(x => x.text).join(' ')), 'no leftover reference to the old PARTNER_RATES block');
      R.perCalc.push(['§17 / §19', 'Explore order and rows, emoji accessible names, Ask visibility, Settings block, admin view, partner override, workbook Settings', R.pass - p17, R.fail.length - f17]); }
    // ---------- §21 (Explore tiles, Experts boxes) and §22 (Step 7 skippable, banner) ----------
    { const s2 = secs.find(s => s.title === '2. Explore structure'), s3 = secs.find(s => s.title === '3. Rules and Your assumptions'), p21 = R.pass, f21 = R.fail.length, T = e => e ? e.textContent.replace(/\s+/g, ' ').trim() : '';
      await page.evaluate(() => { loadSample(); S.tab = 'explore'; S.xs = []; lastId = null; render(); });
      const tl = await page.evaluate(() => ({ n: document.querySelectorAll('.ttile').length, items: [...document.querySelectorAll('.ttile')].map(e => [e.querySelector('.em').textContent, e.querySelector('b').textContent, e.querySelector('.s').textContent, (e.getAttribute('style').match(/--art-[a-z]+/) || [''])[0]]), arts: ['mortgage', 'pension', 'protection', 'investing', 'savings', 'everyday'].map(k => '--art-' + k) }));
      ok(tl.n === 6 && s2.text.includes('is a grid of 6 square tiles, two per row'), 'Focus on one area: 6 tiles');
      tl.items.forEach(([em, nm, bl, art]) => { const t = s2.blocks.find(b => b.t === 'tbl' && b.rows[0][0] === 'Emoji' && b.rows[0][1] === 'Tile name'); ok(t && t.rows.some(r => r[0] === em && r[1] === nm && r[2] === bl && r[3] === art), 'Tile "' + nm + '": blurb "' + bl + '" and slot ' + art); });
      ok(tl.arts.every(a => s2.text.includes(a)), 'every --art-* slot named'); ok(/measured at 7:1 or better/.test(s2.text) && /not AI-generated/.test(s2.text), 'tiles: contrast and honesty line');
      for (const st of ['home', 'c0', 'c1']) { await page.evaluate(s => { loadSample(); S.tab = 'exp'; S.exp = s; lastId = null; render(); }, st);
        const ex = await page.evaluate(() => ({ h: [...document.querySelectorAll('#main h3')].map(h => h.textContent).includes('Talk to a specialist'), boxes: [...document.querySelectorAll('button.goal.spec')].map(e => [e.querySelector('.ic').textContent, e.querySelector('b').textContent, e.querySelector('.small').textContent]), chips: document.querySelectorAll('.chips [data-a="spec"]').length }));
        const bt = s2.blocks.find(b => b.t === 'tbl' && b.rows[0][0] === 'Icon' && b.rows[0][1] === 'Box name (verbatim)');
        ok(ex.h && ex.boxes.length === 5 && ex.chips === 0 && bt && ex.boxes.every(x => bt.rows.some(r => r[0] === x[0] && r[1] === x[1] && r[2] === x[2])), 'Experts ' + st + ': five specialist boxes match 2.5 (' + ex.boxes.map(x => x[1]).join(', ') + ')'); }
      ok(s2.text.includes('They are not shown on the consent, time and booked screens (C2, C3, C4)'), 'Experts boxes: where shown');
      await page.evaluate(() => { loadSample(); S.app = false; S.shell = true; S.pb = true; S.tab = 'plan'; S.scr = 'P4'; S.retireSet = false; S.infl = null; S.asm = {}; S.pRetSet = false; S.checked = false; lastId = null; render(); });
      const q = await page.evaluate(() => ({ h: [...document.querySelectorAll('#p4-asm h3')].map(h => h.textContent), p: document.querySelector('#p4-3 h3 + p').textContent, cnt: document.getElementById('p4-count').textContent, rest: document.querySelector('#p4-rest summary + p').textContent, btn: 'Skip, show my results', note: 'Both are disabled until the required choices are made', sum: document.querySelector('#p4-rest summary').textContent, need: document.getElementById('p4-need').textContent, see: document.getElementById('seeres').textContent, skip: document.getElementById('skipres').textContent, dis: [document.getElementById('seeres').disabled, document.getElementById('skipres').disabled], tick: !!document.querySelector('[data-chk]') }));
      [...q.h, q.p, q.cnt, q.rest.replace(/^\d+ of \d+/, '').trim().slice(0, 20), q.btn, q.note, q.sum, q.need, q.see, q.skip].forEach(t => ok(s3.text.includes(t), 'Step 7 text in 3.5: "' + t.slice(0, 50) + '"'));
      ok(q.dis[0] && q.dis[1] && !q.tick && /Both are disabled until the required choices are made/.test(s3.text) && /The required tick .{0,60} is gone/.test(s3.text), 'Step 7: both buttons disabled, no tick');
      { const u2 = await page.$('[data-a="useall"][data-p="p4"]'); const ua2 = await page.evaluate(() => ({ infl: S.infl, ret: S.retireSet, end: asmMine('planEnd') })); ok(!u2 && ua2.infl == null && !ua2.ret && !ua2.end, 'No standards button on Step 7; the 3 required choices stay unchosen (' + JSON.stringify(ua2) + ')'); }
      await page.evaluate(() => { S.retireSet = true; S.retireAge = 65; S.infl = 0.02; S.asm.planEnd = 90; S.pRetSet = true; S.pRet = 66; render(); }); await page.click('#skipres'); await page.waitForTimeout(1800);
      const bn = await page.evaluate(() => ({ app: S.app, b: (document.getElementById('miss-banner') || {}).textContent || '', n: missingFlags().length }));
      ok(bn.app && bn.b.length > 0, 'Skip opens results with a banner (' + bn.b + ')');
      for (const k of [1, 3]) { const o = await page.evaluate(k => { loadSample(); S.app = true; S.shell = true; S.pb = false; S.tab = 'plan'; S.planSeg = 'main'; S.retireSet = true; S.infl = 0.02; S.asm.planEnd = 90; useAllStd(); const ks = []; FSEC.forEach(s => s.f.filter(fieldVisible).filter(x => x !== 'retireAge' && !FF[x].opt).forEach(x => ks.push(x))); ks.forEach(x => { S.src[x] = 'typed'; }); Object.keys(S.look).forEach(x => delete S.look[x]); ks.slice(0, k).forEach(x => { delete S.src[x]; delete S.fin[x]; }); lastId = null; render(); return { n: missingFlags().length, b: (document.getElementById('miss-banner') || {}).textContent.replace('ℹ️', '') }; }, k);
        ok(o.n === k && s3.text.includes(o.b), 'Banner text for ' + k + ' missing is in 3.5.1: "' + o.b + '"'); }
      R.perCalc.push(['§21 / §22', 'Focus on one area tiles, Experts specialist boxes, Step 7 skippable, results banner', R.pass - p21, R.fail.length - f21]); }
    // ---------- §23 to §25 (naming, cover photo, Budget note, Liabilities, What-if, saving files, photos, videos) ----------
    { const s2 = secs.find(s => s.title === '2. Explore structure'), s4 = secs.find(s => s.title.startsWith('4. ')), s5 = secs.find(s => s.title === '5. LifeMap name and cover'), s7 = secs.find(s => s.title.startsWith('7. ')), pm = R.pass, fm = R.fail.length, SRC = fs.readFileSync(path.join(__dirname, 'proto-head.html'), 'utf8'), ALL = secs.map(s => s.title + ' ' + s.text).join(' ');
      // naming
      await page.evaluate(() => { loadSample(); delete S.asm.safetyMonths; S.infl = 0.02; S.retireSet = true; S.asm.planEnd = 90; S.tab = 'plan'; lastId = null; render(); });
      const nm = await page.evaluate(() => ({ gate: chooseTxt({ n: ASM.safetyMonths.n }), label: ASM.safetyMonths.l, group: ASM_GRP.find(g => g[0] === 'safety')[1], row: assumeRows().find(r => /Emergency fund/.test(r[0])), q: CALCS.find(c => c.id === 'emergency').q, any: [...document.body.innerText.matchAll(/.{0,30}safety[- ]net.{0,20}/gi)].map(m => m[0]) }));
      ok(nm.gate === 'Choose your emergency fund months to see this' && s7.text.includes(nm.gate) && s7.text.includes(nm.label) && s7.text.includes(nm.group) && s7.text.includes(nm.row.join(' · ')) && s7.text.includes(nm.q), 'Emergency fund naming (7.1): gate, label, group, row, question');
      ['Building a safety net for emergencies', 'No safety net', 'Strong safety net', 'Nothing is set aside for surprises yet.', '6 months or more of savings to fall back on.'].forEach(t => ok(s7.text.includes(t) && SRC.includes(t), 'Kept Lifecast wording listed in 7.1 and still in the prototype: ' + t));
      const stray = secs.filter(s => s !== s7 && !/^Appendix/.test(s.title)).flatMap(s => (s.text.match(/.{0,40}safety[- ]net.{0,30}/gi) || []).map(m => s.title + ': ' + m)).filter(m => !/Building a safety net for emergencies/.test(m));
      ok(stray.length === 0, 'no stray "safety net" outside 7.1 and the D1 chip: ' + stray.slice(0, 4).join(' | '));
      ok(s7.text.includes('Your emergency fund is also meant for other things.') && SRC.includes('Your emergency fund is also meant for other things.') && !SRC.includes('Your safety money'), 'Thin buffer meaning reworded to Emergency fund');
      // cover
      const cv = await page.evaluate(() => { S = fresh(); S.scr = 'D0'; lastId = null; render(); return { pos: getComputedStyle(document.querySelector('.cover-photo')).backgroundPosition, jpeg: /^url\("data:image\/jpeg;base64,/.test(getComputedStyle(document.documentElement).getPropertyValue('--cover-photo')) }; });
      ok(cv.jpeg && s5.text.includes('Position: ' + cv.pos) && /912 × 502/.test(s5.text) && /larger portrait original/.test(s5.text), 'Cover photo: JPEG slot, position ' + cv.pos + ', honesty note');
      const ct = s5.blocks.find(b => b.t === 'tbl' && b.rows[0][0] === 'Viewport (px)'); ok(ct && ct.rows.length === 5 && ct.rows.slice(1).every(r => r.slice(1).every(x => parseFloat(x) >= 4.5)) && ['390 × 844', '360 × 640', '844 × 390', '1280 × 800'].every(z => ct.rows.some(r => r[0] === z)), 'Cover contrast table: four viewports, every line at least 4.5:1');
      // Budget note
      const bu = await page.evaluate(() => { loadSample(); S.sheet = 'assume'; render(); const a = (document.getElementById('b27-sheet') || {}).textContent; S.sheet = null; S.tab = 'plan'; render(); return { a, r: (document.getElementById('b27-res') || {}).textContent, c: BUDGET27 }; });
      ok(bu.a === bu.c && bu.r === bu.c && s7.text.includes(bu.c) && !/46,500|2,125/.test(ALL), 'Budget 2027 note: same text in the sheet, the footnote and 7.4; no Budget figures named');
      // tiles with photos
      const tp = await page.evaluate(() => ({ pos: TOPIC_PHOTO, kinds: ['mortgage', 'pension', 'protection', 'investing', 'savings', 'everyday'].map(k => /^url\("data:image\/jpeg/.test(getComputedStyle(document.documentElement).getPropertyValue('--art-' + k)) ? 'photo' : 'drawn') }));
      ok(JSON.stringify(tp.kinds) === JSON.stringify(['photo', 'photo', 'drawn', 'photo', 'photo', 'photo']) && Object.entries(tp.pos).every(([k, p]) => s2.text.includes('object-position ' + p)) && s2.text.includes('Protection has no matching photo'), 'Focus tiles: five photos with their object-positions in 2.2, Protection drawn');
      // videos
      await page.evaluate(() => { S = fresh(); S.shell = true; S.app = false; S.tab = 'home'; lastId = null; render(); });
      const vd = await page.evaluate(() => ({ real: VIDEOS.filter(v => v.src).map(v => [v.t, VKIND[v.kind], v.dur, v.src, v.poster, C(v.tool).name]), home: [...document.querySelectorAll('#main .vthumb b')].map(e => e.textContent), fail: VID_FAIL }));
      const vt = s2.blocks.find(b => b.t === 'tbl' && b.rows[0][0] === 'Title (verbatim)' && b.rows[0][2] === 'Length');
      vd.real.forEach(v => ok(vt && vt.rows.some(r => r[0] === v[0] && r[1] === v[1] && r[2] === v[2] && r[3] === v[3] && r[4] === v[4] && r[5].startsWith(v[5])), 'Video row in 2.6: ' + v[0]));
      ok(vd.real.length === 2 && vd.home.includes('What is auto-enrolment?') && s2.text.includes(vd.fail) && /Captions not available yet/.test(s2.text) && /could not be tested/.test(s2.text) && /(NOT|never) embedded/.test(ALL), 'Videos: both in Home, failure message, captions and testing honesty in the doc ' + JSON.stringify([vd.real.length, vd.home, s2.text.includes(vd.fail), /Captions not available yet/.test(s2.text), /could not be tested/.test(s2.text), /NOT embedded/.test(ALL)]));
      await page.evaluate(() => { S.tab = 'explore'; S.xs = [{ v: 'VID', p: 'v7' }]; lastId = null; render(); });
      const pl = await page.evaluate(() => { const e = document.getElementById('vid-el'); return { c: e.controls, p: e.getAttribute('preload'), s: e.getAttribute('src'), po: e.getAttribute('poster') }; });
      ok(pl.c && pl.p === 'metadata' && s2.text.includes('preload="metadata"') && s2.text.includes('src="media/') , 'Video element attributes match 2.6 (' + JSON.stringify(pl) + ')');
      // Liabilities
      const lb = await page.evaluate(() => { loadSample(); S.app = true; S.shell = true; S.tab = 'me'; S.me = 'fin'; S.fsec = 3; lastId = null; render(); return { q: FF.mortYN.l, add: LDEF.mort2.add, f: LDEF.mort2.f.map(f => FFI['mort2.' + f].l), ord: [...document.querySelectorAll('#main .card > b')].map(b => b.textContent.replace(/\s+/g, ' ').trim()) }; });
      ok(s4.text.includes(lb.q) && s4.text.includes(lb.add) && lb.f.every(l => s4.text.includes(l)) && /Mortgage, Credit cards, Other loans/.test(s4.text), 'Liabilities (4.8.2): question, add button and other-property fields');
      // What-if
      const wi = await page.evaluate(() => { loadSample(); S.tab = 'plan'; S.planSeg = 'main'; S.planGo = 'wi'; S.wi.g = S.goals[1].id; S.wi.m = 0; lastId = null; render(); const o = { h: [...document.querySelectorAll('#r-wi .wih')].map(e => e.textContent), labels: [...document.querySelectorAll('#r-wi .wisec .flabel')].map(e => e.textContent.replace(/\s+/g, ' ').trim()).filter(x => /^(Your saving today|Extra each month)$/.test(x)) }; [0, 725].forEach(m => { S.wi.m = m; liveUpdate(); o['l' + m] = document.getElementById('wi-live').innerText.replace(/\s+/g, ' ').trim(); }); return o; });
      ok(wi.h[0] === 'Your monthly saving' && s7.text.includes('section "Your monthly saving"') && wi.labels.every(l => s7.text.includes(l)) && s7.text.includes(wi.l0) && s7.text.includes(wi.l725.replace(/ ⚠️.*$/, '')), 'What-if (7.2): sections, labels and the live line verbatim');
      // Saving files
      ['Preparing your PDF…', 'We couldn\'t make the PDF here, so we saved your plan as LifeMap-plan.html. Open it and choose Print to get a PDF.', 'Opening the print window. Choose "Save as PDF" as the printer.', 'LifeMap-plan.pdf', 'LifeMap-meeting.txt'].forEach(t => ok(s7.text.includes(t) && SRC.replace(/\\'/g, "'").includes(t), 'Saving files (7.3): "' + t.slice(0, 50) + '"'));
      ok(s7.text.includes('cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js') && SRC.includes('jspdf.umd.min.js') && /Not tested: the real Claude viewer/.test(s7.text), 'Saving files: library URLs and the honest limits');
      // ---------- §26 and the fix rounds: re-driven live (same collector as the screenshots), compared with the doc ----------
      { const Z = await require('./s26lib')(page, false), I = Z.inv, XLX0 = require('./s26x.json'), I0 = Z.inv, T7 = s7.text, T3 = secs.find(s => s.title.startsWith('3. ')).text, T2 = s2.text, hit = (m, t, tx) => ok(tx.includes(t), m + ': "' + String(t).slice(0, 70) + '"');
        hit('7.5 gate title', Z.gate.res.title, T7); hit('7.5 gate text', Z.gate.res.p, T7); Z.gate.res.rows.forEach(r => { hit('7.5 row', r.name, T7); hit('7.5 aria', r.aria, T7); });
        ok(Z.gate.res.rows.length === 4 && Z.gate.three.rows.length === 3 && Z.gate.home.rows.join() === Z.gate.res.rows.map(r => r.name).join() && Z.gate.report.rows.join() === Z.gate.res.rows.map(r => r.name).join() && Z.gate.report.title === Z.gate.res.title && Z.gate.strip.title === Z.gate.res.title && Z.gate.report.h2 === 'Almost there', 'The gate card has the same title and rows on Results, Home, the report sheet and the strip');
        ok(Z.gateJump.tab === 'me' && Z.gateJump.me === 'asm' && Z.gateJump.open === 'length' && Z.gateJump.flash === true && Z.gateAfter.ready === true && !/Use the standards for the rest/.test(await page.evaluate(() => document.body.innerText)), 'Choose jumps to Your assumptions, opens the group and highlights the box; no "Use the standards for the rest" wall');
        hit('7.5 strip', Z.gate.strip.small, T7); hit('7.5 report', Z.gate.report.h2, T7);
        hit('7.6 mortgage item', Z.mort2.p4.replace(/⚠️Pension.*$/, '').replace(/^❓/, '❓ '), T7); ok(Z.mort2.ready === true && Z.mort2.missing.length === 0 && /Assumed: add yours · we use 25 years/.test(Z.mort2.p4), 'Other-property mortgage with a balance only: never blocks, assumed 25 years, labelled');
        ok(I.inv.v === 0.026 && I.inv.vc === 0.019 && I.at6 === 0.033 && T7.includes(I.inv.by) && T7.includes(I.inv.src) && T7.includes(I.invGross.src) && T7.includes(I.inv.guide), 'Investment standard 2.6% / cautious 1.9% (3.3% at 6% growth), wording and sources in 7.7');
        const XLX = require('./s26x.json'); ok(Math.abs(+XLX.inv.value - I.inv.v) < 1e-9 && Math.abs(+XLX.cautious.value - I.inv.vc) < 1e-9 && T7.includes(XLX.inv.formula) && /Set_invGross/.test(XLX.inv.formula), 'Workbook Set_inv and Set_inv_Cautious equal the prototype values and the formula is in 7.7');
        [Z.strength.sample, Z.strength.over, Z.strength.none].forEach(t => hit('7.8 strength', t, T7)); ok(Z.strength.sample === 'Emergency fund is 100% covered' && /^No strength/.test(Z.strength.over) && /^Nothing is fully covered/.test(Z.strength.none), 'Strength rules: covered goal / overspending / nothing covered');
        hit('7.9 four things', Z.p4partner.h3 + '": "' + Z.p4partner.p, T7); ok(Z.p4partner.req.length === 4 && Z.p4single.req.length === 3 && Z.p4single.h3 === 'Choose 3 things' && Z.p4partner.count === '0 of 4 chosen', 'Required choices: 4 with a partner income, 3 without'); hit('7.9 summary', Z.p4partner.summary, T7); hit('7.9 known limits', Z.knownLimit, T7);
        Z.rates.card.chips.forEach(t => hit('7.10 chip', t, T7)); hit('7.10 card help', Z.rates.card.help[0], T7); hit('7.10 loan help', Z.rates.loan.help[0], T7); hit('7.10 mortgage help', Z.rates.mort.help[0], T7); ok(Z.rates.card.tags[0] === 'Assumed: add yours' && Z.rates.loan.tags[0] === 'Assumed: add yours' && Z.rates.mort.tags[0] === 'Assumed: add yours', 'Rates we do not know are tagged Assumed: add yours');
        hit('7.11 typed amount note', Z.emerg.note, T7); ok(Z.emerg.auto === Z.emerg.expect && Z.emerg.typed === Z.emerg.afterSync, 'Emergency fund goal = months x essential spending; a typed amount stays'); hit('7.11 repayment flag', Z.paylow.msg, T7); ok(Z.paylow.flag && !Z.paylow.noflag && !Z.paylow.noRate, 'Repayment flag: on below interest + 1%, off above, off with no rate');
        Z.bounds.forEach(b => ok(T7.includes(b[1] + ' (Set_' + b[0] + ')') && T7.includes(b[2]), '7.12 range: ' + b[0] + ' ' + b[2]));
        ok(Z.dev.age.age === null && Z.dev.age.ph === 'Add your age' && Z.dev.age.nextDisabled && T7.includes(Z.dev.age.ph), 'No invented age: blank box, Next off'); ok(/Age\s*Not given yet/.test(Z.dev.me) && Z.dev.me.includes('Not given yet'), 'Me shows Age: Not given yet'); hit('7.13 add-age sheet', Z.dev.addAge.sub, T7); ok(Z.dev.addAge.h2 === 'Add your age first', 'Add-age gate title');
        ok(Z.dev.wi.kids[2].startsWith('wisec') && Z.dev.wi.kids[3].startsWith('wisec') && /wigrow/.test(Z.dev.wi.kids[5]) && !Z.dev.wi.growOpen && Z.dev.wi.growBelowLive && Z.dev.wi.growBelowOut && Z.dev.wi.growSummary === 'Growth and inflation settings' && T7.includes(Z.dev.wi.growSummary), 'What-if order: saving controls first, growth and inflation collapsed below');
        ok(Z.dev.exLabel.fresh.top === 'Example figures. Change them to yours.' && T2.includes(Z.dev.exLabel.fresh.top) && Z.dev.exLabel.plan.topHidden && Z.dev.exLabel.all.every(x => x[2]) && Z.dev.exLabel.all.length === 28, 'Example figures label: top label on all 28 tools without a plan, hidden with a plan, text in 2.7'); ok(Z.dev.exLabel.all.filter(x => x[3]).length >= 1 && /result/.test(T2), 'Example label also on results (where a result shows)');
        ok(Z.dev.report.on && Z.dev.report.focus === 'print' && Z.dev.report.inert.every(Boolean) && Z.dev.report.afterEsc.on === false && Z.dev.report.afterEsc.focus === 'report' && Z.dev.report.afterEsc.inert.every(x => !x) && T7.includes(Z.dev.report.label), 'Report dialog: focus to Print, background inert, Esc returns focus to the opener');
        hit('7.13 banner', Z.dev.banner.miss.replace('ℹ️', ''), T7); ok(Z.dev.banner.rough.length === 3 || Z.dev.banner.rough.length >= 1, 'Banner present');
        hit('7.1/7.13 Explorer watch-out', Z.dev.types.E[1], T7); ok(!/safety net/i.test(Z.dev.types.E[1] + Z.dev.types.C[1]), 'Personality watch-outs no longer say safety net');
        const rd = XLX.readme; ok(/^Version 2\.7/.test(rd) && T7.includes(rd) && T7.includes(XLX.budget.body) && /fullCalcOnLoad/.test(T7), 'Workbook README v2.7, Budget note block and calcPr are in 7.17');
        ok(T7.includes(XLX.how.C12) && T7.includes(XLX.how.C15) && T7.includes(XLX.how.C16) && XLX.planSheets.length === 9 && XLX.planSheets.every(x => T7.includes(x[0] + ': ' + x[1])), '7.17: Plan sheets, gate logic, 20-goal limit warning and retirement-age logic are the workbook text');
        ok(/^To see your results we need \d things?$/.test(XLX.gate[11][1]) && XLX.gate[10][1].split(', ').filter(x => /^(Retirement age|Plan until age|Inflation|Partner's retirement age)$/.test(x)).join(', ') === (XLX.gate[10][1].includes('Partner') ? Z.gate.res.rows : Z.gate.three.rows.map(r => ({ name: r }))).map(r => r.name || r).join(', ') && XLX.gate[11][1] === 'To see your results we need ' + XLX.gate[8][1] + ' things' && T7.includes(XLX.gate[11][1]), 'Workbook gate card: same heading words and the same required names, in the same order, as the app (the workbook adds the age rows)');
        ok(XLX.sheets.length >= 43 && XLX.access.row[1] === Z.access.v && XLX.access.row[5] === Z.access.by && T7.includes(XLX.access.row[8]), 'Workbook has the Pension access age standard equal to the app (value, wording) and its guidance is in 7.17');
        // §27 in the app
        ok(Z.c07.run.opp === 4786 && T7.includes('€4,786') && T7.includes(Z.c07.dep.help[0]) && Z.c07.dep.tags[0] === 'Assumed: add yours', 'C07: deposit earnings use the suggested rate (Assumed: add yours) and the opportunity cost is €4,786 on the default example');
        { const dn = await page.evaluate(() => { loadSample(); S.app = false; S.shell = true; S.pb = true; S.tab = 'plan'; S.scr = 'P4'; S.retireSet = true; S.retireAge = 65; S.infl = 0.02; S.asm = Object.assign({}, S.asm, { planEnd: 90 }); S.pRetSet = true; S.pRet = 66; lastId = null; render(); return { h: document.querySelector('#p4-3 h3').textContent, p: document.querySelector('#p4-3 h3 + p').textContent, c: document.getElementById('p4-count').textContent }; }); ok(dn.h === 'All 4 chosen' && dn.p === 'Your results have what they need. You can change any of these.' && T3.includes(dn.h) && T3.includes(dn.p), 'Step 7 when everything is chosen: "' + dn.h + '" and its line are in 3.5'); }
        ok(Z.tags.set.tags[0] === 'Set by LifeMap' && Z.tags.mine.tags[0] === 'Your choice' && Z.tags.mine.chips[0].startsWith('Back to LifeMap') && Z.tags.assumed.tags[0] === 'Assumed: add yours' && Z.tags.notChosen.tags[0] === 'Not chosen yet' && T7.includes(Z.tags.set.label) && T7.includes(Z.tags.mine.chips[0]), 'Tags: Set by LifeMap, Your choice with Back to LifeMap figure, Assumed: add yours, Not chosen yet');
        ok(T7.includes(Z.access.name) && T7.includes(Z.access.guide) && Z.access.v === 60 && Z.access.chips.length === 2 && T7.includes(Z.access.src), 'Pension access age standard (60, chips From 60 / From 50) is in 7.15');
        ok(Z.retire.min === Z.retire.age + 1 && Z.retire.max === Z.retire.planEnd - 1 && T7.includes(Z.retire.notes['40']) && T7.includes(Z.retire.notes['55']) && T7.includes(Z.retire.pnotes['40']) && T7.includes(Z.retire.pnotes['55']) && Z.retire.notes['60'] === '' && Z.early.every((e, i, a) => i === 0 || e.pct >= a[i - 1].pct), 'Free retirement age: range, calm notes under 50 and under 60, none from 60; results rise with the age');
        ok(Z.passed.text === 'Date has passed' && Z.passed.btn.length > 0 && Z.passed.btn[0] === 'Change the date' && T7.includes('"' + Z.passed.text + '"') && T7.includes(Z.passed.whenEdit) && T7.includes(Z.passed.chip[0]) && !/-\d+ yrs?/.test(Z.passed.when), '"Date has passed" and "Change the date" are in the app and in 7.15');
        ok([360, 390, 1280].every(w => Z.overlap[w].bad.length === 0 && Z.overlap[w].checked > 100), 'Number boxes: no unit overlaps a typed long value at 360, 390 and 1280 px (' + Z.overlap[390].checked + ' boxes)');
        for (const [k, re] of [['c12', /State Pension you fund yourself/], ['c12sft', /Standard Fund Threshold/], ['c12early', /Most pensions/], ['c22', /Illness Benefit is paid/], ['c20', /gap in euros/], ['c15big', /run out in the first year/], ['c15early', /Most pensions/], ['c10zero', /costs nothing/], ['c07clamp', /excluding VAT/], ['c01', /excluding VAT/], ['c02', /compounded monthly/], ['c28', /effective yearly rate/], ['c13', /same every year/]]) { const sen = String(Z.audit[k].line).split(/(?<=[.!?])\s+(?=[A-Z])/).map(x => x.trim()).filter(x => re.test(x)).join(' '); ok(sen.length > 0 && T7.includes(sen), 'Audit fix ' + k + ' sentence is in 7.16: ' + sen.slice(0, 60)); }
        ok(Z.audit.c12age.val === 'Choose a retirement age after your age to see this' && T7.includes(Z.audit.c12age.line) && Z.audit.c22cap.val === 'up to 2 years' && /Less than a year/.test(Z.audit.c15big.val), 'Audit: C12 age gate, C22 capped at 2 years, C15 less than a year'); }

      R.perCalc.push(['§23 to §25', 'Emergency fund naming, cover photo, Budget note, Liabilities, What-if, saving files, photo tiles, real videos', R.pass - pm, R.fail.length - fm]); }
    R.perCalc.push(['§15 / §16', 'Example cards, statuses, checklist, gaps in calculators; LifeMap cover, Q8, tile', R.pass - p4, R.fail.length - f4]); }
  R.errors = errors; await browser.close();
  fs.writeFileSync(path.join(__dirname, process.env.DOCX ? 'check-mut.json' : 'check.json'), JSON.stringify(R, null, 1));
  console.log('PASS', R.pass, 'FAIL', R.fail.length, 'console errors', errors.length); R.fail.slice(0, 5000).forEach(f => console.log(' -', f));
})();
