import re
s=open('b-body.js').read()
def rp(a,b,n=1):
    global s
    assert s.count(a)==n,(s.count(a),a[:80]); s=s.replace(a,b)
# 1 purpose page
rp("['Built from', 'Prototype commit fc0d2ae (journey-spec §14 to §20: example cards, LifeMap name and cover, Irish-tone Q8, Explore order, emoji accessibility, Ask hidden in onboarding, suggested market rates, and the §19 feedback items: lists, complete-on-save, Settings, Emergency fund months, goal order, and the §20 copy pass) and the workbook committed with it (sheets Settings and Your lists), branch claude/simplify-customer-journey-zqxep3. File names keep \"LifeGoals\" for now (§16).']",
"['Built from', 'The prototype at the head of branch claude/simplify-customer-journey-zqxep3 (journey-spec §14 to §25: example cards, LifeMap name and cover photo, Irish-tone Q8, Explore order, emoji accessibility, Ask hidden in onboarding, suggested market rates, the §19 lists, Settings and Emergency fund months, the §20 copy pass, §21 Experts boxes and Focus tiles, §22 skippable Step 7, §23 Emergency fund naming and Budget 2027 note, §24 Liabilities, What-if and saving files, §25 photos and two real videos) and the workbook committed with it (sheets Settings and Your lists). File names keep \"LifeGoals\" for now (§16).'], ['Files to keep together', MEDIA_LIST]")
rp("const XL = require('./xl.json');","const XL = require('./xl.json');\nconst MEDIA_LIST = (() => { const R = '/home/user/lifegoals-prototype/', mb = f => (fs.statSync(R + f).size / 1e6).toFixed(1) + ' MB', kb = f => Math.round(fs.statSync(R + f).size / 1024) + ' KB';\n  return 'LifeGoals-Customer-Journey-Prototype.html (one file, ' + mb('LifeGoals-Customer-Journey-Prototype.html') + ': the cover photo and the five Focus-tile photos are embedded as data URIs) and the folder media/ beside it (' + mb('media/auto-enrolment-explained.mp4') + ' auto-enrolment-explained.mp4 and ' + mb('media/retirement-plan-how-it-works.mp4') + ' retirement-plan-how-it-works.mp4, which are NOT embedded and play only when media/ is next to the page or published with the page; and the five photos again as JPEG files, used as video posters: house-for-sale.jpg ' + kb('media/house-for-sale.jpg') + ', retired-reading.jpg ' + kb('media/retired-reading.jpg') + ', money-plant.jpg ' + kb('media/money-plant.jpg') + ', team-with-charts.jpg ' + kb('media/team-with-charts.jpg') + ', car-and-calculator.jpg ' + kb('media/car-and-calculator.jpg') + '). Without media/ every page still works; the two videos then show the message \"This video can\\'t play right now\" and their posters are missing. LifeGoals-Calculators.xlsx and this document complete the set.'; })();",1) if "const XL = require('./xl.json');" in s else None
open('b-body.js','w').write(s)
s=open('b-body.js').read()
# bullets on purpose page
rp("  B('**Goals** (section 6): one Emergency fund months value everywhere, and the \"Which goal first?\" order.'),","  B('**Goals** (section 6): one Emergency fund months value everywhere, and the \"Which goal first?\" order.'),\n  B('**Naming, results screens and saving files** (section 7): \"Emergency fund\" everywhere (and the Lifecast wording that stays), the What-if card, saving the plan and other files through the downloads capability, and the Budget 2027 note (journey-spec §23 and §24). Photos on the Focus tiles (2.2) and the two real videos (2.6) are journey-spec §25.'),")
# 2.2
rp("Each tile is a drawn scene (an SVG illustration, not a photo and not AI-generated) with a small, slow looping animation.","Five tiles show Pooja\\'s photos (the files in media/, embedded as data URIs so the HTML stays one file); Protection has no matching photo and keeps its drawn shield (an SVG illustration, not a photo and not AI-generated). Each photo is cropped with its own object-position and moves with a very slow zoom; the shield keeps its small looping animation.")
rp("two per row (journey-spec §21).","two per row (journey-spec §21, §25).")
rp("measured at 9:1 or better on the worst pixel","measured at 7:1 or better on the worst pixel")
rp(", each a data-URI SVG. To use a photo instead, set that one property to url(\"photo.jpg\") and set --fx:none on the tile to hide the animated overlay. Nothing else changes.", ", each a data-URI (JPEG for the five photos, SVG for the Protection shield). To change a picture, set that one property to another url(...); a photo tile already hides the drawn overlay (--fx:none) and has its own --pos. Nothing else changes.")
rp("'Scene and animation'","'Picture and animation'")
a=s.index("ART = { Mortgages:"); b=s.index("};",a)+2
s=s[:a]+"PK = { Mortgages: 'mortgage', Pensions: 'pension', Protection: 'protection', Investing: 'investing', Savings: 'savings', 'Everyday money': 'everyday' }, PF = { mortgage: 'house-for-sale.jpg', pension: 'retired-reading.jpg', investing: 'team-with-charts.jpg', savings: 'money-plant.jpg', everyday: 'car-and-calculator.jpg' }, PP = require('./s23.json').tiles.pos, ART = Object.fromEntries(Object.entries(PK).map(([n, k]) => [n, PF[k] ? 'Photo ' + PF[k] + ', object-position ' + PP[k] + ', very slow zoom (24 s, alternate)' : 'Drawn shield with a tick (SVG), a soft shine across it']));"+s[b:]
rp("imgGrid([{ file: 'T-tiles-390.png', caption: 'Focus on one area at 390 px: six square tiles, two per row' }","imgGrid([{ file: 'T-tiles-photos-390.png', caption: 'Focus on one area at 390 px: photos on five tiles, drawn shield on Protection' }")
# 2.6 videos before section 3
VID = r'''push(H2('2.6 Videos: two real videos (journey-spec §25)'));
{ const V = require('./s23.json').videos, PL = V.player, real = V.list.filter(v => v.src);
  push(P('Two real MP4 videos (H.264 video, AAC audio) join the other video places. They are loaded from the folder media/ by relative path and are **never embedded** in the HTML. The six placeholder videos from Lifecast stay. Both real videos lead the Pensions lists: the Home strip "Watch · picked for you" (before a plan), the same strip on Explore, the "All videos" library (listed first) and the Pensions filter and Pensions topic page.', { size: 18 }));
  push(table([2200, 1100, 700, 2400, 1900, W - 8300], ['Title (verbatim)', 'Topic', 'Length', 'File (relative path)', 'Poster', 'Matching tool · expert'], real.map(v => [v.t, v.kind, v.dur, v.src, v.poster, v.tool + ' (pre-filled) · Talk to a pension & retirement expert']), { size: 15 }));
  push(P('Order in the library: ' + V.lib.map(t => '"' + t + '"').join(', ') + '. Home strip before a plan: ' + V.home.map(t => '"' + t + '"').join(', ') + '.', { size: 17 }));
  push(table([2300, W - 2300], ['Part', 'Specification (verbatim)'], [
    ['Video card', 'Thumbnail with the poster photo under a dark scrim, ▶, the length (' + real.map(v => v.dur).join(' and ') + '), the title and the line "Pensions explainer". The photos are the Savings and Pensions tile photos (money-plant, retired-reading).'],
    ['Player', '<video id="vid-el" controls preload="' + PL.attrs.preload + '" playsinline poster="' + PL.attrs.poster + '" src="' + PL.attrs.src + '" aria-label="{title}" aria-describedby="vid-cap">. Controls: ' + (PL.attrs.controls ? 'native controls' : 'none') + ' (play/pause, seek, volume, full screen).'],
    ['Keyboard', 'The browser\'s own controls are used, so Tab focuses the video, Space plays and pauses, the arrow keys seek. A video card is a button: Enter opens it.'],
    ['Under the player', 'Title (h2), "' + PL.meta + '", the matching tool button "' + PL.tool.find(x => /Try (?!again)/.test(x)) + '" (the calculator opens pre-filled from the customer\'s figures), then ' + PL.expert.map(x => '"' + x + '"').join(' and ') + ' and "Save for later"; then the line "' + PL.caps + '"'],
    ['Captions', '**Captions not available yet.** There are no captions or transcript for these two files and none is invented here. The placeholder videos keep their mock captions and transcript.'],
    ['If it can\'t load or play', 'The video is hidden and a panel replaces the blank player (role="alert"): "' + PL.fail + '" with the button "Try again", which reloads the file.'],
    ['Publishing', 'The Artifact is published with files mapping media/* so the videos play on the shared link; the standalone HTML needs the media folder beside it (see the file list on the first page).']], { size: 15 }));
  push(P('**What was and was not tested.** The browser used for the checks has no H.264 decoder, so real playback could not be tested. Verified instead: the video element and its attributes, the relative src, the poster, native controls, keyboard focus, the failure message (shown here because the browser cannot decode the file), "Try again", and the lists and order. Playback, sound, seeking and full screen must be checked on a real phone and on the published link.', { size: 17 }));
  push(imgGrid([{ file: 'T-video-home.png', caption: 'Home: Watch · picked for you' }, { file: 'T-video-library.png', caption: 'Explore: All videos' }, { file: 'T-video-player-fallback.png', caption: 'Player with the failure message (no H.264 in the test browser)' }], 3, 1100)); }
'''
rp("push(H1('3. Rules and Your assumptions'));",VID+"push(H1('3. Rules and Your assumptions'));")
# 5.1
i=s.index("push(H2('5.1 Cover (D0)'));"); j=s.index("push(H2('5.2 D1")
COV = r'''push(H2('5.1 Cover (D0)'));
const CV = EX.cover;
{ const C3 = require('./s23.json').cover;
push(table([2300, W - 2300], ['Part', 'Specification (verbatim)'], [['Photo', 'Pooja\'s photo: a hand holding a magnifying glass over a map, with a mountain valley behind (journey-spec §23). It is one CSS custom property, --cover-photo, on :root, a JPEG data URI (' + C3.css.kb + ' KB). Position: ' + C3.css.photoPos + ' (the magnifier and the map stay in view), cover.'], ['Shade', 'Navy gradient over the photo, clear at the top and dark at the bottom: .cover-shade{' + cssRule('.cover-shade') + '}. Short screens start it higher. A navy band at the very top (.cover-shade::before{' + cssRule('.cover-shade::before') + '}) keeps the wordmark legible.'], ['Logo', CV.logo + ' (mark + white wordmark with a soft shadow)'], ['Top right', '"' + CV.invite + '" (white pill, navy text; opens "Enter your invite code")'], ['Headline (h2, focused on arrival)', CV.h], ['Line', CV.line], ['Button', CV.btn + ' (gold, full width; goes to D1)'], ['Under the button', CV.under], ['Link', '"' + CV.why + '" (white; opens "Why we ask")'], ['Nothing else', 'No trust line and no "Guidance, not advice." on the cover (that stays wherever results are shown).']], { size: 15 }));
push(imgGrid([{ file: 'B-cover.png', caption: '390 × 844' }, { file: 'B-cover-360x640.png', caption: '360 × 640' }, { file: 'B-cover-844x390.png', caption: '844 × 390 (landscape)' }, { file: 'B-cover-1280x800.png', caption: '1280 × 800 (phone frame)' }], 4, 700));
const SZ = Object.keys(C3.sizes), NM = C3.sizes[SZ[0]].map(x => x[0]);
push(table([1700].concat(NM.map(() => Math.floor((W - 1700) / NM.length))), ['Viewport (px)'].concat(NM), SZ.map(z => [z.replace('x', ' × ')].concat(C3.sizes[z].map(x => x[1] + ':1'))), { size: 15 }));
push(P('Contrast: each line of text measured against the lightest pixel behind it (text hidden, screenshot sampled). The rule is 4.5:1; every line passes at all four sizes. The invite pill has its own white background.', { size: 16, color: MUTED }));
push(P('**How sharp is it?** The photo is 912 × 502 pixels (55 KB). Full-bleed on a 390 × 844 phone it is scaled up about 1.7 times (about 5 times on a 3× screen), so it looks soft: fine as a dark-washed backdrop under the text, but the map lines and magnifier edge are visibly low resolution. A larger portrait original (at least 1800 pixels tall; 2400 × 3200 is better) is advisable before launch. Swap it into --cover-photo; nothing else changes.', { size: 17 })); }
'''
s=s[:i]+COV+s[j:]
# 4.8.2 liabilities
rp("push(H3('4.8.2 Liabilities (credit cards and other loans)'));","""push(H3('4.8.2 Liabilities: mortgage first, then credit cards and other loans'));
{ const Q = require('./s23.json').liab, ST = Q.states;
  push(P('Journey-spec §24.1. The order is **Mortgage, Credit cards, Other loans**. The Mortgage block is always visible, even for a customer who rents or owns outright. It opens with the question "' + Q.sample.mort[0][0] + '" (' + Q.sample.q.join(' / ') + '). The question stays in step with "Your home": Yes sets Your home to Own with mortgage, No sets Own outright, and changing Your home changes the answer. If the customer rents or lives with family and says Yes, Your home is left as they said it and the mortgage is treated as one on another property.', { size: 18 }));
  push(table([2300, W - 2300], ['Part', 'Copy and behaviour (verbatim)'], [
    ['Mortgage card heading', '🏠 Mortgage · "The mortgage on the home you live in comes first." · renters who say Yes also see: "' + Q.rent.note + '"'],
    ['Fields when Yes (own with mortgage)', Q.sample.mort.slice(1).map(f => '"' + f[0] + '" (' + (f[1] === 'eur' ? '€ amount' : f[1] === 'pct' ? '% (decimal)' : 'number') + (f[2] ? ', optional' : '') + (f[3] ? '; hint: "' + f[3] + '"' : '') + ')').join(' · ')],
    ['Upload', 'Link "📄 Upload your mortgage statement (optional)" (opens the Liabilities document reader). The statement fills balance, repayment, years left and the rate.'],
    ['Add on another property', 'Ghost button "' + Q.sample.add + '". It adds an item "' + Q.sample.one.charAt(0).toUpperCase() + Q.sample.one.slice(1) + ' 1" with: ' + Q.sample.fields.map(f => '"' + f[0] + '"' + (f[2] ? ' (optional)' : '')).join(', ') + ' and the link "📄 ' + Q.sample.up + '". With items, the card is headed "🏠 ' + Q.sample.title + '".'],
    ['In the plan', 'Counted as debt: balance, repayment and rate are added to "other loans" (rate: the item\\'s own, else the mortgage rate the customer chose). It is never the main-home mortgage, so the mortgage-free goal ignores it. A blank item counts as €0. If a rate is missing, the plan needs the mortgage rate choice ("Choose your mortgage rate to see this").'],
    ['Answer by home', Object.keys(ST).map(h => h + ': question shows ' + (ST[h].yn || 'no answer yet') + '; main-mortgage fields ' + (ST[h].main ? 'shown' : 'hidden') + '; add button ' + (ST[h].add ? 'shown' : 'hidden')).join('. ') + '.'],
    ['Example cards (§15)', '"Not sure? See an example" on the question and on each new field (mortgage rate; the four other-property fields use an imagined buy-to-let, never the sample customers\\' results). See 4.4.']], { size: 15 }));
  push(imgGrid([{ file: 'S24-liabilities.png', caption: 'Liabilities for a renter who has a mortgage on another property' }], 1, 1000)); }
push(P('Credit cards and other loans:', { bold: true, size: 18 }));""")
# section 7 before the calculators
rp("for (const c of data.calcs) { const S = SPEC[c.id], cat = CATN[c.cat],","@@SEC7@@\nfor (const c of data.calcs) { const S = SPEC[c.id], cat = CATN[c.cat],")
SEC7 = r'''{ const Q = require('./s23.json'), N = Q.naming, W2 = Q.wi, SV = Q.save;
push(H1('7. Naming, results screens and saving files'));
push(H2('7.1 Naming: always "Emergency fund" (journey-spec §23)'));
push(P('The emergency fund is called **Emergency fund** everywhere a customer sees it: goal, assumption, gate message, group name, calculator, Settings and the workbook. Cell names in the workbook (for example Set_safetyMonths, Safety_Goal_Years) are unchanged.', { size: 18 }));
push(table([2600, W - 2600], ['Where', 'Now (verbatim)'], [['Gate message', N.gate], ['Assumption label (Your assumptions, Settings)', N.label], ['Short name in messages', N.n], ['Group in Your assumptions', N.group], ['What your plan assumes (row · tag · value)', N.row.join(' · ')], ['Me menu line', N.me], ['C11 question', N.calcQ], ['C11 result line (no gap)', N.calcLine + ' {Months_Wanted} «month|months». Great foundation.'], ['C11 result rows', N.rows.join(' · ')], ['Money-profile text (risk read)', N.mis[0] + ' ' + N.mis[1]], ['Workbook', 'C11 labels, the years-to-build gate and the prompt titles say Emergency fund (data validation prompt titles are shortened to 32 characters).']], { size: 15 }));
push(P('**Kept verbatim, for Pooja to decide** (Lifecast Discover wording, money-term tags and the D1 chip):', { size: 18, bold: true }));
['D1 chip: "Building a safety net for emergencies" (journey-spec §16: the chips stay unchanged).', 'Discover Q7 answer tag "No safety net" (answer "I\'m not sure") and its meaning "Nothing is set aside for surprises yet."', 'Understand Me answer tag "Strong safety net" (answer "6 months or more") and its meaning "6 months or more of savings to fall back on."', 'Money personality "watch out" line for the Contented type: "Jumping in before your safety net is in place."', 'Money terms "Cushion" ("money for surprises") and the tag "Thin buffer" with the meaning "Your safety money is also meant for other things."'].forEach(t => push(B(t)));
push(H2('7.2 The What if…? card (journey-spec §24.2)'));
push(P('Before, the card showed "My monthly saving" and, a few lines later, "Monthly amount +€725", so raising the second changed nothing visible in the first. The card now has two separate sections and a live line that adds them up.', { size: 18 }));
push(table([2300, W - 2300], ['Part', 'Copy and behaviour (verbatim)'], [
  ['Order', 'Growth assumptions · inflation choice · "Your assumptions" link · section "' + W2.sections[0] + '" · section "' + W2.head + '" · the result line for the chosen goal (e.g. "Travel goes from 28% to 58%") · buttons "' + W2.btns.join('" · "') + '".'],
  ['Section 1: ' + W2.sections[0], '"' + W2.sub[0] + '" · label "' + W2.labels[0] + '" with − / + (€25 steps) and "a month" · the line about where the figure comes from and the spare money, with "Use my answer" · the 💡 nudge ("You may be able to save more than you said…") stays here. The base saving can still be edited, and only here.'],
  ['Section 2: ' + W2.head, '"' + W2.sub[1] + '" · "' + W2.put + '" goal chips · "' + W2.labels.find(x => /^Extra/.test(x)) + '" (−€500 to +€1,000 a month, − / + and a slider) · "One-off amount" with "' + W2.once + '".'],
  ['Live line (under both)', 'role="status". No extra: "' + W2.lines['0'].t + '". With an extra: "' + W2.lines['40'].t + '". Template: With this what-if you\'d save {base + extra} a month ({base} + {extra} extra) · spare money about {spare}. A negative extra reads "({base} − {less} less)"; the total never goes below €0.'],
  ['Warning', 'When the total is more than the spare money the line turns amber and adds "' + W2.lines['725'].t.split('⚠️ ')[1] + '" Example: "' + W2.lines['725'].t + '"'],
  ['Unchanged', '"Save as my preferred plan" and "Back to my plan" behave as before; the goal list, the result line and the charts update live.']], { size: 15 }));
push(P('Styles: .wisec{' + cssRule('.wisec') + '} .wi-live{' + cssRule('.wi-live') + '} .wi-live.over{' + cssRule('.wi-live.over') + '}', { size: 15 }));
push(imgGrid([{ file: 'S24-whatif.png', caption: 'What if…? with an extra of €725 (sample customer: €62 saved, €125 spare)' }], 1, 1000));
push(H2('7.3 Saving the plan and other files (journey-spec §24.3)'));
push(P('Inside the shared page the viewer blocks printing and downloads, so files go through the **downloads** capability: claude.use("downloads").save({filename, data}). Allowed types: gif png jpg jpeg webp mp4 webm txt json md docx pptx epub csv ttf html svg pdf xlsx zip (so ".ics" is not allowed). The Artifact is published with capabilities {downloads: true}.', { size: 18 }));
push(table([2300, W - 2300], ['Situation', 'What happens (verbatim messages)'], [
  ['Button', '"' + SV.pdf.button.replace(/^\S+\s/, '') + '" in the top bar of the plan report (the Results button "⬇ Download my plan" opens the report). A status line next to it (role="status") and a toast show every message.'],
  ['1. Downloads available', 'Message "Preparing your PDF…". On this click only, the libraries jsPDF 2.5.1 and html2canvas 1.4.1 are loaded from cdnjs.cloudflare.com (' + SV.consts.jspdf + ' and ' + SV.consts.h2c + '; 20 s limit each). The report is drawn in the page, paginated on A4 (' + SV.consts.pdf.mx + ' mm side margins, ' + SV.consts.pdf.my + ' mm top and bottom for the header and footer): header "LifeMap" and the plan name; footer "Preliminary guidance, not financial advice. Illustrative, not guaranteed." and "Page n of N". Sections are kept whole (up to 10% too tall is scaled to fit; longer ones split between paragraphs or table rows, and the year-by-year table repeats its header row); a heading stays with what follows. Then save({filename: "LifeMap-plan.pdf"}). Success: "' + SV.pdf.msg + '"'],
  ['2. The PDF fails (for example the library is blocked)', 'The self-contained report is saved as LifeMap-plan.html instead. Message: "' + SV.html.msg + '" If that fails too: "We couldn\'t save your plan here. Please try again, or open this page in your browser."'],
  ['3. No downloads (the standalone file opened locally)', 'window.print() opens the browser\'s print window. Message: "' + SV.print.msg + '" If printing is blocked: "Printing is blocked here. Open this page in your browser to save the PDF."'],
  ['Adviser meeting', 'Booked screen button: "' + SV.meeting.withDl.trim() + '" when downloads exists; it saves ' + SV.meeting.file.join(', ') + ' (adviser, time, how, length, and a note to add it to the calendar by hand). Opened locally it reads "' + SV.meeting.local.trim() + '" and downloads the .ics file as before. I chose a .txt rather than hiding the button, because the customer still needs the details and the file works everywhere.']], { size: 15 }));
push(P('**How this was tested, and its limits.** In Playwright, with window.claude.use("downloads") replaced by a mock that records the save() call, and again with it absent. cdnjs is blocked in the build sandbox, so the same library builds (jsPDF 2.5.1, html2canvas 1.4.1, from npm) were served locally in its place: the real PDF was rendered (A4, ' + SV.pdf.saves[0].size + ' bytes, several pages, every page with its header and footer) and the library-blocked case saved the .html. Not tested: the real Claude viewer. The exact data type save() accepts is not documented here: the code passes a Blob and, if that is refused, an ArrayBuffer.', { size: 17 }));
push(H2('7.4 Budget 2027 note (journey-spec §23)'));
push(P('Nothing from Budget 2027 is used in any calculation until it is final and official, and no unconfirmed figure is named. Where results depend on the rules, customers see: "' + Q.budget + '" It appears in "What your plan assumes" (under the rules version line), in the results footnote (above "Guidance, not advice.") and in the plan report (section 9). Items in the rules register still marked "verify before release" are listed in docs/pre-release-verify.md (item, value, source, what to check). Customers always see the source and date next to each suggested figure and can type their own.', { size: 18 })); }
'''
rp("@@SEC7@@",SEC7)
# appendix B
rp("  '**§16 · Cover photo**: the cover uses a drawn placeholder until the licensed photo is supplied; swap it in --cover-photo and re-check the text contrast (at least 4.5:1).' ]","  '**Cover photo resolution (§23)**: the supplied photo is 912 × 502 and looks soft full-bleed on a phone; a larger portrait original is advisable (5.1).',\n  '**Emergency fund naming (§23)**: the Lifecast wording that still says \"safety net\" is listed in 7.1 for Pooja to decide.',\n  '**Saving files (§24.3)**: tested with a mocked downloads capability and local copies of the libraries; not tested in the real viewer. The data type save() accepts is to be confirmed (7.3).',\n  '**Other-property mortgages (§24.1)**: folded into \"other loans\" in the projection, so a line such as \"Loans of €X clear in about N months\" also counts them.',\n  '**Videos (§25)**: no captions or transcript yet; real playback not tested here (no H.264 decoder in the test browser); the media folder must travel with the HTML (first page).' ]")
rp("'**Budget 2027 (6 October 2026)**: not yet applied.","'**Budget 2027 (6 October 2026)**: not yet applied; customers see the note in 7.4 and the items to verify are in docs/pre-release-verify.md.")
open('b-body.js','w').write(s)
