s=open('b-body.js').read()
def rp(a,b,n=1):
    global s
    assert s.count(a)==n,(s.count(a),a[:90]); s=s.replace(a,b)
def rline(startswith, new):
    """replace the whole source line that starts with `startswith`"""
    global s
    L=s.split('\n'); idx=[i for i,l in enumerate(L) if l.startswith(startswith)]
    assert len(idx)==1,(len(idx),startswith[:60]); L[idx[0]]=new; s='\n'.join(L)
# first page
rp("(journey-spec §14 to §26 and the fix rounds of 7 October (planner, developer):","(journey-spec §14 to §27, the audit fixes and the fix rounds of 7 and 8 October (planner, developer):")
rp("§26 What-if order and labelled example figures, and the planner and developer fix rounds)","§26 What-if order and labelled example figures, §27 the simpler journey with only four required choices, and the planner and developer fix rounds)")
rp("market rate (never pre-filled; chip \"Use the suggested rate (X) · source\" from the single Settings block; the customer can always type their own); official range (\"Usually between X and Y (source)\", only where an official source exists); personal choice (blank, \"Generally the standard is X (source). Choose what you want to use.\" and a \"Use the standard (X)\" chip)'","market rate (suggested rate chip \"Use the suggested rate (X) · source\" from the single Settings block; in the plan the suggested rate is used and tagged \"Assumed: add yours\"; the customer can always type their own); official range (\"Usually between X and Y (source)\", only where an official source exists); LifeMap standard (§27: applied from the start, tagged \"Set by LifeMap\", changeable, then \"Your choice\" with a \"Back to LifeMap\\'s figure\" chip); only four personal choices are required and block results (retirement age, plan-until age, inflation, a working partner\\'s retirement age)'")
# calculators default state
rp("'The calculator opened from Explore before a plan with nothing chosen yet (journey-spec §14): assumption inputs are blank with the tag \"Not chosen yet\" (market rates: blank with a suggested-rate chip, never pre-filled; optional ones are never required) and the result card reads \"Choose your … to see this\". \"Choices made\" is the same screen after the standards are used and the example values typed into the remaining blanks; most result copy is specified from that state.'","'The calculator opened from Explore before a plan (journey-spec §14, §27). Inputs that have a LifeMap standard (growth, pay rises, emergency fund months and the like) start at the standard with the tag \"Set by LifeMap\". A market rate with no standard (mortgage rate, fund charges, card and loan APR) stays blank with a suggested-rate chip and the tag \"Not chosen yet\", and the result card reads \"Choose your … to see this\" until it is chosen: a calculator does not guess a rate for the customer. Own figures missing from Your finances still read \"Add … to see this\". \"Choices made\" is the same screen after the suggested rates are chosen and the example values typed into the remaining blanks; most result copy is specified from that state.'")
rp(", \"Not now\", \"Use the standard for all of these\"'",", \"Not now\"'")
rp("['Blank input', 'Label + tag \"Not chosen yet\" for a §14 choice, or","['Blank input', 'Label + tag \"Not chosen yet\" for a market rate or a required choice, or")
rp("['Standard chip', '\"Use the standard ({X})\" (.chip.sm): one tap fills the standard and counts as the customer\\'s choice. Only for personal choices; market rates have the suggested-rate chip instead; official-range values and retirement ages have neither.']","['Standard chip', '\"Back to LifeMap\\'s figure ({X})\" (.chip.sm), shown only after the customer has changed a LifeMap standard (§27): one tap returns to the standard and the tag goes back to \"Set by LifeMap\". There is no \"Use the standard\" tap any more because standards are applied from the start. Market rates have the suggested-rate chip instead; official-range values and retirement ages have neither.']")
rp("; \"Use the standard for all of these\" when a personal choice is missing; note \"These are your plan-wide choices: changing one here changes it everywhere.\"']","; note \"These are your plan-wide choices: changing one here changes it everywhere.\"']")
rp("; \"Use the standard for all of these\" also sets 2%.'],","; the \"Add to my plan\" message is the same.'],")
rp("[\"Value-type tags\", ","[\"Value-type tags\", ",0) if False else None
rp("'Value-type tags', '\"Not chosen yet\" (.tag.look), \"Your choice\" (.tag.doc),","'Value-type tags', '\"Set by LifeMap\" (.tag.set: a standard applied from the start, §27), \"Assumed: add yours\" (.tag.look: a suggested or planning rate in use because the customer has not given theirs; counted in \"N details missing\"), \"Not chosen yet\" (.tag.look: only the required choices and calculator market rates), \"Your choice\" (.tag.doc),")
# Your assumptions
rline("  ['3. Personal choice',", "  ['3. LifeMap standard (§27)', 'Applied from the start; nothing to tap. Every figure that is the same for everyone is used straight away and listed.', '\"LifeMap uses {X} ({wording}). Change it if you want to use your own.\" Tag \"Set by LifeMap\". When the customer changes it: tag \"' + M.T_MINE + '\" and the chip \"Back to LifeMap\\'s figure ({X})\".', 'Pay rises, cash, investment and pension growth, tax bands and State Pension in future, how the pension is drawn, pension access age, lump-sum share, share you pay, emergency fund months, years kept as cash, spare-money shares, retirement target multiple and spending share, life-cover share and years, budget split, rent-vs-buy figures, risk-and-return illustration figures'],\n  ['3b. Required personal choice', 'Never filled in for the customer. Blank until chosen: it is one of the four that block results.', 'Retirement age, plan-until age (life expectancy), inflation, and a working partner\\'s retirement age. Tag \"Not chosen yet\", then \"' + M.T_MINE + '\".', 'Retirement age, plan-until age, inflation, partner\\'s retirement age'],")
rline("  ['Chosen individually',", "  ['Required choices', 'Retirement age, plan-until age, inflation and the partner\\'s retirement age are never defaulted and are the only things that block results (§27.4).', 'Retirement age: \"' + M.RETIRE_HELP + ' Choose the age you want to plan for, any age from your age + 1 to your plan-until age − 1.\" Plan until age: \"' + M.ASM.planEnd.help + '\"', '—'],")
rline("push(P('\"Use the standard for all of these\" (ghost small button)", "push(P('There is no \"Use the standard for all of these\" button any more (journey-spec §27.5): LifeMap sets every figure that is the same for everyone from the start, shows it as \"Set by LifeMap\" with its wording and source, and the customer may change any of them. Nothing is silent: each applied figure is listed in Your assumptions, in \"What your plan assumes\" and in the Step 7 list \"What we\\'ve set for you\". Until a required choice is made, results show the gate card of 7.5. The sample customer has every plan choice made.', { size: 18 }));")
rline("push(table([2300, W - 2300], ['Part', 'Copy and behaviour (verbatim)'], [['Top card (while personal choices are missing)'", "push(table([2300, W - 2300], ['Part', 'Copy and behaviour (verbatim)'], [['Top card', '\"' + TOP.b + '\" (or \"Everything your results need is chosen\") · \"' + TOP.p + '\"'], ['Cards', M.ASM_GRP.map(g => '\"' + g[1] + '\"').join(', ') + ', then \"' + M.T_GOV + '\" (collapsible details; \"Prices & growth\" opens first; \"Plan length\" opens when a required choice is jumped to)'], ['Prices & growth extras', 'The inflation chips (1.8) and \"Growth assumptions set\" (Standard / Cautious). Choosing a set fills pay rises, cash, investment and pension growth with its rates.'], ['Each input', 'Label + tag (\"Set by LifeMap\" / \"Your choice\" / \"Assumed: add yours\" / \"Not chosen yet\" for the four required choices); value box or chips; \"Back to LifeMap\\'s figure ({X})\" once changed; one guidance line (verbatim below).'], ['Plan length card', 'Retirement age (box, prefix \"age\", whole numbers, any age from your age + 1 to your plan-until age − 1, with a calm note below 60: see 7.15): \"' + M.RETIRE_HELP + ' Choose the age you want to plan for.\" Plan until age, and the partner\\'s retirement age when their income is counted.'], ['Budget check', 'When all three budget shares are chosen and do not total 100%: \"Your budget split adds up to {n}%. It should total 100%.\"'], ['Set by Government card', data.asm.law.dom.groups[0].law.rows.length + ' rows (below) and \"' + data.asm.law.dom.groups[0].law.note + '\"']], { size: 15 }));")
# 3.5 Step 7
rp("is skippable (journey-spec §22). Nothing blocks except","is short and skippable (journey-spec §22, §27.8). Nothing blocks except")
rp("From the top: a card \"' + A.h3[0] + '\", a card \"' + A.h3[1] + '\", then the list of details worth a second look, then the buttons.'","From the top: a card \"' + A.h3[0] + '\", a collapsed \"' + A.summary + '\", then the list of details worth a second look, then the buttons.'")
rline("    ['Card 1: ' + A.h3[0],", "    ['Card 1: ' + A.h3[0], '\"' + A.p3 + '\" · counter \"' + A.count + '\" (role=status; counts up to the number of choices) · Retirement age · Plan until age (life expectancy) · the inflation chips (see 1.8) · Your partner\\'s retirement age (only when a partner\\'s income is counted). Each starts blank with the tag \"Not chosen yet\" and its own guidance line (e.g. \"' + A.fields[0].help + '\"), and reads \"Your choice\" once chosen. These are never filled in for the customer (journey-spec §14, §27).'],")
rline("    ['Card 2: ' + A.h3[1],", "    ['Collapsed: ' + A.summary, '\"' + A.restP + '\" Inside: every other Your-assumptions figure with its tag and wording; any one can be changed. Nothing in it blocks the results.'],")
rline("    ['After \"Skip\"',", "    ['After \"Skip\"', 'Results open with the banner in 3.5.1. Because only the four required choices block results and they are made, nothing else is asked: every other figure is the LifeMap standard or a labelled assumption (journey-spec §27). If a required choice were missing, the gate card of 7.5 would show instead.']], { size: 15 }));")
rp("Missing figures count as €0. Both buttons open My Plan and its results.'","Missing figures count as €0. Both buttons open My Plan and its results.'")
# 3.7
rp("A customer can still change any standard for their own plan; \"Use the standard (X)\" is the one-tap chip and counts as their own choice, so journey-spec §14 still holds.","LifeMap applies every standard from the start (tag \"Set by LifeMap\", journey-spec §27.5); a customer can change any of them for their own plan, which then reads \"Your choice\" with a \"Back to LifeMap\\'s figure ({X})\" chip.")
rp("**Standards** (types 3): blank until chosen; guidance \"Generally the standard is {X} ({wording}). Choose what you want to use.\" and the chip \"Use the standard ({X})\". They are never pre-filled and the chip is their own explicit choice.","**Standards** (types 3): applied from the start, tag \"Set by LifeMap\"; guidance \"LifeMap uses {X} ({wording}). Change it if you want to use your own.\"; after a change the tag \"Your choice\" and the chip \"Back to LifeMap\\'s figure ({X})\".")
# 6.1 rows
rp("'Blank at first: the box is empty with the tag \"' + MO.calcBlank.tag + '\" and the gate reads \"' + MO.calcBlank.gate.replace(/\\n/g, ' · ') + '\". Typing ' + MO.calcSet.box","'Starts at the standard: the box shows ' + MO.calcBlank.box + ' with the tag \"' + MO.calcBlank.tag + '\" and the result shows straight away. Typing ' + MO.calcSet.box")
rp("'Before any choice: tag \"' + MO.p4Before.field.tag + '\", empty box, chip \"' + MO.p4Before.field.chip + '\". After typing 3 in the calculator: tag \"' + MO.p4AfterCalc.field.tag + '\", box ' + MO.p4AfterCalc.field.box + ', no chip. After 4 in the goal: tag \"' + MO.p4AfterGoal.field.tag + '\", box ' + MO.p4AfterGoal.field.box + ', chip \"' + MO.p4AfterGoal.field.chip + '\" (the chip appears because the value differs from the standard).'","'Before any choice: tag \"' + MO.p4Before.field.tag + '\", box ' + MO.p4Before.field.box + ', no chip. After typing 3 in the calculator: tag \"' + MO.p4AfterCalc.field.tag + '\", box ' + MO.p4AfterCalc.field.box + '. After 4 in the goal: tag \"' + MO.p4AfterGoal.field.tag + '\", box ' + MO.p4AfterGoal.field.box + ', chip \"' + MO.p4AfterGoal.field.chip + '\" (the chip appears because the value now differs from the standard).'")
rp("(Your assumptions, \"' + M.ASM.safetyMonths.l + '\"; Settings standard 6 months, 3 with two secure incomes)","(Your assumptions, \"' + M.ASM.safetyMonths.l + '\"; LifeMap standard 6 months, 3 with two secure incomes, applied from the start)")
open('b-body.js','w').write(s)
