// shared by capture-s26.js (screenshots on) and check.js (screenshots off): live strings for journey-spec §23-§27, the audit fixes and the fix rounds
const SHOTS = __dirname + '/shots/';
module.exports = async function collect(page, shots) { const out = {}; const ev = (f, a) => page.evaluate(f, a);
  const tall = async (w, h) => { await page.setViewportSize({ width: w, height: h }); await page.waitForTimeout(250); };
  const phone = async f => { if (!shots) return; await ev(() => { document.getElementById('toast').innerHTML = ''; document.activeElement && document.activeElement.blur(); }); await page.waitForTimeout(200); await page.locator('#phone').screenshot({ path: SHOTS + f }); };
  await tall(390, 1500);
  // 1. §27.7 the gate card: exact names, a button each, same on Home, Results, Report and the timeline strip
  out.gate = await ev(() => { const T = e => e ? e.textContent.replace(/\s+/g, ' ').trim() : null; const o = {};
    const setup = () => { loadSample(); S.asm = {}; S.retireSet = false; S.infl = null; S.pRetSet = false; S.app = true; S.shell = true; S.tab = 'plan'; S.planSeg = 'main'; lastId = null; render(); };
    setup(); const g = document.getElementById('gate-res'); o.res = { title: T(g.querySelector('b')), p: T(g.querySelector('p')), rows: [...g.querySelectorAll('.mini')].map(r => ({ name: T(r.querySelector('b')), btn: T(r.querySelector('button')), aria: r.querySelector('button').getAttribute('aria-label'), key: r.querySelector('button').dataset.p })) };
    const ts = document.getElementById('tl-strip'); o.strip = { title: T(ts.querySelector('b')), small: T(ts.querySelector('.small')), btn: T(ts.querySelector('button')) };
    S.tab = 'home'; lastId = null; render(); const h = document.getElementById('gate-home'); o.home = { title: T(h.querySelector('b')), rows: [...h.querySelectorAll('.mini b')].map(T) };
    S.tab = 'plan'; S.sheet = 'gate|report'; render(); const sh = document.querySelector('.sheet'); o.report = { h2: T(sh.querySelector('h2')), title: T(sh.querySelector('#gate-report b')), buttons: [...sh.querySelectorAll('button:not(.sx)')].map(T), rows: [...sh.querySelectorAll('#gate-report .mini b')].map(T) }; S.sheet = null;
    loadSample(); S.about.partner = false; S.asm = {}; S.retireSet = false; S.infl = null; lastId = null; render(); S.tab = 'plan'; render(); const g3 = document.getElementById('gate-res'); o.three = { title: T(g3.querySelector('b')), rows: [...g3.querySelectorAll('.mini b')].map(T) };
    return o; });
  await ev(() => { loadSample(); S.asm = {}; S.retireSet = false; S.infl = null; S.pRetSet = false; S.app = true; S.shell = true; S.tab = 'plan'; S.planSeg = 'main'; lastId = null; render(); }); await phone('S27-gate-results.png');
  out.gateJump = await ev(() => { document.querySelector('#gate-res [data-a="gofix"][data-p="planEnd"]').click(); const el = document.querySelector('.asmf[data-k="planEnd"]'); return { tab: S.tab, me: S.me, open: S.asmOpen, flash: el ? el.classList.contains('flash') : null, head: (document.querySelector('header.sky h2') || {}).textContent }; });
  await phone('S27-gate-jump.png');
  out.gateAfter = await ev(() => { S.retireSet = true; S.retireAge = 65; S.asm = Object.assign({}, S.asm, { planEnd: 90 }); S.infl = 0.02; S.pRetSet = true; S.pRet = 66; applyAssume(); return { missing: planMissing().map(x => x.t), ready: planReady() }; });
  // 2. other-property mortgage with a balance only
  out.mort2 = await ev(() => { const T = e => e ? e.textContent.replace(/\s+/g, ' ').trim() : null; loadSample(); S.lists.mort2 = [newItem('mort2')]; S.lists.mort2[0].f.owed = '180000'; syncLists(); S.app = true; S.shell = true; S.tab = 'plan'; S.planSeg = 'main'; lastId = null; render();
    const o = { missing: planMissing().map(x => chooseTxt(x)), ready: planReady(), needsTerm: typeof mort2NeedsTerm === 'function' ? mort2NeedsTerm() : null, items: checkItems().filter(x => /mortgage/i.test(x.n || x.k || '')).map(x => [x.k, x.n, x.st, x.msg || x.look || '']), pay: Math.round(mort2Nums().pay) };
    S.app = false; S.pb = true; S.scr = 'P4'; lastId = null; render(); o.p4 = [...document.querySelectorAll('#main .card')].map(c => T(c)).find(t => /Other-property mortgage/.test(t)) || null; o.banner = missingFlags().length;
    return o; });
  // 3. derived investment standard
  out.inv = await ev(() => { const g = k => { const s = SETTINGS.s[k]; return { n: s.n, v: s.pv != null ? s.pv : s.v, vc: s.vc, by: s.by, src: s.src, guide: s.guide }; }; const o = { inv: g('inv'), invGross: g('invGross'), fundChg: g('fundChg'), exit: RI.sav.exit, deemed: RI.sav.deemed, chgStd: INV_CHG_STD, invCaut: invNet(0.01) };
    const fc = SETTINGS.s.fundChg, fpv = fc.pv; fc.pv = 0.015; o.chg15 = [invNet(0), invNet(0.01)]; if (fpv == null) delete fc.pv; else fc.pv = fpv; const sv = SETTINGS.s.invGross.v; SETTINGS.s.invGross.v = 0.06; o.at6 = invNet(0); SETTINGS.s.invGross.v = sv; return o; });
  // 4. main strength rules
  out.strength = await ev(() => { const o = {}; loadSample(); S.app = true; o.sample = findings(project()).sT;
    loadSample(); S.src.costsM = 'typed'; S.fin.costsM = 9000; o.over = findings(project()).sT;
    loadSample(); S.app = true; S.goals.forEach(g => { if (g.k !== 'retire') { g.amount = 5000000; g.auto = false; } }); S.retireAge = 58; S.about.age = 50; o.none = findings(project()).sT; return o; });
  // 5. Step 7 with 4 / 3 things (texts from capture-s21 too)
  await ev(() => { loadSample(); S.app = false; S.shell = true; S.pb = true; S.tab = 'plan'; S.scr = 'P4'; S.retireSet = false; S.infl = null; S.asm = {}; S.pRetSet = false; S.checked = false; lastId = null; render(); }); await tall(390, 2300);
  out.p4partner = await ev(() => { const T = e => e ? e.textContent.replace(/\s+/g, ' ').trim() : null; return { h3: T(document.querySelector('#p4-3 h3')), p: T(document.querySelector('#p4-3 h3 + p')), count: T(document.getElementById('p4-count')), need: T(document.getElementById('p4-need')), req: reqKeys(), order: [...document.querySelectorAll('#p4-3 .field')].map(x => x.dataset.k || x.id), summary: T(document.querySelector('#p4-rest summary')), restP: T(document.querySelector('#p4-rest summary + p')) }; });
  await phone('S27-step7-four.png');
  await ev(() => { S.about.partner = false; lastId = null; render(); });
  out.p4single = await ev(() => { const T = e => e ? e.textContent.replace(/\s+/g, ' ').trim() : null; return { h3: T(document.querySelector('#p4-3 h3')), p: T(document.querySelector('#p4-3 h3 + p')), count: T(document.getElementById('p4-count')), req: reqKeys() }; });
  out.knownLimit = await ev(() => { loadSample(); applyAssume(); const r = assumeRows().find(x => x[0] === 'Known limits'); return r ? r[1] : null; });
  // 6. rates we don't know: planning rate labelled "Assumed: add yours" (journey-spec §27.6)
  out.rates = await ev(() => { const T = e => e ? e.textContent.replace(/\s+/g, ' ').trim() : null; loadSample(); S.asm = {}; S.advRate = {}; applyAssume(); S.app = true; S.shell = true; S.tab = 'me'; S.me = 'asm'; lastId = null; render();
    const mk = k => { const h = document.createElement('div'); h.innerHTML = asmInput(k); return { label: T(h.querySelector('.flabel')), tags: [...h.querySelectorAll('.flabel .tag')].map(T), chips: [...h.querySelectorAll('button.chip')].map(T), help: [...h.querySelectorAll('span.small')].map(T) }; };
    const o = { card: mk('cardRate'), loan: mk('loanRate'), mort: mk('mortRate'), cap: GD.cardCap, rows: assumeRows().filter(r => /rate/i.test(r[0])).map(r => r.slice(0, 3)) };
    S.asm = Object.assign({}, S.asm, { cardRate: GD.cardCap }); applyAssume(); o.cardMine = mk('cardRate'); o.rowsMine = assumeRows().filter(r => /Credit-card rate/.test(r[0])); return o; });
  // 7. emergency fund goal amount, repayment flag
  out.emerg = await ev(() => { loadSample(); S.app = true; S.shell = true; const F = finNums(), e = essM(F), g = S.goals.find(x => x.k === 'safety'); const o = { essM: e, months: asmV('safetyMonths'), auto: null, expect: Math.round(e * SAVE.buffer), buffer: SAVE.buffer };
    g.auto = true; syncSafety(); o.auto = g.amount; g.amount = 15000; g.auto = false; o.note = (safeNote(g).replace(/<[^>]+>/g, '')); o.typed = g.amount; syncSafety(); o.afterSync = g.amount; return o; });
  out.paylow = await ev(() => ({ msg: PAY_LOW, mort: MORT_LOW, flag: payLowFlag(6000, 40, 0.22), noflag: payLowFlag(6000, 200, 0.22), noRate: payLowFlag(6000, 40, 0), thresh: 6000 * (0.22 / 12 + 0.01) }));
  // 8. partner override ranges
  out.bounds = await ev(() => Object.keys(SETBOUNDS).map(k => [k, SET[k] ? SET[k].n : k, setBoundMsg(k)]));
  // 9. §27.5 tags on the standards, and Back to LifeMap's figure
  out.tags = await ev(() => { const T = e => e ? e.textContent.replace(/\s+/g, ' ').trim() : null; loadSample(); S.asm = {}; S.advRate = {}; applyAssume(); const mk = k => { const h = document.createElement('div'); h.innerHTML = asmInput(k); return { label: T(h.querySelector('.flabel')), tags: [...h.querySelectorAll('.flabel .tag')].map(T), chips: [...h.querySelectorAll('button.chip')].map(T) }; };
    const o = { set: mk('wage'), setAccess: mk('accessAge'), assumed: mk('cardRate'), notChosen: mk('planEnd') };
    S.asm = Object.assign({}, S.asm, { wage: 0.035 }); applyAssume(); o.mine = mk('wage'); S.asm = Object.assign({}, S.asm, { planEnd: 90 }); applyAssume(); o.chosenReq = mk('planEnd'); return o; });
  // 10. Pension access age standard
  out.access = await ev(() => { const T = e => e ? e.textContent.replace(/\s+/g, ' ').trim() : null; loadSample(); applyAssume(); const s = SETTINGS.s.accessAge, h = document.createElement('div'); h.innerHTML = asmInput('accessAge'); const row = assumeRows().find(r => r[0] === 'Pension access age');
    return { name: s.n, v: s.v, by: s.by, src: s.src, asat: s.asat, verify: !!s.verify, guide: s.guide || null, label: T(h.querySelector('.flabel')), chips: [...h.querySelectorAll('.chips button')].map(T), help: [...h.querySelectorAll('span.small')].map(T), row, count: Object.keys(SETTINGS.s).length, bound: setBoundMsg ? (SETBOUNDS.accessAge ? setBoundMsg('accessAge') : null) : null }; });
  // 11. §27.3 free retirement age: the range, the calm notes at 40..75, partner too
  out.retire = await ev(() => { const T = e => e ? e.textContent.replace(/\s+/g, ' ').trim() : null; loadSample(); S.app = true; S.shell = true; S.tab = 'me'; S.me = 'asm'; applyAssume(); const o = { min: retMin(), max: retMax(), age: S.about.age, planEnd: asmV('planEnd'), notes: {}, pnotes: {}, help: RETIRE_HELP };
    [40, 45, 50, 55, 60, 63, 66, 75].forEach(a => { o.notes[a] = retNote(a); o.pnotes[a] = pRetNote(a); }); return o; });
  await ev(() => { lastId = null; render(); }); await tall(390, 1500);
  // engine at those ages (the doc shows the calm line the customer sees and the first year the plan is short)
  out.early = await ev(() => { const o = []; [40, 45, 50, 55, 60, 66, 75].forEach(a => { loadSample(); S.app = true; S.retireAge = a; S.retireSet = true; S.about.age = 38; const rg = S.goals.find(g => g.k === 'retire'); if (rg) rg.age = a; applyAssume(); const P = project(); const r = P.rows.find(x => x.age === a - 1) || {}, r2 = P.rows.find(x => x.age === a) || {}; o.push({ age: a, pct: rg ? P.pct[rg.id] : null, shortAt: (P.rows.find(x => x.retired && x.shortLiving > 0) || {}).age || null }); }); return o; });
  // 12. §27.1 "Date has passed" + Change the date
  out.passed = await ev(() => { const T = e => e ? e.textContent.replace(/\s+/g, ' ').trim() : null; loadSample(); S.app = true; S.shell = true; S.tab = 'plan'; S.planSeg = 'main'; S.about.age = 45; const g = S.goals.find(x => x.k === 'travel') || S.goals[1]; g.age = 41; lastId = null; render();
    const o = { text: PASSED, yearsTxt: yearsTxt(g), when: whenTxt(g, false), whenEdit: whenTxt(g, true), btn: [...document.querySelectorAll('#main button, #main .link')].filter(b => /Change the date/.test(b.textContent)).map(T), name: g.name };
    o.chip = [...document.querySelectorAll('#main .tl-chip, #main [data-a="tlchip"], #main .chip')].map(T).filter(t => /passed/i.test(t)); return o; });
  await phone('S27-date-passed.png');
  // 13. developer round (unchanged areas)
  out.dev = {};
  out.dev.age = await ev(() => { const T = e => e ? e.textContent.replace(/\s+/g, ' ').trim() : null; S = fresh(); S.scr = 'B1'; S.shell = false; lastId = null; render(); const i = document.getElementById('age-v'); const nx = document.querySelector('.foot [data-a="go"]'); return { age: S.about.age, ph: i && i.placeholder, val: i && i.value, nextDisabled: nx && nx.disabled, nextText: T(nx) }; });
  await phone('S27-age-blank.png');
  out.dev.me = await ev(() => { const T = e => e ? e.textContent.replace(/\s+/g, ' ').trim() : null; S = fresh(); S.app = true; S.shell = true; S.tab = 'me'; S.me = 'details'; lastId = null; render(); return T(document.querySelector('#main .card')); });
  out.dev.addAge = await ev(() => { const T = e => e ? e.textContent.replace(/\s+/g, ' ').trim() : null; S = fresh(); S.shell = true; S.app = false; S.tab = 'explore'; S.xs = [{ v: 'CALC', p: 'compound' }]; S.sheet = 'calcadd|compound'; lastId = null; render(); const s = document.querySelector('.sheet'); return s ? { h2: T(s.querySelector('h2')), sub: T(s.querySelector('p.sub')), btns: [...s.querySelectorAll('button:not(.sx)')].map(T) } : null; });
  await phone('S27-add-age-sheet.png');
  out.dev.wi = await ev(() => { const T = e => e ? e.textContent.replace(/\s+/g, ' ').trim() : null; loadSample(); S.tab = 'plan'; S.planSeg = 'main'; S.planGo = 'wi'; S.wi.g = S.goals[1].id; S.wi.m = 325; lastId = null; render(); const c = document.getElementById('r-wi'); const kids = [...c.children].map(x => (x.className || x.tagName) + ' | ' + T(x).slice(0, 70)); const gr = c.querySelector('details.wigrow'); return { kids, growSummary: T(gr.querySelector('summary')), growOpen: gr.open, growBelowLive: !!(document.getElementById('wi-live').compareDocumentPosition(gr) & 4), growBelowOut: !!(document.getElementById('wi-out').compareDocumentPosition(gr) & 4) }; });
  await ev(() => { document.getElementById('r-wi').scrollIntoView(); }); await tall(390, 2600); await phone('S27-whatif-order.png'); await tall(390, 1500);
  out.dev.exLabel = {};
  out.dev.exLabel.fresh = await ev(() => { const T = e => e ? e.textContent.replace(/\s+/g, ' ').trim() : null; S = fresh(); S.shell = true; S.app = false; S.tab = 'explore'; S.xs = [{ v: 'CALC', p: 'borrow' }]; lastId = null; render(); const l = document.getElementById('exlab'); const r = document.querySelector('.exres'); return { top: T(l), topHidden: l && l.hidden, res: T(r), n: CALCS.length }; });
  await phone('S27-example-figures.png');
  out.dev.exLabel.plan = await ev(() => { loadSample(); S.app = true; S.shell = true; S.tab = 'explore'; S.xs = [{ v: 'CALC', p: 'borrow' }]; lastId = null; render(); const l = document.getElementById('exlab'); return { topHidden: l && l.hidden, res: !!document.querySelector('.exres') }; });
  out.dev.exLabel.all = await ev(() => CALCS.map(c => { S = fresh(); S.shell = true; S.app = false; S.tab = 'explore'; S.xs = [{ v: 'CALC', p: c.id }]; lastId = null; render(); const l = document.getElementById('exlab'); const r = document.querySelector('.exres'); return [c.id, !!l, !!(l && !l.hidden), !!r]; }));
  out.dev.print = { opening: 'Opening the print window. Choose "Save as PDF" as the printer.', blocked: 'Printing is blocked here. Open this page in your browser to save the PDF.', nothing: 'Nothing opened. Printing looks blocked here. Open this page in your browser to save the PDF.' };
  out.dev.report = await ev(() => { loadSample(); S.app = true; S.shell = true; S.tab = 'plan'; S.planSeg = 'main'; lastId = null; render(); const b = document.querySelector('#screen [data-a="report"]'); if (b) b.focus(); openReport(); const R = document.getElementById('report'); return { on: R.classList.contains('on'), focus: document.activeElement && document.activeElement.dataset.r, role: R.getAttribute('role'), label: R.getAttribute('aria-label') }; }); await page.waitForTimeout(150); out.dev.report.inert = await ev(() => [...document.querySelectorAll('.stage,.side')].map(e => e.inert));
  await page.keyboard.press('Tab'); out.dev.report.tab2 = await ev(() => document.activeElement.dataset.r || document.activeElement.tagName); await page.keyboard.press('Escape'); await page.waitForTimeout(250);
  out.dev.report.afterEsc = await ev(() => ({ on: document.getElementById('report').classList.contains('on'), focus: document.activeElement.dataset.a || document.activeElement.tagName, inert: [...document.querySelectorAll('.stage,.side')].map(e => e.inert) }));
  out.dev.banner = await ev(() => { const T = e => e ? e.textContent.replace(/\s+/g, ' ').trim() : null; loadSample(); S.app = true; S.shell = true; S.tab = 'plan'; S.planSeg = 'main'; delete S.fin.pensionM; lastId = null; render(); return { miss: T(document.getElementById('miss-banner')), rough: [...document.querySelectorAll('#main .nudge')].map(x => T(x).slice(0, 90)) }; });
  out.dev.types = await ev(() => Object.fromEntries(Object.entries(TYPES).map(([k, t]) => [k, [t.name, t.watch]])));

  // 14. audit fixes: live engine output for the scenarios the independent audit raised (no plan, standards and suggested rates chosen)
  out.audit = await ev(() => { const run = (id, over) => { S = fresh(); S.shell = true; S.app = false; S.infl = 0.02; S.retireSet = true; S.retireAge = 66; S.asm = Object.assign({}, S.asm, { planEnd: 90, cardRate: 0.2, loanRate: 0.08, mortRate: 0.0375, fundChg: 0.01, buyFees: 3000, depEarn: 0.01 }); applyAssume(); const c = C(id); S.xs = [{ v: 'CALC', p: id }]; const v = Object.assign({}, calcVals(c), over || {}); const r = c.run(v); return { lbl: r.lbl, val: r.val, line: r.line, rows: r.rows }; };
    return { c12: run('retirement', {}), c12sft: run('retirement', { pot: 3000000, m: 3000 }), c12early: run('retirement', { ra: 55 }), c12age: run('retirement', { ra: 30, age: 38 }), c22cap: run('incomegap', { e: 1000, s: 1000000 }), c22: run('incomegap', {}), c20: run('riskreturn', { s: 2 }), c20c: run('riskreturn', { s: 1, y: 30 }),
      c15big: run('lastmoney', { w: 600000, pot: 400000 }), c15early: run('lastmoney', { age: 55 }), c16big: run('drawdown', { w: 600000, pot: 400000 }), c10zero: run('lumpsum', { f: 0, r: 0 }), c10: run('lumpsum', {}), c07clamp: run('rentbuy', { dep: 600000, price: 300000 }), c01: run('borrow', {}), c03: run('deposit', {}), c02: run('repayment', {}), c28: run('loan', {}), c13: run('contrib', {}), c20zero: run('riskreturn', { s: 0 }), c10unset: (() => { const r0 = run('lumpsum', {}); S.infl = null; S.adjInfl = { lumpsum: true }; const c = C('lumpsum'); const r = c.run(calcVals(c)); return { lbl: r.lbl, val: r.val, line: r.line, rows: r.rows }; })() }; });

  // 15. §27.2 number boxes: the unit never overlaps what is typed (long values typed in every visible box, three widths)
  out.overlap = {};
  for (const w of [360, 390, 1280]) { await ev(() => { S = fresh(); S.shell = true; S.tab = 'explore'; S.xs = []; lastId = null; render(); }); await tall(w, 1600); let checked = 0; const bad = [];
    const scan = async label => { const r = await ev(lab => { const res = { n: 0, bad: [] }; document.querySelectorAll('input.nb').forEach(i => { if (i.offsetParent === null) return; const box = i.closest('.nbox'); if (!box) return; const old = i.value; i.value = i.dataset.nb && /pct|rate/i.test(i.dataset.nb) ? '12.3456' : '12345678901'; i.dispatchEvent(new Event('input', { bubbles: true })); const ri = i.getBoundingClientRect(); [...box.querySelectorAll('.nbu')].forEach(u => { const ru = u.getBoundingClientRect(); const ov = Math.min(ri.right, ru.right) - Math.max(ri.left, ru.left); const ovy = Math.min(ri.bottom, ru.bottom) - Math.max(ri.top, ru.top); if (ov > 1 && ovy > 1) res.bad.push(lab + ' ' + (i.dataset.nb || i.id) + ' unit "' + u.textContent + '" overlaps by ' + Math.round(ov) + 'px'); }); if (i.scrollWidth > i.clientWidth + 1) res.bad.push(lab + ' ' + (i.dataset.nb || i.id) + ' text wider than its box'); res.n++; i.value = old; }); return res; }, label); checked += r.n; bad.push(...r.bad); };
    await ev(() => { loadSample(); S.app = true; S.shell = true; S.tab = 'me'; S.me = 'asm'; lastId = null; render(); document.querySelectorAll('#main details').forEach(d => d.open = true); }); await scan('assumptions');
    for (const id of await ev(() => CALCS.map(c => c.id))) { await ev(id => { loadSample(); S.app = true; S.shell = true; S.tab = 'explore'; S.xs = [{ v: 'CALC', p: id }]; lastId = null; render(); document.querySelectorAll('#main details').forEach(d => d.open = true); }, id); await scan(id); }
    await ev(() => { loadSample(); S.app = false; S.shell = true; S.pb = true; S.tab = 'plan'; S.scr = 'F2'; lastId = null; render(); }); await scan('timeline');
    await ev(() => { loadSample(); S.app = false; S.shell = true; S.pb = true; S.tab = 'plan'; S.scr = 'P4'; S.retireSet = false; S.infl = null; S.asm = {}; lastId = null; render(); document.querySelectorAll('#main details').forEach(d => d.open = true); }); await scan('step7');
    out.overlap[w] = { checked, bad }; }
  await tall(390, 1500);

  out.counts = await ev(() => { loadSample(); S.app = true; S.shell = true; S.tab = 'me'; S.me = 'asm'; lastId = null; render(); return { standards: Object.keys(SETTINGS.s).length, guidance: Object.keys(SETTINGS.g).length, asmKeys: ASM_KEYS().length, boxes: document.querySelectorAll('#main .field.asmf').length }; });
  out.c07 = await ev(() => { const run = (over, plan) => { S = fresh(); S.shell = true; S.app = false; S.infl = 0.02; S.retireSet = true; S.retireAge = 66; S.asm = Object.assign({}, S.asm, { planEnd: 90, mortRate: 0.0375, buyFees: 3000 }); applyAssume(); const c = C('rentbuy'); S.xs = [{ v: 'CALC', p: 'rentbuy' }]; const v = Object.assign({}, calcVals(c), over || {}); const r = c.run(v); return { val: r.val, line: r.line, rows: r.rows, opp: Math.round(r.num.Opportunity_Cost) }; }; S = fresh(); S.shell = true; S.app = false; S.infl = 0.02; applyAssume(); const h = document.createElement('div'); h.innerHTML = asmInput('depEarn'); const T = e => e ? e.textContent.replace(/\s+/g, ' ').trim() : null; return { run: run(), dep: { label: T(h.querySelector('.flabel')), tags: [...h.querySelectorAll('.flabel .tag')].map(T), help: [...h.querySelectorAll('span.small')].map(T) } }; });
  return out; };
