// ---------- 3 Rules and Your assumptions ----------
push(H1('3. Rules and Your assumptions'));
push(H2('3.1 Rules version'));
push(callout('**' + RULES_NOTE + '.** Budget 2027 is on 6 October 2026: it will require updates to the register below (tax bands and credits, USC, PRSI path, State Pension and benefit rates, pension and savings tax) and to copy that quotes them (e.g. "€299.30 a week", "€254 a week", "€259.50 a week", "DIRT at 33%", "exit tax at 38%", "€2.2m in 2026", "1% up to €1m"). Re-check every row marked "Verify" and change the version label.'));
push(P('Customers see the label in Your assumptions (Set by Government card: "Set by law and the same for everyone, so you can\'t change them. ' + RULES_NOTE + '.") and in "What your plan assumes" (row "Rules", tag "Set by Government · 2026").', { size: 18 }));
push(H2('3.2 Three types of value (journey-spec §14)'));
push(table([1600, 2700, 2900, W - 7200], ['Type', 'Rule', 'Wording on screen (verbatim pattern)', 'Examples'], [
  ['1. Set by law', 'Set automatically, the same for everyone, not editable.', '"' + M.T_GOV + '" (tag .tag.none)', 'Income tax bands and credits, USC, PRSI, pension relief %, earnings cap, lump-sum tax, DIRT, exit tax, Central Bank limits, full State Pension, Illness Benefit and survivor\'s pension rates'],
  ['2. Usual range', 'The customer enters theirs; the range is stated. Blank until entered (unless their own data gives it).', '"Usually between {low} and {high} ({source})." In "What your plan assumes" the tag reads "Usually {low}–{high}".', 'Mortgage rate 3.5%–4.5%, card APR 13%–23%, loan APR 6%–10%, fund charges 0.5%–1.5%, buying fees €2,500–€3,500, own State Pension, Illness Benefit'],
  ['3. Personal choice', 'No default: blank until chosen. One tap on the standard chip fills it and counts as the customer\'s decision.', '"Generally the standard is {X} ({source}). Choose what you want to use." Chip "Use the standard ({X})". Tag "' + M.T_MINE + '" once chosen.', 'Inflation, pay rises, cash, investment and pension growth, share you pay, emergency fund months, withdrawal timing, retirement multiple, budget split'],
  ['Chosen individually', 'Retirement age and plan-until age are never defaulted and never part of "Use the standard for all of these".', 'Retirement age: "' + M.RETIRE_HELP + ' Choose the age you want to plan for." Plan until age: "' + M.ASM.planEnd.help + '"', '—'],
  ['How the plan works', 'Fixed modelling rules, not choices.', '"' + M.T_HOW + '" (tag .tag.typed)', 'Spare money not saved is assumed spent; order savings go to goals; known limits']], { size: 15 }));
push(P('"Use the standard for all of these" (ghost small button) fills every personal choice not made yet, including inflation (2%); helper text: "Fills every choice you haven\'t made yet with its standard. It never sets your retirement age or plan-until age: choose those yourself." Toast: "Standard used for {n} choices" (e.g. "' + (data.asm.useAllToast || '').replace(/^\W+/, '') + '"). Until a required choice is made, results read "Choose your {item} to see this". The sample customer has every plan choice made.', { size: 18 }));
push(H2('3.3 Irish rules 2026 register'));
push(P('Every figure in one place (RULES_IE_2026): it (income tax), usc, prsi, pen, ae, sp, sav, home and infl are set by law or official statistics; guide holds the usual ranges and guidance facts (type 2); std holds the standards for personal choices (type 3). ' + M.RULES.length + ' values, ' + M.RULES.filter(r => r[4]).length + ' marked to verify before release.', { size: 18 }));
push(table([2700, 2900, 2600, W - 8200], ['Key', 'Value', 'Effective', 'Verify'], M.RULES.map(r => [r[0], r[1].length > 90 ? r[1].slice(0, 90) + '…' : r[1], r[2], r[4] ? 'Yes' : 'No']), { size: 14, cantSplit: true }));
push(H2('3.4 Your assumptions screen'));
const AH = data.asm.prices.head.split('\n').map(s => s.trim()).filter(Boolean), TOP = data.asm.prices.dom.top;
push(P('Opened from Me ("🧮 Your assumptions"), the plan what-if, "Make my choices" on a gate, and "Choose" on the timeline strip. Header: "' + AH.find(x => x === 'Your assumptions') + '", subtitle "' + AH[AH.length - 1] + '".'));
push(table([2300, W - 2300], ['Part', 'Copy and behaviour (verbatim)'], [['Top card (while personal choices are missing)', '"' + TOP.b + '" (e.g., count of choices not made) · "' + TOP.p + '" · button "' + TOP.btn + '" · "' + TOP.note + '"'], ['Cards', M.ASM_GRP.map(g => '"' + g[1] + '"').join(', ') + ', then "' + M.T_GOV + '" (collapsible details; "Prices & growth" opens first)'], ['Prices & growth extras', 'The inflation chips (1.8) and "Growth assumptions set" (Standard / Cautious). Choosing a set fills pay rises, cash, investment and pension growth with its rates.'], ['Each input', 'Label + tag ("Not chosen yet" / "Your choice"); value box or chips (empty until chosen); "Use the standard (X)" chip for personal choices; one guidance line (verbatim below).'], ['Plan length card', 'Starts with Retirement age (box, prefix "age", whole numbers, 50 or your age + 1 to 75): "' + M.RETIRE_HELP + ' Choose the age you want to plan for."'], ['Budget check', 'When all three budget shares are chosen and do not total 100%: "Your budget split adds up to {n}%. It should total 100%."'], ['Set by Government card', data.asm.law.dom.groups[0].law.rows.length + ' rows (below) and "' + data.asm.law.dom.groups[0].law.note + '"']], { size: 15 }));
const typeTxt = d => d.ty === 2 ? '2 · Usual range' : d.own ? '3 · Choose yourself' : '3 · Personal choice';
const asmRange = d => d.t === 'choice' ? d.o.map(o => '"' + o[1] + '"').join(' / ') : d.t === 'pct' ? F.nbFmt(d.min) + '% to ' + F.nbFmt(d.max) + '%' : d.t === 'eur' || d.t === 'eurw' ? F.eur(d.min) + ' to ' + (d.t === 'eurw' ? '€' + (+d.max).toFixed(2) : F.eur(d.max)) : F.nbFmt(d.min) + ' to ' + F.nbFmt(d.max);
const asmCtl = d => d.t === 'choice' ? 'Chips' : d.t === 'pct' ? 'Box, suffix "%"' : d.t === 'eur' || d.t === 'eurw' ? 'Box, prefix "€"' : d.t === 'yrs' ? 'Box, suffix "yrs"' : d.t === 'age' ? 'Box, prefix "age"' : 'Box, no unit';
for (const [g, gt] of M.ASM_GRP) { push(H3('3.4.' + (M.ASM_GRP.findIndex(x => x[0] === g) + 1) + ' ' + gt));
  const G = data.asm[g].dom.groups[0];
  push(table([550, 2350, 1000, 1150, 1250, 600, W - 6900], ['Code', 'Label (verbatim)', 'Type', 'Control', 'Range / options', 'Step', 'Guidance (verbatim) · standard chip · used by'], G.fields.map(f => { const d = M.ASM[f.k];
    if (!d) return ['—', f.label, '3 · Choose yourself', 'Box, prefix "age"', '50 (or age + 1) to 75', '1', f.guide + ' · No standard chip · Used by: plan, C12, C13, C14, C15'];
    return [d.b, f.label, typeTxt(d), asmCtl(d), asmRange(d), d.t === 'choice' ? '—' : (d.t === 'pct' ? F.nbFmt(d.step) + '%' : F.nbFmt(d.step)), (f.guide || '—') + ' · ' + (f.std ? 'Chip "' + f.std + '"' : 'No standard chip') + ' · Used by: ' + (ASM_USE[f.k] || 'Plan')]; }), { size: 14 }));
  const SL = require('./slices.json')[g]; push(imgGrid(SL.map((f, i) => ({ file: f, caption: 'Your assumptions · ' + gt + ' (' + (i + 1) + ' of ' + SL.length + ')' })), 4, 640)); }
push(H3('3.4.5 ' + M.T_GOV));
push(table([2800, W - 2800], ['Row', 'Value shown (verbatim)'], data.asm.law.dom.groups[0].law.rows, { size: 15 }));
push(H2('3.5 Plan builder step 7: "Your assumptions"'));
const S7 = data.step7.text.split('\n').map(x => x.trim()).filter(Boolean);
push(P('Step 7 of 8 ("' + data.step7.head.split('\n').map(x => x.trim()).filter(Boolean)[1] + '"), under the check list and the "These details are right, as far as I know" tick, a card "' + S7[0] + '": "' + S7[1] + '" It holds, in order: the inflation chips; Retirement age; Plan until age; any usual-range values the plan needs (e.g. your partner\'s State Pension, card and loan APRs when you have those debts); then "Other choices" with "{n} of {total} not chosen yet." (e.g. "' + (S7.find(x => /not chosen yet\.$/.test(x)) || '') + '"), "Use the standard for all of these" and a collapsible "See or change each one". "See my results" stays disabled until everything is chosen; the line above it reads "Choose your {first missing item} above to see your results." (e.g. "' + data.step7.foot.split('\n')[0] + '").'));
push(imgP('P-step7.png', 300, 860), cap('Step 7 · Your assumptions card (sample customer with every choice cleared)'));
push(H2('3.6 "What your plan assumes"'));
const AS2 = data.assumeSheet;
push(P('Sheet opened from "What your plan assumes" on the results page. Title "' + AS2.title + '", intro "' + AS2.intro + '". Each row: label, a tag naming its type, and the value. Type-1 rows are folded into a collapsible "' + AS2.gov + '". Values below are for the sample customer.', { size: 18 }));
push(table([3000, 2300, W - 5300], ['Row', 'Tag (type)', 'Value (sample customer)'], AS2.rows, { size: 14 }));
