// ---------- 3.7 Settings (journey-spec §19.6, option C; generalises §18 partner rates) ----------
{ const EXP = require('./ex.json'), S19 = require('./s19b.json'), SET = M.SETTINGS, SS = SET.s, XS = XL._settings.rows, ck = Object.keys(SS), GRP = [...new Set(ck.map(k => SS[k].grp))], nm = k => 'Set_' + k;
  const wrow = n => XS.find(row => row.some(c => c[1].includes(n))) || null;
  push(H2('3.7 Settings: every standard in one block (journey-spec §19.6, option C)'));
  push(P('Law values (tax bands and credits, USC, PRSI, DIRT, exit tax, pension relief limits, the full State Pension rate, Central Bank lending limits) are fixed for everyone and cannot be changed by anyone. Everything else the app suggests is one **Settings block** (SETTINGS in the prototype, the sheet "Settings" in the workbook) that **LifeMap or a partner** (credit union, adviser firm, company, agent) controls: **' + ck.length + ' standards**, each with its wording, source, "as at" date and guidance. It replaces the earlier partner rates block (§18), which is now the group "Market rates" of this block. A customer can still change any standard for their own plan; "Use the standard (X)" is the one-tap chip and counts as their own choice, so journey-spec §14 still holds. **Retirement age and life expectancy (plan-until age) are never defaulted**, in Settings or anywhere: life expectancy is only guidance (' + Object.keys(SET.g).length + ' figures).'));
  push(H3('3.7.1 The ' + ck.length + ' standards (verbatim)'));
  push(P('Columns: the setting; the LifeMap standard as shown to customers; the wording after "Generally the standard is X (…)" (for a market rate: the label on the chip "Use the suggested rate (X) · {label}"); the source, "as at" date and guidance; and whether the page must be opened and the figure verified before release (' + ck.filter(k => SS[k].verify).length + ' of ' + ck.length + '). The workbook name of the standard is in brackets (cells on the sheet Settings).', { size: 16 }));
  for (const g of GRP) { const ks = ck.filter(k => SS[k].grp === g); push(H3('3.7.1.' + (GRP.indexOf(g) + 1) + ' ' + g + ' (' + ks.length + ')'));
    push(table([2400, 1050, 2250, 3416, 750], ['Setting (workbook name)', 'Standard', 'Wording / chip label', 'Source · as at · guidance', 'Verify'], ks.map(k => { const x = SS[k]; return [x.n + ' (' + nm(k) + (x.u === 'pct3' ? '_1 to _3' : '') + ')', M.SFMT[k], x.label || x.by, [(x.src || 'no source (no published figure)') + ' · as at ' + x.asat].concat(x.guide ? ['Guidance: ' + x.guide] : [], x.note ? ['Note: ' + x.note] : []), x.verify ? 'Yes' : 'No']; }), { size: 13 })); }
  push(P('Guidance figures (shown, never filled in for you): ' + Object.entries(SET.g).map(([k, x]) => x.n + ' = ' + x.v + ' (' + x.by + '; as at ' + x.asat + '; verify before release)').join('; ') + '. Fixed values on the same workbook sheet, not customer-editable: Inflation "Ireland now" (Set_inflNow, 3.9%, CSO HICP flash, Sep 2026) and the new-credit-card cap (Card_APR_Cap, 23%, Central Bank of Ireland).', { size: 16 }));
  push(H3('3.7.2 How a partner replaces the standards'));
  const OV = S19.override, A0 = S19.admin, A1 = OV.admin;
  ['A partner types its name in the one **Partner name** box at the top of the admin view (workbook: **Partner_Name**, C4 of the sheet Settings) and, for any standard it wants to change, its own figure in the "Partner figure" box of that row (workbook: the partner figure cell, column D, of a market-rate row; the other rows use the same box in the prototype). A blank box means "the LifeMap standard". Nothing else changes.',
   'The figure in use is the partner\'s if there is one, otherwise the LifeMap standard. A changed row shows the tag "' + ((A1.groups[0].fields.find(f => f.tag) || {}).tag || 'Changed by {partner}') + '" and a "Reset" link; once anything is changed the link "' + A1.resetAll + '" appears under the partner name.',
   '**"Suggested by {partner}" appears only beside a figure the partner has changed.** Every other figure keeps its LifeMap source wording. Example with the partner "Example Credit Union", inflation 2.5%, mortgage rate 3.99% and Emergency fund months 4 (invented for the test, not shipped):'].forEach(t => push(B(t)));
  push(table([2700, 3300, W - 6000], ['Where the customer sees it', 'Changed by the partner', 'Not changed'], [
    ['Inflation (card, Your assumptions)', OV.infl.help + ' Chip: "' + OV.infl.chips[0] + '"', 'Generally the standard is 2% (the ECB target for the long term). …'],
    ['Emergency fund months (Your assumptions)', OV.safety.safetyMonths.guide + ' Chip: "' + OV.safety.safetyMonths.std + '"', M.ASM.safetyMonths.guide || 'Generally the standard is 6 months (…)'],
    ['Mortgage rate chip', OV.safety.mortRate.std, 'Use the suggested rate (3.48%) · Central Bank of Ireland: average rate on new mortgages, Jul 2026'],
    ['Pay rises (a standard left alone)', '—', OV.prices.wage ? OV.prices.wage.guide : 'Generally the standard is 3% (Irish pay has grown about 3%–4% a year recently (CSO)). Choose what you want to use. Pick lower if your pay is fixed or you expect to work part-time.'],
    ['Other loans chip (a rate left alone)', '—', OV.safety.loanRate.std],
    ['What your plan assumes', OV.sheet.filter(t => /^(Prices rise|Mortgage rate)/.test(t)).join('; '), OV.sheet.find(t => /^Other loans rate/.test(t)) || '']], { size: 14 }));
  push(H3('3.7.3 The admin view'));
  push(P('Shown in the prototype only for LifeMap and partners and **clearly marked not for customers**: it is reached from the jump list ("Admin (not for customers)" › "Settings: standards, wording, sources, partner label", screen ADMIN-SET) and is not part of any customer journey. Header: "' + A0.head.replace(/^‹ Back\s*A?/, '').replace('Settings🔒', 'Settings · 🔒') + '", back button "' + A0.back + '".', { size: 18 }));
  push(table([2600, W - 2600], ['Part', 'Copy and behaviour (verbatim)'], [
    ['Marked-off note (role="note", amber background #FFF3CD, border #E0B84A)', A0.note],
    ['Partner name', '"' + A0.partnerLabel + '" (text box, placeholder "e.g. a credit union")'],
    ['Groups', A0.groups.map(g => '"' + g.summary + '"').join(' · ') + ' (collapsible cards; each opens to its rows)'],
    ['A row', 'Label (+ tag) · "LifeMap standard: {value} · {wording} · as at {date}" + "· verify before release" where it applies · "Guidance: …" · "Note: …" · "Source: {url}" · "Partner figure (leave blank for the LifeMap standard):" · a box (placeholder = the standard) with its unit; three boxes for growth, volatility and budget; a drop-down starting "LifeMap standard" for choices · "Reset" once changed. Example: "' + A0.groups[0].fields[0].lines[0] + '"'],
    ['Guidance figures', '"' + A0.groups[A0.groups.length - 1].summary + '": ' + A0.groups[A0.groups.length - 1].fields.map(f => f.label).join('; ') + '; "' + (A0.groups[A0.groups.length - 1].tail || '') + '"']], { size: 14 }));
  push(imgGrid([{ file: 'T-admin-top.png', caption: 'Admin view: top and first group' }, { file: 'T-admin-market.png', caption: 'Admin view: Market rates group' }, { file: 'T-admin-override.png', caption: 'With a partner name and changed figures' }], 3, 780));
  push(imgGrid([{ file: 'T-cust-mort-partner.png', caption: 'Customer: mortgage rate chip, "Suggested by …"' }, { file: 'T-cust-wage.png', caption: 'Customer: a standard left alone keeps its source' }], 2, 220));
  push(H3('3.7.4 What the customer sees'));
  ['**Standards** (types 3): blank until chosen; guidance "Generally the standard is {X} ({wording}). Choose what you want to use." and the chip "Use the standard ({X})". They are never pre-filled and the chip is their own explicit choice.',
   '**Market rates**: never pre-filled; chip "Use the suggested rate ({X}) · {label}" ("Use the suggested figure ({€}) · {label}" for euro amounts); no suggestion where the block has none (credit card, buying fees: only the 23% cap is quoted; buying fees are optional). The customer can always type their own.',
   '**What your plan assumes** and step 7 show the figure in use; the tag of a market-rate row is "Suggested {X}%" or "Your figure".',
   '**Not in Settings**: law values (fixed, "Set by Government · 2026"), retirement age and plan-until age (the customer\'s own choice).'].forEach(t => push(B(t)));
  push(H3('3.7.5 Workbook: the sheet Settings'));
  push(P('"' + XL._settings.intro + '"', { size: 16 }));
  const hd = XS[5].map(c => c[0]);
  push(table([2500, 900, 1000, 1200, 1500, 1166, W - 8266], ['Setting', 'Standard (value)', '2nd / partner figure', '3rd / cautious', 'Names', 'As at', 'Group · type'], XS.slice(6).filter(r => r[1][0] && r[2][0] !== '' || (r[1][0] && /Set_|Card_APR/.test(r[1][0]))).map(r => [r[1][0].replace(/\s+\[.*$/, ''), r[2][0] ? (isNaN(+r[2][0]) ? r[2][0] : F.nbFmt(+r[2][0])) : '—', r[3][0] || '—', r[5][0] ? (isNaN(+r[5][0]) ? r[5][0] : F.nbFmt(+r[5][0])) : '—', [].concat(...r.map(c => c[1])).filter((v, i, a) => a.indexOf(v) === i).join(', ') || '—', r[8][0] || '—', r[10][0] || '—']), { size: 12 }));
  push(P('Named cells: Partner_Name (C4); for each standard Set_{key} (the standard), Set_{key}_Label (the wording), Set_{key}_Cautious (the cautious value where there is one) and for the three-value rows Set_{key}_1 to _3; for each market rate also Set_{key}_Published and Suggest_{Name} (the figure suggested: the partner\'s if set, else the standard) with Suggest_{Name}_Label (the label shown). Calculator input guidance in the workbook is built from these names, for example C01: "' + XL.C01.inputs[4].allowed + '"', { size: 16 }));
}
