// ---------- 4.8 Lists (journey-spec §19.2, §19.4, §19.5) ----------
{ const A = require('./s19a.json').s, A0 = require('./s19a.json'), LD = M.LDEF, FI = M.FFI, ID = M.ITEMDOC, FS = M.FSEC;
  push(H2('4.8 Lists: each card, loan, pension and policy on its own (journey-spec §19.2, §19.4, §19.5)'));
  push(P('Debts, pensions and protection are not one total. The customer adds **each credit card, loan, pension and policy separately** with a "＋" button; every item has its own fields and its own optional upload. The plan engine still reads one total per group (the sum of the items), so results, calculators and the checklist work as before. The Liabilities and Pension sections show their lists; Protection shows a list under each type answered "Yes".', { size: 18 }));
  push(H3('4.8.1 The item block'));
  const itemF = A.liabBlank.lists[0].items[0];
  push(table([2300, W - 2300], ['Part', 'Specification (verbatim)'], [
    ['List card', 'A .card with data-list="{type}": heading "{emoji} {title}" (e.g. "' + A.liabBlank.lists[0].title + '"), then one item block per item, then the add button.'],
    ['Item block', 'A nested card (border 1.5px #D5E0EA, no shadow) titled "{One} {n}" (e.g. "' + itemF.title + '"; a pension with a name shows its name) and a "' + itemF.remove + '" link (aria-label "Remove {title}"). Removing shows the toast "Removed".'],
    ['Fields', 'Each field is a labelled box with the status tag, an optional hint and the link "Not sure? See an example" (the §15 card for that field, 4.4). € boxes show a "€" prefix, rates a "%" suffix; the lender and name boxes are text.'],
    ['Upload', 'Without a document: the link "📄 {upload text}". With one: "✅ From {document}" with "Replace statement" and "Remove statement" (4.8.4).'],
    ['Add button', 'Ghost small button, full width, below the items: "' + A.liabBlank.lists[0].add + '" · "' + A.liabBlank.lists[1].add + '" · "' + A.pensBlank.lists[0].add + '". Tapping it adds an empty item below and moves focus to its first box.'],
    ['First item', 'A section with no items shows one empty item (so the first entry needs no tap); removing every item leaves the section empty with the add button.']], { size: 15 }));
  push(H3('4.8.2 Liabilities (credit cards and other loans)'));
  push(table([2000, 2300, 1100, W - 5400], ['List', 'Field label (verbatim)', 'Kind', 'Notes'], ['cards', 'loans'].flatMap(lk => LD[lk].f.map((f, i) => { const d = FI[lk + '.' + f]; return [i ? '' : LD[lk].em + ' ' + LD[lk].t + ' · button "' + LD[lk].add + '" · upload "' + LD[lk].up + '"', d.l, d.type === 'eur' ? '€ amount' : d.type === 'pct' ? '% (decimal)' : 'Text', d.opt ? 'Optional' : 'Always shown; blank counts as €0']; })), { size: 14 }));
  ['**Totals feed the engine as the sum** of the items, with the card and other-loan split kept (credit-card balance and repayment, other-loan balance and repayment). The APR of a group is the average of the items\' rates weighted by the amount owed; items without a rate do not count.',
   '**Worked-out repayment** (§15): a card or loan with no, or too small, a repayment still gets the line "' + (A0.afterUplToast ? '' : '') + 'Worked out from your figures: {€} a month clears it in 5 years, because …" (4.5), shown once under the list.'].forEach(t => push(B(t)));
  push(imgGrid([{ file: 'L-liab-blank.png', caption: 'Liabilities, nothing entered yet' }, { file: 'L-liab-sample.png', caption: 'Liabilities, sample customer (items from statements)' }, { file: 'L-liab-afterupl.png', caption: 'After a per-item upload' }], 3, 1000));
  push(H3('4.8.3 Protection'));
  const PB = A.protBlank, PS = A.protSample;
  push(table([2300, W - 2300], ['Part', 'Copy and behaviour (verbatim)'], [
    ['Header', PB.head.replace(/^‹ Back/, '')],
    ['Lead-in', '"' + PB.lead[0] + '" then "' + PB.lead[1] + '"'],
    ['Under the header', '"' + PB.note + '" (no generic upload at the top of this section: the Upload / Type it switch is not shown)'],
    ['Each type', PB.fields.map(f => '"' + f.label + '" (' + f.chips.join(' / ') + ')').join(' · ') + '. A new answer shows "❓ Missing" until chosen.'],
    ['"Yes"', 'Opens the list for that type: ' + ['life', 'ip', 'ci', 'workCover', 'health'].map(t => LD[t].f.map(f => FI[t + '.' + f].l).join(' + ')).filter((v, i, a) => true).map((v, i) => ['Life cover', 'Income protection', 'Serious illness', 'Cover through work', 'Health insurance'][i] + ': ' + v).join('; ') + '. Each item has the upload link "' + LD.life.up + '" ("' + LD.workCover.up + '" for cover through work).'],
    ['Add more', ['life', 'ip', 'ci', 'workCover', 'health'].map(t => '"' + LD[t].add + '"').join(' · ')],
    ['"No" / "Not sure"', 'Hides the list. Cover through work with "Not sure" still shows the hint below.'],
    ['Cover through work', 'Hint (.small, id ph-workCover): "' + M.PROT_HINT.workCover + '" Fields: "' + FI['workCover.amount'].l + '" or "' + FI['workCover.mult'].l + '"; a multiple is turned into an amount using the customer\'s yearly income (e.g. 3 × ' + F.eur(58000) + ' = ' + F.eur(174000) + '). Both blank counts as nothing.'],
    ['Totals', 'Life cover and cover through work are summed (existing cover for the cover estimator); income protection a month; serious illness; health insurance a year.']], { size: 15 }));
  push(imgGrid([{ file: 'L-prot-blank.png', caption: 'Protection, nothing answered' }, { file: 'L-prot-work.png', caption: 'Cover through work: hint and multiple of salary' }, { file: 'L-prot-sample.png', caption: 'Protection, sample customer' }], 3, 1000));
  push(H3('4.8.4 Pensions and the per-item upload'));
  push(table([2000, 2600, 1100, W - 5700], ['List', 'Field label (verbatim)', 'Kind', 'Notes'], LD.pens.f.map((f, i) => { const d = FI['pens.' + f]; return [i ? '' : LD.pens.em + ' ' + LD.pens.t + ' · button "' + LD.pens.add + '" · upload "' + LD.pens.up + '"', d.l, d.type === 'eur' ? '€ amount' : 'Text', (d.opt ? 'Optional. ' : 'Counts as €0 if blank. ') + (d.hint || '')]; }), { size: 14 }));
  ['**Pensions are separate items**: value, monthly payment and own share are each summed by the engine. A blank own share uses the share chosen in Your assumptions; an item with a typed own share uses it (never more than that item\'s monthly payment). The own-share box is hidden for a customer who is not working.',
   '**Per-item upload**: the link opens the document reader for that one item (sample documents: ' + ['cards', 'loans', 'pens', 'life', 'ip', 'ci', 'workCover', 'health'].map(k => '"' + ID[k].title + '"').join(', ') + '). The confirm screen reads "' + A.upl.cur.replace(/^PU-confirm · /, '') + '"; its rows are "' + A.upl.text + '"; buttons "' + A.upl.foot.replace(/\n/g, '" · "') + '". After "Looks right, add them" the item shows the tags "From document · {n}%", the toast "' + A.afterUplToast.replace(/^\W+/, '') + '" and the row "' + A.afterUpl.lists[0].items[0].docRow + '". Precedence is as in 4.5: a typed figure is kept under a statement figure ("You typed … Your statement says …"), and "Remove statement" brings it back.',
   'A pension statement over 12 months old shows "' + ID.pens.old + '" (tag "Needs a look").'].forEach(t => push(B(t)));
  push(imgGrid([{ file: 'L-pens-sample.png', caption: 'Pension, sample customer' }, { file: 'L-upl-confirm.png', caption: 'Per-item upload: confirm screen' }, { file: 'E-card-pens.own.png', caption: 'Example card on an item field' }], 3, 1000));
  push(H2('4.9 A saved section is complete; blanks are optional (journey-spec §19.3)'));
  const H1_ = A0.hubFresh, H2_ = A0.hubSaved, H3_ = A0.hubBlankSaved;
  ['**Saving completes the section.** "Save this section" (the gold button at the foot of every Your finances section; toast "{section} saved") marks the section Done, even with blank fields. Blank figures count as €0 and stay visible as optional. **The customer never has to type 0.**',
   'A note under the header of every section except About you: "' + A.liabBlank.blank + '"',
   'Hub status words: ' + H1_.cards.map(c => c.t + ' = ' + c.st).join(', ') + ' at the start; after saving Liabilities with a card and Assets with every field blank: ' + H3_.map(c => c.t + ' = ' + c.st).join(', ') + '.',
   '**Checklist wording** (Check your details, step 7, and My money · To sharpen your plan): ❓ items read "' + A0.p4.rows.find(r => /optional/.test(r.line)).line + '" and, in My money, "· optional" after the field name; ⚠️ Needs a look is unchanged. A section left entirely empty is still one row ("· skipped", "Not added yet, so it counts as €0 for now"; Protection "Not added yet"), with "Add now" and "Leave for my adviser". A saved section with blank fields does not block "See my results".'].forEach(t => push(B(t)));
  push(imgGrid([{ file: 'L-hub-saved.png', caption: 'Hub after saving two sections' }, { file: 'L-p4-optional.png', caption: 'Check your details: Missing · optional' }], 2, 900));
  push(H2('4.10 Workbook: the sheet "Your lists" and the calculators that use it (journey-spec §19.2 to §19.5)'));
  const XLS = XL._lists, LR = XLS.rows;
  push(P('"' + XLS.intro + '"', { size: 16 }));
  push(table([3500, 2000, W - 5500], ['Total (label)', 'Defined name', 'Sums'], LR.filter(r => r[1][1].length && /Total|Avg/.test(r[1][1][0] + (r[2][1] || []).join(''))).concat(LR.filter(r => !r[1][1].length && (r[2][1] || []).length && /Total|Avg/.test(r[2][1].join()))).map(r => { const nmx = [].concat(...r.map(c => c[1])).join(', '); return [r[0][0].replace(/\s+\[.*$/, '').replace(/^$/, r[1][0].replace(/\s+\[.*$/, '')), nmx, r[1][0].replace(/\s+\[.*$/, '')]; }).filter(r => r[1]), { size: 14 }));
  push(P('Item rows: Cards and Loans (8 each): lender (optional), owed, repaid a month, APR (optional); Pensions (8): name, value today, paid in each month, own share, own share used; Protection: life cover (4: amount, term), cover through work (4: amount, or multiple of salary), income protection (4: monthly benefit, term), serious illness (4: amount, term), health insurance (4: yearly premium). Blank = €0; never type 0.', { size: 16 }));
  const FB = XL._fallback, FBN = { C12: 'Retirement projection', C13: 'Contribution impact', C14: 'AVC impact', C21: 'Life cover estimator', C24: 'Net worth', C25: 'Monthly surplus' };
  push(table([1900, 1000, 3300, W - 6200], ['Calculator', 'Cell', 'Input (workbook label)', 'Falls back to (when the yellow cell is left blank)'], Object.entries(FB).flatMap(([c, l]) => l.map(([cellN, lab, nms], i) => [i ? '' : c + ' ' + FBN[c], cellN, lab, nms.join(' + ')])), { size: 14 }));
  push(P('**Typing in a calculator always wins**: the list total is used only while the calculator\'s own yellow cell is blank. **C27 and C28 are not fed** by the lists (one debt at a time, typed in the tool). In the prototype the same totals are the Your finances totals that pre-fill the calculators (section 4.7 and each calculator\'s pre-fill table).', { size: 18 }));
}
