// Result-card specification for every calculator, transcribed from CALCS[].run() in the prototype (Irish rules 2026 build).
// Template syntax: {Name} = dynamic value (placeholder table; names follow the workbook's defined names where one exists);
// «A|B» = one of the options (rule in "Shown when"); an empty option = nothing shown.
const TYPES = {
  eur: ['€ amount', 'Whole euros, rounded, en-IE thousands commas, e.g. €1,074. Negative: "−€1,931" (U+2212 minus sign before €).'],
  seur: ['Signed € amount', '"+" or "−" (U+2212) in front, then the € amount, e.g. +€170, −€161, +€0.'],
  int: ['Whole number', 'Integer, no separators.'],
  num: ['Number as entered', 'The value as held (slider step or typed figure), no trailing zeros, e.g. 4, 3.85, 0.6.'],
  d1: ['1 decimal', 'Always one decimal place, e.g. 2.5, 8.0.'],
  d2: ['2 decimals', 'Always two decimal places, e.g. 3.75, 1.00.'],
  pct: ['Percent', 'A rate as a percent, up to 2 decimals, no trailing zeros, e.g. 2%, 3.9%, 2.75%.'],
  yrs: ['Duration', 'From months: "N yr" / "N yrs", plus " M mo" when M > 0; under 12 months "1 month" / "M months" (e.g. 2 yrs 5 mo, 1 yr, 0 months).'],
  yrn: ['Years', '"1 year" or "N years" (the number as entered).'],
};
const NO = 'Enter your inflation rate';
const BT = 'Before tax: deposit interest pays DIRT at 33%; investment funds and life policies pay exit tax at 38% (plus 8-year deemed disposal). No tax is taken off here.';
const INFL = { infl: ['pct', 'Inflation rate the customer chose (shared by every tool and the plan; blank until picked)'] };
const yrsOr = (extra) => [['{T}', 'Under 1,200 months'], ['Over 100 years', 'More than 1,200 months']].concat(extra || []);
const SPEC = {
 borrow: { xin: { rate: 'Interest_Rate', term: 'Term_Years', xdep: 'Extra_Deposit' },
  ph: { Home_Price: ['eur', 'Homes up to about'], Income_Multiple: ['num', '4 (first-time buyer) or 3.5'], Buying_Fees: ['eur', 'Buying fees (Your assumptions, suggested €3,000)'], Max_Loan: ['eur', 'Most you could borrow'], Borrow_By_Income: ['eur', 'Borrowing allowed by income'], Stamp_Duty: ['eur', 'Stamp duty on that price'], Total_Deposit: ['eur', 'Deposit + what-if extra'], Monthly_Repayment: ['eur', 'Monthly repayment (illustrative)'] },
  lbl: [['Homes up to about', 'Always']], val: [['{Home_Price}', 'Always']],
  line: [['Central Bank rules: up to {Income_Multiple}× income for «first-time|second and subsequent» buyers, and at least a 10% deposit (90% loan-to-value). Your deposit also pays the stamp duty (1% up to €1m) and buying fees ({Buying_Fees}, your assumption). Here «your deposit|your income» sets the amount. Lenders can lend above these limits for a small share of loans each year, so some buyers get an exception. Your lender decides.', '"first-time" when First-time buyer? = Yes. "your deposit" when the deposit limit is lower (Limit_Set_By = "Your deposit"), else "your income" (a tie shows "your income").']],
  rows: [['Most you could borrow', [['{Max_Loan}', '']], 'Always'], ['Borrowing allowed by income ({Income_Multiple}×)', [['{Borrow_By_Income}', '']], 'Always'], ['Stamp duty on that price (paid from your deposit)', [['{Stamp_Duty}', '']], 'Always'], ['Your deposit', [['{Total_Deposit}', '']], 'Always'], ['Monthly repayment (illustrative)', [['{Monthly_Repayment}', '']], 'Always']],
  goal: 'Spending goal "Buy a home (deposit goal)" 🏡: amount = 10% deposit + stamp duty + fees (Plan_Goal_Amount), already saved = your deposit, in 3 years. Button "Add it".',
  states: ['First-time buyer? is a Yes/No chip pair (no slider, no decimals).', 'A deposit smaller than the buying fees leaves nothing for the price: the headline can be €0.'] },
 repayment: { xin: { dr: 'Rate_Change' },
  ph: { New_Rate: ['d2', 'Rate + what-if change, never below 0%'], Repayment_If_Changed: ['eur', 'What-if monthly repayment'], Change_Abs: ['eur', 'Size of the change (what-if − now), always positive'], Actual_Repayment: ['eur', 'The stated monthly repayment (statement or typed)'], Monthly_Repayment: ['eur', 'Monthly repayment (stated figure if in use, else the formula)'], Change_Per_Year: ['seur', 'What if: change over a year'], Term_Years: ['yrn', 'Term'], Interest_Rate: ['d2', 'Interest rate'], Formula_Repayment: ['eur', 'Repayment by formula (standard annuity)'], T: ['yrs', 'Mortgage free in (from Months_To_Pay)'], Total_Interest: ['eur', 'Total interest'], Total_Repaid: ['eur', 'Total repaid'] },
  lbl: [['Monthly repayment', 'What-if 0, no stated repayment'], ['Your monthly repayment', 'What-if 0, a stated repayment is in use'], ['If your rate changed to {New_Rate}%', '"If rates changed by" is not 0']],
  val: [['{Monthly_Repayment}', 'What-if 0'], ['{Repayment_If_Changed}', 'What-if not 0']],
  line: [['Over {Term_Years} at {Interest_Rate}%, using the standard repayment formula.', 'What-if 0, no stated repayment'], ['From «your statement|your figures».« The standard formula on these figures gives about {Formula_Repayment}; we use your lender\'s figure.|»', 'What-if 0 and a stated repayment is in use. Second sentence only when the formula differs by €5 or more.'], ['What-if: your repayment would be about {Repayment_If_Changed} a month, {Change_Abs} «more|less» than «the {Actual_Repayment} on «your statement|your figures»|now».« With a stated repayment this is an approximation: it moves by the same amount as the standard formula would.|»', 'What-if not 0. Last sentence only with a stated repayment.']],
  rows: [['Mortgage free in', yrsOr([['Never at this repayment', 'Repayment does not cover the interest']]), 'What-if 0'], ['Total interest', [['{Total_Interest}', ''], ['—', 'Never at this repayment']], 'What-if 0'], ['Total repaid', [['{Total_Repaid}', ''], ['—', 'Never at this repayment']], 'What-if 0'], ['Repayment now', [['{Monthly_Repayment}', '']], 'What-if not 0'], ['Change over a year', [['{Change_Per_Year}', '']], 'What-if not 0']],
  goal: 'Spending goal "Buy a home (deposit goal)" 🏡: amount = the deposit for this loan (loan × 10 ÷ 90), in 3 years. Button "Add it".',
  states: ['Statement precedence: if Mortgage amount, Interest rate and Term are all still pre-filled (not moved or typed) and Your finances holds a stated monthly repayment (statement or typed, not an estimate), that figure is the repayment. "From your statement." / "From your figures." tells the customer which.', 'Payoff uses whole months (NPER rounded up); over 1,200 months shows "Over 100 years"; a repayment that does not cover the interest shows "Never at this repayment".', 'The what-if rate never goes below 0%.'] },
 deposit: { xin: {},
  ph: { T: ['yrs', 'Time to your deposit (Months_To_Deposit, rounded up)'], Total_Needed: ['eur', 'Total you need'], Deposit_Needed: ['eur', 'Deposit'], Stamp_Duty: ['eur', 'Stamp duty'], Buying_Fees: ['eur', 'Buying fees (Your assumptions)'], Saved: ['eur', 'Saved so far'], Monthly_Saving: ['eur', 'Monthly saving + what-if extra'], Still_To_Save: ['eur', 'Still to save'] },
  lbl: [['Time to your deposit', 'Always']], val: [['{T}', 'Still to save > 0'], ['You have your deposit', 'Still to save = 0']],
  line: [['You need {Total_Needed} (deposit {Deposit_Needed}, stamp duty {Stamp_Duty} and fees {Buying_Fees}) and have {Saved}.« Saving {Monthly_Saving} a month closes the gap (no interest and no house-price rises assumed).|» The Central Bank minimum deposit is 10%.', 'The "Saving…" sentence only while there is still something to save.']],
  rows: [['Total you need', [['{Total_Needed}', '']], 'Always'], ['Deposit', [['{Deposit_Needed}', '']], 'Always'], ['Stamp duty', [['{Stamp_Duty}', '']], 'Always'], ['Still to save', [['{Still_To_Save}', '']], 'Always']],
  goal: 'Spending goal "Home deposit" 🔑: amount = total you need, already saved = saved so far, in (months ÷ 12, rounded up, at least 1) years.',
  states: ['Deposit needed starts at 10% (the Central Bank minimum; the slider cannot go lower).'] },
 overpay: { xin: {},
  ph: { T: ['yrs', 'Duration (months shown as yrs/mo)'], Repayment_Now: ['eur', 'Repayment now (stated figure if in use, else formula)'], Extra: ['eur', 'Extra each month'], Interest_Saved: ['eur', 'Interest saved'] },
  lbl: [['Mortgage free sooner by', 'Always']], val: [['{T}', 'Both repayments clear the mortgage (Months_Sooner)'], ['No change', 'Extra 0'], ['—', 'A repayment does not clear the mortgage']],
  line: [['Paying {Extra} extra a month on top of {Repayment_Now}« (from «your statement|your figures»)|» could save about «{Interest_Saved}|—» in interest (illustrative; check your lender\'s overpayment terms).', 'Bracket only with a stated repayment (rule as C02).'], ['Your repayment of {Repayment_Now} doesn\'t clear the mortgage: not at this repayment.', 'The current repayment does not clear the mortgage.']],
  rows: [['Mortgage free now in', yrsOr([['Not at this repayment', 'Repayment does not cover the interest']]), 'Always'], ['With the extra', yrsOr([['—', 'Never']]), 'Always'], ['Interest saved', [['{Interest_Saved}', ''], ['—', 'Either never clears']], 'Always']],
  goal: 'Milestone "Mortgage free" 🔑 in (months with the extra ÷ 12, rounded up) years, no cash amount. No goal if it never clears.',
  states: ['Stated repayment rule as C02 (fields Mortgage balance, Interest rate, Years left).'] },
 ratechange: { xin: {},
  ph: { Monthly_Change: ['seur', 'Monthly change'], New_Rate: ['d2', 'Current rate + change, never below 0%'], Repayment_After: ['eur', 'After change'], Repayment_Now: ['eur', 'Now (stated figure if in use)'], Yearly_Change: ['seur', 'Change over a year'] },
  lbl: [['Monthly change', 'Always']], val: [['{Monthly_Change}', 'Always']],
  line: [['What-if: if your rate changed to {New_Rate}%, your repayment would be about {Repayment_After} a month instead of {Repayment_Now}« (from «your statement|your figures»)|».', 'Bracket only with a stated repayment.']],
  rows: [['Now', [['{Repayment_Now}', '']], 'Always'], ['After change', [['{Repayment_After}', '']], 'Always'], ['Change over a year', [['{Yearly_Change}', '']], 'Always']],
  goal: null, states: ['A fall shows "−€158" and "−€1,902"; no change shows "+€0".'] },
 term: { xin: {},
  ph: { Interest_Difference: ['eur', 'Interest difference'], Short: ['num', 'The shorter term'], Term_A: ['num', 'Term A'], Term_B: ['num', 'Term B'], Monthly_A: ['eur', ''], Monthly_B: ['eur', ''], Interest_A: ['eur', ''], Interest_B: ['eur', ''] },
  lbl: [['Interest difference', 'Always']], val: [['{Interest_Difference}', 'Always']],
  line: [['The {Short}-year term costs more each month but less interest overall.', 'Terms differ'], ['Both terms are the same.', 'Term A = Term B']],
  rows: [['{Term_A}-year monthly', [['{Monthly_A}', '']], 'Always'], ['{Term_B}-year monthly', [['{Monthly_B}', '']], 'Always'], ['{Term_A}-year total interest', [['{Interest_A}', '']], 'Always'], ['{Term_B}-year total interest', [['{Interest_B}', '']], 'Always']],
  goal: null, states: [] },
 rentbuy: { xin: {},
  ph: { Years: ['yrn', 'Years to compare'], Home_Equity: ['eur', 'Home equity'], Rent_Paid: ['eur', 'Rent paid (rising)'], Rent_Rise: ['pct', 'Rent rises (Your assumptions)'], Buying_Costs: ['eur', 'Buying costs that don\'t build equity'], Deposit_Used: ['eur', 'Deposit used (at least 10% of the price)'], Home_Value: ['eur', 'Home value'], Balance_After: ['eur', 'Mortgage left'] },
  lbl: [['Home equity after {Years}', 'Always']], val: [['{Home_Equity}', 'Always']],
  line: [['Illustration only: renting costs about {Rent_Paid} over {Years} (rent rising {Rent_Rise} a year), while the costs of buying that don\'t build equity are about {Buying_Costs}: interest, upkeep, stamp duty, fees and what your deposit could have earned. Local Property Tax and insurance are not included.« The deposit must be at least 10% of the price, so {Deposit_Used} is used.|»', 'Last sentence only when the deposit typed is below 10% of the price.']],
  rows: [['Rent paid (rising each year)', [['{Rent_Paid}', '']], 'Always'], ['Buying costs that don\'t build equity', [['{Buying_Costs}', '']], 'Always'], ['Home value', [['{Home_Value}', '']], 'Always'], ['Mortgage left after the years', [['{Balance_After}', '']], 'Always']],
  goal: 'Spending goal "Buy a home (deposit goal)" 🏡: amount = deposit used + stamp duty + fees, in 3 years.',
  states: ['Rent rise, house-price rise (pre-fills the slider), upkeep, buying fees and what the deposit could earn come from Your assumptions.'] },
 goalplanner: { xin: { r: 'Growth_Rate' },
  ph: Object.assign({ Monthly_Saving: ['eur', 'Monthly amount to save'], Future_Cost: ['eur', 'Will cost about'], Years: ['yrn', 'Years until the goal'], Goal_Amount: ['eur', 'Goal in today\'s prices'], Saved_Grows_To: ['eur', 'Your savings grow to'], Still_Needed: ['eur', 'Still needed at the goal year'] }, INFL),
  lbl: [['Monthly amount to save', 'Always']], val: [['{Monthly_Saving}', 'Inflation chosen'], [NO, 'No inflation rate yet']],
  line: [['«Your goal will cost about {Future_Cost} in {Years}. Setting aside about {Monthly_Saving} a month could reach it. Prices rising {infl} a year, your choice.|Pick an inflation rate to see what your goal will cost by then and the monthly amount.» ' + BT, 'First part when an inflation rate is chosen, else the prompt. The tax note always follows.']],
  rows: [['Goal in today\'s prices', [['{Goal_Amount}', '']], 'Always'], ['Will cost about (in {Years})', [['{Future_Cost}', ''], [NO, 'No rate']], 'Always'], ['Your savings grow to', [['{Saved_Grows_To}', '']], 'Always'], ['Still needed at the goal year', [['{Still_Needed}', ''], [NO, 'No rate']], 'Always']],
  goal: 'Spending goal "My goal" 🎯: amount = goal in today\'s prices, already saved, in Years.', states: ['Savings covering the goal give €0 a month.'] },
 compound: { xin: {},
  ph: Object.assign({ Grows_To: ['eur', 'Could grow to'], Paid_In: ['eur', 'Paid in'], Growth_Earned: ['eur', 'Illustrative growth'], Value_Today: ['eur', 'Worth in today\'s money'] }, INFL),
  lbl: [['Could grow to', 'Always']], val: [['{Grows_To}', 'Always']],
  line: [['You would put in {Paid_In}. Growth could add about {Growth_Earned} (illustrative, not guaranteed). «Worth about {Value_Today} in today\'s money. Prices rising {infl} a year, your choice.|Pick an inflation rate to see what it\'s worth in today\'s money.» ' + BT, 'Today\'s-money sentences when a rate is chosen, else the prompt.']],
  rows: [['Paid in', [['{Paid_In}', '']], 'Always'], ['Illustrative growth', [['{Growth_Earned}', '']], 'Always'], ['Worth in today\'s money', [['{Value_Today}', ''], [NO, 'No rate']], 'Always']],
  goal: 'Savings pot "Grow my wealth" 📈: amount = value in today\'s money, in Years. Without an inflation rate the sheet says "Choose an inflation rate first" and shows the inflation chips.', states: [] },
 lumpsum: { xin: {},
  ph: Object.assign({ Grows_To: ['eur', 'Value after fees if you start today'], Value_Today: ['eur', 'In today\'s money'], rr: ['d1', 'Real return a year after fees'], g: ['num', 'Growth after fees, %'], Wait_Years: ['yrn', 'Years you might wait'], Cost_Of_Waiting: ['eur', 'Cost of waiting'], Value_Start_Later: ['eur', 'If you start later'], Fees_Cost: ['eur', 'Fees cost'] }, INFL),
  lbl: [['Could grow to« (after fees)|»', 'Switch off. "(after fees)" when Yearly fees is not 0.'], ['In today\'s money« (after fees)|»', 'Switch on.']],
  val: [['{Grows_To}', 'Switch off'], ['{Value_Today}', 'Switch on, rate chosen'], [NO, 'Switch on, no rate']],
  line: [['«Real return about {rr}% a year ({g}% growth« after fees|», prices rising {infl}). |Pick an inflation rate to see it in today\'s money. |»Waiting {Wait_Years} before starting could mean about «{Cost_Of_Waiting}|' + NO + '» less, which is the cost of waiting. ' + BT, 'Real-return sentence: switch on and a rate chosen. Prompt: switch on, no rate. Nothing: switch off.']],
  rows: [['If you start today (after fees)', [['{Grows_To}', '']], 'Always'], ['If you start in {Wait_Years}', [['{Value_Start_Later}', '']], 'Always'], ['Worth in today\'s money', [['{Value_Today}', ''], [NO, 'No rate']], 'Switch on'], ['Fees cost', [['{Fees_Cost}', '']], 'Yearly fees not 0']],
  goal: 'Savings pot "Grow my wealth" 📈 in today\'s money, in Years; blocked ("Choose an inflation rate first") until a rate is chosen.', states: ['Investment statement without charges: Yearly fees = 0 with no tag.'] },
 emergency: { xin: { mt: 'Months_Wanted' },
  ph: { Months_Covered: ['d1', 'Months covered, rounded down to 1 decimal'], Target: ['eur', 'Target cushion'], Months_Wanted: ['num', 'Months you want covered'], Still_To_Build: ['eur', 'Still to build'] },
  lbl: [['You currently have', 'Always']], val: [['{Months_Covered} «month|months»', '"month" only for exactly 1.0']],
  line: [['Your target is {Target} ({Months_Wanted} «month|months»). You are {Still_To_Build} away.', 'Still a gap'], ['Your cushion covers {Months_Wanted} «month|months». Great foundation.', 'No gap']],
  rows: [['Target cushion', [['{Target}', '']], 'Always'], ['Still to build', [['{Still_To_Build}', '']], 'Always']],
  goal: 'Safety net "Safety net" 🪂 (a reserve, not a spend): amount = target, already saved = savings, in 2 years. No goal when there is no gap.',
  states: ['Tip under the question: "💡 Ideal emergency fund: 6 months of your monthly spending."', 'Months you want covered is pre-filled from Your assumptions (safety net months: 6, or 3 for a two-income employed couple).'] },
 retirement: { xin: { d: 'Desired_Income', o: 'Other_Income', g: 'Growth_Rate' },
  ph: Object.assign({ Gap_Today: ['eur', 'Illustrative gap in today\'s money'], Fund_Today: ['eur', 'Projected fund in today\'s money'], Target_Today: ['eur', 'Illustrative target in today\'s money'], wage: ['pct', 'Pay rises (Your assumptions)'], Projected_Fund: ['eur', 'Projected fund at retirement'], Retire_Multiple: ['num', 'Target multiple (Your assumptions, 25)'], Bridge_Years: ['yrn', 'Years before the State Pension at 66'], Lump_Sum_Net: ['eur', 'Lump sum after tax'], Retiring_At: ['num', 'Retirement age + what-if'], nra: ['num', 'Normal retirement age on the statement'], proj: ['eur', 'Statement\'s projected value'], Calculated_Fund: ['eur', 'Fund on our assumptions'] }, INFL),
  lbl: [['Illustrative gap (today\'s money)', 'Always']], val: [['{Gap_Today}', 'Gap > 0'], ['On track: no gap', 'No gap'], [NO, 'No rate']],
  line: [['«Pick an inflation rate to compare your fund with the target in today\'s money. |Your projected fund is worth about {Fund_Today} in today\'s money, against a target of {Target_Today}. |On these assumptions your projected fund meets the illustrative target. »«Most pensions can\'t be taken before 60 (PRSA and personal pensions; occupational schemes from 50 only if you have left that job). |»«Above the Standard Fund Threshold (€2.2m in 2026, rising to €2.8m by 2029): the excess is taxed at 40%. |»Contributions are assumed to rise with pay ({wage} a year), as in your plan. The target includes the State Pension you fund yourself for each year you retire before 66. Desired income and the State Pension are before tax: the State Pension is taxable (USC-exempt) and drawdown pays income tax and USC. About 25% of the fund can be taken as a lump sum: the first €200,000 tax-free, the next €300,000 at 20%.', 'First sentence: no rate / gap / no gap. Early warning when retiring before 60. SFT warning when the fund is above €2.2m.']],
  rows: [['Projected fund at retirement« (from your statement)|»', [['{Projected_Fund}', '']], 'Always. "(from your statement)" under the statement rule.'], ['Projected fund in today\'s money', [['{Fund_Today}', ''], [NO, 'No rate']], 'Always'], ['Illustrative target ({Retire_Multiple} × the income you need« + {Bridge_Years} before the State Pension|», today\'s money)', [['{Target_Today}', '']], 'Always; the bridge part when retiring before 66'], ['Lump sum you could take (after tax)', [['{Lump_Sum_Net}', '']], 'Always'], ['Retiring at', [['{Retiring_At}', '']], 'Always'], ['Your statement projects (age {nra})', [['{proj}', '']], 'Pension statement with a projection'], ['On our assumptions (age {Retiring_At})', [['{Calculated_Fund}', '']], 'Pension statement with a projection']],
  goal: 'Updates the retirement goal (no new goal): "Your retirement goal becomes {€ income} a year from age {age}. No new goal is added." Button "Update it".',
  states: ['Statement rule: the statement\'s projection is used only when it has one, the retirement age (with what-if) equals the statement\'s normal retirement age, "Save more" is 0 and Your age, Pension value, Contributions and Growth are untouched. A statement projection in future money is deflated like ours; one in today\'s money is used as is.', 'Other yearly income is pre-filled with the State Pension estimate (€299.30 a week × 52 × your expectation).'] },
 contrib: { xin: { g: 'Growth_Rate', tr: 'Tax_Rate', age: 'Age', ex: 'Existing_Pension_Year' },
  ph: Object.assign({ Grows_To: ['eur', 'Could add to your pension'], Extra_Per_Month: ['eur', 'Extra per month'], Net_Cost_Per_Month: ['eur', 'Cost after tax relief, a month'], Tax_Rate: ['num', '20 or 40'], Relief_Pct: ['int', 'Age-related relief limit %'], Relief_Limit_Year: ['eur', 'Relief limit a year'], Relief_Per_Month: ['eur', 'Tax relief a month'], Value_Today: ['eur', 'Worth in today\'s money'] }, INFL),
  lbl: [['Could add to your pension', 'Always']], val: [['{Grows_To}', 'Always']],
  line: [['An extra {Extra_Per_Month} a month could cost about {Net_Cost_Per_Month} after tax relief at {Tax_Rate}% (USC and PRSI still apply). Relief only applies within your age limit ({Relief_Pct}% of earnings up to €115,000, less what you already pay in: {Relief_Limit_Year} a year).' + '« Prices rising {infl} a year, your choice.|»', 'Last sentence when a rate is chosen.']],
  rows: [['Extra per month', [['{Extra_Per_Month}', '']], 'Always'], ['Cost to you after tax relief, a month', [['{Net_Cost_Per_Month}', '']], 'Always'], ['Tax relief a month', [['{Relief_Per_Month}', '']], 'Always'], ['Worth in today\'s money', [['{Value_Today}', ''], [NO, 'No rate']], 'Always']],
  goal: 'Raises the plan\'s pension contribution (not a spending goal): "Your plan\'s pension contribution goes up by {€} a month. Pension money is not a spending goal." Button "Raise it".',
  states: ['Your tax rate is a 20% / 40% chip pair, pre-filled from income and tax status.', 'The relief-limit figure in the copy is the full age limit; the relief itself also subtracts what you already pay in.'] },
 avc: { xin: { g: 'Growth_Rate', tr: 'Tax_Rate', age: 'Age', ex: 'Existing_Pension_Year' },
  ph: Object.assign({ Grows_To: ['eur', 'Could add'], AVC: ['eur', 'AVC per month'], Net_Cost_Per_Month: ['eur', 'Monthly cost after relief'], Relief_Pct: ['int', 'Age-related relief limit %'], Paid_In: ['eur', 'Paid in'], Net_Cost: ['eur', 'Net cost to you'], Relief_Per_Month: ['eur', 'Tax relief a month'], Value_Today: ['eur', 'Worth in today\'s money'] }, INFL),
  lbl: [['Could add', 'Always']], val: [['{Grows_To}', 'Always']],
  line: [['Each {AVC} AVC could cost about {Net_Cost_Per_Month} after tax relief. The age-related limit ({Relief_Pct}% of earnings up to €115,000) covers your main scheme and AVCs together, so enter what you already pay in.« Prices rising {infl} a year, your choice.|»', 'Last sentence when a rate is chosen.']],
  rows: [['Paid in', [['{Paid_In}', '']], 'Always'], ['Net cost to you', [['{Net_Cost}', '']], 'Always'], ['Tax relief a month', [['{Relief_Per_Month}', '']], 'Always'], ['Worth in today\'s money', [['{Value_Today}', ''], [NO, 'No rate']], 'Always']],
  goal: 'Raises the plan\'s pension contribution: goal name "Raise my pension contribution (AVC)", button "Raise it".', states: [] },
 lastmoney: { xin: {},
  ph: Object.assign({ Years_Lasting: ['yrn', 'Years the money lasts (cap 60)'], w: ['eur', 'Yearly withdrawal (first year)'], Lasts_To_Age: ['int', 'Lasts to about age'], Plan_To_Age: ['int', 'Plan to age (Your assumptions)'], Withdrawal_Rate: ['d1', 'Withdrawal rate (first year), %'] }, INFL),
  lbl: [['Could last about', 'Always']], val: [['{Years_Lasting}', 'Under 60 years'], ['60+ years', '60 or more'], [NO, 'No rate']],
  line: [['Withdrawing {w} at the «start|end» of each year«, rising with prices ({infl} a year): money lasts to about age {Lasts_To_Age}«, before the end of your plan ({Plan_To_Age}).|.»|. Pick an inflation rate to see how long it lasts.» Before tax: ARF and vested PRSA withdrawals pay income tax and USC (and PRSI before 66). From 61 you must take at least 4% a year (5% from 71). An illustration, not a guarantee.', '"start"/"end" from Your assumptions (drawdown timing). The end-of-plan clause when the age is below Plan to age.']],
  rows: [['Money lasts to about age', [['{Lasts_To_Age}', ''], [NO, 'No rate']], 'Always'], ['Withdrawal rate (first year)', [['{Withdrawal_Rate}%', '']], 'Always']],
  goal: null, states: ['At the 60-year cap the age shown is start age + 60 (e.g. "about age 126").'] },
 drawdown: { xin: {},
  ph: Object.assign({ T: ['yrn', 'Years the money lasts'], g1: ['pct', 'Cautious growth (Your assumptions)'], g2: ['pct', 'Balanced growth'], g3: ['pct', 'Growth growth'] }, INFL),
  lbl: [['Balanced scenario lasts', 'Always']], val: [['{T}', 'Under 60'], ['60+ years', '60 or more'], [NO, 'No rate']],
  line: [['Three illustrative growth scenarios (your assumptions); withdrawals at the «start|end» of each year«, rising with prices ({infl} a year).|. Pick an inflation rate to see them.» Real returns vary year to year. Before tax.', 'As C15.']],
  rows: [['Cautious ({g1})', [['{T}', ''], ['60+ years', ''], [NO, '']], 'Always'], ['Balanced ({g2})', [['{T}', ''], ['60+ years', ''], [NO, '']], 'Always'], ['Growth ({g3})', [['{T}', ''], ['60+ years', ''], [NO, '']], 'Always']],
  goal: null, states: [] },
 realreturn: { xin: {},
  ph: Object.assign({ Future_Value: ['eur', 'Future value'], Value_Today: ['eur', 'In today\'s money'], r: ['num', 'Return a year'], rr1: ['d1', 'Real return, 1 decimal'], rr2: ['num', 'Real return, up to 2 decimals'] }, INFL),
  lbl: [['Future value', 'No rate'], ['In today\'s money', 'Rate chosen']], val: [['{Future_Value}', 'No rate'], ['{Value_Today}', 'Rate chosen']],
  line: [['Pick an inflation rate to see the real return and what it\'s worth in today\'s money. ' + BT, 'No rate'], ['A {r}% return with prices rising {infl} is really about {rr1}% a year. ' + BT, 'Rate chosen']],
  rows: [['Future value', [['{Future_Value}', '']], 'Always'], ['In today\'s money', [[NO, '']], 'No rate'], ['Real return a year', [['{rr2}%', ''], [NO, 'No rate']], 'Always'], ['Value in today\'s money', [['{Value_Today}', '']], 'Rate chosen']],
  goal: null, states: [] },
 regularinvest: { xin: {},
  ph: Object.assign({ Value_After_Fees: ['eur', 'Could grow to (after fees)'], Value_Today: ['eur', 'In today\'s money'], rr: ['d1', 'Real return after fees'], g: ['num', 'Growth after fees, %'], f: ['num', 'Yearly fees %'], Fees_Cost: ['eur', 'Fees cost'], Years: ['yrn', 'Years'], Paid_In: ['eur', 'Paid in'], Value_Before_Fees: ['eur', 'Before fees'] }, INFL),
  lbl: [['Could grow to (after fees)', 'Switch off'], ['In today\'s money (after fees)', 'Switch on']], val: [['{Value_After_Fees}', 'Switch off'], ['{Value_Today}', 'Switch on, rate chosen'], [NO, 'Switch on, no rate']],
  line: [['«Real return about {rr}% a year ({g}% growth after fees, prices rising {infl}). |Pick an inflation rate to see it in today\'s money. |»Fees of {f}% a year could cost about {Fees_Cost} over {Years}. ' + BT, 'As C10.']],
  rows: [['Paid in', [['{Paid_In}', '']], 'Always'], ['Before fees', [['{Value_Before_Fees}', '']], 'Always'], ['Fees cost', [['{Fees_Cost}', '']], 'Always'], ['Worth in today\'s money', [['{Value_Today}', ''], [NO, 'No rate']], 'Switch on']],
  goal: 'Savings pot "Grow my wealth" 📈 in today\'s money; blocked until a rate is chosen.', states: [] },
 fees: { xin: {},
  ph: { Difference: ['eur', 'Difference'], Fee_Gap: ['d2', 'Difference between the fees, %'], a: ['num', 'Fee A %'], b: ['num', 'Fee B %'], Value_With_Fee_A: ['eur', ''], Value_With_Fee_B: ['eur', ''] },
  lbl: [['Difference', 'Always']], val: [['{Difference}', 'Always']],
  line: [['A {Fee_Gap}% difference in yearly fees could change the outcome by about {Difference}. Before tax.', 'Always']],
  rows: [['With {a}% fees', [['{Value_With_Fee_A}', '']], 'Always'], ['With {b}% fees', [['{Value_With_Fee_B}', '']], 'Always']],
  goal: null, states: [] },
 riskreturn: { xin: { s: 'Style' },
  ph: { Middle: ['eur', 'Middle outcome'], fall: ['int', 'Difficult_Year_Fall as a whole %'], Weaker: ['eur', ''], Stronger: ['eur', ''] },
  lbl: [['«Cautious|Balanced|Growth» · middle outcome', 'Style chip 1 / 2 / 3']], val: [['{Middle}', 'Always']],
  line: [['Illustrative only. About a 1-in-20 bad year could see a fall of around {fall}%. Longer timeframes narrow the range; "weaker" is roughly a 1-in-6 chance of doing worse, not the worst case.', 'Always']],
  rows: [['Weaker outcome', [['{Weaker}', '']], 'Always'], ['Middle outcome', [['{Middle}', '']], 'Always'], ['Stronger outcome', [['{Stronger}', '']], 'Always']],
  goal: null, states: ['Style is three chips ("1 · Cautious", "2 · Balanced", "3 · Growth"); growth and volatility per style come from Your assumptions.'] },
 lifecover: { xin: {},
  ph: { Cover_Gap: ['eur', 'Illustrative cover gap'], Income_Need: ['eur', 'Income need after the State pension'], Debts_To_Clear: ['eur', ''], Already_Have: ['eur', ''], Share: ['int', 'Life cover share of income (Your assumptions)'], Income_Replacement: ['eur', ''] },
  lbl: [['Illustrative cover gap', 'Always']], val: [['{Cover_Gap}', 'Always']],
  line: [['A rough estimate of the gap between what your family might need and what you have. A protection expert can refine this. Cohabiting partners can now qualify for the State Bereaved Partner\'s Pension.', 'Gap > 0'], ['Your existing cover and savings look like they meet this rough estimate.', 'No gap']],
  rows: [['Income your family would need (after the State pension)', [['{Income_Need}', '']], 'Always'], ['Debts to clear', [['{Debts_To_Clear}', '']], 'Always'], ['Existing cover + savings', [['{Already_Have}', '']], 'Always'], ['Income replacement before State pension ({Share}%)', [['{Income_Replacement}', '']], 'Always']],
  goal: 'Notes a protection need for the adviser (not money to save): "We note a life cover need of {€} for your adviser. Cover is bought for a premium; it is not money to save." Button "Note it". None when there is no gap.',
  states: ['State-benefit netting: the State survivor\'s pension (€259.50 a week, Your assumptions) × 52 is taken off the yearly income need before multiplying by the years.', 'Mortgage protection Yes (default) removes the mortgage from the debts to clear.'] },
 incomegap: { xin: {},
  ph: { cope: ['d1', 'Months you could cope'], ib: ['eur', 'Illness Benefit a week'], Monthly_Gap: ['eur', 'Monthly gap after Illness Benefit'], IP_Needed: ['eur', 'Income protection to aim for'], sv: ['d1', 'Savings would cover, months'], sp: ['num', 'Months of sick pay'] },
  lbl: [['You could cope for about', 'Always']], val: [['{cope} months', 'Gap > 0'], ['Indefinitely', 'Illness Benefit covers the spending']],
  line: [['After Illness Benefit ({ib} a week, if you have enough PRSI; lower if you earned under €300 a week) you would have a gap of about {Monthly_Gap} a month. Income protection is designed for this. Statutory sick pay is only 5 days a year.', 'Gap > 0'], ['Illness Benefit ({ib} a week, if you have enough PRSI) would cover your essential spending.', 'No gap']],
  rows: [['Monthly gap after Illness Benefit', [['{Monthly_Gap}', '']], 'Always'], ['Income protection to aim for, a month', [['{IP_Needed}', '']], 'Always'], ['Savings would cover', [['{sv} months', ''], ['Indefinitely', 'No gap']], 'Always'], ['Sick pay', [['{sp} «month|months»', '']], 'Always']],
  goal: 'Notes an income protection need for the adviser: "We note a income protection need of {€} a month for your adviser. Cover is bought for a premium; it is not money to save." (sic, see Appendix B). Button "Note it".',
  states: ['State-benefit netting: Illness Benefit (€254 a week × 52 ÷ 12 a month) is taken off essential spending; income protection to aim for is capped at 75% of gross income less Illness Benefit.'] },
 mortgageprotect: { xin: {},
  ph: { Cover_Today: ['eur', 'Cover needed today'], Repayment: ['eur', 'Monthly repayment used'], B: ['eur', 'Balance in N years'] },
  lbl: [['Cover needed today', 'Always']], val: [['{Cover_Today}', 'Always']],
  line: [['Mortgage protection usually reduces as your mortgage does. Illustrative balance over time, repaying {Repayment} a month:', 'Repayment covers the interest'], ['Your repayment doesn\'t cover the interest: please check the figures.', 'Stated repayment below the interest']],
  rows: [['In 5 years', [['{B}', ''], ['—', 'Warning']], 'Always'], ['In 10 years', [['{B}', ''], ['—', 'Warning']], 'Always'], ['In 15 years', [['{B}', ''], ['—', 'Warning']], 'Always']],
  goal: null, states: ['Stated repayment rule as C02, without a "(from your statement)" note.'] },
 networth: { xin: {},
  ph: { Net_Worth: ['eur', 'Your net worth'], You_Own: ['eur', ''], You_Owe: ['eur', ''] },
  lbl: [['Your net worth', 'Always']], val: [['{Net_Worth}', 'Always (negative shows −€)']],
  line: [['Everything you own minus everything you owe. Pensions are before tax; property is before selling costs. Track it once or twice a year.', 'Always']],
  rows: [['You own', [['{You_Own}', '']], 'Always'], ['You owe', [['{You_Owe}', '']], 'Always']], goal: null, states: [] },
 surplus: { xin: { inc: 'Take_Home' },
  ph: { Surplus: ['eur', 'Monthly surplus'], pc: ['int', 'Surplus ÷ take-home, %'], Take_Home: ['eur', ''], Going_Out: ['eur', ''] },
  lbl: [['Monthly surplus', 'Always']], val: [['{Surplus}', 'Always']],
  line: [['About {pc}% of your take-home pay is free for goals.', 'Surplus > 0'], ['Nothing left over this month.', 'Surplus = 0'], ['Spending is above income right now. Small changes to lifestyle spending can help.', 'Surplus < 0']],
  rows: [['Take-home', [['{Take_Home}', '']], 'Always'], ['Going out', [['{Going_Out}', '']], 'Always']],
  goal: 'Savings pot "Save my surplus" 🐷: amount = surplus × 12, in 1 year. None when the surplus is 0 or less.', states: [] },
 budget: { xin: { inc: 'Take_Home' },
  ph: { Save: ['eur', 'Save each month'], sum: ['int', 'Total of the three shares'], n: ['int', 'Needs share %'], w: ['int', 'Wants share %'], s: ['int', 'Savings share %'], Needs: ['eur', ''], Wants: ['eur', ''] },
  lbl: [['Save each month', 'Always']], val: [['{Save}', 'Always']],
  line: [['«Your shares add up to {sum}%, not 100%. |»A common starting point: {n}% needs, {w}% wants, {s}% savings and debt. Adjust it to fit your life in Your assumptions.', 'First sentence only when the three shares in Your assumptions do not total 100%.']],
  rows: [['Needs ({n}%)', [['{Needs}', '']], 'Always'], ['Wants ({w}%)', [['{Wants}', '']], 'Always'], ['Savings & debt ({s}%)', [['{Save}', '']], 'Always']], goal: null, states: ['The split comes from Your assumptions (50 / 30 / 20 suggested).'] },
 debtpay: { xin: {},
  ph: { T: ['yrs', 'Debt free in (Months_To_Clear)'], Total_Interest: ['eur', ''], Monthly_Rate: ['d2', 'Monthly rate from the APR, %'] },
  lbl: [['Debt free in', 'Always']], val: [['{T}', 'Clears within 100 years'], ['Never at this repayment', 'Payment does not cover the interest'], ['Over 100 years', 'More than 1,200 months']],
  line: [['You would pay about {Total_Interest} in interest. The APR is a yearly rate: about {Monthly_Rate}% a month.', 'Clears within 100 years'], ['The payment does not cover the interest. Try a higher amount.', 'Never'], ['Payment too low to clear this debt in a reasonable time.', 'Over 100 years']],
  rows: [['Total interest', [['{Total_Interest}', ''], ['—', 'Never']], 'Always']],
  goal: 'None: "Nothing to add · This result doesn\'t create a goal: your plan already repays this debt."', states: ['The APR is an effective yearly rate: monthly rate = (1 + APR)^(1/12) − 1.'] },
 loan: { xin: {},
  ph: { Monthly_Repayment: ['eur', ''], Total_Interest: ['eur', ''], Years: ['yrn', ''], Total_Repaid: ['eur', ''] },
  lbl: [['Monthly repayment', 'Always']], val: [['{Monthly_Repayment}', 'Always']],
  line: [['Total interest of about {Total_Interest} over {Years}. The APR is a yearly rate.', 'Always']],
  rows: [['Total repaid', [['{Total_Repaid}', '']], 'Always'], ['Total interest', [['{Total_Interest}', '']], 'Always']], goal: null, states: ['APR is effective yearly, as C27.'] },
};
// Pre-fill sources (calcPre + statement). [Your finances / plan / Your assumptions, statement]
const PF = {
 borrow: { inc: ['Your finances · Gross yearly income', ''], inc2: ['Your finances · Partner income', ''], dep: ['Saved on a "Buy a home" goal', ''], ftb: ['Your finances · Home: No if it starts "Own…", else Yes', ''], rate: ['Your assumptions · Mortgage rate (3.75%), always', ''] },
 repayment: { loan: ['Your finances · Mortgage balance', 'Mortgage statement · Outstanding balance'], rate: ['Your assumptions · Mortgage rate (always); Your finances · Mortgage rate if stated', 'Mortgage statement · Interest rate'], term: ['Your finances · Years left (25 if unknown)', 'Mortgage statement · Term remaining'] },
 deposit: { saved: ['Saved on a "Buy a home" goal', ''] },
 overpay: { bal: ['Your finances · Mortgage balance', 'Mortgage statement · Outstanding balance'], rate: ['Your assumptions · Mortgage rate; Your finances if stated', 'Mortgage statement · Interest rate'], yrs: ['Your finances · Years left (25 if unknown)', 'Mortgage statement · Term remaining'] },
 ratechange: { loan: ['Your finances · Mortgage balance', 'Mortgage statement · Outstanding balance'], rate: ['Your assumptions · Mortgage rate; Your finances if stated', 'Mortgage statement · Interest rate'], term: ['Your finances · Years left (25 if unknown)', 'Mortgage statement · Term remaining'] },
 term: { loan: ['Your finances · Mortgage balance', 'Mortgage statement · Outstanding balance'], rate: ['Your assumptions · Mortgage rate; Your finances if stated', 'Mortgage statement · Interest rate'], a: ['Your finances · Years left (25 if unknown)', 'Mortgage statement · Term remaining'] },
 rentbuy: { rate: ['Your assumptions · Mortgage rate (always)', ''], g: ['Your assumptions · House prices rise (always)', ''] },
 emergency: { e: ['Living costs + mortgage + debt repayments (with living costs)', ''], mt: ['Your assumptions · Safety net months (always)', ''], s: ['Your finances · Cash savings', ''] },
 incomegap: { e: ['Living costs + mortgage + debt repayments (with living costs)', ''], s: ['Your finances · Cash savings', ''], inc: ['Your finances · Gross yearly income', ''] },
 retirement: { age: ['About you · Age (always)', ''], ra: ['Plan retirement age (always)', 'Plan retirement age, else the statement\'s normal retirement age'], pot: ['Your finances · Pension value', 'Pension statement · Current pension value'], m: ['Your finances · Monthly pension contributions', 'Pension statement · Your + employer contribution'], d: ['Retirement goal amount', ''], o: ['State Pension estimate (always)', 'From PRSI years, rounded to €500'], g: ['Pension growth after charges (always)', 'Growth after the statement\'s charges (if shown)'] },
 contrib: { sal: ['Your finances · Gross yearly income', ''], tr: ['20% / 40% from income and tax status', ''], ex: ['Your own pension contributions × 12', ''], y: ['Plan retirement age − age (always)', 'Retirement age − age'], g: ['Pension growth (always)', 'After the statement\'s charges (if shown)'], age: ['About you · Age (always)', ''] },
 avc: { sal: ['Your finances · Gross yearly income', ''], tr: ['20% / 40% from income and tax status', ''], ex: ['Your own pension contributions × 12', ''], y: ['Plan retirement age − age (always)', 'Retirement age − age'], g: ['Pension growth (always)', 'After the statement\'s charges (if shown)'], age: ['About you · Age (always)', ''] },
 lastmoney: { pot: ['Projected pension at retirement', 'Pension statement · projected value (else current value)'], g: ['Your assumptions · Pension grows once you retire (always)', ''], age: ['Plan retirement age, at least 60 (always)', ''] },
 drawdown: { pot: ['Projected pension at retirement', 'Pension statement · projected value (else current value)'] },
 realreturn: { p: ['Your finances · Investments', 'Investment statement · Total value'] },
 lumpsum: { p: ['Your finances · Investments', 'Investment statement · Total value'], f: ['', 'Investment statement · Annual charges (0, no tag, if not shown)'] },
 regularinvest: { m: ['', 'Investment statement · Monthly amount invested'], f: ['', 'Investment statement · Annual charges (0, no tag, if not shown)'] },
 fees: { p: ['Your finances · Investments', 'Investment statement · Total value'], a: ['', 'Investment statement · Annual charges (0, no tag, if not shown)'] },
 riskreturn: { p: ['Your finances · Investments', 'Investment statement · Total value'], s: ['', 'From shares %: ≥70 → 3, ≥40 → 2, else 1'] },
 lifecover: { inc: ['Your finances · Gross yearly income', ''], y: ['Your assumptions · Life cover years (always)', ''], mort: ['Your finances · Mortgage balance', ''], debt: ['Your finances · Card + loan balances', ''], sav: ['Your finances · Cash + investments', ''], surv: ['Your assumptions · State survivor\'s pension (always)', ''] },
 mortgageprotect: { bal: ['Your finances · Mortgage balance', ''], rate: ['Your assumptions · Mortgage rate; Your finances if stated', ''], y: ['Your finances · Years left (25 if unknown)', ''] },
 networth: { sav: ['Your finances · Cash', ''], inv: ['Your finances · Investments', ''], pen: ['Your finances · Pension value', ''], prop: ['Your finances · Home + other property', ''], mort: ['Your finances · Mortgage balance', ''], loans: ['Your finances · Card + loan balances', ''] },
 surplus: { inc: ['Plan · take-home pay this year ÷ 12', ''], ess: ['Living costs + one-offs ÷ 12 + mortgage', ''], life: ['0 (inside living costs)', ''], debt: ['Debt repayments', ''] },
 budget: { inc: ['Plan · take-home pay this year ÷ 12', ''] },
 debtpay: { b: ['The debt that takes longer to clear (card or loan)', ''], apr: ['Your assumptions · Credit-card rate (always); that debt\'s rate if known', ''], p: ['That debt\'s monthly payment', ''] },
 loan: { apr: ['Your assumptions · Other loans rate (always)', ''] },
};
module.exports = { SPEC, TYPES, PF, NO, BT };
