const { open } = require('./lib');
(async () => { const { browser, page, errors } = await open();
  const setup = () => page.evaluate(() => { S = fresh(); S.shell = true; S.tab = 'explore'; S.xs = []; render(); ACT.calc('borrow'); });
  const h = () => page.evaluate(() => [document.getElementById('co-rate').value, document.getElementById('nh-ck-rate').textContent]);
  await setup(); await page.fill('#co-rate', '9'); console.log('typing (no commit):', await h());
  await page.press('#co-rate', 'Enter'); console.log('after Enter:', await h());
  await page.evaluate(() => document.activeElement.blur()); console.log('after Enter then blur:', await h());
  await setup(); await page.fill('#co-rate', '9'); await page.evaluate(() => document.activeElement.blur()); console.log('blur only:', await h());
  await page.click('#c-term'); console.log('after other interaction:', await h());
  await setup(); await page.fill('#co-rate', '0.5'); await page.evaluate(() => document.activeElement.blur()); console.log('min:', await h());
  await setup(); await page.fill('#co-inc', '9000000'); await page.evaluate(() => document.activeElement.blur()); console.log('eur max:', await page.evaluate(() => [document.getElementById('co-inc').value, document.getElementById('nh-ck-inc').textContent, document.getElementById('c-inc').max]));
  await setup(); await page.fill('#co-inc', '100'); await page.evaluate(() => document.activeElement.blur()); console.log('eur min:', await page.evaluate(() => [document.getElementById('co-inc').value, document.getElementById('nh-ck-inc').textContent]));
  await setup(); await page.fill('#co-inc', ''); await page.evaluate(() => document.activeElement.blur()); console.log('empty:', await page.evaluate(() => [document.getElementById('co-inc').value]));
  await setup(); await page.fill('#co-inc', 'abc'); await page.evaluate(() => document.activeElement.blur()); console.log('abc:', await page.evaluate(() => [document.getElementById('co-inc').value]));
  await setup(); await page.fill('#co-inc', '72,500.55'); await page.evaluate(() => document.activeElement.blur()); console.log('decimal eur:', await page.evaluate(() => [document.getElementById('co-inc').value, document.querySelector('#cout').innerText.slice(0,60)]));
  await page.evaluate(() => { S = fresh(); S.shell = true; S.tab = 'explore'; S.xs = []; render(); ACT.calc('retirement'); }); await page.fill('#co-age', '80'); await page.evaluate(() => document.activeElement.blur()); console.log('age:', await page.evaluate(() => [document.getElementById('co-age').value, document.getElementById('nh-ck-age').textContent]));
  await page.evaluate(() => { S = fresh(); S.shell = true; S.tab = 'explore'; S.xs = []; render(); ACT.calc('emergency'); }); await page.fill('#co-mt', '20'); await page.evaluate(() => document.activeElement.blur()); console.log('mo:', await page.evaluate(() => [document.getElementById('co-mt').value, document.getElementById('nh-ck-mt').textContent]));
  await page.fill('#co-mt', '0'); await page.evaluate(() => document.activeElement.blur()); console.log('mo min:', await page.evaluate(() => [document.getElementById('co-mt').value, document.getElementById('nh-ck-mt').textContent]));
  await page.evaluate(() => { S = fresh(); S.shell = true; S.tab = 'explore'; S.xs = []; render(); ACT.calc('goalplanner'); }); await page.fill('#co-y', '50'); await page.evaluate(() => document.activeElement.blur()); console.log('y:', await page.evaluate(() => [document.getElementById('co-y').value, document.getElementById('nh-ck-y').textContent]));
  await page.evaluate(() => { S = fresh(); S.shell = true; S.tab = 'explore'; S.xs = []; render(); ACT.calc('repayment'); }); await page.fill('#co-dr', '-5'); await page.evaluate(() => document.activeElement.blur()); console.log('neg:', await page.evaluate(() => [document.getElementById('co-dr').value, document.getElementById('nh-ck-dr').textContent]));
  console.log(errors); await browser.close(); })();
