const { chromium } = require('playwright');
const OUT = __dirname + '/build/v2-';
(async () => { const b = await chromium.launch(); const errs = []; const ctx = await b.newContext({viewport:{width:390,height:844}, hasTouch:true}); const p = await ctx.newPage();
  p.on('pageerror', e => errs.push(e.message)); p.on('console', m => { if (m.type() === 'error') errs.push(m.text()); });
  await p.route('**/fonts.googleapis.com/**', r => r.fulfill({status:200, contentType:'text/css', body:''})); await p.route('**/fonts.gstatic.com/**', r => r.abort());
  await p.goto('file:///home/user/lifegoals-prototype/LifeGoals-Customer-Journey-Prototype.html'); await p.waitForTimeout(300);
  let n = 0; const shot = async name => { n++; await p.screenshot({path: OUT + String(n).padStart(2, '0') + '-' + name + '.png'}); };
  const click = async s => { await p.locator(s).first().click(); await p.waitForTimeout(150); };
  const cur = () => p.evaluate(() => document.getElementById('curid').textContent.split(' · ')[0]);
  await shot('welcome'); await click('text=Start · about 1 min'); await click('[data-a="why"][data-p="track"]'); await click('[data-a="why"][data-p="other"]'); await p.fill('#why-note', 'Moving abroad'); await shot('why');
  await click('.qfoot .wbtn');
  for (let i = 0; i < 6; i++) { if (i === 0 || i === 3) await shot('q' + (i + 1) + '-tags'); await click('.opt >> nth=' + [2,0,1,3,3,1][i]); await p.waitForTimeout(400); }
  await shot('reveal'); await p.evaluate(() => document.querySelector('.qbody').scrollTo(0, 99999)); await shot('reveal-terms');
  await click('text=Get a more accurate picture: make my plan'); await p.fill('#ds-email', 'aoife@example.ie'); await shot('save-results'); await click('[data-a="dssave"]');
  console.log('after save', await cur(), await p.evaluate(() => S.acct.email)); await shot('home-before-plan'); await p.evaluate(() => document.getElementById('main').scrollTo(0, 99999)); await shot('home-before-plan-teasers');
  await click('[data-a="tab"][data-p="explore"]'); await shot('explore'); await p.evaluate(() => document.getElementById('main').scrollTo(0, 700)); await shot('explore-more');
  await click('[data-a="calc"][data-p="goalplanner"]'); await shot('calc'); await click('[data-a="calcadd"]'); await shot('calc-add'); await click('[data-a="confirmcalcadd"]'); console.log('goal added pre-plan', await p.evaluate(() => S.goals.map(g => g.name).join(',')));
  await click('[data-a="xback"]'); await click('.vthumb >> nth=0'); await click('[data-a="vplay"]'); await shot('video');
  await click('[data-a="tab"][data-p="plan"]'); await shot('plan-empty');
  await click('[data-a="makeplan"]'); await p.fill('#b-name', 'Aoife'); await click('[data-a="partner"][data-p="Yes"]'); await click('[data-a="pmode"][data-p="manual"]'); await p.fill('#p-name', 'Cian'); await click('[data-a="deps"][data-p="1"]'); await shot('step1-about');
  await click('.foot .btn'); for (const t of ['Buy a home', 'Travel']) await click('.gtile:has-text("' + t + '")'); await shot('step2-goals');
  await click('text=Place them on my timeline'); await shot('step3-timeline'); await click('.foot .btn'); await shot('step3-lifemap'); await click('text=This looks right');
  await shot('step4-money-profile'); await p.evaluate(() => document.getElementById('main').scrollTo(0, 900)); await shot('step4-money-profile-more');
  await click('[data-a="umpick"][data-p="d6|1"]'); await click('[data-a="umpick"][data-p="u10|2"]'); await click('text=Save and continue');
  console.log('step5', await cur(), 'email', await p.inputValue('#a-email')); await p.fill('#a-mob', '087 123 4567'); await p.check('[data-acct="c1"]'); await shot('step5-account'); await click('#acctgo');
  await p.keyboard.type('123456'); await shot('step5-code'); await click('.foot .btn'); await p.keyboard.type('123456'); await click('.foot .btn'); await click('text=Not now');
  await shot('step6-finances'); await click('[data-a="fsec"][data-p="0"]'); await shot('step6-about-prefilled'); if (await p.locator('#f-pAge').count()) await p.fill('#f-pAge', '36'); await click('text=Save this section'); await click('[data-a="fsec"][data-p="1"]'); await click('[data-a="fchoice"][data-p="work|Employed"]'); await p.fill('#f-income', '52000'); if (await p.locator('#f-pIncome').count()) await p.fill('#f-pIncome', '30000'); await p.fill('#f-costsM', '3000'); await click('[data-a="fnone"][data-p="otherM"]'); await click('[data-a="fnone"][data-p="oneOffY"]').catch(() => {}); await shot('step6-income'); await click('text=Save this section');
  await click('[data-a="fsec"][data-p="5"]'); await click('[data-a="fmode"][data-p="upload"]'); await click('text=Use a sample document'); await p.waitForTimeout(1800); await click('text=Looks right, add them');
  await click('text=Check my details'); await shot('step7-check'); await click('[data-a="infl"][data-p="0.02"]'); await p.check('[data-chk]'); await click('#seeres'); await p.waitForTimeout(400); await shot('step8-loading'); await p.waitForTimeout(1600); console.log('results', await cur());
  await p.locator('#r-res, #r-goals').first().scrollIntoViewIfNeeded(); await shot('step8-results');
  // assumptions toggle both ways
  const snap = () => p.evaluate(() => ({goals:document.getElementById('r-goals').innerText.replace(/\s+/g, ' ').slice(0, 90), asm:S.assume, infl:AS.infl, road:document.querySelector('#r-glance svg[role=img]') ? [...document.querySelectorAll('#r-glance svg line[stroke^="var(--"]')].map(l => l.getAttribute('stroke')).filter(x => /sunny|showers|storm/.test(x)).join('').length : 0}));
  await p.evaluate(() => { loadSample(); lastId = null; render(); }); await p.waitForTimeout(100);
  const s0 = await snap(); await p.locator('#r-wi').scrollIntoViewIfNeeded(); await click('#r-wi [data-a="assume"][data-p="cautious"]'); const s1 = await snap(); await p.locator('#r-wi').screenshot({path: OUT + 'assume-cautious-whatif.png'});
  console.log('standard', JSON.stringify(s0)); console.log('cautious', JSON.stringify(s1));
  const home = async () => { await click('[data-a="tab"][data-p="home"]'); const t = await p.locator('.card.row b').first().innerText(); await click('[data-a="tab"][data-p="plan"]'); return t; };
  console.log('home cautious:', await home()); await click('[data-a="sheet"][data-p="assume"]'); await p.screenshot({path: OUT + 'assume-sheet.png'}); await click('.sheet [data-a="assume"][data-p="standard"]'); await p.screenshot({path: OUT + 'assume-sheet-standard.png'}); await p.evaluate(() => { S.sheet = null; render(); }); console.log('back to standard', JSON.stringify(await snap()), 'home:', await home());
  await click('[data-a="report"]'); await p.waitForTimeout(200); console.log('report states set:', await p.evaluate(() => /Growth assumptions: Standard/.test(document.getElementById('report').innerText)));
  await p.evaluate(() => document.getElementById('report').classList.remove('on'));
  console.log('ERRORS', errs.length, JSON.stringify(errs)); await b.close(); })();
