from lib import *
import p_inputs as PI

PARAS = [
 ('Plan inputs', 'Everything the "Make my plan" engine needs, in one yellow block. It mirrors the prototype\'s customer state: about you and your family, your goals (type, year, amount, saved so far, priority, rank), Your finances (the card, loan, pension and other-property mortgage totals come from the "Your lists" sheet, which wins over a typed figure when it has any figure, exactly like the prototype), your assumptions (a blank one means "not chosen": the plan then uses the standard from Settings, and Plan results lists what still needs choosing), the inflation you choose, your saving choice, and the what-if. A blank figure is €0, never a made-up number. With "Fill example values" on README set to Yes, every blank cell uses the grey example (the sample customer).'),
 ('Plan pay & tax', 'The top block turns inputs into the figures the plan uses (the prototype\'s finNums and asmV): standards for any unchosen assumption, the mortgage repayment (given, or worked out from balance, rate and years), cards and loans (the repayment given if it covers the interest, otherwise a 5-year repayment; other-property mortgages are folded into other loans), pension contributions (your own share and the employer\'s), auto-enrolment, State Pension share, partner, tax credits. The year table below works out, for each year of the plan, your pay and your partner\'s (rising with pay), pension contributions and tax relief, the pension pot (growth, the lump sum and Standard Fund Threshold at retirement, the minimum or chosen drawdown), the State Pension and other income, and income tax, USC and PRSI (the prototype\'s hhTax, with joint assessment, age credit, rent, home carer and single-parent credits). Bands and credits rise with prices unless you chose "stay as today".'),
 ('Plan debt months', 'Each loan, card and the mortgage is paid month by month inside each plan year: interest is added, then the repayment is taken (never more than is owed), until the balance is 50 cent or less. The mortgage "path" (the mortgage with no goal payments) prices a Be-mortgage-free goal at its date.'),
 ('Plan cashflow', 'One row per year from today to the plan-until age. Order inside a year: money in (after tax and pension contributions) -> living costs and one-offs -> mortgage, card and loan repayments -> goals due this year are paid from their own pot, then from spare money (a goal that cannot be paid leaves a goal gap) -> if money is left over, the saving amount is put towards the goals still to come in funding order (each goal gets what it needs this year, level in real terms, until its pot reaches its cost), and the rest is assumed spent while working (kept as savings once retired) -> if the year is short, spare money, then the buffer, then the goal pots (latest goals first) give way -> growth (spare money at your cash and invested mix, pots at the cash or investment rate). The what-if extra, one-off and "save less" change this table the same way as in the app.'),
 ('Plan goals', 'Part 1 lists your goals and puts the funded ones in funding order: your ranking if you ranked them (Emergency fund first unless you moved it), otherwise Emergency fund, then must-haves before nice-to-haves, then soonest. Part 2 gives each funded goal its cost (inflated to its date; a mortgage-free goal costs the mortgage balance then), its growth rate (the cash rate if it is less than the "years kept as cash" away, otherwise the investment rate), and its starting pot (saved so far, the what-if one-off, then a share of spare savings in order). Part 3 and 4 turn the Plan cashflow table into the % covered for each goal (rounded down, so 99.6% never reads 100%), its band (95%+ on track, 70%+ needs a nudge, below that needs attention), the average a month you put in, and the Option B goal line.'),
 ('Plan results', 'What the Results screens show, as formulas: the saving numbers, the gate (the card "To see your results we need N things", with one row each for Retirement age, Plan until age, Inflation and, for a working partner, Partner\'s retirement age, in the order the app asks), the main strength, gap and biggest decision (a strength is only a fully covered goal, never while working-year spending is more than comes in), retirement at a glance, and the five foundations levels with the "strengthen your foundations first" rule. The what-if affects goal % and goal lines; the findings and foundations are the base plan, so they match the app only when the what-if is zero.'),
 ('Plan profile', 'The money personality and the risk profile, scored from the Discover and Understand Me answers exactly as the prototype does: each answer adds weight to a personality type (the highest wins, a tie is broken in a fixed order, and at least 4 of the 6 weighted answers are needed); the risk profile is the lowest of your attitude (want), your capacity to bear a loss (can afford), your time horizon and your knowledge and experience; a mismatch between them picks the message, and the profile is shown as provisional until all 13 questions are answered. It is indicative guidance only: an adviser confirms a risk profile with you.'),
 ('Calculation register', 'A list of every place the prototype calculates, scores or shows a number: the screen, the label, the prototype function and line, the rule in words, where it sits in this workbook and whether a test matched it. Rows that say "Not built" or "Not testable" are the known gaps, so nothing is hidden.'),
 ('Units and allowed values', 'Money is in euros. Every rate or share is a fraction, the same as on the calculator sheets and on Your lists: 0.0375 means 3.75%, 0.2 means 20%. The statement rates (mortgage, cards, loans, pension charges) are fractions too, although the app shows them as a %. Every yellow cell on Plan inputs, Plan profile and Settings refuses a value outside what the app allows (for example age 18 to 80, plan-until age 80 to 105, retirement age 18 to 105, a mortgage term of 1 to 40 years, the ranges of the Your assumptions sliders). If a value is pasted in anyway, the plan treats it as not given: a required choice then shows the same "Choose your ... to see this" text as the app, and nothing turns into an error value.'),
 ('Limits of this workbook', 'The app has no limit on goals (a customer can add "Something else" again and again). This workbook holds 22 goal rows: up to 20 goals saved for from savings (each has its own column block on Plan cashflow), plus Retire comfortably and Leave a legacy. If more than 20 funded goals are set, or all 22 rows are used, a red warning appears at the top of Plan inputs and Plan results and the results are not complete. The plan runs to age 105 at most (90 year rows). Tested against the app with 9, 12, 15 and 20 goal plans.'),
 ('What the workbook cannot do in one pass', 'The app finds some figures by searching: the smallest extra a month that takes a goal to 100% (extraTo100), the extra that closes the main gap (extraFor), and the "before" percentages of the what-if sentence (a second run with the what-if off). A spreadsheet cannot re-run itself, so these are typed cells: Plan goals column L (extra a month, or "none"), Plan results "Find_ExtraFor", and Plan goals column Z (% with the what-if off, only needed while a what-if is on). With Fill example values = Yes, the sample customer\'s own figures are used so the demo reproduces the app. The findings, foundations, home counts, next best step and video lines are for the base plan: they match the app when the what-if is zero.'),
 ('Specification of the two searches (for the developer who builds them in code)', 'extraTo100(goal): let w = the what-if if it is for this goal, else extra 0 and one-off 0. ok(m) = the goal % covered when the whole plan is run again with an extra m a month on top of w.extra and the one-off w.lump; "100" means covered to within one euro. If ok(5000) is false the answer is none (the goal line then says "more than your spare money"). Otherwise lo = 0, hi = 5000; repeat 13 times: mid = (lo + hi) / 2; if ok(mid) then hi = mid else lo = mid. The answer is hi rounded UP to the next multiple of 5. The goal line is: needs = average a month you put in + the answer (or the goal\'s need if none); "more than your spare money" if needs is above spare money a month.  extraFor(goal): the first m in 25, 50, 75, 100, 150, 200, 250, 300, 400, 500, 600, 750, 1000, 1250, 1500, 2000 for which the goal reaches 95% with an extra m a month (and no one-off); none if no m does. Test vector (the sample customer, Fill example values = Yes): Kids\' education, 50% covered. ok(m) for m = 5000, 2500, 1250, 625, 312.5 is 100; at 156.25 it is 85; 234.375 gives 97; 273.438 gives 100; 253.906 gives 100; 244.141 gives 98; 249.023 gives 99; 251.465 gives 99; 252.686 gives 99; 253.296 gives 100, so hi = 253.296 and the answer is 255; the line reads "Needs about €462 a month, more than your spare money · on average you\'ll put €207 a month" (462 = 207 + 255). Travel, 28% covered: extraFor tries 25 to 2000 and reaches only 35, 43, 49, 54, 58 and then stays at 58, so the answer is none; the line reads "Needs about €337 a month, more than your spare money · on average you\'ll put €97 a month", and the biggest decision reads "Moving travel later, or changing the amount, would make the biggest difference". The test harness (tools/plan-vs-xlsx) feeds the app\'s own answers into the typed cells for hundreds of customers and checks every goal line and finding word for word.'),
 ('Gates and wording', 'Only four choices block the plan (journey-spec section 27): retirement age, plan-until age, inflation, and a working partner\'s retirement age. The gate on Plan results follows the app\'s planMissing in the app\'s order and shows the count ("we need N things"). Every other figure has a labelled value and never blocks: the LifeMap standards (Set by LifeMap) are used automatically, and a market rate or figure the customer has not given uses the suggested published rate or the planning rate (Assumed: add yours; the app counts these in "N details missing"). Every calculator sheet follows the app\'s calcMissing: a LifeMap standard starts from the standard and never gates; the customer\'s own figures (market rates, State Pension, Illness Benefit, retirement age) still gate, in the app\'s order, with the inflation gate only after every other one, and the words are the app\'s words (for example "Choose your mortgage rate to see this"). tools/calc-vs-xlsx checks the text for every calculator.'),
 ('Retirement age, access age and "Date has passed"', 'Retirement age is free: any age from your age + 1 to plan-until age - 1. Below 50 and below 60 the app shows a calm note and the plan carries on. The pension can be drawn from the pension access age: 60 by default (a LifeMap standard on Settings), 50 if the customer says their occupational scheme allows it. Between retiring and the access age (and before the State Pension at 66) the years are paid from savings; any shortfall is shown, for the customer and for a partner. A goal dated before today\'s age reads "Date has passed" on Plan results instead of "in -4 years" (the app adds a "Change the date" button). The line under the retirement age box, the two calm notes and the three "we use ..." status lines (mortgage years 25, partner age = yours, Employed, and the unchosen rates) are cells on Plan results with the app\'s words (Retire_RangeText, Retire_Note, PRet_Note, Use_*). An age outside 18 to 80 (partner 18 to 85), a part-year age or a word is never read as 0: the gate card asks for it ("Your age", "Partner\'s age"). An unchosen deposit-earn rate (Rent vs buy) uses the suggested Central Bank rate after DIRT, as the app does.'),
]

def build_how(bk):
    wb = bk.wb
    if 'Plan how it works' in wb.sheetnames: del wb['Plan how it works']
    ws = wb.create_sheet('Plan how it works'); ws.sheet_properties.tabColor = '5B9BD5'
    ws['B1'] = 'Plan how it works: a plain-English walk through the Plan sheets'; ws['B1'].font = Font(bold=True, size=14)
    ws.column_dimensions['A'].width = 2; ws.column_dimensions['B'].width = 44; ws.column_dimensions['C'].width = 120
    r = 3
    for t, p in PARAS:
        ws.cell(r, 2, t).font = B; c = ws.cell(r, 3, p); c.alignment = Alignment(wrap_text=True, vertical='top'); ws.row_dimensions[r].height = max(30, 15 * (len(p) // 115 + 1)); r += 1
    r += 1
    ws.cell(r, 2, 'Plan inputs -> prototype state key').font = B; r += 1
    for j, h in enumerate(['Plan inputs name', 'Prototype state key / meaning']):
        c = ws.cell(r, 2 + j, h); c.fill = HEAD; c.font = WH
    r += 1
    for grp in (PI.ABOUT, PI.WHATIF, PI.FIN, PI.SESS):
        for k in grp: ws.cell(r, 2, 'In_' + k[0] + ' / Has_' + k[0]); ws.cell(r, 3, k[1] + '   [' + k[5] + ']'); r += 1
    for key, label, unit, ex, pk in PI.ASMS: ws.cell(r, 2, 'In_' + key + ' / Has_' + key); ws.cell(r, 3, label + '   [S.asm.' + pk + ']'); r += 1
    for nm, lab in [('Goal{i}_key / name / age / amount / saved / prio / rank / auto', 'Goal i: S.goals[i-1] .k / .name / .age / .amount / .saved / .prio; rank = position in S.rank; auto = .auto (Emergency fund amount follows months x essential spending)'),
                    ('Your lists (cards, loans, pensions, mortgages on other properties)', "S.lists.cards / .loans / .pens / .mort2 (items with owed, pay, rate, years, value, monthly, own)")]:
        ws.cell(r, 2, nm); ws.cell(r, 3, lab); r += 1
    return ws
