s=open('p_reg.py').read()
def rep(a,b):
    global s
    assert a in s, a[:70]
    s=s.replace(a,b,1)
rep("'Tool list picked from the types of your goals (max 4), in a fixed order.'","'Tool list picked from the types of your goals (the first 6 of the list), in a fixed order.'")
rep("('Results', 'Retirement at a glance', 'function project', 'Retirement year, pot at retirement, net income a month, net lump sum.', 'Plan results: Ret_Year, Ret_PotNominal, Ret_IncomeMonth, Ret_LumpNet', OK),","('Explore > C12 Retirement projection (pre-filled from your plan)', 'Years to retirement, pension pot at retirement, income a month, lump sum after tax', 'function calcPre', 'Pot = the plan pension pot at the start of the retirement year; income a month = money in after tax in the first retired year in today prices; lump sum after tax as in C12.', 'Plan results: Ret_Year, Ret_PotNominal, Ret_IncomeMonth, Ret_LumpNet', 'Matched in test for years, pot and income (plan-vs-xlsx); the lump sum is checked through C12 only'),")
rep("('Home', 'Readiness \"rough\" flag', 'function roughNote', 'Shown when a section of Your finances is skipped or more than 2 required figures were not given or read from a document.', '-', 'Not testable: depends on where each figure came from (typed / document / skipped), which the workbook does not hold. Known gap.'),","('Home', 'Readiness \"rough\" flag and the \"Rough picture\" note', 'function roughNote', 'Rough when a section of Your finances is skipped or more than 2 required figures are missing; the note only shows when no detail is already flagged.', 'Plan results: Home_Rough, Rough_Show, Fin_Skipped, Fin_Quality', OK + ' (a figure counts as given when it is typed; reading it from a document is not recorded, which does not change the count)'),")
rep("'Plan results: Fnd_NextN / Fnd_NextT / Fnd_NextD (foundation part only)', 'Partly built. The goal-based wording (nextStep) is not in the workbook. Known gap.'),","'Plan results: Next_N, Next_T, Next_D, Next_B (use Fnd_NextN, Fnd_NextT, Fnd_NextD, Look_Count, Prof_NeedsProfile and the session facts on Plan inputs)', OK + ' (base plan, what-if off)'),")
rep("('Results > What-if', '\"What changes\" sentence listing goals that moved', 'function wiText', 'Lists each goal whose % changed, from old % to new %.', '-', 'Not built (text assembled from the two runs). Goal % before / after are testable by running the workbook twice. Known gap.'),","('Results > What-if', '\"What changes\" sentence listing goals that moved', 'function wiText', 'Lists each goal whose % changed, from old % to new %.', 'Plan results: Wi_Text; Plan goals: GR{i}_WiTxt, GR{i}_PctBefore (typed % with the what-if off)', 'Matched in test when the before % is typed (the workbook has one run, so the before figure is typed, or the same when there is no what-if)'),")
rep("('Report / PDF', 'Section 5 what-if text', 'function wiText', 'See What-if.', 'Plan pay & tax: WI_M, WI_L', 'Figures matched in test; sentence not built. Known gap.'),","('Report / PDF', 'Section 5 what-if text', 'function wiText', 'See What-if.', 'Plan results: Wi_Text; Plan pay & tax: WI_M, WI_L', 'Matched in test when the before % is typed'),")
rep("('Timeline', 'Chart: goal name labels over years, selected-year detail', 'function chartDetail', 'Names of goals due that year; the selected year shows the row\\'s own figures.', 'Plan cashflow: rows (figures); names -', 'Figures matched in test; goal-name list not built (text). Known gap.'),","('Timeline', 'Chart: selected-year detail and the per-year label', 'function chaptersHTML', 'Each year reads Comfortable, Using savings or Gap to plan for: short €x from the row figures; the goals due that year are named from the goal list.', 'Plan cashflow: yrLabel and the row figures; names: Plan goals GR{i}_Name', OK + ' (labels and figures); the list of names of goals due in a year is display-only (not a calculation)'),\n ('Plan > Timeline', 'Chapter story under each decade', 'function chaptersHTML', 'Short by about the average shortfall a year in n of these years; else living on pensions and savings; else some years dip into savings; else income comfortably covers life.', 'Plan results: Chap_Story', OK),")
rep("('Results', 'Goal status ring, \"when\" text', 'function whenTxt', 'Years = goal age minus your age; year = this year plus years.', 'Plan goals: GR{i}_When', OK),","('Results', 'Goal status ring, \"in N years\" text', 'function yearsTxt', 'Years = goal age minus your age; at the end of your plan for a legacy goal; at the retirement age for retire.', 'Plan goals: GR{i}_When', OK),\n ('Plan, Timeline, goal tiles, Confirm my LifeMap, Report section 4', 'Calendar year beside every goal (age 41 · 2030, Age 63 · 2052, (2037))', 'function whenTxt', 'First plan year + (goal age - your age).', 'Plan goals: GR{i}_Year, GR{i}_AgeYear', OK),")
rep("('Report / PDF', 'Section 6 money snapshot (every Your finances figure, tag, \"N items missing\")', 'function fmtField', 'Displays the figures you gave and where each came from; the count of items missing.', 'Plan results: Missing_Count', 'Figures are the inputs themselves; source tags (document / typed) not held. Count matched. Known gap for tags.'),","('Report / PDF', 'Section 6 money snapshot (every Your finances figure, tag, \"N items missing\")', 'function fmtField', 'Displays the figures you gave and the count of items missing; the tag (document / typed) is display-only.', 'Plan results: Missing_Count', OK + ' for the count; the tags are display-only (not a calculation)'),\n ('Me > My money, Your finances hub (step 6)', 'Section progress (5 of 6 done; Done / Needs a look / Started / Not started per section)', 'function secStatus', 'A section is done when every required figure shown is given or you saved it; needs a look if a figure is flagged; started if anything beyond the pre-filled age is typed.', 'Plan results: Fin1_St, Fin2_St, Fin3_St, Fin4_St, Fin5_St, Fin6_St, Fin_Done, Fin_MinOK', OK),\n ('Me > My money > Check details', 'N details look good and N need a look', 'function checkItems', 'Every shown figure that is given and not flagged looks good; flagged or required-and-missing ones need a look.', 'Plan results: Good_Count, Missing_Count, Look_Count', OK),")
rep("('Me', 'Mismatch message (want higher than can afford, etc.)', 'MIS_ADV',","('Me > Understand Me', 'Per-section counts (2 of 3 answered, 3 of 5) and the line 6 of 7 left · your first 6 answers are filled in', 'function umLeftTxt', 'Answers given in each of the 3 sections; new questions still to answer of 7.', 'Plan profile: Prof_UmSec1, Prof_UmSec2, Prof_UmSec3, Prof_UmLeft, Prof_UmLeftTxt', OK),\n ('Me', 'Mismatch message (want higher than can afford, etc.)', 'MIS_ADV',")
rep("('Explore', 'Videos for you: order', 'function videosForYou', 'Videos sorted so the one about the weakest goal comes first, then those about your goals.', '-', 'Not built (a sort of a fixed list). Known gap.'),","('Explore', 'Videos for you: order', 'function videosForYou', 'Videos sorted so the one about the weakest goal comes first, then those about your goals.', 'Plan results: Expert_Key', 'Display-only: a sort of a fixed list of videos, not a calculation. The weakest goal it is based on is matched (Expert_Idx).'),\n ('Explore home', 'What-ifs for your goals: Try a what-if for travel, 28% covered now', 'function xWorst', 'One tile for each goal under 95%, with its % covered.', 'Plan results: Slip_Count, Slip_Names; Plan goals: GR{i}_Pct', OK),\n ('Video page', 'Why this is for you: your goal is N% covered', 'V.VID = id =>', 'The first goal whose specialist type matches the video (pension videos use the retirement goal) and its % covered.', 'Plan results: Vid_mortgage_Pct, Vid_pension_Pct, Vid_protection_Pct, Vid_investment_Pct, Vid_planner_Pct', OK + ' (base plan)'),\n ('Explore > categories', '7 tools, 3 tools per category', 'const CATS', 'Count of the 28 tools in each category.', 'Plan results: Cat_N1, Cat_N2, Cat_N3, Cat_N4, Cat_N5, Cat_N6 (counted from the README list)', OK),")
rep("('Ask / Experts', 'Suggested questions that quote plan figures', 'function askPlan', 'Text built from goal % and ages.', '-', 'Not built (text only). Known gap.'),","('Ask / Experts', 'Suggested questions that quote plan figures', 'function askPlan', 'Text built from goal % and ages.', '-', 'Display-only text built from figures already in the workbook (goal %, goal line, retirement age): not a calculation, not built.'),\n ('Report', 'Header: Created 29 Sep 2026 · version 2', 'function openReport', 'A date typed in the app and the number of saved versions.', '-', 'Constant / session count: not a calculation.'),\n ('Results', 'Typed-search goal lines (extraTo100, extraFor)', 'function extraTo100', 'Bisection and a fixed ladder; see the specification and test vectors on Plan how it works.', 'Plan goals: GR{i}_Extra, GR{i}_ExtraUsed; Plan results: Find_ExtraFor, Find_ExtraUsed', 'Matched in test when the app figure is typed in; the sample customer figures are built in for the demo'),")
open('p_reg.py','w').write(s)
print('ok')
