/* ---------- "Your assumptions" (journey-spec §14, Pooja 2 Oct 2026; binding) ----------
   Every number is one of three types. Type 1 (law) lives in RULES_IE_2026 and is shown as "Set by Government · 2026", not editable.
   Type 2 (range): the customer enters theirs; we show "Usually between X and Y (source)". Type 3 (personal judgement): blank until chosen;
   "Generally the standard is X (source). Choose what you want to use." with a one-tap "Use the standard (X)" chip.
   Retirement age and plan-until age (life expectancy) are never defaulted and never part of "Use the standard for all of these".
   Engine: asmV() falls back to the standard (type 3) or a mid-range figure (type 2) ONLY so the maths never breaks. No result is shown
   while planMissing() is not empty: the screens show "Choose your [item] to see this" instead. */
const twoSecure = () => !!(S && S.about.partner && +S.fin.income > 0 && +S.fin.pIncome > 0 && S.fin.work === 'Employed');
const curSet = () => AS_SETS[(S && S.assume) || 'standard'];
const ST = RI.std, GD = RI.guide, STB = RULES_IE_2026.std, GDB = RULES_IE_2026.guide;
const eurW = n => '€' + (+n).toFixed(2);   // weekly DSP rates keep their cents (€299.30)
const ASM_GRP = [['prices', 'Prices & growth'], ['retire', 'Retirement'], ['safety', 'Safety net & debt'], ['length', 'Plan length']];
const finN = k => { const v = S && S.fin ? S.fin[k] : null; return v != null && v !== '' && !isNaN(+v) ? +v : 0; };
const spOwnOpt = () => (S.fin.sp || 'Not sure'), spYearsKnown = () => (S.fin.spYears != null && S.fin.spYears !== '') || asmGet('spYears') != null;
const ASM = {
  inv:{g:'prices', b:'B3', ty:3, n:'investment growth', l:'Investments grow (a year, after charges and tax)', t:'pct', min:0, max:7, step:0.25, sug:() => ST.inv, by:STB.inv.by, need:() => true, help:'A typical mixed fund has grown 5%–6% a year before charges and tax over long periods, but not every year.'},
  invGross:{g:'prices', b:'B3', ty:3, n:'growth before fees', l:'Investments grow before fees and tax (a year; the growth and fees tools)', t:'pct', min:0, max:10, step:0.25, sug:() => ST.invGross, by:STB.invGross.by, need:() => false, help:'Used by the lump sum, regular investing, fees and real return tools. Growth is never guaranteed.'},
  cash:{g:'prices', b:'B4', ty:3, n:'cash growth', l:'Cash savings earn (a year, after DIRT)', t:'pct', min:0, max:4, step:0.05, sug:() => ST.cash, by:STB.cash.by, need:() => true, help:'Deposit accounts usually pay between ' + pcs(GD.depLo) + ' and ' + pcs(GD.depHi) + ' before 33% DIRT. Demand accounts pay less.'},
  pen:{g:'prices', b:'B5', ty:3, n:'pension growth', l:'Pension grows while you work (a year, after charges)', t:'pct', min:0, max:7, step:0.05, sug:() => ST.pen, by:STB.pen.by, need:() => true, help:'Pension growth is tax-free inside the fund.'},
  penRet:{g:'prices', b:'B5', ty:3, n:'pension growth once retired', l:'Pension grows once you retire (a year, after charges)', t:'pct', min:0, max:7, step:0.05, sug:() => ST.penRet, by:STB.penRet.by, need:() => true, help:'Most people take less risk once retired, so growth is usually lower.'},
  penChg:{g:'prices', b:'B6', ty:3, n:'typical pension charges', l:'Typical pension charges already allowed for in the pension growth above', t:'pct', min:0, max:2.5, step:0.05, sug:() => ST.penChg, by:STB.penChg.by + ' (usually between ' + pcs(GD.chgLo) + ' and ' + pcs(GD.chgHi) + ')', need:() => !!(S.fin && S.fin.penChg != null && S.fin.penChg !== ''), help:'When your statement shows your own charges, we use them instead of this.'},
  wage:{g:'prices', b:'B8', ty:3, n:'pay rises', l:'Pay rises (a year)', t:'pct', min:0, max:6, step:0.1, sug:() => ST.wage, by:STB.wage.by, need:() => true, help:'Pick lower if your pay is fixed or you expect to work part-time.'},
  bands:{g:'prices', b:'B10', ty:3, n:'tax bands in future', l:'Tax bands in future', t:'choice', o:[['prices', 'Rise with prices'], ['flat', 'Stay as today']], sug:() => 'prices', by:'Budgets have broadly kept pace over time', need:() => true, help:'Irish tax bands are set each Budget and don\'t rise automatically. "Stay as today" is the cautious view (more tax later).'},
  rentRise:{g:'prices', b:'B25', ty:3, n:'rent rises', l:'Rent vs buy: rent rises (a year)', t:'pct', min:0, max:8, step:0.5, sug:() => ST.rentRise, by:STB.rentRise.by, need:() => false, help:'Renting has rent rises. Buying has costs that don\'t build equity: interest, stamp duty, fees, LPT and repairs.'},
  houseGrow:{g:'prices', b:'B25', ty:3, n:'house price growth', l:'Rent vs buy: house prices rise (a year)', t:'pct', min:0, max:6, step:0.5, sug:() => ST.houseGrow, by:STB.houseGrow.by, need:() => false, help:'House prices can fall as well as rise.'},
  upkeep:{g:'prices', b:'B25', ty:3, n:'upkeep', l:'Rent vs buy: upkeep a year (share of the home value)', t:'pct', min:0, max:3, step:0.1, sug:() => ST.upkeep, by:STB.upkeep.by, need:() => false, help:''},
  buyFees:{g:'prices', b:'B25', ty:3, n:'buying fees', l:'Buying fees (legal and survey), plus stamp duty', t:'eur', min:0, max:10000, step:250, sug:() => ST.buyFees, by:STB.buyFees.by, need:() => false, help:'Stamp duty is set by law and added on top: 1% up to €1m.'},
  depEarn:{g:'prices', b:'B25', ty:3, n:'what the deposit could earn', l:'Rent vs buy: what the deposit could earn instead (a year, after tax)', t:'pct', min:0, max:6, step:0.25, sug:() => ST.depEarn, by:STB.depEarn.by, need:() => false, help:'If you rent, your deposit stays in savings.'},
  riskMu1:{g:'prices', b:'B26', ty:3, n:'Cautious style growth', l:'Risk & return: Cautious style growth (a year)', t:'pct', min:0, max:8, step:0.5, sug:() => ST.riskMu[0], by:STB.riskMu.by, need:() => false, help:'Your adviser uses the fund\'s own risk rating (SRI 1–7).'},
  riskMu2:{g:'prices', b:'B26', ty:3, n:'Balanced style growth', l:'Risk & return: Balanced style growth (a year)', t:'pct', min:0, max:8, step:0.5, sug:() => ST.riskMu[1], by:STB.riskMu.by, need:() => false, help:''},
  riskMu3:{g:'prices', b:'B26', ty:3, n:'Growth style growth', l:'Risk & return: Growth style growth (a year)', t:'pct', min:0, max:8, step:0.5, sug:() => ST.riskMu[2], by:STB.riskMu.by, need:() => false, help:''},
  riskVol1:{g:'prices', b:'B26', ty:3, n:'Cautious style ups and downs', l:'Risk & return: Cautious style ups and downs (volatility)', t:'pct', min:0, max:25, step:1, sug:() => ST.riskVol[0], by:STB.riskVol.by, need:() => false, help:'How much a year can swing.'},
  riskVol2:{g:'prices', b:'B26', ty:3, n:'Balanced style ups and downs', l:'Risk & return: Balanced style ups and downs (volatility)', t:'pct', min:0, max:25, step:1, sug:() => ST.riskVol[1], by:STB.riskVol.by, need:() => false, help:''},
  riskVol3:{g:'prices', b:'B26', ty:3, n:'Growth style ups and downs', l:'Risk & return: Growth style ups and downs (volatility)', t:'pct', min:0, max:25, step:1, sug:() => ST.riskVol[2], by:STB.riskVol.by, need:() => false, help:''},
  spGrow:{g:'retire', b:'B11', ty:3, n:'State Pension in future', l:'State Pension in future', t:'choice', o:[['prices', 'Rises with prices'], ['pay', 'Rises with pay'], ['flat', 'Stays flat']], sug:() => 'prices', by:'it has broadly kept pace with prices over time', need:() => true, help:'The State Pension is set each Budget.'},
  spYears:{g:'retire', b:'B9', ty:2, n:'PRSI years', l:'How many years of PRSI will you have at 66? (leave blank if you don\'t know)', t:'yrs', min:0, max:45, step:1, rng:() => [0, 45], by:'a full State Pension needs ' + RI.sp.fullYears + '; at least ' + RI.sp.minYears + ' to qualify', opt:true, fb:() => null, need:() => false, help:'Check your record on MyWelfare. If you give your years, we work out your State Pension from them (set by law).'},
  spWeek:{g:'retire', b:'B9', ty:2, n:'State Pension', l:'Your State Pension a week at 66', t:'eurw', min:0, max:RI.sp.week, step:0.1, rng:() => [0, RI.sp.week], by:'DSP 2026: the full rate needs ' + RI.sp.fullYears + ' years of PRSI; partial rates are lower', fb:() => RI.sp.week * (spOwnOpt() === 'Partly' ? 0.6 : 0.8),
    need:() => ['Partly', 'Not sure'].includes(spOwnOpt()) && !spYearsKnown(), help:'Your State Pension statement on MyWelfare shows your expected rate. Or tell us your PRSI years.'},
  pSpWeek:{g:'retire', b:'B9', ty:2, n:'partner\'s State Pension', l:'Your partner\'s State Pension a week at 66', t:'eurw', min:0, max:RI.sp.week, step:0.1, rng:() => [0, RI.sp.week], by:'DSP 2026', fb:() => RI.sp.week * ((S.fin.pSp || 'Not sure') === 'Own partial' ? 0.6 : 0.8),
    need:() => !!S.about.partner && ['Own partial', 'Not sure'].includes(S.fin.pSp || 'Not sure'), help:'Their MyWelfare statement shows it.'},
  ownShare:{g:'retire', b:'B1', ty:3, n:'share of your pension you pay', l:'Of the money paid into your pension each month, the share you pay yourself (the rest is your employer)', t:'pct', min:0, max:100, step:5, sug:() => S && S.fin.work === 'Self-employed' ? 1 : ST.ownShare, by:STB.ownShare.by,
    need:() => finN('pensionM') > 0 && S.fin.work !== 'Not working' && !(S.fin.pensionOwnM != null && S.fin.pensionOwnM !== ''), help:'Your payslip shows what comes out of your pay. Only your own share gets tax relief. If you type your own amount in Your finances, we use that.'},
  retireMult:{g:'retire', b:'B17', ty:3, n:'retirement savings target', l:'Retirement savings target: times the yearly income you need', t:'num', min:20, max:33, step:1, sug:() => ST.retireMult, by:STB.retireMult.by, need:() => false, help:'Retiring early or planning to 95 needs more.'},
  retireSpend:{g:'retire', b:'B18', ty:3, n:'retirement spending', l:'Retirement spending if you haven\'t set a goal (share of today\'s spending)', t:'pct', min:50, max:120, step:5, sug:() => ST.retireSpend, by:STB.retireSpend.by, need:() => !retireGoal(), help:''},
  lumpSum:{g:'retire', b:'B19', ty:3, n:'retirement lump sum', l:'Tax-free lump sum to take at retirement (share of your pension, 0% = none)', t:'pct', min:0, max:25, step:1, sug:() => ST.lumpSum, by:STB.lumpSum.by, need:() => true, help:'Set by law: up to €200,000 is tax-free and the next €300,000 is taxed at 20%. Your adviser can compare it with leaving it invested.'},
  drawRule:{g:'retire', b:'B20', ty:3, n:'how you draw your pension', l:'How you draw your pension', t:'choice', o:[['spread', 'Spread to plan end'], ['min', 'Minimum only (4% / 5%)'], ['fixed', 'Fixed amount']], sug:() => 'spread', by:'spread over your plan, at least the legal minimum', need:() => true, help:'Set by law: from 61 you must take at least 4% a year from an ARF (5% from 71).'},
  ddTiming:{g:'retire', b:'B20', ty:3, n:'withdrawal timing', l:'Drawdown tools: withdrawals taken at the', t:'choice', o:[['start', 'Start of the year'], ['end', 'End of the year']], sug:() => 'start', by:'the prudent choice: the money has less time to grow before you take it', need:() => false, help:''},
  drawFixed:{g:'retire', b:'B20', ty:3, own:true, n:'fixed yearly amount', l:'Fixed amount a year (today\'s money), if you chose "Fixed amount"', t:'eur', min:0, max:200000, step:500, fb:() => 20000, need:() => asmGet('drawRule') === 'fixed', help:'Never less than the legal minimum once you are 61.'},
  safetyMonths:{g:'safety', b:'B16', ty:3, n:'safety-net months', l:'Safety net: months of essential spending', t:'num', min:3, max:12, step:1, sug:() => twoSecure() ? ST.safetyMonthsTwo : ST.safetyMonths, by:STB.safetyMonths.by, need:() => true, help:'Easy-access cash for surprises or a gap in pay. Essential spending = living costs + mortgage + loan repayments.'},
  mortRate:{g:'safety', b:'B13', ty:2, n:'mortgage rate', l:'Your mortgage rate (if your statement doesn\'t say)', t:'pct', min:1, max:8, step:0.05, rng:() => [GD.mortLo, GD.mortHi], by:GDB.mortLo.by, fb:() => 0.0375,
    need:() => S.fin.home === 'Own with mortgage' && finN('mortBal') > 0 && !(finN('mortRate') > 0), help:'Your mortgage statement shows your rate.'},
  cardRate:{g:'safety', b:'B14', ty:2, n:'credit-card rate', l:'Your credit-card rate, APR (if your statement doesn\'t say)', t:'pct', min:0, max:35, step:0.5, rng:() => [GD.cardLo, GD.cardHi], by:GDB.cardLo.by, fb:() => 0.20,
    need:() => finN('cardBal') > 0 && !(finN('cardRate') > 0), help:'Your card statement shows your APR.'},
  loanRate:{g:'safety', b:'B15', ty:2, n:'loan rate', l:'Your other loans rate, APR (if your statement doesn\'t say)', t:'pct', min:0, max:25, step:0.25, rng:() => [GD.loanLo, GD.loanHi], by:GDB.loanLo.by, fb:() => 0.08,
    need:() => finN('loanBal') + finN('debt') > 0 && !(finN('loanRate') > 0), help:'Your loan agreement shows your APR.'},
  cashYears:{g:'safety', b:'B21', ty:3, n:'years kept as cash', l:'Money for goals sooner than this is kept as cash (years)', t:'yrs', min:1, max:10, step:1, sug:() => ST.cashYears, by:STB.cashYears.by, need:() => true, help:'Longer-term money has more time to ride out ups and downs.'},
  investShare:{g:'safety', b:'B21', ty:3, n:'share of spare savings invested', l:'Spare savings: share invested (the rest stays in cash)', t:'pct', min:0, max:100, step:5, sug:() => ST.investShare, by:STB.investShare.by, need:() => true, help:''},
  saveShare:{g:'safety', b:'B22', ty:3, n:'share of spare money saved', l:'Share of your spare money you save, at most', t:'pct', min:0, max:100, step:5, sug:() => ST.saveShare, by:STB.saveShare.by, need:() => S.saveM == null, help:'We never count more than this share of your spare money as saved, unless you set your own monthly saving.'},
  noAnswer:{g:'safety', b:'B22', ty:3, n:'monthly saving', l:'Monthly saving if you haven\'t told us how much you could invest', t:'eur', min:0, max:5000, step:25, sug:() => ST.noAnswer, by:STB.noAnswer.by, need:() => S.saveM == null && typeof S.ans['6'] !== 'number', help:'Used until you answer "How much could you comfortably invest each month?".'},
  lifeShare:{g:'safety', b:'B24', ty:3, n:'share of income your family would need', l:'Life cover: share of your income your family would need', t:'pct', min:30, max:100, step:5, sug:() => ST.lifeShare, by:STB.lifeShare.by, need:() => false, help:''},
  lifeYears:{g:'safety', b:'B24', ty:3, n:'years of support', l:'Life cover: years your family would need support', t:'yrs', min:1, max:30, step:1, sug:() => ST.lifeYears, by:STB.lifeYears.by, need:() => false, help:''},
  survivor:{g:'safety', b:'B24', ty:2, n:'survivor\'s pension', l:'Life cover: State survivor\'s pension a week', t:'eurw', min:0, max:400, step:0.5, rng:() => [0, RI.sp.survivor66], by:'DSP 2026: ' + eurW(RI.sp.survivor) + ' under 66, ' + eurW(RI.sp.survivor66) + ' at 66+, nothing if not eligible', fb:() => RI.sp.survivor, need:() => false, help:'Cohabiting partners can now qualify (Bereaved Partner\'s Pension).'},
  budgetNeeds:{g:'safety', b:'B27', ty:3, n:'budget split', l:'Budget split: needs', t:'pct', min:0, max:100, step:5, sug:() => ST.budget[0], by:STB.budget.by, need:() => false, help:''},
  budgetWants:{g:'safety', b:'B27', ty:3, n:'budget split', l:'Budget split: wants', t:'pct', min:0, max:100, step:5, sug:() => ST.budget[1], by:STB.budget.by, need:() => false, help:''},
  budgetSave:{g:'safety', b:'B27', ty:3, n:'budget split', l:'Budget split: savings and debt', t:'pct', min:0, max:100, step:5, sug:() => ST.budget[2], by:STB.budget.by, need:() => false, help:''},
  planEnd:{g:'length', b:'B12', ty:3, own:true, n:'plan-until age', l:'Plan until age (life expectancy)', t:'age', min:80, max:105, step:1, fb:() => S && S.about.partner ? GD.planHi : GD.planLo, need:() => true,
    help:'At 65, average life expectancy in Ireland is about ' + GD.lifeMen65 + ' for men and ' + GD.lifeWomen65 + ' for women (' + GDB.lifeMen65.by + '); many people plan to ' + GD.planLo + '–' + GD.planHi + '.'},
  startYear:{g:'length', b:'B23', ty:3, n:'plan start year', l:'Start the plan in', t:'choice', o:[[2026, '2026'], [2027, '2027']], sug:() => (new Date() > new Date('2026-09-30T23:59:59') ? 2027 : 2026), by:'from October most of this year has passed', need:() => true, help:''}
};
const RETIRE_HELP = 'You can usually draw a pension from ' + RI.pen.earliestAge + ' (' + GDB.schemeEarliest.by + ' from ' + GD.schemeEarliest + '); State Pension is paid from ' + RI.sp.age + '.';
const asmGet = k => S && S.asm && S.asm[k] != null && S.asm[k] !== '' ? S.asm[k] : null;
// engine value: the customer's choice; otherwise an internal fallback that is never shown as a result (planMissing() gates every result)
const asmV = k => { const x = asmGet(k), d = ASM[k]; return x != null ? x : d.sug ? d.sug() : d.fb ? d.fb() : null; };
const asmMine = k => asmGet(k) != null;
const ASM_KEYS = () => Object.keys(ASM);
const asmStd = k => ASM[k].ty === 3 && !ASM[k].own && ASM[k].sug;   // has a "Use the standard (X)" chip and is part of "use all"
// Everything the plan needs that the customer hasn't chosen yet, in the order we ask: inflation, retirement age, plan-until age, the rest.
function planMissing(){ if (!S) return []; const out = [];
  if (!inflSet()) out.push({k:'infl', n:'inflation rate', ty:3});
  if (!S.retireSet) out.push({k:'retireAge', n:'retirement age', ty:3, own:true});
  ASM_KEYS().filter(k => ASM[k].need() && !asmMine(k)).sort((a, b) => (a === 'planEnd' ? -1 : 0) - (b === 'planEnd' ? -1 : 0)).forEach(k => out.push({k, n:ASM[k].n, ty:ASM[k].ty, own:!!ASM[k].own}));
  return out; }
const planReady = () => !planMissing().length;
const chooseTxt = m => 'Choose your ' + m.n + ' to see this';
// "Use the standard for all of these": every type-3 item not chosen yet, incl. inflation. Never retirement age or plan-until age; never type 2.
function useAllStd(){ S.asm = Object.assign({}, S.asm); let n = 0; ASM_KEYS().filter(k => asmStd(k) && !asmMine(k)).forEach(k => { S.asm[k] = ASM[k].sug(); n++; });
  if (!inflSet()){ S.infl = ST.infl; S.inflOther = false; n++; } applyAssume(); return n; }
function applyAssume(){ Object.assign(AS, curSet()); AS.infl = S && S.infl != null ? S.infl : INFL_STD;   // inflation is the client's own choice (S.infl); INFL_STD is only an internal fallback before they choose
  ['wage', 'cash', 'inv', 'pen', 'penRet', 'mortRate', 'cardRate', 'loanRate'].forEach(k => { AS[k] = +asmV(k); });
  AS.end = +asmV('planEnd'); AS.sp = RI.sp.week * RI.sp.weeks; AS.spAge = RI.sp.age; YEAR0 = +asmV('startYear');
  SAVE.buffer = +asmV('safetyMonths'); SAVE.longYrs = +asmV('cashYears'); SAVE.share = +asmV('saveShare'); SAVE.noAnswer = +asmV('noAnswer'); }
