// FP round 6: data precedence (document > typed > estimate > default), stated figures used as stated, calculator accuracy.
// Run: NODE_PATH=/opt/node22/lib/node_modules node precedence.js   → prints each check, then "FAILS n" and "ERRORS n".
const { chromium } = require('playwright');
const URL = 'file:///home/user/lifegoals-prototype/LifeGoals-Customer-Journey-Prototype.html';
(async () => {
  const b = await chromium.launch(); const p = await (await b.newContext({viewport:{width:390, height:844}})).newPage();
  const errs = []; p.on('pageerror', e => errs.push('PAGEERROR ' + e.message)); p.on('console', m => { if (m.type() === 'error' && !/ERR_CERT|net::/.test(m.text())) errs.push(m.text()); });
  await p.route('**/fonts.googleapis.com/**', r => r.fulfill({status:200, contentType:'text/css', body:''})); await p.route('**/fonts.gstatic.com/**', r => r.abort());
  await p.goto(URL); await p.waitForTimeout(300);
  const res = []; const ok = (name, cond, info) => { res.push([cond ? 'PASS' : 'FAIL', name, info == null ? '' : JSON.stringify(info)]); };
  const ev = (f, a) => p.evaluate(f, a); const settle = () => p.waitForTimeout(120);
  const liabIdx = await ev(() => FSEC.findIndex(s => s.id === 'liab'));
  // ---------- 1. Plan: type → upload → type again → remove / replace ----------
  await ev(() => { loadSample(); ['mortBal','mortPayM','mortYears','mortRate','debt','debtPayM'].forEach(k => { delete S.fin[k]; delete S.src[k]; delete S.conf[k]; }); S.fin.home = 'Own with mortgage'; S.src.home = 'typed'; S.goals = S.goals.filter(g => g.k !== 'mfree'); render(); });
  await ev(i => openSec(i), liabIdx); await settle();
  await p.fill('[data-fin="mortPayM"]', '1300'); await p.fill('[data-fin="mortBal"]', '200000'); await p.fill('[data-fin="mortYears"]', '20'); await settle();
  let st = await ev(() => ({v:S.fin.mortPayM, s:S.src.mortPayM, tag:document.getElementById('tag-mortPayM').textContent}));
  ok('1a typed figure is used before any statement', st.v === 1300 && st.s === 'typed' && /Your figure/.test(st.tag), st);
  await ev(() => startUpload('liab', ['Mortgage statement.pdf'])); await p.waitForSelector('[data-a="uplok"]'); await p.click('[data-a="uplok"]'); await settle();
  await ev(i => openSec(i), liabIdx); await settle();
  st = await ev(() => ({v:S.fin.mortPayM, s:S.src.mortPayM, bal:S.fin.mortBal, note:(document.getElementById('dn-mortPayM') || {}).textContent, look:S.look.mortPayM, eng:finNums().mortPayM}));
  ok('1b document uploaded after typing wins (€1,180)', st.v === 1180 && st.s === 'doc' && st.eng === 1180 && !st.look, st);
  ok('1c "You typed €A, the document says €B" note resolved to the document', /You typed €1,300\. Your statement says €1,180; we're using that\./.test(st.note || ''), st.note);
  await p.fill('[data-fin="mortPayM"]', '1500'); await settle();
  st = await ev(() => ({v:S.fin.mortPayM, s:S.src.mortPayM, man:S.man.mortPayM, note:document.getElementById('dn-mortPayM').textContent, eng:finNums().mortPayM}));
  ok('1d later manual entry does not override the statement', st.v === 1180 && st.s === 'doc' && st.eng === 1180 && st.man.v === 1500, st);
  ok('1e note "Your statement says €1,180; we\'re using that" shown', /Your statement says €1,180; we're using that/.test(st.note), st.note);
  await ev(() => { S.fest = 1; ACT.fest('mortPayM'); }); st = await ev(() => ({v:S.fin.mortPayM, s:S.src.mortPayM}));
  ok('1f "Estimate for me" does not override the statement', st.v === 1180 && st.s === 'doc', st);
  await ev(() => ACT.fchoice('home|Rent')); st = await ev(() => ({v:S.fin.home, s:S.src.home}));
  ok('1g a choice typed after the statement does not override it', st.v === 'Own with mortgage' && st.s === 'doc', st);
  st = await ev(() => ({bar:!!document.getElementById('docbar'), rep:!!document.querySelector('[data-a="docrep"]'), rem:!!document.querySelector('[data-a="docrem"]')}));
  ok('1h section shows Replace statement / Remove statement', st.bar && st.rep && st.rem, st);
  await p.click('[data-a="docrem"]'); await settle();
  st = await ev(() => ({v:S.fin.mortPayM, s:S.src.mortPayM, bal:[S.fin.mortBal, S.src.mortBal], rate:S.fin.mortRate, eng:finNums().mortPayM}));
  ok('1i Remove statement goes back to the latest manual figures (here "Estimate for me" €1,100; balance typed €200,000)', st.v === 1100 && st.s === 'est' && st.bal[0] === 200000 && st.bal[1] === 'typed' && st.rate == null && st.eng === 1100, st);
  await ev(i => openSec(i), liabIdx); await settle(); await p.click('[data-a="fmode"][data-p="type"]').catch(() => {});
  await ev(() => startUpload('liab', ['Mortgage statement.pdf'])); await p.waitForSelector('[data-a="uplok"]'); await p.fill('[data-uv="mortBal"]', '205000'); await p.click('[data-a="uplok"]'); await settle();
  await ev(i => openSec(i), liabIdx); await settle();
  st = await ev(() => ({v:S.fin.mortBal, s:S.src.mortBal, fix:S.fix.mortBal, tag:document.getElementById('tag-mortBal').textContent, other:document.getElementById('tag-mortYears').textContent, low:S.look.mortPayM}));
  ok('1j correction on "We read these values" stays a statement figure, tagged "(corrected)"', st.v === 205000 && st.s === 'doc' && st.fix && /From your statement \(corrected\)/.test(st.tag) && /From document/.test(st.other), st);
  await p.click('[data-a="docrep"]'); await settle(); st = await ev(() => ({mode:S.fmode.liab, pick:!!document.querySelector('[data-a="upl"][data-p="liab"]')}));
  ok('1k Replace statement opens the upload', st.mode === 'upload' && st.pick, st);
  // ---------- 2. Explore mortgage statement: €1,180 stays €1,180 in the tool, the plan and the report ----------
  await ev(() => { loadSample(); ['mortBal','mortPayM','mortYears','mortRate'].forEach(k => { delete S.fin[k]; delete S.src[k]; }); S.goals = S.goals.filter(g => g.k !== 'mfree'); S.fin.mortBal = 250000; S.src.mortBal = 'typed'; S.fin.mortPayM = 1500; S.src.mortPayM = 'typed';
    S.calcV = {}; S.tab = 'explore'; S.xs = [{v:'XCAT', p:'home'}]; lastId = null; render(); });
  await p.click('[data-a="pstup"][data-p="home"]'); await p.waitForSelector('[data-a="pstok"]', {timeout:5000}); await p.click('[data-a="pstok"]'); await settle();
  st = await ev(() => { const F = finNums(), P = project(), a0 = S.about.age, end = P.rows.findIndex(r => r.t > 0 && r.fixed < F.debtPayM * 12 + 1);
    return {cout:document.getElementById('cout').textContent, fin:[S.fin.mortPayM, S.src.mortPayM, S.fin.mortBal, S.src.mortBal, (S.man.mortBal || {}).v], eng:F.mortPayM, y0:Math.round(P.rows[0].fixed), debt12:Math.round(P.rows[0].fixed - 1180 * 12), endAge:a0 + end, a0}; });
  ok('2a repayment tool shows €1,180 from the statement (not the €1,228 formula)', /€1,180/.test(st.cout) && /From your statement/.test(st.cout) && !/1,228/.test(st.cout), st.cout.slice(0, 160));
  ok('2b statement wins over earlier typed figures in Your finances (typed kept for Remove)', st.fin[0] === 1180 && st.fin[1] === 'doc' && st.fin[2] === 203700 && st.fin[3] === 'doc' && st.fin[4] === 250000, st.fin);
  ok('2c plan engine pays €1,180 a month', st.eng === 1180 && st.debt12 >= 0 && st.debt12 < 2400, {eng:st.eng, y0:st.y0});
  const toolEnd = await ev(() => C('repayment').run(calcVals(C('repayment'))).rows[0][1]);
  ok('2d tool "Mortgage free in 21 yrs" = plan mortgage end (age ' + (st.a0 + 21) + ')', toolEnd === '21 yrs' && st.endAge === st.a0 + 21, {toolEnd, planEnd:st.endAge});
  const rep = await ev(() => { openReport(); const r = document.getElementById('report').innerText; document.getElementById('report').classList.remove('on'); return {has1180:/Monthly repayment\s*€1,180/.test(r), has1228:/1,228/.test(r)}; });
  await ev(() => { S.sheet = null; render(); });
  ok('2e report shows €1,180 (and never €1,228)', rep.has1180 && !rep.has1228, rep);
  st = await ev(() => { S.tab = 'explore'; S.xs = [{v:'XCAT', p:'home'}, {v:'CALC', p:'repayment'}]; lastId = null; render(); const i = document.querySelector('[data-ck="dr"]'); i.value = '1'; i.dispatchEvent(new Event('input')); return document.getElementById('cout').textContent; });
  ok('2f calculated value appears only as a labelled what-if ("If your rate changed to 4.85%")', /If your rate changed to 4\.85%/.test(st) && /What-if/.test(st), st.slice(0, 200));
  st = await ev(() => ['overpay', 'ratechange', 'mortgageprotect'].map(id => { const r = C(id).run(calcVals(C(id))); return id + ':' + r.line; }).join(' | '));
  ok('2g overpayment, rate impact and protection tools start from the stated €1,180', (st.match(/1,180/g) || []).length === 3, st.slice(0, 300));
  await ev(() => ACT.pstrem('home'));
  st = await ev(() => ({fin:[S.fin.mortPayM, S.src.mortPayM, S.fin.mortBal, S.src.mortBal], pdoc:!!S.pdocs.home, rate:S.fin.mortRate, tool:C('repayment').run(calcVals(C('repayment'))).lbl}));
  ok('2h Explore "Remove statement" restores the typed figures and un-tags the tools', st.fin[0] === 1500 && st.fin[1] === 'typed' && st.fin[2] === 250000 && !st.pdoc && st.rate == null, st);
  // ---------- 3. Sample statements are internally consistent ----------
  st = await ev(() => { const h = DOCT.home.f, g = k => h.find(x => x[0] === k)[2], bal = g('bal'), r = g('rate'), pay = g('pay'), y = g('yrs'), i = r / 1200, n = y * 12, f = bal * i / (1 - Math.pow(1 + i, -n));
    const u = UPL.liab.v, rt = DOCT.retire.f, gr = k => rt.find(x => x[0] === k)[2]; S = fresh(); S.about.age = 38; applyAssume();
    let pot = gr('pot'); for (let t = 0; t < gr('nra') - 38; t++) pot = pot * (1 + AS.pen) + (gr('youM') + gr('empM')) * 12 * Math.pow(1 + AS.wage, t);
    return {formula:Math.round(f), pay, sameInPlanUpload:u.mortBal[0] === bal && u.mortPayM[0] === pay && u.mortYears[0] === y, proj:gr('proj'), ours:Math.round(pot), invest:[DOCT.invest.f[0][2], UPL.assets.v.invest[0]]}; });
  ok('3a mortgage statement amortises: €203,700 at 3.85% over 21 years = €1,180 a month', st.formula === st.pay && st.sameInPlanUpload, st);
  ok('3b pension statement projection matches the projection rule (age 38 → 66)', Math.abs(st.proj - st.ours) / st.ours < 0.005, st);
  ok('3c investment statement agrees with the plan upload', st.invest[0] === st.invest[1], st.invest);
  // ---------- 4. Explore pension statement: statement projection used as stated; tool = plan ----------
  await ev(() => { loadSample(); S.app = true; S.tab = 'explore'; S.xs = [{v:'XCAT', p:'retire'}]; lastId = null; render(); });
  await p.click('[data-a="pstup"][data-p="retire"]'); await p.waitForSelector('[data-a="pstok"]', {timeout:5000}); await p.click('[data-a="pstok"]'); await settle();
  st = await ev(() => { const P = project(), a0 = S.about.age, R = S.retireAge, v = calcVals(C('retirement')), r = C('retirement').run(v);
    const v66 = Object.assign({}, v, {ra:66}); S.calcT.retirement = {}; const r66 = C('retirement').run(Object.assign({}, v, {ra:66}));
    return {ra:v.ra, tool:eur(r.num.Projected_Fund), plan:eur(P.rows[R - a0 - 1].pen), rows:JSON.stringify(r.rows), r66:[r66.num.Use_Statement_Projection, eur(r66.num.Projected_Fund), r66.rows[0][0]]}; });
  ok('4a retirement tool projection = plan pension pot at the plan retirement age', st.tool === st.plan, st);
  const DOCT_PROJ = await ev(() => DOCT.retire.f.find(x => x[0] === 'proj')[2]);
  ok('4b at the statement age (66) the tool uses the statement projection as stated', st.r66[0] === 'Yes' && st.r66[1] === ('€' + DOCT_PROJ.toLocaleString('en-IE')) && /from your statement/.test(st.r66[2]), st.r66);
  // ---------- 5. Calculators: reference cases (hand-computed / standard formula values) ----------
  const ref = await ev(() => { S = fresh(); applyAssume(); const out = []; const run = (id, v) => C(id).run(Object.assign({}, calcVals(C(id)), v)); const chk = (id, got, exp, tol) => out.push([id, got, exp, Math.abs(got - exp) <= (tol == null ? 1 : tol)]);
    const num = x => +String(x).replace(/[^\d.-]/g, '');
    const iE = r => Math.pow(1 + r, 1 / 12) - 1, fvAe = (m, r, y) => m * (Math.pow(1 + iE(r), y * 12) - 1) / iE(r), pm = (P, r, y) => { const i = r / 12; return P * i / (1 - Math.pow(1 + i, -y * 12)); };
    chk('repayment €300k 4% 30y = €1,432.25 (standard)', num(run('repayment', {loan:300000, rate:4, term:30, dr:0}).val), 1432, 1);
    chk('loan €15k 8% APR 5y = €302.15 (APR effective, workbook C28)', num(run('loan', {a:15000, apr:8, y:5}).val), 302, 1);
    let r = run('borrow', {inc:60000, inc2:0, dep:25000, ftb:1, xdep:0}); chk('borrow FTB €60k, €25k deposit, €3,000 fees: deposit pays 10% + 1% stamp duty → (25,000 − 3,000) ÷ 0.11 = €200,000 (workbook C01)', num(r.val), 200000, 0);
    r = run('borrow', {inc:60000, inc2:0, dep:60000, ftb:1, xdep:0}); chk('borrow FTB €60k, €60k deposit: (4× income + 57,000) ÷ 1.01 = €294,059 (workbook C01)', num(r.val), (240000 + 57000) / 1.01, 1);
    r = run('borrow', {inc:60000, inc2:0, dep:60000, ftb:0, xdep:0}); chk('borrow mover €60k: (3.5× income + 57,000) ÷ 1.01 = €264,356 (workbook C01)', num(r.val), (210000 + 57000) / 1.01, 1);
    chk('deposit €350k, 10% + stamp duty €3,500 + fees €3,000, €12k saved, €800/m → 37 months (workbook C03)', run('deposit', {price:350000, pc:10, saved:12000, mo:800, xmo:0}).num.Months_To_Deposit, Math.ceil((35000 + 3500 + 3000 - 12000) / 800), 0);
    chk('compound €5k + €200/m, 4%, 20y', num(run('compound', {p:5000, m:200, r:4, y:20}).val), 5000 * Math.pow(1.04, 20) + fvAe(200, .04, 20), 1);
    chk('lumpsum €10k 4% 15y = €18,009', num(run('lumpsum', {p:10000, r:4, y:15}).val), 18009, 1);
    S.infl = 0.025; chk('goal planner (absorbs future cost) €20k at 2.5% for 10y = €25,602', num(run('goalplanner', {t:20000, y:10, s:0, r:0}).rows.find(x => x && x[0].startsWith('Will cost'))[1]), 25602, 1);
    chk('goalplanner €15k, 3y, €2k saved, 2%, prices rising 2.5% (future cost)', num(run('goalplanner', {t:15000, y:3, s:2000, r:2}).val), (15000 * Math.pow(1.025, 3) - 2000 * Math.pow(1.02, 3)) / fvAe(1, .02, 3), 1);
    chk('emergency €2,500 × 6, €6,250 saved → 2.5 months', num(run('emergency', {e:2500, mt:6, s:6250}).val), 2.5, 0.05);
    S.infl = 0.025; chk('realreturn €20k 4% vs 2.5% 15y = €24,874 (exact)', num(run('realreturn', {p:20000, r:4, y:15}).val), 20000 * Math.pow(1.04 / 1.025, 15), 1);
    chk('fees €50k 5% 20y, 0.5% vs 1.5%', num(run('fees', {p:50000, y:20, g:5, a:0.5, b:1.5}).val), 50000 * (Math.pow(1.05 * .995, 20) - Math.pow(1.05 * .985, 20)), 1);
    chk('regularinvest €300/m 5% 15y 1% fee', num(run('regularinvest', {m:300, y:15, g:5, f:1}).val), fvAe(300, 1.05 * .99 - 1, 15), 1);
    chk('contrib €60k +2% at 40%: net cost €60/m', num(run('contrib', {sal:60000, inc:2, y:25, g:4.5, tr:40}).rows[1][1]), 60, 0);
    let pot = 400000, w = 24000, y = 0; while (y < 60){ pot = pot * 1.03 - w; if (pot < 0) break; w *= 1.02; y++; }
    S.infl = 0.02; chk('lastmoney €400k, €24k rising 2%, 3% → full years paid', num(run('lastmoney', {pot:400000, w:24000, g:3}).val), y, 0);
    let bal = 5000, m = 0; while (bal > 0){ bal = bal * (1 + .18 / 12) - 250; m++; } chk('debtpay €5k 18% €250/m → ' + m + ' months', (s => { const a = s.match(/(\d+) yr/), b = s.match(/(\d+) mo/); return (a ? +a[1] * 12 : 0) + (b ? +b[1] : 0); })(run('debtpay', {b:5000, apr:18, p:250, x:0}).val), m, 0);
    chk('ratechange €300k 4%→5% 25y', num(run('ratechange', {loan:300000, rate:4, term:25, d:1}).val), pm(300000, .05, 25) - pm(300000, .04, 25), 1);
    chk('term €300k 4%: 25y monthly', num(run('term', {loan:300000, rate:4, a:25, b:35}).rows[0][1]), pm(300000, .04, 25), 1);
    r = run('overpay', {bal:250000, rate:4, yrs:25, x:200}); chk('overpay €250k 4% 25y: no extra = 25 yrs', num(r.rows[0][1]), 25, 0);
    chk('mortgageprotect €250k 4% 25y: balance after 5y', num(run('mortgageprotect', {bal:250000, rate:4, y:25}).rows[0][1]), (() => { let b = 250000; const p = pm(250000, .04, 25); for (let k = 0; k < 60; k++) b = b * (1 + .04 / 12) - p; return b; })(), 1);
    chk('networth', num(run('networth', {sav:15000, inv:10000, pen:60000, prop:350000, mort:250000, loans:8000}).val), 177000, 0);
    chk('surplus €3,500 − 2,000 − 800 − 200', num(run('surplus', {inc:3500, ess:2000, life:800, debt:200}).val), 500, 0);
    chk('budget 20% of €3,500', num(run('budget', {inc:3500}).val), 700, 0);
    chk('incomegap 3 + 8000 / (2500 − Illness Benefit 1100.67) = 8.7 (workbook C22)', num(run('incomegap', {e:2500, sp:3, s:8000, inc:60000}).val), 8.7, 0.05);
    chk('avc €200/m 4.5% 15y', num(run('avc', {m:200, y:15, g:4.5, tr:40}).val), fvAe(200, .045, 15), 1);
    chk('lifecover (mortgage protected, survivor €259.50 a week) = €227,590 (workbook C21)', num(run('lifecover', {inc:60000, y:15, mort:250000, mp:1, debt:10000, sav:20000, ex:100000, surv:259.5}).val), 227590, 0);
    chk('riskreturn balanced middle €20k 4% 10y', num(run('riskreturn', {p:20000, y:10, s:2}).val), 20000 * Math.pow(1.04, 10), 1);
    let pot2 = 72000; for (let t = 0; t < 25; t++) pot2 = pot2 * 1.045 + 520 * 12 * Math.pow(1 + AS.wage, t);
    chk('retirement €72k + €520/m, 4.5%, 40→65 (contributions rise with pay)', run('retirement', {age:40, ra:65, pot:72000, m:520, g:4.5, later:0, more:0}).num.Calculated_Fund, pot2, 1);
    return out; });
  ref.forEach(([n, g, e, pass]) => ok('5 ' + n, pass, {got:g, exp:Math.round(e * 100) / 100}));
  // ---------- 6. Calculators agree with the plan for the same inputs ----------
  st = await ev(() => { loadSample(); S.goals = S.goals.filter(g => g.k !== 'mfree'); const P = project(), F = finNums(), a0 = S.about.age, out = {};
    out.surplus = [num => num, C('surplus').run(calcVals(C('surplus'))).val, eur((P.rows[0].inflow - P.rows[0].needs) / 12)].slice(1);   // unclamped spare money (can be negative)
    const end = P.rows.findIndex(r => r.t > 0 && r.fixed < F.debtPayM * 12 + 1); out.mortgageEnd = [C('overpay').run(Object.assign({}, calcVals(C('overpay')), {x:0})).rows[0][1], (end) + ' yrs'];
    out.retire = [eur(C('retirement').run(calcVals(C('retirement'))).num.Projected_Fund), eur(P.rows[S.retireAge - a0 - 1].pen)];
    const dEnd = P.rows.findIndex(r => r.t > 0 && Math.round(r.fixed) === Math.round(F.mortPayM * 12)); const dTool = C('debtpay').run(calcVals(C('debtpay'))).val; out.debt = [dTool, dEnd];
    return out; });
  ok('6a Monthly surplus tool = plan spare money (within €5: a card that clears mid-year is paid for fewer months in the plan)', Math.abs(+st.surplus[0].replace(/[^\d−-]/g, '').replace('−', '-') - +st.surplus[1].replace(/[^\d−-]/g, '').replace('−', '-')) <= 5, st.surplus);
  ok('6b Mortgage payoff (tool) = plan mortgage end year', st.mortgageEnd[0] === st.mortgageEnd[1], st.mortgageEnd);
  ok('6c Retirement projection = plan pension pot at retirement age', st.retire[0] === st.retire[1], st.retire);
  ok('6d Debt repayment tool clears the debt in the year the plan does', (() => { const m = st.debt[0].match(/(\d+) yr/), mo = st.debt[0].match(/(\d+) mo/); const months = (m ? +m[1] * 12 : 0) + (mo ? +mo[1] : 0); return Math.ceil(months / 12) === st.debt[1]; })(), st.debt);
  res.forEach(r => console.log(r.join(' | ')));
  console.log('FAILS', res.filter(r => r[0] === 'FAIL').length, 'of', res.length); console.log('ERRORS', errs.length, JSON.stringify(errs)); await b.close();
})();
