  },
  // §14 type 2: set by Government or the market but varies within a known range → the customer enters theirs ("Usually between X and Y (source)").
  // Also the other guidance facts the copy quotes. Each figure is quoted once, from here.
  guide:{
    mortLo:RV_(0.035, 'https://centralbank.ie/statistics/data-and-analysis/credit-and-banking-statistics/retail-interest-rates', 'mid-2026', true, 'Central Bank of Ireland, new mortgages, 2026'),
    mortHi:RV_(0.045, 'https://centralbank.ie/statistics/data-and-analysis/credit-and-banking-statistics/retail-interest-rates', 'mid-2026', true, 'Central Bank of Ireland, new mortgages, 2026'),
    depLo:RV_(0.02, 'docs/journey-spec.md §14 (verify against CBI retail interest rates: term deposits averaged 1.86% in Jun 2026)', '2026', true, 'Irish deposit accounts, before 33% DIRT'),
    depHi:RV_(0.023, 'docs/journey-spec.md §14 (verify against CBI retail interest rates)', '2026', true, 'Irish deposit accounts, before 33% DIRT'),
    cardLo:RV_(0.13, 'https://www.centralbank.ie/news/article/central-bank-review-finds-over-400-000-credit-cards-are-on-historic-high-interest-rates', '2026', true, 'Central Bank of Ireland'),
    cardHi:RV_(0.23, 'https://www.centralbank.ie/news/article/central-bank-review-finds-over-400-000-credit-cards-are-on-historic-high-interest-rates', '2026', true, 'Central Bank of Ireland'),
    loanLo:RV_(0.07, 'https://www.anpost.com/Money/Loans (CCPC comparison, 27 Apr 2026)', 'Apr 2026', true, 'CCPC comparison, Apr 2026; credit unions average about 10.4%'),
    loanHi:RV_(0.13, 'https://www.creditunion.ie/what-we-offer/loans/cu-loan-rates/', 'Apr 2026', true, 'CCPC comparison, Apr 2026; credit unions average about 10.4%'),
    chgLo:RV_(0.005, 'docs/journey-spec.md §14 (verify: Pensions Authority / CCPC charges guidance)', '2026', true, 'typical fund charges'),
    chgHi:RV_(0.015, 'docs/journey-spec.md §14 (verify: Pensions Authority / CCPC charges guidance)', '2026', true, 'typical fund charges'),
    payLo:RV_(0.03, 'https://www.cso.ie/en/statistics/earnings/', '2025–2026', true, 'CSO earnings'),
    payHi:RV_(0.04, 'https://www.cso.ie/en/statistics/earnings/', '2025–2026', true, 'CSO earnings'),
    lifeMen65:RV_(83, 'https://www.cso.ie/en/statistics/birthsdeathsandmarriages/irishlifetables/', 'latest', true, 'CSO'),
    lifeWomen65:RV_(86, 'https://www.cso.ie/en/statistics/birthsdeathsandmarriages/irishlifetables/', 'latest', true, 'CSO'),
    planLo:RV_(90, 'docs/journey-spec.md §14', '2026', false, 'many people plan to'),
    planHi:RV_(95, 'docs/journey-spec.md §14', '2026', false, 'many people plan to'),
    schemeEarliest:RV_(50, 'https://www.revenue.ie/en/tax-professionals/tdm/pensions/index.aspx', 'Law', true, 'some occupational schemes')
  },
  // §14 type 3: personal judgement → no default. Blank until the customer chooses; "Generally the standard is X (source)" and a one-tap "Use the standard (X)" chip.
  std:{
    infl:RV_(0.02, 'https://www.bundesbank.de/en/tasks/topics/european-central-bank-updates-monetary-policy-strategy-970824', '2025 strategy', true, 'the ECB target for the long term'),
    wage:RV_(0.03, 'https://www.cso.ie/en/statistics/earnings/', '2026', true, 'Irish pay has grown about 3%–4% a year recently (CSO)'),
    cash:RV_(0.01, 'https://centralbank.ie/statistics/data-and-analysis/credit-and-banking-statistics/retail-interest-rates', 'Jun 2026', true, 'Irish deposit rates after 33% DIRT'),
    inv:RV_(0.035, 'deliverables/irish-rules-and-rates-audit.md §3 B3', '2026', true, 'a typical mixed fund after about 1% charges and 38% exit tax'),
    invGross:RV_(0.05, 'deliverables/irish-rules-and-rates-audit.md §3 B3', '2026', true, 'a typical mixed fund has grown 5%–6% a year before charges and tax over long periods'),
    pen:RV_(0.045, 'deliverables/irish-rules-and-rates-audit.md §3 B5', '2026', true, 'a typical pension fund after charges'),
    penRet:RV_(0.0315, 'deliverables/irish-rules-and-rates-audit.md §3 B5', '2026', true, 'a lower-risk fund once retired, after charges'),
    penChg:RV_(0.01, 'deliverables/irish-rules-and-rates-audit.md §3 B6', '2026', true, 'the middle of typical fund charges'),
    ownShare:RV_(0.5, 'deliverables/irish-rules-and-rates-audit.md §3 B1', '2026', false, 'a common 5% + 5% split with your employer; 100% if self-employed'),
    safetyMonths:RV_(6, 'deliverables/irish-rules-and-rates-audit.md §3 B16', '2026', false, '6 months for a single income or self-employed, 3 for two secure incomes'),
    safetyMonthsTwo:RV_(3, 'deliverables/irish-rules-and-rates-audit.md §3 B16', '2026', false, 'two secure incomes'),
    retireMult:RV_(25, 'deliverables/irish-rules-and-rates-audit.md §3 B17', '2026', false, 'a common rule of thumb, about 4% a year'),
    retireSpend:RV_(0.8, 'deliverables/irish-rules-and-rates-audit.md §3 B18', '2026', false, 'most people spend a bit less once work costs and the mortgage stop'),
    lumpSum:RV_(0.25, 'deliverables/irish-rules-and-rates-audit.md §3 B19', 'Law limit 25%', false, 'most people take the full tax-free amount'),
    cashYears:RV_(5, 'deliverables/irish-rules-and-rates-audit.md §3 B21', '2026', false, 'money needed within 5 years is usually kept as cash'),
    investShare:RV_(0.4, 'deliverables/irish-rules-and-rates-audit.md §3 B21', '2026', false, 'a balanced cash and invested mix'),
    saveShare:RV_(0.5, 'deliverables/irish-rules-and-rates-audit.md §3 B22', '2026', false, 'half of your spare money'),
    noAnswer:RV_(300, 'deliverables/irish-rules-and-rates-audit.md §3 B22', '2026', false, 'a modest regular amount'),
    lifeShare:RV_(0.6, 'deliverables/irish-rules-and-rates-audit.md §3 B24', '2026', false, 'families usually need less than full pay'),
    lifeYears:RV_(15, 'deliverables/irish-rules-and-rates-audit.md §3 B24', '2026', false, 'often until your youngest child is 23'),
    rentRise:RV_(0.03, 'deliverables/irish-rules-and-rates-audit.md §3 B25', '2026', true, 'a long-run planning figure'),
    houseGrow:RV_(0.02, 'deliverables/irish-rules-and-rates-audit.md §3 B25', '2026', true, 'a long-run planning figure; prices can fall'),
    upkeep:RV_(0.01, 'deliverables/irish-rules-and-rates-audit.md §3 B25', '2026', false, 'repairs, insurance and maintenance'),
    buyFees:RV_(3000, 'deliverables/irish-rules-and-rates-audit.md §3 B25', '2026', true, 'typical legal and survey fees'),
    depEarn:RV_(0.01, 'deliverables/irish-rules-and-rates-audit.md §3 B25', '2026', true, 'cash savings after DIRT'),
    riskMu:RV_([0.02, 0.04, 0.06], 'deliverables/irish-rules-and-rates-audit.md §3 B26', '2026', false, 'illustrations, not forecasts'),
    riskVol:RV_([0.05, 0.10, 0.16], 'deliverables/irish-rules-and-rates-audit.md §3 B26', '2026', false, 'illustrations, not forecasts'),
    budget:RV_([0.5, 0.3, 0.2], 'deliverables/irish-rules-and-rates-audit.md §3 B27', '2026', false, 'the 50/30/20 rule')
  }
};
