from ed import Ed
e = Ed()
e.rep("const asmSrcLbl = k =>","const srcTxt = s => /^https?:\\/\\//.test(s || '') ? s.replace(/^https?:\\/\\/(www\\.)?/, '').split('/')[0] : (s || '');\nconst stdNote = k => { const sk = SGK[k] || k, s = SET[sk]; return s ? SB(sk) + '. Source: ' + srcTxt(s.src) + (s.asat ? ' (' + s.asat + ')' : '') + '.' : ''; };\nconst asmSrcLbl = k =>")
# Step 7 / Your assumptions list: wording and source
e.rep("  return '<div class=\"field asmf\" data-k=\"' + k + '\" data-kind=\"' + (mine ? 'mine' : kind) + '\" style=\"margin:0 0 14px\"><span class=\"flabel\" id=\"' + id + '\">' + esc(d.l) + ' ' + asmTagK(k) + '</span>' + ctl + chip + idk + using +\n    '<span class=\"small\" style=\"display:block;margin-top:4px\">' + esc([asmGuide(d), d.help].filter(Boolean).join(' ')) + '</span></div>'; }",
      "  return '<div class=\"field asmf\" data-k=\"' + k + '\" data-kind=\"' + (mine ? 'mine' : kind) + '\" style=\"margin:0 0 14px\"><span class=\"flabel\" id=\"' + id + '\">' + esc(d.l) + ' ' + asmTagK(k) + '</span>' + ctl + chip + idk + using +\n    '<span class=\"small\" style=\"display:block;margin-top:4px\">' + esc([asmGuide(d), d.help].filter(Boolean).join(' ')) + '</span>' + (kind === 'std' && stdNote(k) ? '<span class=\"small\" style=\"display:block;margin-top:2px\">' + esc(stdNote(k)) + '</span>' : '') + '</div>'; }")
# What your plan assumes: a second line with wording and source for LifeMap's figures
e.rep("const rowHTML = x => '<div class=\"mini\"><span>' + esc(x[0]) + '<br><span class=\"tag ' + TAG_CLS(x[2]) + '\">' + esc(x[2]) + '</span></span><b>' + esc(x[1]) + '</b></div>';","const rowHTML = x => '<div class=\"mini\"><span>' + esc(x[0]) + '<br><span class=\"tag ' + TAG_CLS(x[2]) + '\">' + esc(x[2]) + '</span>' + (x[3] ? '<br><span class=\"small\">' + esc(x[3]) + '</span>' : '') + '</span><b>' + esc(x[1]) + '</b></div>';")
# add the note (4th element) to the standards rows
e.rep("R.push([l, asmFmt(ASM[k], asmV(k)) + ' a year', asmSrcLbl(k)]));","R.push([l, asmFmt(ASM[k], asmV(k)) + ' a year', asmSrcLbl(k), asmSrcLbl(k) === T_SET ? stdNote(k) : '']));")
e.rep("R.push(['State Pension in future', asmFmt(ASM.spGrow, asmV('spGrow')), asmSrcLbl('spGrow')], ['Tax bands in future', asmFmt(ASM.bands, asmV('bands')), asmSrcLbl('bands')]);","R.push(['State Pension in future', asmFmt(ASM.spGrow, asmV('spGrow')), asmSrcLbl('spGrow'), asmSrcLbl('spGrow') === T_SET ? stdNote('spGrow') : ''], ['Tax bands in future', asmFmt(ASM.bands, asmV('bands')), asmSrcLbl('bands'), asmSrcLbl('bands') === T_SET ? stdNote('bands') : '']);")
e.rep("['Plan starts', '' + YEAR0, asmSrcLbl('startYear')]);\n  R.push(['Pension access age', 'From ' + asmV('accessAge') + (asmV('accessAge') < RI.pen.earliestAge ? ' (an occupational scheme that allows it)' : ' (most pensions)'), asmSrcLbl('accessAge')]);","['Plan starts', '' + YEAR0, asmSrcLbl('startYear')]);\n  R.push(['Pension access age', 'From ' + asmV('accessAge') + (asmV('accessAge') < RI.pen.earliestAge ? ' (an occupational scheme that allows it)' : ' (most pensions)'), asmSrcLbl('accessAge'), asmSrcLbl('accessAge') === T_SET ? stdNote('accessAge') : '']);")
e.rep("asmV('lumpSum') > 0 ? Math.round(asmV('lumpSum') * 100) + '% of your pension (tax as set by law, above)' : 'None', asmSrcLbl('lumpSum')]);","asmV('lumpSum') > 0 ? Math.round(asmV('lumpSum') * 100) + '% of your pension (tax as set by law, above)' : 'None', asmSrcLbl('lumpSum'), asmSrcLbl('lumpSum') === T_SET ? stdNote('lumpSum') : '']);")
e.save()
