from ed import Ed
e = Ed()
# ---------- pension access age: a LifeMap standard (60), changeable to 50 for some occupational schemes
e.rep("  lumpSum:{n:'Tax-free lump sum to take (share of pension; law limit 25%)',","  accessAge:{n:'Pension access age (the earliest age you can draw your pension)', u:'choice', grp:'Retirement', v:60, by:'most pensions can be drawn from 60; some occupational schemes allow 50', src:'Revenue Commissioners: pension benefits can usually be taken from age 60 (PRSAs and personal pensions); some occupational schemes allow retirement from 50 (see the law register)', asat:'2026', verify:true, guide:'We assume 60. Choose 50 only if your occupational scheme says it allows it. Before this age your plan pays for life from savings and other income.'},\n  lumpSum:{n:'Tax-free lump sum to take (share of pension; law limit 25%)',")
e.rep("  drawRule:{g:'retire', b:'B20', ty:3, n:'how you draw your pension',","  accessAge:{g:'retire', b:'B20', ty:3, n:'pension access age', l:'Earliest age you can draw your pension', t:'choice', o:[[60, 'From 60 (most pensions)'], [50, 'From 50 (some occupational schemes)']], sug:() => SV('accessAge'), get by(){ return STB.accessAge.by; }, need:() => false, get help(){ return SG('accessAge'); }},\n  drawRule:{g:'retire', b:'B20', ty:3, n:'how you draw your pension',")
e.rep("const V = Math.max(R, RI.pen.earliestAge), lsPct","const V = Math.max(R, +asmV('accessAge')), lsPct")
e.rep("early = ra < RI.pen.earliestAge ? 'Most pensions can\\'t be taken before ' + RI.pen.earliestAge + ' (PRSA and personal pensions; occupational schemes from 50 only if you have left that job). ' : ''",
      "early = ra < +asmV('accessAge') ? 'Most pensions can\\'t be taken before ' + RI.pen.earliestAge + ' (PRSA and personal pensions; some occupational schemes allow it from 50). Until then you would live on savings and other income. ' : ''")
e.rep("case 'lastmoney': case 'drawdown': if ((has('pension') || has('pensionM')) && S.retireSet && asmMine('pen') && asmMine('wage'))","case 'lastmoney': case 'drawdown': if ((has('pension') || has('pensionM')) && S.retireSet)")
e.rep("p.age = Math.max(S.retireAge, RI.pen.earliestAge); break;","p.age = Math.max(S.retireAge, +asmV('accessAge')); break;")
e.rep("'From ' + PN.earliestAge + ' at the earliest;","'From ' + PN.earliestAge + ' at the earliest (50 for some occupational schemes);")
# ---------- retirement age: any age after your own, up to plan-until age - 1 (§27.3)
e.rep("const NB = {","const retMin = () => (S.about.age || 0) + 1, retMax = () => Math.max(retMin(), +asmV('planEnd') - 1);\nconst pRetMin = () => (finN('pAge') > 0 ? finN('pAge') : (S.about.age || 0)) + 1, pRetMax = () => Math.max(pRetMin(), pRetMin() - 1 + (+asmV('planEnd') - (S.about.age || 0)) - 1);\nconst NB = {")
e.rep("  ret:{ lim(){ return {min:Math.max(50, (S.about.age || 0) + 1), max:75, smax:75, widen:false, u:'age', int:true}; },","  ret:{ lim(){ return {min:retMin(), max:retMax(), smax:retMax(), widen:false, u:'age', int:true}; },")
e.rep("  pret:{ lim(){ return {min:50, max:75, smax:75, widen:false, u:'age', int:true}; },","  pret:{ lim(){ return {min:pRetMin(), max:pRetMax(), smax:pRetMax(), widen:false, u:'age', int:true}; },")
e.rep("  retireAge:{l:'Retirement age', type:'num', min:50, max:75, pre:1, hint:'From your timeline flag'},","  retireAge:{l:'Retirement age', type:'num', pre:1, hint:'From your timeline flag'},")
e.rep("if (used && k === 'retireAge' && S.fin.retireAge >= 50 && S.fin.retireAge <= 75) setRetireAge(S.fin.retireAge);","if (used && k === 'retireAge' && S.fin.retireAge >= retMin() && S.fin.retireAge <= retMax()) setRetireAge(S.fin.retireAge);")
e.rep("setRetireAge(clamp(g.age, Math.max(55, a0 + 1), 75)); return 'Retirement goal updated'; }","setRetireAge(clamp(g.age, a0 + 1, retMax())); return 'Retirement goal updated'; }")
e.rep("age = g.kind === 'retire' ? clamp(age, Math.max(55, a0 + 1), 75) : clamp(age, a0 + 1, AS.end);","age = g.kind === 'retire' ? clamp(age, a0 + 1, retMax()) : clamp(age, a0 + 1, AS.end);")
e.rep("aria-valuemin=\"' + (ret ? 55 : a0 + 1) + '\" aria-valuemax=\"' + (ret ? 75 : 90) + '\"","aria-valuemin=\"' + (a0 + 1) + '\" aria-valuemax=\"' + (ret ? retMax() : 90) + '\"")
# ---------- the calm notes under the retirement age boxes
e.rep("const RETIRE_HELP = ","""// §27.3: no hard limit; a calm one-line note, never a block
const retNote = a => a < 50 ? 'Retiring before 50 is possible. Pensions can usually be drawn from 60 (some schemes from 50) and the State Pension from ' + RI.sp.age + ', so until then your plan uses savings and other income. Your results will show any gap honestly.'
  : a < +asmV('accessAge') || a < 60 ? 'Pensions can usually be drawn from 60 (some schemes from 50) and the State Pension from ' + RI.sp.age + ', so until then your plan uses savings and other income. Your results will show any gap honestly.' : '';
const pRetNote = a => a < 50 ? 'Their pay stops at this age. Until their State Pension at ' + RI.sp.age + ' your plan uses savings and other income, and the results will show any gap honestly.' : a < 60 ? 'Their pay stops at this age. Their own pension is not modelled, so until their State Pension at ' + RI.sp.age + ' your plan relies on savings and other income. Your results will show any gap honestly.' : '';
const RETIRE_HELP = """)
e.rep("    '<span class=\"small\" style=\"display:block;margin-top:4px\">' + esc(RETIRE_HELP) + ' Choose the age you want to plan for.</span></div>'; }","    '<span class=\"small\" style=\"display:block;margin-top:4px\">' + esc(RETIRE_HELP) + ' Choose the age you want to plan for, any age from ' + retMin() + ' to ' + retMax() + '.</span>' + (S.retireSet && retNote(S.retireAge) ? '<span class=\"small\" id=\"ret-note\" role=\"status\" style=\"display:block;margin-top:4px;color:var(--nudge-t)\">' + esc(retNote(S.retireAge)) + '</span>' : '') + '</div>'; }")
e.rep("We count their pay until this age, then only their State Pension. Only you can choose it, so we never fill it in for you.</span></div>'; }","We count their pay until this age, then only their State Pension. Only you can choose it, so we never fill it in for you.</span>' + (S.pRetSet && pRetNote(S.pRet) ? '<span class=\"small\" id=\"pret-note\" role=\"status\" style=\"display:block;margin-top:4px;color:var(--nudge-t)\">' + esc(pRetNote(S.pRet)) + '</span>' : '') + '</div>'; }")
# the plan-until age change keeps the retirement age before it
e.rep("  asm:{ lim(k){ const d = ASM[k]; return d ? {min:d.min, max:d.max, smax:d.max, widen:false, u:nbUnit(d), int:d.t !== 'pct' && d.step % 1 === 0} : null; },\n    apply(k, v){ const d = ASM[k]; S.asm = S.asm || {}; if (S.advRate) delete S.advRate[k]; S.asm[k] = d.t === 'pct' ? +(v / 100).toFixed(6) : d.step % 1 === 0 ? Math.round(v) : v; applyAssume(); } },",
"  asm:{ lim(k){ const d = ASM[k]; return d ? {min:d.min, max:d.max, smax:d.max, widen:false, u:nbUnit(d), int:d.t !== 'pct' && d.step % 1 === 0} : null; },\n    apply(k, v){ const d = ASM[k]; S.asm = S.asm || {}; if (S.advRate) delete S.advRate[k]; S.asm[k] = d.t === 'pct' ? +(v / 100).toFixed(6) : d.step % 1 === 0 ? Math.round(v) : v; applyAssume();\n      if (k === 'planEnd' && S.retireSet && S.retireAge > retMax()){ const r = retMax(); setRetireAge(r); toast('We moved your retirement age to ' + r + ' so it stays before your plan-until age'); } } },")
e.save()
