from ed import Ed
e = Ed()
e.rep("const TAG_CLS = t => t === T_GOV ? 'none' : t === T_MINE ? 'doc' : t === T_HOW ? 'typed' : 'pre';","const TAG_CLS = t => t === T_GOV ? 'none' : t === T_MINE ? 'doc' : t === T_HOW ? 'typed' : t === T_ASSUMED ? 'look' : 'pre';")
e.rep("[['Pay rises', 'wage'], ['Cash savings grow (after DIRT)', 'cash'], ['Investments grow (after charges and exit tax)', 'inv'], ['Pensions grow while you work (after charges)', 'pen'], ['Pensions grow once retired (after charges)', 'penRet']].forEach(([l, k]) => R.push([l, mine(k) ? ch(k) + ' a year' : NC, T_MINE]));",
      "[['Pay rises', 'wage'], ['Cash savings grow (after DIRT)', 'cash'], ['Investments grow (after charges and exit tax)', 'inv'], ['Pensions grow while you work (after charges)', 'pen'], ['Pensions grow once retired (after charges)', 'penRet']].forEach(([l, k]) => R.push([l, asmFmt(ASM[k], asmV(k)) + ' a year', asmSrcLbl(k)]));")
e.rep("R.push(['State Pension in future', mine('spGrow') ? ch('spGrow') : NC, T_MINE], ['Tax bands in future', mine('bands') ? ch('bands') : NC, T_MINE]);","R.push(['State Pension in future', asmFmt(ASM.spGrow, asmV('spGrow')), asmSrcLbl('spGrow')], ['Tax bands in future', asmFmt(ASM.bands, asmV('bands')), asmSrcLbl('bands')]);")
e.rep("['Plan until age', mine('planEnd') ? 'Age ' + AS.end : NC, T_MINE], ['Plan starts', mine('startYear') ? '' + YEAR0 : NC, T_MINE]);","['Plan until age', mine('planEnd') ? 'Age ' + AS.end : NC, T_MINE], ['Plan starts', '' + YEAR0, asmSrcLbl('startYear')]);\n  R.push(['Pension access age', 'From ' + asmV('accessAge') + (asmV('accessAge') < RI.pen.earliestAge ? ' (an occupational scheme that allows it)' : ' (most pensions)'), asmSrcLbl('accessAge')]);")
e.rep("R.push(['Lump sum at retirement', mine('lumpSum') ? (asmV('lumpSum') > 0 ? Math.round(asmV('lumpSum') * 100) + '% of your pension (tax as set by law, above)' : 'None') : NC, T_MINE]);","R.push(['Lump sum at retirement', asmV('lumpSum') > 0 ? Math.round(asmV('lumpSum') * 100) + '% of your pension (tax as set by law, above)' : 'None', asmSrcLbl('lumpSum')]);")
e.rep("R.push(['Pension drawdown', mine('drawRule') ? {spread:'Spread to the end of the plan, at least the legal minimum', min:'The legal minimum only', fixed:(mine('drawFixed') ? eur(asmV('drawFixed')) : 'A fixed amount') + ' a year (today\\'s money), at least the legal minimum'}[asmV('drawRule')] : NC, T_MINE]);",
      "R.push(['Pension drawdown', {spread:'Spread to the end of the plan, at least the legal minimum', min:'The legal minimum only', fixed:eur(asmV('drawFixed')) + ' a year (today\\'s money), at least the legal minimum' + (mine('drawFixed') ? '' : ' (a planning figure: add yours)')}[asmV('drawRule')], asmSrcLbl('drawRule')]);")
e.rep("  if (ASM.ownShare.need()) R.push(['Share of your pension you pay', mine('ownShare') ? ch('ownShare') : NC, T_MINE]);","  if (F.pensionM > 0) R.push(['Share of your pension you pay', ch('ownShare') === NC ? pcs(asmV('ownShare')) : ch('ownShare'), asmSrcLbl('ownShare')]);")
# market rates
e.rep("if (F.mortBal > 0) R.push(['Mortgage rate', finN('mortRate') > 0 ? pcs(finN('mortRate') / 100) + ' (from your statement)' : mine('mortRate') ? ch('mortRate') + ' (your figure)' : 'Not given yet', tMarket(ASM.mortRate)]);",
      "if (F.mortBal > 0) R.push(['Mortgage rate', finN('mortRate') > 0 ? pcs(finN('mortRate') / 100) + ' (from your statement)' : mine('mortRate') ? ch('mortRate') + ' (your figure)' : pcs(asmV('mortRate')) + ' (' + (mkSug(ASM.mortRate) ? SL('mortRate') : 'a planning rate') + ')', finN('mortRate') > 0 || mine('mortRate') ? T_MINE : T_ASSUMED]);")
e.rep("' (a planning rate: you don\\'t know your rate, so it is left for your adviser)' : ' (your figure)') : 'Not given yet', tMarket(ASM.cardRate)]);","' (a planning rate: you don\\'t know your rate, so it is left for your adviser)' : ' (your figure)') : pcs(asmV('cardRate')) + ' (a planning rate)', finN('cardRate') > 0 || mine('cardRate') ? T_MINE : T_ASSUMED]);")
e.rep("' (a planning rate: you don\\'t know your rate, so it is left for your adviser)' : ' (your figure)') : 'Not given yet', tMarket(ASM.loanRate)]);","' (a planning rate: you don\\'t know your rate, so it is left for your adviser)' : ' (your figure)') : pcs(asmV('loanRate')) + ' (' + (mkSug(ASM.loanRate) ? SL('loanRate') : 'a planning rate') + ')', finN('loanRate') > 0 || mine('loanRate') ? T_MINE : T_ASSUMED]);")
e.rep("R.push(['What you save', S.saveM != null ? eur(S.saveM) + ' a month (your choice)' : !mine('saveShare') ? NC : (P ?","R.push(['What you save', S.saveM != null ? eur(S.saveM) + ' a month (your choice)' : (P ?")
e.rep("', ' + eur(SAVE.noAnswer) + ' a month until you tell us how much you could invest' : ''), T_MINE]);","', ' + eur(SAVE.noAnswer) + ' a month until you tell us how much you could invest' : ''), S.saveM != null || mine('saveShare') ? T_MINE : T_SET]);")
e.rep("R.push(['Emergency fund', S.goals.some(g => g.k === 'safety') ? 'Your Emergency fund goal covers this' : mine('safetyMonths') ? ch('safetyMonths') + ' of essential spending kept aside' : NC, T_MINE]);","R.push(['Emergency fund', S.goals.some(g => g.k === 'safety') ? 'Your Emergency fund goal covers this' : asmFmt(ASM.safetyMonths, asmV('safetyMonths')) + ' of essential spending kept aside', S.goals.some(g => g.k === 'safety') ? T_MINE : asmSrcLbl('safetyMonths')]);")
e.rep("R.push(['Money for goals sooner than', mine('cashYears') ? ch('cashYears') + ': kept as cash' : NC, T_MINE], ['Spare savings invested', mine('investShare') ? ch('investShare') + ' (the rest in cash)' : NC, T_MINE]);","R.push(['Money for goals sooner than', asmFmt(ASM.cashYears, asmV('cashYears')) + ': kept as cash', asmSrcLbl('cashYears')], ['Spare savings invested', asmFmt(ASM.investShare, asmV('investShare')) + ' (the rest in cash)', asmSrcLbl('investShare')]);")
e.save()
